# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(605, 347)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(150, 160, 91, 131))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout.addWidget(self.checkBox_2, 1, 0, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout.addWidget(self.checkBox_3, 2, 0, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout.addWidget(self.checkBox_4, 3, 0, 1, 1)
        self.radioButton = QtGui.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(410, 170, 82, 17))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(500, 170, 82, 17))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.buttonGroup.addButton(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(410, 200, 82, 17))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.buttonGroup_2 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.radioButton_3)
        self.radioButton_4 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(500, 200, 82, 17))
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.buttonGroup_2.addButton(self.radioButton_4)
        self.radioButton_5 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(410, 230, 82, 17))
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.buttonGroup_3 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName(_fromUtf8("buttonGroup_3"))
        self.buttonGroup_3.addButton(self.radioButton_5)
        self.radioButton_6 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_6.setGeometry(QtCore.QRect(500, 230, 82, 17))
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.buttonGroup_3.addButton(self.radioButton_6)
        self.radioButton_7 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_7.setGeometry(QtCore.QRect(410, 260, 82, 17))
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.buttonGroup_4 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_4.setObjectName(_fromUtf8("buttonGroup_4"))
        self.buttonGroup_4.addButton(self.radioButton_7)
        self.radioButton_8 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_8.setGeometry(QtCore.QRect(500, 260, 82, 17))
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.buttonGroup_4.addButton(self.radioButton_8)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 180, 131, 91))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(290, 180, 111, 91))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(400, 10, 191, 91))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 100, 81, 41))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(100, 80, 21, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(180, 80, 21, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(260, 80, 21, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(340, 80, 21, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(100, 110, 69, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(6, _fromUtf8(""))
        self.comboBox_2 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(180, 110, 69, 22))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.setItemText(6, _fromUtf8(""))
        self.comboBox_3 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(340, 110, 69, 22))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.setItemText(6, _fromUtf8(""))
        self.comboBox_4 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(260, 110, 69, 22))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.setItemText(6, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 605, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.checkBox.setText(_translate("MainWindow", "C1", None))
        self.checkBox_2.setText(_translate("MainWindow", "C2", None))
        self.checkBox_3.setText(_translate("MainWindow", "C3", None))
        self.checkBox_4.setText(_translate("MainWindow", "C4", None))
        self.radioButton.setText(_translate("MainWindow", "Yes", None))
        self.radioButton_2.setText(_translate("MainWindow", "No", None))
        self.radioButton_3.setText(_translate("MainWindow", "Yes", None))
        self.radioButton_4.setText(_translate("MainWindow", "No", None))
        self.radioButton_5.setText(_translate("MainWindow", "Yes", None))
        self.radioButton_6.setText(_translate("MainWindow", "No", None))
        self.radioButton_7.setText(_translate("MainWindow", "Yes", None))
        self.radioButton_8.setText(_translate("MainWindow", "No", None))
        self.label_2.setText(_translate("MainWindow", "Choose diagnostic device", None))
        self.label_8.setText(_translate("MainWindow", "Full waveforms?", None))
        self.label_9.setText(_translate("MainWindow", "VELA Charge Logger", None))
        self.pushButton.setText(_translate("MainWindow", "Start writing to EPICS", None))
        self.label_7.setText(_translate("MainWindow", "Diagnostic Types", None))
        self.label_10.setText(_translate("MainWindow", "C1", None))
        self.label_11.setText(_translate("MainWindow", "C2", None))
        self.label_12.setText(_translate("MainWindow", "C3", None))
        self.label_13.setText(_translate("MainWindow", "C4", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "WCM", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "ICT1", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "ICT2", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "FCUP-ED", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "FCUP-SP1", None))
        self.comboBox.setItemText(5, _translate("MainWindow", "FCUP-BA1", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "WCM", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "ICT1", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "ICT2", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "FCUP-ED", None))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "FCUP-SP1", None))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "FCUP-BA1", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "WCM", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "ICT1", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "ICT2", None))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "FCUP-ED", None))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "FCUP-SP1", None))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "FCUP-BA1", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "WCM", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "ICT1", None))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "ICT2", None))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "FCUP-ED", None))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "FCUP-SP1", None))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "FCUP-BA1", None))

