# This is the configuration file for HRFOv2_EPICS.

#Master_Dict_path:  "C:\\Users\\zup98752\\OneDrive - Science and Technology Facilities Council\\Axions\\CASCADE_2\\Data"
savepath:  "C:\\Users\\zup98752\\OneDrive - Science and Technology Facilities Council\\Hold_RF_On\\Python\\Analysis"
#Interpolated_datapath:  "C:\\Users\\zup98752\\OneDrive - Science and Technology Facilities Council\\Axions\\CASCADE_2\\Data\\Interpolated_data"
#CL_datapath:  "C:\\Users\\zup98752\\OneDrive - Science and Technology Facilities Council\\Axions\\CASCADE_2\\Data\\CLs"


# Date & time from:
# date in the format "YYYY-MM-DD"
# time in the format "HH:MM:SS.SS"
date_from:  "2020-10-10"
time_from:  "10:00:00.00"


# Date & time to:
# date in the format "YYYY-MM-DD"
# time in the format "HH:MM:SS.SS"
date_to:  "2020-10-20"
time_to:  "14:00:00.00"


# Full list of all PVs of interest
all_mod_PVs:  
 #- "CLA-GUNS-HRF-MOD-01:HvPs:HvPs1:CurrRead"
 #- "CLA-GUNS-HRF-MOD-01:HvPs:HvPs1:TrigCountRead"
 #- "CLA-GUNS-HRF-MOD-01:HvPs:HvPs1:VoltRead"
 #- "CLA-GUNS-HRF-MOD-01:HvPs:HvPs2:CurrRead"
 #- "CLA-GUNS-HRF-MOD-01:HvPs:HvPs2:VoltRead"
 #- "CLA-GUNS-HRF-MOD-01:HvPs:HvPs3:CurrRead"
 #- "CLA-GUNS-HRF-MOD-01:HvPs:HvPs3:VoltRead"
 #- "CLA-GUNS-HRF-MOD-01:Pt:Diag:CtArc"
 #- "CLA-GUNS-HRF-MOD-01:Pt:Diag:CtRead"
 #- "CLA-GUNS-HRF-MOD-01:Pt:Diag:CvdArc"
 #- "CLA-GUNS-HRF-MOD-01:Pt:Diag:CvdRead"
 #- "CLA-GUNS-HRF-MOD-01:Pt:Diag:PlswthFwhmRead"
 #- "CLA-GUNS-HRF-MOD-01:Pt:Diag:PlswthRead"
 #- "CLA-GUNS-HRF-MOD-01:Pt:Diag:PowRead"
 #- "CLA-GUNS-HRF-MOD-01:Pt:Diag:PrfRead"
 #- "CLA-GUNS-HRF-MOD-01:Pt:FilPs:CurrRead"
 #- "CLA-GUNS-HRF-MOD-01:Pt:FilPs:VoltRead"
 #- "CLA-GUNS-HRF-MOD-01:Rf:Cool:BodyOutletTemp"
 #- "CLA-GUNS-HRF-MOD-01:Rf:Cool:KlystLimit"
 #- "CLA-GUNS-HRF-MOD-01:Rf:Cool:KlystPower"
 #- "CLA-GUNS-HRF-MOD-01:Rf:Ionp:PresRead1"
 #- "CLA-GUNS-HRF-MOD-01:Rf:MagPs1:CurrRead"
 #- "CLA-GUNS-HRF-MOD-01:Rf:MagPs1:VoltRead"
 #- "CLA-GUNS-HRF-MOD-01:Rf:MagPs2:CurrRead"
 #- "CLA-GUNS-HRF-MOD-01:Rf:MagPs2:VoltRead"
 #- "CLA-GUNS-HRF-MOD-01:Rf:MagPs3:CurrRead"
 #- "CLA-GUNS-HRF-MOD-01:Rf:MagPs3:VoltRead"
 #- "CLA-GUNS-HRF-MOD-01:Rf:MagPs4:CurrRead"
 #- "CLA-GUNS-HRF-MOD-01:Rf:MagPs4:VoltRead"
 #- "CLA-GUNS-HRF-MOD-01:Sys:ErrorRead.SVAL"
 #- "CLA-GUNS-HRF-MOD-01:Sys:ExtComm:AccessLevel"
 #- "CLA-GUNS-HRF-MOD-01:Sys:HvHoursRead"
 #- "CLA-GUNS-HRF-MOD-01:Sys:OffHoursRead"
 #- "CLA-GUNS-HRF-MOD-01:Sys:RemainingTime"
 #- "CLA-GUNS-HRF-MOD-01:Sys:StandbyHoursRead"
 - "CLA-GUNS-HRF-MOD-01:Sys:StateRead"
 - "CLA-GUNS-HRF-MOD-01:Sys:StateSet"
 - "CLA-GUNS-HRF-MOD-01:Sys:Trig:PlswthSet"
 - "CLA-GUNS-HRF-MOD-01:Sys:Trig:PrfSet"
 - "CLA-GUNS-HRF-MOD-01:Sys:TrigHoursRead"


# Separate list for "Sys:INTLK" PVs
interlock_PVs:
 - "CLA-GUNS-HRF-MOD-01:Sys:INTLK1"
 - "CLA-GUNS-HRF-MOD-01:Sys:INTLK2"
 - "CLA-GUNS-HRF-MOD-01:Sys:INTLK3"
 - "CLA-GUNS-HRF-MOD-01:Sys:INTLK4"
 - "CLA-GUNS-HRF-MOD-01:Sys:INTLK5"


# If True then all PVs in "all_mod_PVs" list above will be read in and plotted.
# If False then the previously save .pkl will be read in and stored as the values dictionary
READ_PVs:  False


# if set ti=o True then all individual PVs will be plotted and saved
PLOT_ALL_PVs:  True


# If a change in modulator state is within mod_group_spacing_seconds
# then it is included in the group
# If a change in modulator state is after mod_group_time_spacing seconds
# then it is excluded from the group and forms the first event in a new group
# Values tried = [120, 240.0, 20.0]
# 20.0 seconds seems reasonable after looking at the histogram of delta times
mod_group_time_spacing: 60.0  #  units = seconds


#MODE:  'Standby'