# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\view.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1139, 961)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("crester.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralWidgetLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.centralWidgetLayout.setObjectName("centralWidgetLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 65))
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(9, 0, 9, 5)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_MODE = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_MODE.sizePolicy().hasHeightForWidth())
        self.label_MODE.setSizePolicy(sizePolicy)
        self.label_MODE.setMinimumSize(QtCore.QSize(200, 25))
        self.label_MODE.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_MODE.setObjectName("label_MODE")
        self.horizontalLayout.addWidget(self.label_MODE)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.widget_5 = QtWidgets.QWidget(self.groupBox)
        self.widget_5.setMinimumSize(QtCore.QSize(400, 0))
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_10.setContentsMargins(9, 0, 9, 0)
        self.gridLayout_10.setHorizontalSpacing(6)
        self.gridLayout_10.setVerticalSpacing(2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.Linac1_Amp_Monitor = QtWidgets.QSpinBox(self.widget_5)
        self.Linac1_Amp_Monitor.setEnabled(False)
        self.Linac1_Amp_Monitor.setMinimumSize(QtCore.QSize(70, 0))
        self.Linac1_Amp_Monitor.setAlignment(QtCore.Qt.AlignCenter)
        self.Linac1_Amp_Monitor.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Linac1_Amp_Monitor.setPrefix("")
        self.Linac1_Amp_Monitor.setMaximum(100000)
        self.Linac1_Amp_Monitor.setObjectName("Linac1_Amp_Monitor")
        self.gridLayout_10.addWidget(self.Linac1_Amp_Monitor, 2, 2, 1, 1)
        self.Dipole_Monitor = QtWidgets.QDoubleSpinBox(self.widget_5)
        self.Dipole_Monitor.setEnabled(False)
        self.Dipole_Monitor.setAlignment(QtCore.Qt.AlignCenter)
        self.Dipole_Monitor.setReadOnly(True)
        self.Dipole_Monitor.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Dipole_Monitor.setMinimum(-250.0)
        self.Dipole_Monitor.setMaximum(250.0)
        self.Dipole_Monitor.setObjectName("Dipole_Monitor")
        self.gridLayout_10.addWidget(self.Dipole_Monitor, 2, 5, 1, 1)
        self.Gun_Phase_Monitor = QtWidgets.QDoubleSpinBox(self.widget_5)
        self.Gun_Phase_Monitor.setEnabled(False)
        self.Gun_Phase_Monitor.setMinimumSize(QtCore.QSize(70, 0))
        self.Gun_Phase_Monitor.setAlignment(QtCore.Qt.AlignCenter)
        self.Gun_Phase_Monitor.setReadOnly(True)
        self.Gun_Phase_Monitor.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Gun_Phase_Monitor.setMinimum(-180.0)
        self.Gun_Phase_Monitor.setMaximum(180.0)
        self.Gun_Phase_Monitor.setObjectName("Gun_Phase_Monitor")
        self.gridLayout_10.addWidget(self.Gun_Phase_Monitor, 2, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.widget_5)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_10.addWidget(self.label_31, 1, 5, 1, 1)
        self.Progress_Monitor = QtWidgets.QProgressBar(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Progress_Monitor.sizePolicy().hasHeightForWidth())
        self.Progress_Monitor.setSizePolicy(sizePolicy)
        self.Progress_Monitor.setMinimumSize(QtCore.QSize(70, 0))
        self.Progress_Monitor.setProperty("value", 0)
        self.Progress_Monitor.setTextVisible(False)
        self.Progress_Monitor.setObjectName("Progress_Monitor")
        self.gridLayout_10.addWidget(self.Progress_Monitor, 2, 6, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.widget_5)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_10.addWidget(self.label_27, 1, 0, 1, 2)
        self.label_30 = QtWidgets.QLabel(self.widget_5)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_10.addWidget(self.label_30, 1, 2, 1, 2)
        self.Gun_Amp_Monitor = QtWidgets.QSpinBox(self.widget_5)
        self.Gun_Amp_Monitor.setEnabled(False)
        self.Gun_Amp_Monitor.setMinimumSize(QtCore.QSize(70, 0))
        self.Gun_Amp_Monitor.setAlignment(QtCore.Qt.AlignCenter)
        self.Gun_Amp_Monitor.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Gun_Amp_Monitor.setPrefix("")
        self.Gun_Amp_Monitor.setMaximum(100000)
        self.Gun_Amp_Monitor.setObjectName("Gun_Amp_Monitor")
        self.gridLayout_10.addWidget(self.Gun_Amp_Monitor, 2, 0, 1, 1)
        self.Linac1_Phase_Monitor = QtWidgets.QDoubleSpinBox(self.widget_5)
        self.Linac1_Phase_Monitor.setEnabled(False)
        self.Linac1_Phase_Monitor.setMinimumSize(QtCore.QSize(70, 0))
        self.Linac1_Phase_Monitor.setAlignment(QtCore.Qt.AlignCenter)
        self.Linac1_Phase_Monitor.setReadOnly(True)
        self.Linac1_Phase_Monitor.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Linac1_Phase_Monitor.setMinimum(-180.0)
        self.Linac1_Phase_Monitor.setMaximum(180.0)
        self.Linac1_Phase_Monitor.setObjectName("Linac1_Phase_Monitor")
        self.gridLayout_10.addWidget(self.Linac1_Phase_Monitor, 2, 3, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.widget_5)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_10.addWidget(self.label_32, 1, 6, 1, 1)
        self.Linac1_Timing_Monitor = QtWidgets.QPushButton(self.widget_5)
        self.Linac1_Timing_Monitor.setEnabled(False)
        self.Linac1_Timing_Monitor.setText("")
        self.Linac1_Timing_Monitor.setFlat(False)
        self.Linac1_Timing_Monitor.setObjectName("Linac1_Timing_Monitor")
        self.gridLayout_10.addWidget(self.Linac1_Timing_Monitor, 2, 4, 1, 1)
        self.horizontalLayout.addWidget(self.widget_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.topbutton_widget = QtWidgets.QWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topbutton_widget.sizePolicy().hasHeightForWidth())
        self.topbutton_widget.setSizePolicy(sizePolicy)
        self.topbutton_widget.setMinimumSize(QtCore.QSize(175, 0))
        self.topbutton_widget.setStyleSheet("background: grey")
        self.topbutton_widget.setObjectName("topbutton_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.topbutton_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Save_Data_Buttons = QtWidgets.QDialogButtonBox(self.topbutton_widget)
        self.Save_Data_Buttons.setEnabled(True)
        self.Save_Data_Buttons.setStyleSheet("")
        self.Save_Data_Buttons.setOrientation(QtCore.Qt.Horizontal)
        self.Save_Data_Buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.Save_Data_Buttons.setCenterButtons(True)
        self.Save_Data_Buttons.setObjectName("Save_Data_Buttons")
        self.horizontalLayout_2.addWidget(self.Save_Data_Buttons)
        self.Finish_Button = QtWidgets.QPushButton(self.topbutton_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Finish_Button.sizePolicy().hasHeightForWidth())
        self.Finish_Button.setSizePolicy(sizePolicy)
        self.Finish_Button.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Finish_Button.setObjectName("Finish_Button")
        self.horizontalLayout_2.addWidget(self.Finish_Button)
        self.Abort_Button = QtWidgets.QPushButton(self.topbutton_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Abort_Button.sizePolicy().hasHeightForWidth())
        self.Abort_Button.setSizePolicy(sizePolicy)
        self.Abort_Button.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Abort_Button.setAutoFillBackground(False)
        self.Abort_Button.setStyleSheet("background-color: rgb(255, 0, 0);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Resources/Icons/off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Abort_Button.setIcon(icon1)
        self.Abort_Button.setObjectName("Abort_Button")
        self.horizontalLayout_2.addWidget(self.Abort_Button)
        self.horizontalLayout.addWidget(self.topbutton_widget)
        self.centralWidgetLayout.addWidget(self.groupBox, 0, 0, 2, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.Gun_Tab = QtWidgets.QWidget()
        self.Gun_Tab.setObjectName("Gun_Tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Gun_Tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.Gun_Plots_Box = QtWidgets.QGroupBox(self.Gun_Tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gun_Plots_Box.sizePolicy().hasHeightForWidth())
        self.Gun_Plots_Box.setSizePolicy(sizePolicy)
        self.Gun_Plots_Box.setObjectName("Gun_Plots_Box")
        self.Gun_Plots_Layout = QtWidgets.QVBoxLayout(self.Gun_Plots_Box)
        self.Gun_Plots_Layout.setObjectName("Gun_Plots_Layout")
        self.gridLayout_7.addWidget(self.Gun_Plots_Box, 0, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.Gun_Tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Gun_Startup = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gun_Startup.sizePolicy().hasHeightForWidth())
        self.Gun_Startup.setSizePolicy(sizePolicy)
        self.Gun_Startup.setObjectName("Gun_Startup")
        self.gridLayout = QtWidgets.QGridLayout(self.Gun_Startup)
        self.gridLayout.setObjectName("gridLayout")
        self.label_33 = QtWidgets.QLabel(self.Gun_Startup)
        self.label_33.setMinimumSize(QtCore.QSize(0, 0))
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 4, 0, 1, 1)
        self.Gun_Amp_Set = QtWidgets.QSpinBox(self.Gun_Startup)
        self.Gun_Amp_Set.setMaximum(71000)
        self.Gun_Amp_Set.setSingleStep(100)
        self.Gun_Amp_Set.setProperty("value", 71000)
        self.Gun_Amp_Set.setObjectName("Gun_Amp_Set")
        self.gridLayout.addWidget(self.Gun_Amp_Set, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.Gun_Startup)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.Gun_Startup)
        self.label_13.setMinimumSize(QtCore.QSize(130, 0))
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 0, 1, 2)
        self.Gun_LoadBURT_Button = QtWidgets.QPushButton(self.Gun_Startup)
        self.Gun_LoadBURT_Button.setObjectName("Gun_LoadBURT_Button")
        self.gridLayout.addWidget(self.Gun_LoadBURT_Button, 3, 0, 1, 3)
        self.Gun_TurnOn_Button = QtWidgets.QPushButton(self.Gun_Startup)
        self.Gun_TurnOn_Button.setEnabled(True)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.Gun_TurnOn_Button.setFont(font)
        self.Gun_TurnOn_Button.setFlat(False)
        self.Gun_TurnOn_Button.setObjectName("Gun_TurnOn_Button")
        self.gridLayout.addWidget(self.Gun_TurnOn_Button, 2, 0, 1, 3)
        self.Gun_LinacTiming_Off_Button = QtWidgets.QPushButton(self.Gun_Startup)
        self.Gun_LinacTiming_Off_Button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.Gun_LinacTiming_Off_Button.setObjectName("Gun_LinacTiming_Off_Button")
        self.gridLayout.addWidget(self.Gun_LinacTiming_Off_Button, 4, 1, 1, 2)
        self.Gun_Amp_Step_Set = QtWidgets.QSpinBox(self.Gun_Startup)
        self.Gun_Amp_Step_Set.setMaximum(1000)
        self.Gun_Amp_Step_Set.setSingleStep(100)
        self.Gun_Amp_Step_Set.setProperty("value", 500)
        self.Gun_Amp_Step_Set.setObjectName("Gun_Amp_Step_Set")
        self.gridLayout.addWidget(self.Gun_Amp_Step_Set, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.Gun_Startup)
        self.Gun_Rough_Crest = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gun_Rough_Crest.sizePolicy().hasHeightForWidth())
        self.Gun_Rough_Crest.setSizePolicy(sizePolicy)
        self.Gun_Rough_Crest.setObjectName("Gun_Rough_Crest")
        self.formLayout_5 = QtWidgets.QFormLayout(self.Gun_Rough_Crest)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label = QtWidgets.QLabel(self.Gun_Rough_Crest)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        self.label.setObjectName("label")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.Gun_Rough_NShots_Set = QtWidgets.QSpinBox(self.Gun_Rough_Crest)
        self.Gun_Rough_NShots_Set.setMinimum(2)
        self.Gun_Rough_NShots_Set.setProperty("value", 3)
        self.Gun_Rough_NShots_Set.setObjectName("Gun_Rough_NShots_Set")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Gun_Rough_NShots_Set)
        self.label_10 = QtWidgets.QLabel(self.Gun_Rough_Crest)
        self.label_10.setObjectName("label_10")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.Gun_Rough_PointSeperation_Set = QtWidgets.QDoubleSpinBox(self.Gun_Rough_Crest)
        self.Gun_Rough_PointSeperation_Set.setDecimals(1)
        self.Gun_Rough_PointSeperation_Set.setMinimum(0.1)
        self.Gun_Rough_PointSeperation_Set.setSingleStep(0.1)
        self.Gun_Rough_PointSeperation_Set.setProperty("value", 5.0)
        self.Gun_Rough_PointSeperation_Set.setObjectName("Gun_Rough_PointSeperation_Set")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Gun_Rough_PointSeperation_Set)
        self.label_4 = QtWidgets.QLabel(self.Gun_Rough_Crest)
        self.label_4.setObjectName("label_4")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.Gun_Rough_Fit_Offset = QtWidgets.QSpinBox(self.Gun_Rough_Crest)
        self.Gun_Rough_Fit_Offset.setFrame(True)
        self.Gun_Rough_Fit_Offset.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.Gun_Rough_Fit_Offset.setMinimum(-180)
        self.Gun_Rough_Fit_Offset.setMaximum(180)
        self.Gun_Rough_Fit_Offset.setProperty("value", 10)
        self.Gun_Rough_Fit_Offset.setObjectName("Gun_Rough_Fit_Offset")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Gun_Rough_Fit_Offset)
        self.Gun_Rough_Button = QtWidgets.QPushButton(self.Gun_Rough_Crest)
        self.Gun_Rough_Button.setChecked(False)
        self.Gun_Rough_Button.setObjectName("Gun_Rough_Button")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.Gun_Rough_Button)
        self.verticalLayout.addWidget(self.Gun_Rough_Crest)
        self.Gun_Dipole_Set_Box = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gun_Dipole_Set_Box.sizePolicy().hasHeightForWidth())
        self.Gun_Dipole_Set_Box.setSizePolicy(sizePolicy)
        self.Gun_Dipole_Set_Box.setObjectName("Gun_Dipole_Set_Box")
        self.formLayout_6 = QtWidgets.QFormLayout(self.Gun_Dipole_Set_Box)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_11 = QtWidgets.QLabel(self.Gun_Dipole_Set_Box)
        self.label_11.setMinimumSize(QtCore.QSize(150, 0))
        self.label_11.setObjectName("label_11")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.Gun_Dipole_Set_Box)
        self.label_12.setObjectName("label_12")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.Gun_Dipole_Start_Set = QtWidgets.QDoubleSpinBox(self.Gun_Dipole_Set_Box)
        self.Gun_Dipole_Start_Set.setDecimals(1)
        self.Gun_Dipole_Start_Set.setSingleStep(0.1)
        self.Gun_Dipole_Start_Set.setProperty("value", 7.0)
        self.Gun_Dipole_Start_Set.setObjectName("Gun_Dipole_Start_Set")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Gun_Dipole_Start_Set)
        self.Gun_Dipole_End_Set = QtWidgets.QDoubleSpinBox(self.Gun_Dipole_Set_Box)
        self.Gun_Dipole_End_Set.setDecimals(1)
        self.Gun_Dipole_End_Set.setSingleStep(0.1)
        self.Gun_Dipole_End_Set.setProperty("value", 8.9)
        self.Gun_Dipole_End_Set.setObjectName("Gun_Dipole_End_Set")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Gun_Dipole_End_Set)
        self.Gun_Dipole_Button = QtWidgets.QPushButton(self.Gun_Dipole_Set_Box)
        self.Gun_Dipole_Button.setMinimumSize(QtCore.QSize(0, 23))
        self.Gun_Dipole_Button.setObjectName("Gun_Dipole_Button")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.Gun_Dipole_Button)
        self.label_28 = QtWidgets.QLabel(self.Gun_Dipole_Set_Box)
        self.label_28.setObjectName("label_28")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.Gun_Dipole_Step_Set = QtWidgets.QDoubleSpinBox(self.Gun_Dipole_Set_Box)
        self.Gun_Dipole_Step_Set.setDecimals(2)
        self.Gun_Dipole_Step_Set.setMaximum(1.0)
        self.Gun_Dipole_Step_Set.setSingleStep(0.1)
        self.Gun_Dipole_Step_Set.setProperty("value", 0.1)
        self.Gun_Dipole_Step_Set.setObjectName("Gun_Dipole_Step_Set")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Gun_Dipole_Step_Set)
        self.verticalLayout.addWidget(self.Gun_Dipole_Set_Box)
        self.Gun_Fine_Crest = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gun_Fine_Crest.sizePolicy().hasHeightForWidth())
        self.Gun_Fine_Crest.setSizePolicy(sizePolicy)
        self.Gun_Fine_Crest.setObjectName("Gun_Fine_Crest")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Gun_Fine_Crest)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Gun_Fine_NShots_Set = QtWidgets.QSpinBox(self.Gun_Fine_Crest)
        self.Gun_Fine_NShots_Set.setMinimum(1)
        self.Gun_Fine_NShots_Set.setMaximum(100)
        self.Gun_Fine_NShots_Set.setProperty("value", 10)
        self.Gun_Fine_NShots_Set.setObjectName("Gun_Fine_NShots_Set")
        self.gridLayout_5.addWidget(self.Gun_Fine_NShots_Set, 0, 3, 1, 1)
        self.Gun_Fine_PointSeperation_Set = QtWidgets.QDoubleSpinBox(self.Gun_Fine_Crest)
        self.Gun_Fine_PointSeperation_Set.setDecimals(1)
        self.Gun_Fine_PointSeperation_Set.setMinimum(0.1)
        self.Gun_Fine_PointSeperation_Set.setSingleStep(0.1)
        self.Gun_Fine_PointSeperation_Set.setProperty("value", 2.0)
        self.Gun_Fine_PointSeperation_Set.setObjectName("Gun_Fine_PointSeperation_Set")
        self.gridLayout_5.addWidget(self.Gun_Fine_PointSeperation_Set, 1, 3, 1, 1)
        self.Gun_Fine_Range_Set = QtWidgets.QSpinBox(self.Gun_Fine_Crest)
        self.Gun_Fine_Range_Set.setPrefix("")
        self.Gun_Fine_Range_Set.setMinimum(1)
        self.Gun_Fine_Range_Set.setMaximum(30)
        self.Gun_Fine_Range_Set.setProperty("value", 20)
        self.Gun_Fine_Range_Set.setObjectName("Gun_Fine_Range_Set")
        self.gridLayout_5.addWidget(self.Gun_Fine_Range_Set, 2, 3, 1, 1)
        self.Gun_Fine_Button = QtWidgets.QPushButton(self.Gun_Fine_Crest)
        self.Gun_Fine_Button.setMinimumSize(QtCore.QSize(0, 23))
        self.Gun_Fine_Button.setChecked(False)
        self.Gun_Fine_Button.setObjectName("Gun_Fine_Button")
        self.gridLayout_5.addWidget(self.Gun_Fine_Button, 3, 0, 1, 4)
        self.label_25 = QtWidgets.QLabel(self.Gun_Fine_Crest)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.Gun_Fine_Crest)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 1, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.Gun_Fine_Crest)
        self.label_3.setMinimumSize(QtCore.QSize(150, 0))
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 3)
        self.Gun_Fine_Range_Start = QtWidgets.QSpinBox(self.Gun_Fine_Crest)
        self.Gun_Fine_Range_Start.setMinimum(-180)
        self.Gun_Fine_Range_Start.setMaximum(180)
        self.Gun_Fine_Range_Start.setObjectName("Gun_Fine_Range_Start")
        self.gridLayout_5.addWidget(self.Gun_Fine_Range_Start, 2, 1, 1, 1)
        self.Gun_Fine_Update_Start_Button = QtWidgets.QPushButton(self.Gun_Fine_Crest)
        self.Gun_Fine_Update_Start_Button.setStyleSheet("Text-align:left")
        self.Gun_Fine_Update_Start_Button.setFlat(False)
        self.Gun_Fine_Update_Start_Button.setObjectName("Gun_Fine_Update_Start_Button")
        self.gridLayout_5.addWidget(self.Gun_Fine_Update_Start_Button, 2, 0, 1, 1)
        self.Gun_Fine_Screen_Button = QtWidgets.QPushButton(self.Gun_Fine_Crest)
        self.Gun_Fine_Screen_Button.setMinimumSize(QtCore.QSize(0, 23))
        self.Gun_Fine_Screen_Button.setObjectName("Gun_Fine_Screen_Button")
        self.gridLayout_5.addWidget(self.Gun_Fine_Screen_Button, 4, 0, 1, 4)
        self.verticalLayout.addWidget(self.Gun_Fine_Crest)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Gun_Dipole_Set = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.Gun_Dipole_Set.setEnabled(True)
        self.Gun_Dipole_Set.setObjectName("Gun_Dipole_Set")
        self.gridLayout_3.addWidget(self.Gun_Dipole_Set, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 0, 0, 1, 1)
        self.Gun_Momentum_Set = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.Gun_Momentum_Set.setSingleStep(0.1)
        self.Gun_Momentum_Set.setObjectName("Gun_Momentum_Set")
        self.gridLayout_3.addWidget(self.Gun_Momentum_Set, 1, 0, 1, 1)
        self.Gun_EnergySet_Button = QtWidgets.QPushButton(self.groupBox_2)
        self.Gun_EnergySet_Button.setEnabled(False)
        self.Gun_EnergySet_Button.setObjectName("Gun_EnergySet_Button")
        self.gridLayout_3.addWidget(self.Gun_EnergySet_Button, 2, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.Gun_Set_Phase = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gun_Set_Phase.sizePolicy().hasHeightForWidth())
        self.Gun_Set_Phase.setSizePolicy(sizePolicy)
        self.Gun_Set_Phase.setMinimumSize(QtCore.QSize(0, 0))
        self.Gun_Set_Phase.setObjectName("Gun_Set_Phase")
        self.formLayout = QtWidgets.QFormLayout(self.Gun_Set_Phase)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.Gun_Set_Phase)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.Gun_SetPhase_Button = QtWidgets.QPushButton(self.Gun_Set_Phase)
        self.Gun_SetPhase_Button.setChecked(False)
        self.Gun_SetPhase_Button.setObjectName("Gun_SetPhase_Button")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.Gun_SetPhase_Button)
        self.Gun_OffCrest_Phase_Set = QtWidgets.QDoubleSpinBox(self.Gun_Set_Phase)
        self.Gun_OffCrest_Phase_Set.setDecimals(1)
        self.Gun_OffCrest_Phase_Set.setMinimum(-30.0)
        self.Gun_OffCrest_Phase_Set.setMaximum(30.0)
        self.Gun_OffCrest_Phase_Set.setSingleStep(0.5)
        self.Gun_OffCrest_Phase_Set.setObjectName("Gun_OffCrest_Phase_Set")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Gun_OffCrest_Phase_Set)
        self.verticalLayout.addWidget(self.Gun_Set_Phase)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout_7.addWidget(self.widget, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Resources/Icons/pistol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Gun_Tab, icon2, "")
        self.linac1_Tab = QtWidgets.QWidget()
        self.linac1_Tab.setObjectName("linac1_Tab")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.linac1_Tab)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.Linac1_Plots_Box = QtWidgets.QGroupBox(self.linac1_Tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Linac1_Plots_Box.sizePolicy().hasHeightForWidth())
        self.Linac1_Plots_Box.setSizePolicy(sizePolicy)
        self.Linac1_Plots_Box.setObjectName("Linac1_Plots_Box")
        self.Linac1_Plots_Layout = QtWidgets.QVBoxLayout(self.Linac1_Plots_Box)
        self.Linac1_Plots_Layout.setObjectName("Linac1_Plots_Layout")
        self.gridLayout_11.addWidget(self.Linac1_Plots_Box, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.linac1_Tab)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Linac1_Startup = QtWidgets.QGroupBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Linac1_Startup.sizePolicy().hasHeightForWidth())
        self.Linac1_Startup.setSizePolicy(sizePolicy)
        self.Linac1_Startup.setMinimumSize(QtCore.QSize(150, 0))
        self.Linac1_Startup.setObjectName("Linac1_Startup")
        self.formLayout_2 = QtWidgets.QFormLayout(self.Linac1_Startup)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_16 = QtWidgets.QLabel(self.Linac1_Startup)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.Linac1_Amp_Step_Set = QtWidgets.QSpinBox(self.Linac1_Startup)
        self.Linac1_Amp_Step_Set.setMaximum(1000)
        self.Linac1_Amp_Step_Set.setSingleStep(100)
        self.Linac1_Amp_Step_Set.setProperty("value", 500)
        self.Linac1_Amp_Step_Set.setObjectName("Linac1_Amp_Step_Set")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Linac1_Amp_Step_Set)
        self.label_15 = QtWidgets.QLabel(self.Linac1_Startup)
        self.label_15.setMinimumSize(QtCore.QSize(142, 0))
        self.label_15.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.Linac1_Amp_Set = QtWidgets.QSpinBox(self.Linac1_Startup)
        self.Linac1_Amp_Set.setMaximum(42500)
        self.Linac1_Amp_Set.setSingleStep(100)
        self.Linac1_Amp_Set.setProperty("value", 40000)
        self.Linac1_Amp_Set.setObjectName("Linac1_Amp_Set")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Linac1_Amp_Set)
        self.Linac1_TurnOn_Button = QtWidgets.QPushButton(self.Linac1_Startup)
        self.Linac1_TurnOn_Button.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Linac1_TurnOn_Button.setFont(font)
        self.Linac1_TurnOn_Button.setObjectName("Linac1_TurnOn_Button")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.Linac1_TurnOn_Button)
        self.Linac1_LoadBURT_Button = QtWidgets.QPushButton(self.Linac1_Startup)
        self.Linac1_LoadBURT_Button.setObjectName("Linac1_LoadBURT_Button")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.Linac1_LoadBURT_Button)
        self.label_34 = QtWidgets.QLabel(self.Linac1_Startup)
        self.label_34.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_34.setLineWidth(1)
        self.label_34.setObjectName("label_34")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.widget_2 = QtWidgets.QWidget(self.Linac1_Startup)
        self.widget_2.setMinimumSize(QtCore.QSize(73, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(92, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Linac1_LinacTiming_Off_Button = QtWidgets.QPushButton(self.widget_2)
        self.Linac1_LinacTiming_Off_Button.setObjectName("Linac1_LinacTiming_Off_Button")
        self.horizontalLayout_3.addWidget(self.Linac1_LinacTiming_Off_Button)
        self.Linac1_LinacTiming_On_Button = QtWidgets.QPushButton(self.widget_2)
        self.Linac1_LinacTiming_On_Button.setMinimumSize(QtCore.QSize(42, 0))
        self.Linac1_LinacTiming_On_Button.setObjectName("Linac1_LinacTiming_On_Button")
        self.horizontalLayout_3.addWidget(self.Linac1_LinacTiming_On_Button)
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.widget_2)
        self.verticalLayout_2.addWidget(self.Linac1_Startup)
        self.Linac1_Rough_Crest = QtWidgets.QGroupBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Linac1_Rough_Crest.sizePolicy().hasHeightForWidth())
        self.Linac1_Rough_Crest.setSizePolicy(sizePolicy)
        self.Linac1_Rough_Crest.setObjectName("Linac1_Rough_Crest")
        self.formLayout_9 = QtWidgets.QFormLayout(self.Linac1_Rough_Crest)
        self.formLayout_9.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_6 = QtWidgets.QLabel(self.Linac1_Rough_Crest)
        self.label_6.setMinimumSize(QtCore.QSize(150, 0))
        self.label_6.setObjectName("label_6")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.Linac1_Rough_NShots_Set = QtWidgets.QSpinBox(self.Linac1_Rough_Crest)
        self.Linac1_Rough_NShots_Set.setMinimum(2)
        self.Linac1_Rough_NShots_Set.setProperty("value", 3)
        self.Linac1_Rough_NShots_Set.setObjectName("Linac1_Rough_NShots_Set")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Linac1_Rough_NShots_Set)
        self.label_17 = QtWidgets.QLabel(self.Linac1_Rough_Crest)
        self.label_17.setObjectName("label_17")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.Linac1_Rough_PointSeperation_Set = QtWidgets.QDoubleSpinBox(self.Linac1_Rough_Crest)
        self.Linac1_Rough_PointSeperation_Set.setDecimals(1)
        self.Linac1_Rough_PointSeperation_Set.setMinimum(0.1)
        self.Linac1_Rough_PointSeperation_Set.setSingleStep(0.1)
        self.Linac1_Rough_PointSeperation_Set.setProperty("value", 5.0)
        self.Linac1_Rough_PointSeperation_Set.setObjectName("Linac1_Rough_PointSeperation_Set")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Linac1_Rough_PointSeperation_Set)
        self.label_9 = QtWidgets.QLabel(self.Linac1_Rough_Crest)
        self.label_9.setObjectName("label_9")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.Linac1_Rough_Fit_Offset = QtWidgets.QSpinBox(self.Linac1_Rough_Crest)
        self.Linac1_Rough_Fit_Offset.setMinimum(-180)
        self.Linac1_Rough_Fit_Offset.setMaximum(180)
        self.Linac1_Rough_Fit_Offset.setObjectName("Linac1_Rough_Fit_Offset")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Linac1_Rough_Fit_Offset)
        self.Linac1_Rough_Button = QtWidgets.QPushButton(self.Linac1_Rough_Crest)
        self.Linac1_Rough_Button.setChecked(False)
        self.Linac1_Rough_Button.setObjectName("Linac1_Rough_Button")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.Linac1_Rough_Button)
        self.verticalLayout_2.addWidget(self.Linac1_Rough_Crest)
        self.Linac1_Dipole_Set_Box = QtWidgets.QGroupBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Linac1_Dipole_Set_Box.sizePolicy().hasHeightForWidth())
        self.Linac1_Dipole_Set_Box.setSizePolicy(sizePolicy)
        self.Linac1_Dipole_Set_Box.setObjectName("Linac1_Dipole_Set_Box")
        self.formLayout_10 = QtWidgets.QFormLayout(self.Linac1_Dipole_Set_Box)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_18 = QtWidgets.QLabel(self.Linac1_Dipole_Set_Box)
        self.label_18.setMinimumSize(QtCore.QSize(150, 0))
        self.label_18.setObjectName("label_18")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.Linac1_Dipole_Set_Box)
        self.label_19.setObjectName("label_19")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.Linac1_Dipole_Start_Set = QtWidgets.QDoubleSpinBox(self.Linac1_Dipole_Set_Box)
        self.Linac1_Dipole_Start_Set.setDecimals(1)
        self.Linac1_Dipole_Start_Set.setMaximum(100.0)
        self.Linac1_Dipole_Start_Set.setProperty("value", 60.0)
        self.Linac1_Dipole_Start_Set.setObjectName("Linac1_Dipole_Start_Set")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Linac1_Dipole_Start_Set)
        self.Linac1_Dipole_End_Set = QtWidgets.QDoubleSpinBox(self.Linac1_Dipole_Set_Box)
        self.Linac1_Dipole_End_Set.setDecimals(1)
        self.Linac1_Dipole_End_Set.setMaximum(120.0)
        self.Linac1_Dipole_End_Set.setProperty("value", 80.0)
        self.Linac1_Dipole_End_Set.setObjectName("Linac1_Dipole_End_Set")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Linac1_Dipole_End_Set)
        self.Linac1_Dipole_Button = QtWidgets.QPushButton(self.Linac1_Dipole_Set_Box)
        self.Linac1_Dipole_Button.setObjectName("Linac1_Dipole_Button")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.Linac1_Dipole_Button)
        self.label_29 = QtWidgets.QLabel(self.Linac1_Dipole_Set_Box)
        self.label_29.setObjectName("label_29")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.Linac1_Dipole_Step_Set = QtWidgets.QDoubleSpinBox(self.Linac1_Dipole_Set_Box)
        self.Linac1_Dipole_Step_Set.setDecimals(1)
        self.Linac1_Dipole_Step_Set.setSingleStep(1.0)
        self.Linac1_Dipole_Step_Set.setProperty("value", 1.0)
        self.Linac1_Dipole_Step_Set.setObjectName("Linac1_Dipole_Step_Set")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Linac1_Dipole_Step_Set)
        self.verticalLayout_2.addWidget(self.Linac1_Dipole_Set_Box)
        self.Linac1_Fine_Crest = QtWidgets.QGroupBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Linac1_Fine_Crest.sizePolicy().hasHeightForWidth())
        self.Linac1_Fine_Crest.setSizePolicy(sizePolicy)
        self.Linac1_Fine_Crest.setObjectName("Linac1_Fine_Crest")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Linac1_Fine_Crest)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Linac1_Fine_PointSeperation_Set = QtWidgets.QDoubleSpinBox(self.Linac1_Fine_Crest)
        self.Linac1_Fine_PointSeperation_Set.setDecimals(1)
        self.Linac1_Fine_PointSeperation_Set.setMinimum(0.1)
        self.Linac1_Fine_PointSeperation_Set.setSingleStep(0.1)
        self.Linac1_Fine_PointSeperation_Set.setProperty("value", 2.0)
        self.Linac1_Fine_PointSeperation_Set.setObjectName("Linac1_Fine_PointSeperation_Set")
        self.gridLayout_6.addWidget(self.Linac1_Fine_PointSeperation_Set, 1, 3, 1, 1)
        self.Linac1_Fine_Range_Set = QtWidgets.QSpinBox(self.Linac1_Fine_Crest)
        self.Linac1_Fine_Range_Set.setProperty("value", 10)
        self.Linac1_Fine_Range_Set.setObjectName("Linac1_Fine_Range_Set")
        self.gridLayout_6.addWidget(self.Linac1_Fine_Range_Set, 2, 3, 1, 1)
        self.Linac1_Fine_NShots_Set = QtWidgets.QSpinBox(self.Linac1_Fine_Crest)
        self.Linac1_Fine_NShots_Set.setMaximum(100)
        self.Linac1_Fine_NShots_Set.setProperty("value", 10)
        self.Linac1_Fine_NShots_Set.setObjectName("Linac1_Fine_NShots_Set")
        self.gridLayout_6.addWidget(self.Linac1_Fine_NShots_Set, 0, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.Linac1_Fine_Crest)
        self.label_26.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 2, 2, 1, 1)
        self.Linac1_Fine_Button = QtWidgets.QPushButton(self.Linac1_Fine_Crest)
        self.Linac1_Fine_Button.setMinimumSize(QtCore.QSize(0, 23))
        self.Linac1_Fine_Button.setChecked(False)
        self.Linac1_Fine_Button.setObjectName("Linac1_Fine_Button")
        self.gridLayout_6.addWidget(self.Linac1_Fine_Button, 3, 0, 1, 4)
        self.label_8 = QtWidgets.QLabel(self.Linac1_Fine_Crest)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.Linac1_Fine_Crest)
        self.label_7.setMinimumSize(QtCore.QSize(150, 0))
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 3)
        self.Linac1_Fine_Range_Start = QtWidgets.QSpinBox(self.Linac1_Fine_Crest)
        self.Linac1_Fine_Range_Start.setMinimum(-180)
        self.Linac1_Fine_Range_Start.setMaximum(180)
        self.Linac1_Fine_Range_Start.setObjectName("Linac1_Fine_Range_Start")
        self.gridLayout_6.addWidget(self.Linac1_Fine_Range_Start, 2, 1, 1, 1)
        self.Linac1_Fine_Update_Start_Button = QtWidgets.QPushButton(self.Linac1_Fine_Crest)
        self.Linac1_Fine_Update_Start_Button.setMinimumSize(QtCore.QSize(0, 19))
        self.Linac1_Fine_Update_Start_Button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Linac1_Fine_Update_Start_Button.setStyleSheet("Text-align:left")
        self.Linac1_Fine_Update_Start_Button.setFlat(False)
        self.Linac1_Fine_Update_Start_Button.setObjectName("Linac1_Fine_Update_Start_Button")
        self.gridLayout_6.addWidget(self.Linac1_Fine_Update_Start_Button, 2, 0, 1, 1)
        self.Linac1_Fine_Screen_Button = QtWidgets.QPushButton(self.Linac1_Fine_Crest)
        self.Linac1_Fine_Screen_Button.setMinimumSize(QtCore.QSize(0, 23))
        self.Linac1_Fine_Screen_Button.setObjectName("Linac1_Fine_Screen_Button")
        self.gridLayout_6.addWidget(self.Linac1_Fine_Screen_Button, 4, 0, 1, 4)
        self.verticalLayout_2.addWidget(self.Linac1_Fine_Crest)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 0, 0, 1, 1)
        self.Linac1_Dipole_Set = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.Linac1_Dipole_Set.setEnabled(True)
        self.Linac1_Dipole_Set.setObjectName("Linac1_Dipole_Set")
        self.gridLayout_4.addWidget(self.Linac1_Dipole_Set, 1, 1, 1, 1)
        self.Linac1_Momentum_Set = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.Linac1_Momentum_Set.setObjectName("Linac1_Momentum_Set")
        self.gridLayout_4.addWidget(self.Linac1_Momentum_Set, 1, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 0, 1, 1, 1)
        self.Linac1_EnergySet_Button = QtWidgets.QPushButton(self.groupBox_3)
        self.Linac1_EnergySet_Button.setEnabled(False)
        self.Linac1_EnergySet_Button.setObjectName("Linac1_EnergySet_Button")
        self.gridLayout_4.addWidget(self.Linac1_EnergySet_Button, 2, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.Linac1_Set_Phase = QtWidgets.QGroupBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Linac1_Set_Phase.sizePolicy().hasHeightForWidth())
        self.Linac1_Set_Phase.setSizePolicy(sizePolicy)
        self.Linac1_Set_Phase.setMinimumSize(QtCore.QSize(0, 0))
        self.Linac1_Set_Phase.setObjectName("Linac1_Set_Phase")
        self.formLayout_4 = QtWidgets.QFormLayout(self.Linac1_Set_Phase)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_20 = QtWidgets.QLabel(self.Linac1_Set_Phase)
        self.label_20.setMinimumSize(QtCore.QSize(150, 0))
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.Linac1_SetPhase_Button = QtWidgets.QPushButton(self.Linac1_Set_Phase)
        self.Linac1_SetPhase_Button.setChecked(False)
        self.Linac1_SetPhase_Button.setObjectName("Linac1_SetPhase_Button")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.Linac1_SetPhase_Button)
        self.Linac1_OffCrest_Phase_Set = QtWidgets.QDoubleSpinBox(self.Linac1_Set_Phase)
        self.Linac1_OffCrest_Phase_Set.setDecimals(1)
        self.Linac1_OffCrest_Phase_Set.setMinimum(-30.0)
        self.Linac1_OffCrest_Phase_Set.setMaximum(30.0)
        self.Linac1_OffCrest_Phase_Set.setSingleStep(0.5)
        self.Linac1_OffCrest_Phase_Set.setObjectName("Linac1_OffCrest_Phase_Set")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Linac1_OffCrest_Phase_Set)
        self.verticalLayout_2.addWidget(self.Linac1_Set_Phase)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.gridLayout_11.addWidget(self.widget_3, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../Resources/Icons/bike.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.linac1_Tab, icon3, "")
        self.magnetTab = QtWidgets.QWidget()
        self.magnetTab.setObjectName("magnetTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.magnetTab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_magnets = QtWidgets.QGroupBox(self.magnetTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_magnets.sizePolicy().hasHeightForWidth())
        self.groupBox_magnets.setSizePolicy(sizePolicy)
        self.groupBox_magnets.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_magnets.setObjectName("groupBox_magnets")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_magnets)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_deguassQ = QtWidgets.QCheckBox(self.groupBox_magnets)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../Resources/Icons/Quadrupoles.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_deguassQ.setIcon(icon4)
        self.checkBox_deguassQ.setObjectName("checkBox_deguassQ")
        self.verticalLayout_3.addWidget(self.checkBox_deguassQ)
        self.checkBox_deguassD = QtWidgets.QCheckBox(self.groupBox_magnets)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../Resources/Icons/Dipoles.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_deguassD.setIcon(icon5)
        self.checkBox_deguassD.setObjectName("checkBox_deguassD")
        self.verticalLayout_3.addWidget(self.checkBox_deguassD)
        self.checkBox_deguassC = QtWidgets.QCheckBox(self.groupBox_magnets)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../Resources/Icons/Correctors.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_deguassC.setIcon(icon6)
        self.checkBox_deguassC.setObjectName("checkBox_deguassC")
        self.verticalLayout_3.addWidget(self.checkBox_deguassC)
        self.checkBox_deguassS = QtWidgets.QCheckBox(self.groupBox_magnets)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../Resources/Icons/Solenoids.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_deguassS.setIcon(icon7)
        self.checkBox_deguassS.setObjectName("checkBox_deguassS")
        self.verticalLayout_3.addWidget(self.checkBox_deguassS)
        self.checkBox_quadOff = QtWidgets.QCheckBox(self.groupBox_magnets)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../Resources/Icons/Quadrupoles_Off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_quadOff.setIcon(icon8)
        self.checkBox_quadOff.setObjectName("checkBox_quadOff")
        self.verticalLayout_3.addWidget(self.checkBox_quadOff)
        self.checkBox_corrOff = QtWidgets.QCheckBox(self.groupBox_magnets)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../Resources/Icons/Correctors_Off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_corrOff.setIcon(icon9)
        self.checkBox_corrOff.setObjectName("checkBox_corrOff")
        self.verticalLayout_3.addWidget(self.checkBox_corrOff)
        self.setupMagnetsButton = QtWidgets.QPushButton(self.groupBox_magnets)
        self.setupMagnetsButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.setupMagnetsButton.setChecked(False)
        self.setupMagnetsButton.setObjectName("setupMagnetsButton")
        self.verticalLayout_3.addWidget(self.setupMagnetsButton)
        self.verticalLayout_7.addWidget(self.groupBox_magnets)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../Resources/Icons/magnet_greyscale.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.magnetTab, icon10, "")
        self.logTab = QtWidgets.QWidget()
        self.logTab.setObjectName("logTab")
        self.logTabLayout = QtWidgets.QVBoxLayout(self.logTab)
        self.logTabLayout.setObjectName("logTabLayout")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../Resources/Icons/log.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.logTab, icon11, "")
        self.centralWidgetLayout.addWidget(self.tabWidget, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1139, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSave_Data = QtWidgets.QMenu(self.menubar)
        self.menuSave_Data.setObjectName("menuSave_Data")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_Calibation_Data = QtWidgets.QAction(MainWindow)
        self.actionSave_Calibation_Data.setObjectName("actionSave_Calibation_Data")
        self.actionAuto_Save_Data = QtWidgets.QAction(MainWindow)
        self.actionAuto_Save_Data.setCheckable(True)
        self.actionAuto_Save_Data.setChecked(True)
        self.actionAuto_Save_Data.setObjectName("actionAuto_Save_Data")
        self.actionSave_to_Work_Folder = QtWidgets.QAction(MainWindow)
        self.actionSave_to_Work_Folder.setCheckable(True)
        self.actionSave_to_Work_Folder.setChecked(True)
        self.actionSave_to_Work_Folder.setObjectName("actionSave_to_Work_Folder")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_Defaults = QtWidgets.QAction(MainWindow)
        self.actionSave_Defaults.setObjectName("actionSave_Defaults")
        self.actionReload_Defaults = QtWidgets.QAction(MainWindow)
        self.actionReload_Defaults.setObjectName("actionReload_Defaults")
        self.actionApply_Default_Settings = QtWidgets.QAction(MainWindow)
        self.actionApply_Default_Settings.setObjectName("actionApply_Default_Settings")
        self.menuFile.addAction(self.actionReload_Defaults)
        self.menuFile.addAction(self.actionSave_Defaults)
        self.menuFile.addAction(self.actionApply_Default_Settings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSave_Data.addAction(self.actionAuto_Save_Data)
        self.menuSave_Data.addAction(self.actionSave_to_Work_Folder)
        self.menuSave_Data.addAction(self.actionSave_Calibation_Data)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSave_Data.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Gun_Amp_Set, self.Gun_TurnOn_Button)
        MainWindow.setTabOrder(self.Gun_TurnOn_Button, self.Gun_LoadBURT_Button)
        MainWindow.setTabOrder(self.Gun_LoadBURT_Button, self.Gun_LinacTiming_Off_Button)
        MainWindow.setTabOrder(self.Gun_LinacTiming_Off_Button, self.Gun_Rough_NShots_Set)
        MainWindow.setTabOrder(self.Gun_Rough_NShots_Set, self.Gun_Rough_PointSeperation_Set)
        MainWindow.setTabOrder(self.Gun_Rough_PointSeperation_Set, self.Gun_Rough_Fit_Offset)
        MainWindow.setTabOrder(self.Gun_Rough_Fit_Offset, self.Gun_Rough_Button)
        MainWindow.setTabOrder(self.Gun_Rough_Button, self.Gun_Dipole_Start_Set)
        MainWindow.setTabOrder(self.Gun_Dipole_Start_Set, self.Gun_Dipole_End_Set)
        MainWindow.setTabOrder(self.Gun_Dipole_End_Set, self.Gun_Dipole_Step_Set)
        MainWindow.setTabOrder(self.Gun_Dipole_Step_Set, self.Gun_Dipole_Button)
        MainWindow.setTabOrder(self.Gun_Dipole_Button, self.Gun_Fine_NShots_Set)
        MainWindow.setTabOrder(self.Gun_Fine_NShots_Set, self.Gun_Fine_PointSeperation_Set)
        MainWindow.setTabOrder(self.Gun_Fine_PointSeperation_Set, self.Gun_Fine_Update_Start_Button)
        MainWindow.setTabOrder(self.Gun_Fine_Update_Start_Button, self.Gun_Fine_Range_Start)
        MainWindow.setTabOrder(self.Gun_Fine_Range_Start, self.Gun_Fine_Range_Set)
        MainWindow.setTabOrder(self.Gun_Fine_Range_Set, self.Gun_Fine_Button)
        MainWindow.setTabOrder(self.Gun_Fine_Button, self.Gun_Fine_Screen_Button)
        MainWindow.setTabOrder(self.Gun_Fine_Screen_Button, self.Gun_Momentum_Set)
        MainWindow.setTabOrder(self.Gun_Momentum_Set, self.Gun_Dipole_Set)
        MainWindow.setTabOrder(self.Gun_Dipole_Set, self.Gun_EnergySet_Button)
        MainWindow.setTabOrder(self.Gun_EnergySet_Button, self.Gun_OffCrest_Phase_Set)
        MainWindow.setTabOrder(self.Gun_OffCrest_Phase_Set, self.Gun_SetPhase_Button)
        MainWindow.setTabOrder(self.Gun_SetPhase_Button, self.Linac1_Amp_Step_Set)
        MainWindow.setTabOrder(self.Linac1_Amp_Step_Set, self.Linac1_Amp_Set)
        MainWindow.setTabOrder(self.Linac1_Amp_Set, self.Linac1_TurnOn_Button)
        MainWindow.setTabOrder(self.Linac1_TurnOn_Button, self.Linac1_LoadBURT_Button)
        MainWindow.setTabOrder(self.Linac1_LoadBURT_Button, self.Linac1_LinacTiming_Off_Button)
        MainWindow.setTabOrder(self.Linac1_LinacTiming_Off_Button, self.Linac1_LinacTiming_On_Button)
        MainWindow.setTabOrder(self.Linac1_LinacTiming_On_Button, self.Linac1_Rough_NShots_Set)
        MainWindow.setTabOrder(self.Linac1_Rough_NShots_Set, self.Linac1_Rough_PointSeperation_Set)
        MainWindow.setTabOrder(self.Linac1_Rough_PointSeperation_Set, self.Linac1_Rough_Fit_Offset)
        MainWindow.setTabOrder(self.Linac1_Rough_Fit_Offset, self.Linac1_Rough_Button)
        MainWindow.setTabOrder(self.Linac1_Rough_Button, self.Linac1_Dipole_Start_Set)
        MainWindow.setTabOrder(self.Linac1_Dipole_Start_Set, self.Linac1_Dipole_End_Set)
        MainWindow.setTabOrder(self.Linac1_Dipole_End_Set, self.Linac1_Dipole_Step_Set)
        MainWindow.setTabOrder(self.Linac1_Dipole_Step_Set, self.Linac1_Dipole_Button)
        MainWindow.setTabOrder(self.Linac1_Dipole_Button, self.Linac1_Fine_NShots_Set)
        MainWindow.setTabOrder(self.Linac1_Fine_NShots_Set, self.Linac1_Fine_PointSeperation_Set)
        MainWindow.setTabOrder(self.Linac1_Fine_PointSeperation_Set, self.Linac1_Fine_Update_Start_Button)
        MainWindow.setTabOrder(self.Linac1_Fine_Update_Start_Button, self.Linac1_Fine_Range_Start)
        MainWindow.setTabOrder(self.Linac1_Fine_Range_Start, self.Linac1_Fine_Range_Set)
        MainWindow.setTabOrder(self.Linac1_Fine_Range_Set, self.Linac1_Fine_Button)
        MainWindow.setTabOrder(self.Linac1_Fine_Button, self.Linac1_Fine_Screen_Button)
        MainWindow.setTabOrder(self.Linac1_Fine_Screen_Button, self.Linac1_Momentum_Set)
        MainWindow.setTabOrder(self.Linac1_Momentum_Set, self.Linac1_Dipole_Set)
        MainWindow.setTabOrder(self.Linac1_Dipole_Set, self.Linac1_EnergySet_Button)
        MainWindow.setTabOrder(self.Linac1_EnergySet_Button, self.Linac1_OffCrest_Phase_Set)
        MainWindow.setTabOrder(self.Linac1_OffCrest_Phase_Set, self.Linac1_SetPhase_Button)
        MainWindow.setTabOrder(self.Linac1_SetPhase_Button, self.Finish_Button)
        MainWindow.setTabOrder(self.Finish_Button, self.Abort_Button)
        MainWindow.setTabOrder(self.Abort_Button, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.Dipole_Monitor)
        MainWindow.setTabOrder(self.Dipole_Monitor, self.Gun_Phase_Monitor)
        MainWindow.setTabOrder(self.Gun_Phase_Monitor, self.checkBox_deguassQ)
        MainWindow.setTabOrder(self.checkBox_deguassQ, self.checkBox_deguassD)
        MainWindow.setTabOrder(self.checkBox_deguassD, self.Linac1_Amp_Monitor)
        MainWindow.setTabOrder(self.Linac1_Amp_Monitor, self.checkBox_deguassC)
        MainWindow.setTabOrder(self.checkBox_deguassC, self.checkBox_quadOff)
        MainWindow.setTabOrder(self.checkBox_quadOff, self.checkBox_corrOff)
        MainWindow.setTabOrder(self.checkBox_corrOff, self.setupMagnetsButton)
        MainWindow.setTabOrder(self.setupMagnetsButton, self.Gun_Amp_Monitor)
        MainWindow.setTabOrder(self.Gun_Amp_Monitor, self.Linac1_Phase_Monitor)
        MainWindow.setTabOrder(self.Linac1_Phase_Monitor, self.checkBox_deguassS)
        MainWindow.setTabOrder(self.checkBox_deguassS, self.Linac1_Timing_Monitor)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Autocrester v2"))
        self.groupBox.setTitle(_translate("MainWindow", "Status"))
        self.label_MODE.setText(_translate("MainWindow", "Mode"))
        self.Linac1_Amp_Monitor.setToolTip(_translate("MainWindow", "Linac 1 AMP set"))
        self.Linac1_Amp_Monitor.setSuffix(_translate("MainWindow", " SET"))
        self.Dipole_Monitor.setToolTip(_translate("MainWindow", "C2V Dipole Current"))
        self.Dipole_Monitor.setSuffix(_translate("MainWindow", " A"))
        self.Gun_Phase_Monitor.setToolTip(_translate("MainWindow", "Gun PHASE set"))
        self.Gun_Phase_Monitor.setSuffix(_translate("MainWindow", "°"))
        self.label_31.setText(_translate("MainWindow", "Dipole Current"))
        self.Progress_Monitor.setToolTip(_translate("MainWindow", "Progress of the running scan"))
        self.label_27.setText(_translate("MainWindow", "Gun"))
        self.label_30.setText(_translate("MainWindow", "Linac1"))
        self.Gun_Amp_Monitor.setToolTip(_translate("MainWindow", "Gun AMP set"))
        self.Gun_Amp_Monitor.setSuffix(_translate("MainWindow", " SET"))
        self.Linac1_Phase_Monitor.setToolTip(_translate("MainWindow", "Linac 1 PHASE set"))
        self.Linac1_Phase_Monitor.setSuffix(_translate("MainWindow", "°"))
        self.label_32.setText(_translate("MainWindow", "Progress"))
        self.Linac1_Timing_Monitor.setToolTip(_translate("MainWindow", "Alter the linac timings (GREEN: Linacs timed with beam, RED: Linacs timed away from beam)"))
        self.Save_Data_Buttons.setToolTip(_translate("MainWindow", "Save/Discard cresting data to the work folder"))
        self.Finish_Button.setToolTip(_translate("MainWindow", "Stop the current scan and analyse"))
        self.Finish_Button.setText(_translate("MainWindow", "Finish Scan"))
        self.Abort_Button.setToolTip(_translate("MainWindow", "Abort the current scan"))
        self.Abort_Button.setText(_translate("MainWindow", "Abort"))
        self.Gun_Plots_Box.setTitle(_translate("MainWindow", "Phase Calibration Plots"))
        self.Gun_Startup.setTitle(_translate("MainWindow", "Gun Startup"))
        self.label_33.setText(_translate("MainWindow", "Set Linac Timing away from beam"))
        self.Gun_Amp_Set.setToolTip(_translate("MainWindow", "Ramp amplitude"))
        self.label_14.setText(_translate("MainWindow", "Ramp Rate"))
        self.label_13.setText(_translate("MainWindow", "Amp Set"))
        self.Gun_LoadBURT_Button.setToolTip(_translate("MainWindow", "Load the GunCrest DBURT"))
        self.Gun_LoadBURT_Button.setText(_translate("MainWindow", "Load BURT"))
        self.Gun_TurnOn_Button.setToolTip(_translate("MainWindow", "Ramp Gun up to the maximum in steps"))
        self.Gun_TurnOn_Button.setText(_translate("MainWindow", "Ramp Up Gun"))
        self.Gun_LinacTiming_Off_Button.setToolTip(_translate("MainWindow", "Alter the linac timings to allow cresting of the gun (RED: Linacs timed with beam, GREEN: Linacs timed away from beam)"))
        self.Gun_LinacTiming_Off_Button.setText(_translate("MainWindow", "Set"))
        self.Gun_Amp_Step_Set.setToolTip(_translate("MainWindow", "Ramp Rate"))
        self.Gun_Amp_Step_Set.setSuffix(_translate("MainWindow", "/sec"))
        self.Gun_Rough_Crest.setTitle(_translate("MainWindow", "Rough Crest"))
        self.label.setText(_translate("MainWindow", "Number of Shots (per point)"))
        self.Gun_Rough_NShots_Set.setToolTip(_translate("MainWindow", "How many WCM readings to average for each phase"))
        self.label_10.setText(_translate("MainWindow", "Point Seperation"))
        self.Gun_Rough_PointSeperation_Set.setToolTip(_translate("MainWindow", "Phase seperation for the WCM scan"))
        self.Gun_Rough_PointSeperation_Set.setSuffix(_translate("MainWindow", "°"))
        self.label_4.setText(_translate("MainWindow", "Post-fit Offset"))
        self.Gun_Rough_Fit_Offset.setToolTip(_translate("MainWindow", "Correction to the rough phase scan to find the Gun crest"))
        self.Gun_Rough_Fit_Offset.setSuffix(_translate("MainWindow", "°"))
        self.Gun_Rough_Button.setToolTip(_translate("MainWindow", "Use the WCM to roughly find the Gun crest"))
        self.Gun_Rough_Button.setText(_translate("MainWindow", "Approximately Find Crest with WCM"))
        self.Gun_Dipole_Set_Box.setTitle(_translate("MainWindow", "Dipole Set"))
        self.label_11.setText(_translate("MainWindow", "Starting Current"))
        self.label_12.setText(_translate("MainWindow", "Final Current"))
        self.Gun_Dipole_Start_Set.setToolTip(_translate("MainWindow", "Starting current for the C2V dipole"))
        self.Gun_Dipole_Start_Set.setSuffix(_translate("MainWindow", " A"))
        self.Gun_Dipole_End_Set.setToolTip(_translate("MainWindow", "Final current for the C2V dipole"))
        self.Gun_Dipole_End_Set.setSuffix(_translate("MainWindow", " A"))
        self.Gun_Dipole_Button.setToolTip(_translate("MainWindow", "Find the dipole current to center the beam in the C2V dipole"))
        self.Gun_Dipole_Button.setText(_translate("MainWindow", "Find Dipole Current"))
        self.label_28.setText(_translate("MainWindow", "Step Size"))
        self.Gun_Dipole_Step_Set.setToolTip(_translate("MainWindow", "Step size for the C2V dipole"))
        self.Gun_Dipole_Step_Set.setSuffix(_translate("MainWindow", " A"))
        self.Gun_Fine_Crest.setTitle(_translate("MainWindow", "Fine Crest"))
        self.Gun_Fine_NShots_Set.setToolTip(_translate("MainWindow", "Number of BPM readings to average for the BPM phase scan"))
        self.Gun_Fine_PointSeperation_Set.setToolTip(_translate("MainWindow", "Phase seperation for the BPM phase scan"))
        self.Gun_Fine_PointSeperation_Set.setSuffix(_translate("MainWindow", "°"))
        self.Gun_Fine_Range_Set.setToolTip(_translate("MainWindow", "Range over which to scan for the BPM phase scan"))
        self.Gun_Fine_Range_Set.setSuffix(_translate("MainWindow", "°"))
        self.Gun_Fine_Button.setToolTip(_translate("MainWindow", "Accurately crest the Gun with the C2V BPM"))
        self.Gun_Fine_Button.setText(_translate("MainWindow", "Fine Crest Gun with BPM"))
        self.label_25.setText(_translate("MainWindow", "±"))
        self.label_5.setText(_translate("MainWindow", "Point Seperation"))
        self.label_3.setText(_translate("MainWindow", "Number of Shots (per point)"))
        self.Gun_Fine_Range_Start.setToolTip(_translate("MainWindow", "Center point of the BPM phase scan"))
        self.Gun_Fine_Range_Start.setSuffix(_translate("MainWindow", "°"))
        self.Gun_Fine_Update_Start_Button.setToolTip(_translate("MainWindow", "Press to set the center point of the phase scan to the current Gun phase"))
        self.Gun_Fine_Update_Start_Button.setText(_translate("MainWindow", "Scan From"))
        self.Gun_Fine_Screen_Button.setToolTip(_translate("MainWindow", "Accurately crest the Gun with the C2V Screen - Screen must be in!"))
        self.Gun_Fine_Screen_Button.setText(_translate("MainWindow", "Fine Crest Gun with Screen"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Set Momentum"))
        self.Gun_Dipole_Set.setToolTip(_translate("MainWindow", "C2V dipole current equivalent for the beam momentum"))
        self.Gun_Dipole_Set.setSuffix(_translate("MainWindow", " A"))
        self.label_22.setText(_translate("MainWindow", "Dipole Current"))
        self.label_21.setText(_translate("MainWindow", "Momentum"))
        self.Gun_Momentum_Set.setToolTip(_translate("MainWindow", "Momentum equivalent for the C2V dipole current"))
        self.Gun_Momentum_Set.setSuffix(_translate("MainWindow", " MeV/c"))
        self.Gun_EnergySet_Button.setText(_translate("MainWindow", "Set Dipole Current"))
        self.Gun_Set_Phase.setTitle(_translate("MainWindow", "Set Final Phase"))
        self.label_2.setText(_translate("MainWindow", "Off-crest Phase"))
        self.Gun_SetPhase_Button.setToolTip(_translate("MainWindow", "Set the final Gun phase as crest + Off-crest phase"))
        self.Gun_SetPhase_Button.setText(_translate("MainWindow", "Set Gun Phase"))
        self.Gun_OffCrest_Phase_Set.setToolTip(_translate("MainWindow", "Phase offset from crest for the Gun"))
        self.Gun_OffCrest_Phase_Set.setSuffix(_translate("MainWindow", "°"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Gun_Tab), _translate("MainWindow", "Gun"))
        self.Linac1_Plots_Box.setTitle(_translate("MainWindow", "Phase Calibration Plots"))
        self.Linac1_Startup.setTitle(_translate("MainWindow", "Linac Startup"))
        self.label_16.setText(_translate("MainWindow", "Ramp Rate"))
        self.Linac1_Amp_Step_Set.setToolTip(_translate("MainWindow", "Ramp Rate"))
        self.Linac1_Amp_Step_Set.setSuffix(_translate("MainWindow", "/sec"))
        self.label_15.setText(_translate("MainWindow", "Amp Set"))
        self.Linac1_Amp_Set.setToolTip(_translate("MainWindow", "Ramp amplitude"))
        self.Linac1_TurnOn_Button.setToolTip(_translate("MainWindow", "Ramp Linac 1 up to the maximum in steps"))
        self.Linac1_TurnOn_Button.setText(_translate("MainWindow", "Ramp Up Linac"))
        self.Linac1_LoadBURT_Button.setToolTip(_translate("MainWindow", "Load the LinacCrest DBURT"))
        self.Linac1_LoadBURT_Button.setText(_translate("MainWindow", "Load BURT"))
        self.label_34.setText(_translate("MainWindow", "Set Linac 1 Timing"))
        self.Linac1_LinacTiming_Off_Button.setToolTip(_translate("MainWindow", "Alter the linac 1 timing to disallow cresting (RED: Linacs timed with beam, GREEN: Linacs timed away from beam)"))
        self.Linac1_LinacTiming_Off_Button.setText(_translate("MainWindow", "Away"))
        self.Linac1_LinacTiming_On_Button.setToolTip(_translate("MainWindow", "Alter the linac 1 timing to allow cresting (GREEN: Linacs timed with beam, RED: Linacs timed away from beam)"))
        self.Linac1_LinacTiming_On_Button.setText(_translate("MainWindow", "Normal"))
        self.Linac1_Rough_Crest.setTitle(_translate("MainWindow", "Rough Crest"))
        self.label_6.setText(_translate("MainWindow", "Number of Shots (per point)"))
        self.Linac1_Rough_NShots_Set.setToolTip(_translate("MainWindow", "How many BPM readings to average for each phase"))
        self.label_17.setText(_translate("MainWindow", "Point Seperation"))
        self.Linac1_Rough_PointSeperation_Set.setToolTip(_translate("MainWindow", "Phase seperation for the rough BPM scan"))
        self.Linac1_Rough_PointSeperation_Set.setSuffix(_translate("MainWindow", "°"))
        self.label_9.setText(_translate("MainWindow", "Post-fit Offset"))
        self.Linac1_Rough_Fit_Offset.setToolTip(_translate("MainWindow", "Correction to the rough phase scan to find the Linac 1 crest"))
        self.Linac1_Rough_Fit_Offset.setSuffix(_translate("MainWindow", "°"))
        self.Linac1_Rough_Button.setToolTip(_translate("MainWindow", "Use the S02 BPM to roughly find the Linac 1 crest"))
        self.Linac1_Rough_Button.setText(_translate("MainWindow", "Approximately Find Crest with BPM"))
        self.Linac1_Dipole_Set_Box.setTitle(_translate("MainWindow", "Dipole Set"))
        self.label_18.setText(_translate("MainWindow", "Starting Current"))
        self.label_19.setText(_translate("MainWindow", "Final Current"))
        self.Linac1_Dipole_Start_Set.setToolTip(_translate("MainWindow", "Starting current for the C2V dipole"))
        self.Linac1_Dipole_Start_Set.setSuffix(_translate("MainWindow", " A"))
        self.Linac1_Dipole_End_Set.setToolTip(_translate("MainWindow", "Final current for the C2V dipole"))
        self.Linac1_Dipole_End_Set.setSuffix(_translate("MainWindow", " A"))
        self.Linac1_Dipole_Button.setToolTip(_translate("MainWindow", "Find the dipole current to center the beam in the C2V dipole"))
        self.Linac1_Dipole_Button.setText(_translate("MainWindow", "Find Dipole Current"))
        self.label_29.setText(_translate("MainWindow", "Step Size"))
        self.Linac1_Dipole_Step_Set.setToolTip(_translate("MainWindow", "Step size for the C2V dipole"))
        self.Linac1_Dipole_Step_Set.setSuffix(_translate("MainWindow", " A"))
        self.Linac1_Fine_Crest.setTitle(_translate("MainWindow", "Fine Crest"))
        self.Linac1_Fine_PointSeperation_Set.setToolTip(_translate("MainWindow", "Phase seperation for the C2V BPM phase scan"))
        self.Linac1_Fine_PointSeperation_Set.setSuffix(_translate("MainWindow", "°"))
        self.Linac1_Fine_Range_Set.setToolTip(_translate("MainWindow", "Range over which to scan for the C2V BPM phase scan"))
        self.Linac1_Fine_Range_Set.setSuffix(_translate("MainWindow", "°"))
        self.Linac1_Fine_NShots_Set.setToolTip(_translate("MainWindow", "Number of BPM readings to average for the C2V BPM phase scan"))
        self.label_26.setText(_translate("MainWindow", "±"))
        self.Linac1_Fine_Button.setToolTip(_translate("MainWindow", "Accurately crest Linac 1 with the C2V BPM"))
        self.Linac1_Fine_Button.setText(_translate("MainWindow", "Fine Crest Linac with BPM"))
        self.label_8.setText(_translate("MainWindow", "Point Seperation"))
        self.label_7.setText(_translate("MainWindow", "Number of Shots (per point)"))
        self.Linac1_Fine_Range_Start.setToolTip(_translate("MainWindow", "Center point of the C2V BPM phase scan"))
        self.Linac1_Fine_Range_Start.setSuffix(_translate("MainWindow", "°"))
        self.Linac1_Fine_Update_Start_Button.setToolTip(_translate("MainWindow", "Press to set the center point of the phase scan to the current Linac 1 phase"))
        self.Linac1_Fine_Update_Start_Button.setText(_translate("MainWindow", "Scan From"))
        self.Linac1_Fine_Screen_Button.setToolTip(_translate("MainWindow", "Accurately crest Linac 1 with the C2V Screen - Screen must be in!"))
        self.Linac1_Fine_Screen_Button.setText(_translate("MainWindow", "Fine Crest Linac with Screen"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Set Momentum"))
        self.label_23.setText(_translate("MainWindow", "Momentum"))
        self.Linac1_Dipole_Set.setToolTip(_translate("MainWindow", "C2V dipole current equivalent for the beam momentum"))
        self.Linac1_Dipole_Set.setSuffix(_translate("MainWindow", " A"))
        self.Linac1_Momentum_Set.setToolTip(_translate("MainWindow", "Momentum equivalent for the C2V dipole current"))
        self.Linac1_Momentum_Set.setSuffix(_translate("MainWindow", " MeV/c"))
        self.label_24.setText(_translate("MainWindow", "Dipole Current"))
        self.Linac1_EnergySet_Button.setText(_translate("MainWindow", "Set Dipole Current"))
        self.Linac1_Set_Phase.setTitle(_translate("MainWindow", "Set Final Phase"))
        self.label_20.setText(_translate("MainWindow", "Off-crest Phase"))
        self.Linac1_SetPhase_Button.setToolTip(_translate("MainWindow", "Set the final Linac 1 phase as crest + Off-crest phase"))
        self.Linac1_SetPhase_Button.setText(_translate("MainWindow", "Set Linac Phase"))
        self.Linac1_OffCrest_Phase_Set.setToolTip(_translate("MainWindow", "Phase offset from crest for Linac 1"))
        self.Linac1_OffCrest_Phase_Set.setSuffix(_translate("MainWindow", "°"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.linac1_Tab), _translate("MainWindow", "Linac 1"))
        self.groupBox_magnets.setTitle(_translate("MainWindow", "Magnets"))
        self.checkBox_deguassQ.setText(_translate("MainWindow", "Deguass Quadruoles"))
        self.checkBox_deguassD.setText(_translate("MainWindow", "Deguass Dipoles"))
        self.checkBox_deguassC.setText(_translate("MainWindow", "Deguass Correctors"))
        self.checkBox_deguassS.setText(_translate("MainWindow", "Deguass Solenoids"))
        self.checkBox_quadOff.setText(_translate("MainWindow", "Turn Off Quads"))
        self.checkBox_corrOff.setText(_translate("MainWindow", "Turn Off Correctors"))
        self.setupMagnetsButton.setText(_translate("MainWindow", "Degauss Magnets"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.magnetTab), _translate("MainWindow", "Magnets"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logTab), _translate("MainWindow", "Log"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSave_Data.setTitle(_translate("MainWindow", "Save Data"))
        self.actionSave_Calibation_Data.setText(_translate("MainWindow", "Save Calibation Data"))
        self.actionAuto_Save_Data.setText(_translate("MainWindow", "Auto Save Data"))
        self.actionSave_to_Work_Folder.setText(_translate("MainWindow", "Save to Work Folder"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSave_Defaults.setText(_translate("MainWindow", "Save Settings"))
        self.actionReload_Defaults.setText(_translate("MainWindow", "Reload Settings"))
        self.actionApply_Default_Settings.setText(_translate("MainWindow", "Apply Default Settings"))

