# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1040, 886)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../Resources/Icons/mountain-summit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.centralWidgetLayout = QtGui.QGridLayout(self.centralwidget)
        self.centralWidgetLayout.setObjectName(_fromUtf8("centralWidgetLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_MODE = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_MODE.sizePolicy().hasHeightForWidth())
        self.label_MODE.setSizePolicy(sizePolicy)
        self.label_MODE.setMinimumSize(QtCore.QSize(0, 25))
        self.label_MODE.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_MODE.setObjectName(_fromUtf8("label_MODE"))
        self.gridLayout_2.addWidget(self.label_MODE, 1, 0, 1, 1)
        self.Finish_Button = QtGui.QPushButton(self.groupBox)
        self.Finish_Button.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Finish_Button.setObjectName(_fromUtf8("Finish_Button"))
        self.gridLayout_2.addWidget(self.Finish_Button, 1, 1, 1, 1)
        self.Abort_Button = QtGui.QPushButton(self.groupBox)
        self.Abort_Button.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Abort_Button.setAutoFillBackground(False)
        self.Abort_Button.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Abort_Button.setIcon(icon1)
        self.Abort_Button.setObjectName(_fromUtf8("Abort_Button"))
        self.gridLayout_2.addWidget(self.Abort_Button, 1, 2, 1, 1)
        self.centralWidgetLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Gun_Tab = QtGui.QWidget()
        self.Gun_Tab.setObjectName(_fromUtf8("Gun_Tab"))
        self.gunTabLayout = QtGui.QGridLayout(self.Gun_Tab)
        self.gunTabLayout.setObjectName(_fromUtf8("gunTabLayout"))
        self.Gun_Plots_Box = QtGui.QGroupBox(self.Gun_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gun_Plots_Box.sizePolicy().hasHeightForWidth())
        self.Gun_Plots_Box.setSizePolicy(sizePolicy)
        self.Gun_Plots_Box.setObjectName(_fromUtf8("Gun_Plots_Box"))
        self.Gun_Plots_Layout = QtGui.QVBoxLayout(self.Gun_Plots_Box)
        self.Gun_Plots_Layout.setObjectName(_fromUtf8("Gun_Plots_Layout"))
        self.gunTabLayout.addWidget(self.Gun_Plots_Box, 0, 1, 7, 1)
        self.Gun_Startup = QtGui.QGroupBox(self.Gun_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gun_Startup.sizePolicy().hasHeightForWidth())
        self.Gun_Startup.setSizePolicy(sizePolicy)
        self.Gun_Startup.setObjectName(_fromUtf8("Gun_Startup"))
        self.formLayout_7 = QtGui.QFormLayout(self.Gun_Startup)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.Gun_TurnOn_Button = QtGui.QPushButton(self.Gun_Startup)
        self.Gun_TurnOn_Button.setEnabled(False)
        font = QtGui.QFont()
        font.setStrikeOut(True)
        self.Gun_TurnOn_Button.setFont(font)
        self.Gun_TurnOn_Button.setFlat(False)
        self.Gun_TurnOn_Button.setObjectName(_fromUtf8("Gun_TurnOn_Button"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.SpanningRole, self.Gun_TurnOn_Button)
        self.label_13 = QtGui.QLabel(self.Gun_Startup)
        self.label_13.setMinimumSize(QtCore.QSize(150, 0))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.Gun_Amp_Set = QtGui.QSpinBox(self.Gun_Startup)
        self.Gun_Amp_Set.setMaximum(16280)
        self.Gun_Amp_Set.setSingleStep(100)
        self.Gun_Amp_Set.setProperty("value", 16280)
        self.Gun_Amp_Set.setObjectName(_fromUtf8("Gun_Amp_Set"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.Gun_Amp_Set)
        self.label_14 = QtGui.QLabel(self.Gun_Startup)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.Gun_Amp_Step_Set = QtGui.QSpinBox(self.Gun_Startup)
        self.Gun_Amp_Step_Set.setMaximum(1000)
        self.Gun_Amp_Step_Set.setSingleStep(100)
        self.Gun_Amp_Step_Set.setProperty("value", 100)
        self.Gun_Amp_Step_Set.setObjectName(_fromUtf8("Gun_Amp_Step_Set"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.Gun_Amp_Step_Set)
        self.gunTabLayout.addWidget(self.Gun_Startup, 0, 0, 1, 1)
        self.Gun_Rough_Crest = QtGui.QGroupBox(self.Gun_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gun_Rough_Crest.sizePolicy().hasHeightForWidth())
        self.Gun_Rough_Crest.setSizePolicy(sizePolicy)
        self.Gun_Rough_Crest.setObjectName(_fromUtf8("Gun_Rough_Crest"))
        self.formLayout_5 = QtGui.QFormLayout(self.Gun_Rough_Crest)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label = QtGui.QLabel(self.Gun_Rough_Crest)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_10 = QtGui.QLabel(self.Gun_Rough_Crest)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.Gun_Rough_Button = QtGui.QPushButton(self.Gun_Rough_Crest)
        self.Gun_Rough_Button.setChecked(False)
        self.Gun_Rough_Button.setObjectName(_fromUtf8("Gun_Rough_Button"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.SpanningRole, self.Gun_Rough_Button)
        self.Gun_Rough_NShots_Set = QtGui.QSpinBox(self.Gun_Rough_Crest)
        self.Gun_Rough_NShots_Set.setMinimum(2)
        self.Gun_Rough_NShots_Set.setProperty("value", 3)
        self.Gun_Rough_NShots_Set.setObjectName(_fromUtf8("Gun_Rough_NShots_Set"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.Gun_Rough_NShots_Set)
        self.Gun_Rough_PointSeperation_Set = QtGui.QDoubleSpinBox(self.Gun_Rough_Crest)
        self.Gun_Rough_PointSeperation_Set.setDecimals(1)
        self.Gun_Rough_PointSeperation_Set.setMinimum(0.1)
        self.Gun_Rough_PointSeperation_Set.setSingleStep(0.1)
        self.Gun_Rough_PointSeperation_Set.setProperty("value", 5.0)
        self.Gun_Rough_PointSeperation_Set.setObjectName(_fromUtf8("Gun_Rough_PointSeperation_Set"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.Gun_Rough_PointSeperation_Set)
        self.gunTabLayout.addWidget(self.Gun_Rough_Crest, 1, 0, 1, 1)
        self.Gun_Dipole_Set_Box = QtGui.QGroupBox(self.Gun_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gun_Dipole_Set_Box.sizePolicy().hasHeightForWidth())
        self.Gun_Dipole_Set_Box.setSizePolicy(sizePolicy)
        self.Gun_Dipole_Set_Box.setObjectName(_fromUtf8("Gun_Dipole_Set_Box"))
        self.formLayout_6 = QtGui.QFormLayout(self.Gun_Dipole_Set_Box)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_11 = QtGui.QLabel(self.Gun_Dipole_Set_Box)
        self.label_11.setMinimumSize(QtCore.QSize(150, 0))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtGui.QLabel(self.Gun_Dipole_Set_Box)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_12)
        self.Gun_Dipole_Start_Set = QtGui.QDoubleSpinBox(self.Gun_Dipole_Set_Box)
        self.Gun_Dipole_Start_Set.setDecimals(1)
        self.Gun_Dipole_Start_Set.setProperty("value", 7.0)
        self.Gun_Dipole_Start_Set.setObjectName(_fromUtf8("Gun_Dipole_Start_Set"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.Gun_Dipole_Start_Set)
        self.Gun_Dipole_End_Set = QtGui.QDoubleSpinBox(self.Gun_Dipole_Set_Box)
        self.Gun_Dipole_End_Set.setDecimals(1)
        self.Gun_Dipole_End_Set.setProperty("value", 10.0)
        self.Gun_Dipole_End_Set.setObjectName(_fromUtf8("Gun_Dipole_End_Set"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.Gun_Dipole_End_Set)
        self.Gun_Dipole_Button = QtGui.QPushButton(self.Gun_Dipole_Set_Box)
        self.Gun_Dipole_Button.setObjectName(_fromUtf8("Gun_Dipole_Button"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.SpanningRole, self.Gun_Dipole_Button)
        self.gunTabLayout.addWidget(self.Gun_Dipole_Set_Box, 2, 0, 1, 1)
        self.Gun_Fine_Crest = QtGui.QGroupBox(self.Gun_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gun_Fine_Crest.sizePolicy().hasHeightForWidth())
        self.Gun_Fine_Crest.setSizePolicy(sizePolicy)
        self.Gun_Fine_Crest.setObjectName(_fromUtf8("Gun_Fine_Crest"))
        self.formLayout_2 = QtGui.QFormLayout(self.Gun_Fine_Crest)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_3 = QtGui.QLabel(self.Gun_Fine_Crest)
        self.label_3.setMinimumSize(QtCore.QSize(150, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_5 = QtGui.QLabel(self.Gun_Fine_Crest)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_4 = QtGui.QLabel(self.Gun_Fine_Crest)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.Gun_Fine_Button = QtGui.QPushButton(self.Gun_Fine_Crest)
        self.Gun_Fine_Button.setChecked(False)
        self.Gun_Fine_Button.setObjectName(_fromUtf8("Gun_Fine_Button"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.SpanningRole, self.Gun_Fine_Button)
        self.Gun_Fine_Range_Set = QtGui.QSpinBox(self.Gun_Fine_Crest)
        self.Gun_Fine_Range_Set.setPrefix(_fromUtf8(""))
        self.Gun_Fine_Range_Set.setMinimum(1)
        self.Gun_Fine_Range_Set.setMaximum(30)
        self.Gun_Fine_Range_Set.setProperty("value", 20)
        self.Gun_Fine_Range_Set.setObjectName(_fromUtf8("Gun_Fine_Range_Set"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.Gun_Fine_Range_Set)
        self.Gun_Fine_PointSeperation_Set = QtGui.QDoubleSpinBox(self.Gun_Fine_Crest)
        self.Gun_Fine_PointSeperation_Set.setDecimals(1)
        self.Gun_Fine_PointSeperation_Set.setMinimum(0.1)
        self.Gun_Fine_PointSeperation_Set.setSingleStep(0.1)
        self.Gun_Fine_PointSeperation_Set.setProperty("value", 2.0)
        self.Gun_Fine_PointSeperation_Set.setObjectName(_fromUtf8("Gun_Fine_PointSeperation_Set"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.Gun_Fine_PointSeperation_Set)
        self.Gun_Fine_NShots_Set = QtGui.QSpinBox(self.Gun_Fine_Crest)
        self.Gun_Fine_NShots_Set.setMaximum(100)
        self.Gun_Fine_NShots_Set.setProperty("value", 10)
        self.Gun_Fine_NShots_Set.setObjectName(_fromUtf8("Gun_Fine_NShots_Set"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.Gun_Fine_NShots_Set)
        self.gunTabLayout.addWidget(self.Gun_Fine_Crest, 3, 0, 1, 1)
        self.Gun_Set_Phase = QtGui.QGroupBox(self.Gun_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gun_Set_Phase.sizePolicy().hasHeightForWidth())
        self.Gun_Set_Phase.setSizePolicy(sizePolicy)
        self.Gun_Set_Phase.setMinimumSize(QtCore.QSize(0, 0))
        self.Gun_Set_Phase.setObjectName(_fromUtf8("Gun_Set_Phase"))
        self.formLayout = QtGui.QFormLayout(self.Gun_Set_Phase)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(self.Gun_Set_Phase)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.Gun_SetPhase_Button = QtGui.QPushButton(self.Gun_Set_Phase)
        self.Gun_SetPhase_Button.setChecked(False)
        self.Gun_SetPhase_Button.setObjectName(_fromUtf8("Gun_SetPhase_Button"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.Gun_SetPhase_Button)
        self.Gun_OffCrest_Phase_Set = QtGui.QDoubleSpinBox(self.Gun_Set_Phase)
        self.Gun_OffCrest_Phase_Set.setDecimals(1)
        self.Gun_OffCrest_Phase_Set.setMinimum(-30.0)
        self.Gun_OffCrest_Phase_Set.setMaximum(30.0)
        self.Gun_OffCrest_Phase_Set.setSingleStep(0.5)
        self.Gun_OffCrest_Phase_Set.setObjectName(_fromUtf8("Gun_OffCrest_Phase_Set"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.Gun_OffCrest_Phase_Set)
        self.gunTabLayout.addWidget(self.Gun_Set_Phase, 5, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.Gun_Tab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.Gun_Dipole_Set = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.Gun_Dipole_Set.setEnabled(True)
        self.Gun_Dipole_Set.setObjectName(_fromUtf8("Gun_Dipole_Set"))
        self.gridLayout_3.addWidget(self.Gun_Dipole_Set, 1, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_2)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 0, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_3.addWidget(self.label_21, 0, 0, 1, 1)
        self.Gun_Momentum_Set = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.Gun_Momentum_Set.setObjectName(_fromUtf8("Gun_Momentum_Set"))
        self.gridLayout_3.addWidget(self.Gun_Momentum_Set, 1, 0, 1, 1)
        self.Gun_EnergySet_Button = QtGui.QPushButton(self.groupBox_2)
        self.Gun_EnergySet_Button.setObjectName(_fromUtf8("Gun_EnergySet_Button"))
        self.gridLayout_3.addWidget(self.Gun_EnergySet_Button, 2, 0, 1, 2)
        self.gunTabLayout.addWidget(self.groupBox_2, 4, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/pistol.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Gun_Tab, icon2, _fromUtf8(""))
        self.linac1_Tab = QtGui.QWidget()
        self.linac1_Tab.setObjectName(_fromUtf8("linac1_Tab"))
        self.gridLayout = QtGui.QGridLayout(self.linac1_Tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Linac1_Plots_Box = QtGui.QGroupBox(self.linac1_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Linac1_Plots_Box.sizePolicy().hasHeightForWidth())
        self.Linac1_Plots_Box.setSizePolicy(sizePolicy)
        self.Linac1_Plots_Box.setObjectName(_fromUtf8("Linac1_Plots_Box"))
        self.Linac1_Plots_Layout = QtGui.QVBoxLayout(self.Linac1_Plots_Box)
        self.Linac1_Plots_Layout.setObjectName(_fromUtf8("Linac1_Plots_Layout"))
        self.gridLayout.addWidget(self.Linac1_Plots_Box, 0, 2, 7, 1)
        self.Linac1_Startup = QtGui.QGroupBox(self.linac1_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Linac1_Startup.sizePolicy().hasHeightForWidth())
        self.Linac1_Startup.setSizePolicy(sizePolicy)
        self.Linac1_Startup.setObjectName(_fromUtf8("Linac1_Startup"))
        self.formLayout_8 = QtGui.QFormLayout(self.Linac1_Startup)
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.Linac1_TurnOn_Button = QtGui.QPushButton(self.Linac1_Startup)
        self.Linac1_TurnOn_Button.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(True)
        self.Linac1_TurnOn_Button.setFont(font)
        self.Linac1_TurnOn_Button.setObjectName(_fromUtf8("Linac1_TurnOn_Button"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.SpanningRole, self.Linac1_TurnOn_Button)
        self.label_15 = QtGui.QLabel(self.Linac1_Startup)
        self.label_15.setMinimumSize(QtCore.QSize(150, 0))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_15)
        self.Linac1_Amp_Set = QtGui.QSpinBox(self.Linac1_Startup)
        self.Linac1_Amp_Set.setMaximum(13000)
        self.Linac1_Amp_Set.setSingleStep(100)
        self.Linac1_Amp_Set.setProperty("value", 13000)
        self.Linac1_Amp_Set.setObjectName(_fromUtf8("Linac1_Amp_Set"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.Linac1_Amp_Set)
        self.label_16 = QtGui.QLabel(self.Linac1_Startup)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_16)
        self.Linac1_Amp_Step_Set = QtGui.QSpinBox(self.Linac1_Startup)
        self.Linac1_Amp_Step_Set.setMaximum(1000)
        self.Linac1_Amp_Step_Set.setSingleStep(100)
        self.Linac1_Amp_Step_Set.setProperty("value", 100)
        self.Linac1_Amp_Step_Set.setObjectName(_fromUtf8("Linac1_Amp_Step_Set"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.Linac1_Amp_Step_Set)
        self.gridLayout.addWidget(self.Linac1_Startup, 0, 0, 1, 1)
        self.Linac1_Dipole_Set_Box = QtGui.QGroupBox(self.linac1_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Linac1_Dipole_Set_Box.sizePolicy().hasHeightForWidth())
        self.Linac1_Dipole_Set_Box.setSizePolicy(sizePolicy)
        self.Linac1_Dipole_Set_Box.setObjectName(_fromUtf8("Linac1_Dipole_Set_Box"))
        self.formLayout_10 = QtGui.QFormLayout(self.Linac1_Dipole_Set_Box)
        self.formLayout_10.setObjectName(_fromUtf8("formLayout_10"))
        self.label_18 = QtGui.QLabel(self.Linac1_Dipole_Set_Box)
        self.label_18.setMinimumSize(QtCore.QSize(150, 0))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtGui.QLabel(self.Linac1_Dipole_Set_Box)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_19)
        self.Linac1_Dipole_Start_Set = QtGui.QDoubleSpinBox(self.Linac1_Dipole_Set_Box)
        self.Linac1_Dipole_Start_Set.setDecimals(1)
        self.Linac1_Dipole_Start_Set.setMaximum(100.0)
        self.Linac1_Dipole_Start_Set.setProperty("value", 70.0)
        self.Linac1_Dipole_Start_Set.setObjectName(_fromUtf8("Linac1_Dipole_Start_Set"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.FieldRole, self.Linac1_Dipole_Start_Set)
        self.Linac1_Dipole_End_Set = QtGui.QDoubleSpinBox(self.Linac1_Dipole_Set_Box)
        self.Linac1_Dipole_End_Set.setDecimals(1)
        self.Linac1_Dipole_End_Set.setMaximum(120.0)
        self.Linac1_Dipole_End_Set.setProperty("value", 100.0)
        self.Linac1_Dipole_End_Set.setObjectName(_fromUtf8("Linac1_Dipole_End_Set"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.FieldRole, self.Linac1_Dipole_End_Set)
        self.Linac1_Dipole_Button = QtGui.QPushButton(self.Linac1_Dipole_Set_Box)
        self.Linac1_Dipole_Button.setObjectName(_fromUtf8("Linac1_Dipole_Button"))
        self.formLayout_10.setWidget(2, QtGui.QFormLayout.SpanningRole, self.Linac1_Dipole_Button)
        self.gridLayout.addWidget(self.Linac1_Dipole_Set_Box, 2, 0, 1, 1)
        self.Linac1_Rough_Crest = QtGui.QGroupBox(self.linac1_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Linac1_Rough_Crest.sizePolicy().hasHeightForWidth())
        self.Linac1_Rough_Crest.setSizePolicy(sizePolicy)
        self.Linac1_Rough_Crest.setObjectName(_fromUtf8("Linac1_Rough_Crest"))
        self.formLayout_9 = QtGui.QFormLayout(self.Linac1_Rough_Crest)
        self.formLayout_9.setObjectName(_fromUtf8("formLayout_9"))
        self.label_6 = QtGui.QLabel(self.Linac1_Rough_Crest)
        self.label_6.setMinimumSize(QtCore.QSize(150, 0))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_17 = QtGui.QLabel(self.Linac1_Rough_Crest)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_17)
        self.Linac1_Rough_Button = QtGui.QPushButton(self.Linac1_Rough_Crest)
        self.Linac1_Rough_Button.setChecked(False)
        self.Linac1_Rough_Button.setObjectName(_fromUtf8("Linac1_Rough_Button"))
        self.formLayout_9.setWidget(2, QtGui.QFormLayout.SpanningRole, self.Linac1_Rough_Button)
        self.Linac1_Rough_NShots_Set = QtGui.QSpinBox(self.Linac1_Rough_Crest)
        self.Linac1_Rough_NShots_Set.setMinimum(2)
        self.Linac1_Rough_NShots_Set.setProperty("value", 3)
        self.Linac1_Rough_NShots_Set.setObjectName(_fromUtf8("Linac1_Rough_NShots_Set"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.FieldRole, self.Linac1_Rough_NShots_Set)
        self.Linac1_Rough_PointSeperation_Set = QtGui.QDoubleSpinBox(self.Linac1_Rough_Crest)
        self.Linac1_Rough_PointSeperation_Set.setDecimals(1)
        self.Linac1_Rough_PointSeperation_Set.setMinimum(0.1)
        self.Linac1_Rough_PointSeperation_Set.setSingleStep(0.1)
        self.Linac1_Rough_PointSeperation_Set.setProperty("value", 5.0)
        self.Linac1_Rough_PointSeperation_Set.setObjectName(_fromUtf8("Linac1_Rough_PointSeperation_Set"))
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.FieldRole, self.Linac1_Rough_PointSeperation_Set)
        self.gridLayout.addWidget(self.Linac1_Rough_Crest, 1, 0, 1, 1)
        self.Linac1_Fine_Crest = QtGui.QGroupBox(self.linac1_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Linac1_Fine_Crest.sizePolicy().hasHeightForWidth())
        self.Linac1_Fine_Crest.setSizePolicy(sizePolicy)
        self.Linac1_Fine_Crest.setObjectName(_fromUtf8("Linac1_Fine_Crest"))
        self.formLayout_3 = QtGui.QFormLayout(self.Linac1_Fine_Crest)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_7 = QtGui.QLabel(self.Linac1_Fine_Crest)
        self.label_7.setMinimumSize(QtCore.QSize(150, 0))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.Linac1_Fine_Crest)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.Linac1_Fine_Crest)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.Linac1_Fine_Button = QtGui.QPushButton(self.Linac1_Fine_Crest)
        self.Linac1_Fine_Button.setChecked(False)
        self.Linac1_Fine_Button.setObjectName(_fromUtf8("Linac1_Fine_Button"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.SpanningRole, self.Linac1_Fine_Button)
        self.Linac1_Fine_PointSeperation_Set = QtGui.QDoubleSpinBox(self.Linac1_Fine_Crest)
        self.Linac1_Fine_PointSeperation_Set.setDecimals(1)
        self.Linac1_Fine_PointSeperation_Set.setMinimum(0.1)
        self.Linac1_Fine_PointSeperation_Set.setSingleStep(0.1)
        self.Linac1_Fine_PointSeperation_Set.setProperty("value", 1.0)
        self.Linac1_Fine_PointSeperation_Set.setObjectName(_fromUtf8("Linac1_Fine_PointSeperation_Set"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.Linac1_Fine_PointSeperation_Set)
        self.Linac1_Fine_NShots_Set = QtGui.QSpinBox(self.Linac1_Fine_Crest)
        self.Linac1_Fine_NShots_Set.setMaximum(100)
        self.Linac1_Fine_NShots_Set.setProperty("value", 10)
        self.Linac1_Fine_NShots_Set.setObjectName(_fromUtf8("Linac1_Fine_NShots_Set"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.Linac1_Fine_NShots_Set)
        self.Linac1_Fine_Range_Set = QtGui.QSpinBox(self.Linac1_Fine_Crest)
        self.Linac1_Fine_Range_Set.setProperty("value", 20)
        self.Linac1_Fine_Range_Set.setObjectName(_fromUtf8("Linac1_Fine_Range_Set"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.Linac1_Fine_Range_Set)
        self.gridLayout.addWidget(self.Linac1_Fine_Crest, 3, 0, 1, 1)
        self.Linac1_Set_Phase = QtGui.QGroupBox(self.linac1_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Linac1_Set_Phase.sizePolicy().hasHeightForWidth())
        self.Linac1_Set_Phase.setSizePolicy(sizePolicy)
        self.Linac1_Set_Phase.setMinimumSize(QtCore.QSize(0, 0))
        self.Linac1_Set_Phase.setObjectName(_fromUtf8("Linac1_Set_Phase"))
        self.formLayout_4 = QtGui.QFormLayout(self.Linac1_Set_Phase)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_20 = QtGui.QLabel(self.Linac1_Set_Phase)
        self.label_20.setMinimumSize(QtCore.QSize(150, 0))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_20)
        self.Linac1_SetPhase_Button = QtGui.QPushButton(self.Linac1_Set_Phase)
        self.Linac1_SetPhase_Button.setChecked(False)
        self.Linac1_SetPhase_Button.setObjectName(_fromUtf8("Linac1_SetPhase_Button"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.SpanningRole, self.Linac1_SetPhase_Button)
        self.Linac1_OffCrest_Phase_Set = QtGui.QDoubleSpinBox(self.Linac1_Set_Phase)
        self.Linac1_OffCrest_Phase_Set.setDecimals(1)
        self.Linac1_OffCrest_Phase_Set.setMinimum(-30.0)
        self.Linac1_OffCrest_Phase_Set.setMaximum(30.0)
        self.Linac1_OffCrest_Phase_Set.setSingleStep(0.5)
        self.Linac1_OffCrest_Phase_Set.setObjectName(_fromUtf8("Linac1_OffCrest_Phase_Set"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.Linac1_OffCrest_Phase_Set)
        self.gridLayout.addWidget(self.Linac1_Set_Phase, 5, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.linac1_Tab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_4.addWidget(self.label_23, 0, 0, 1, 1)
        self.Linac1_Dipole_Set = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.Linac1_Dipole_Set.setEnabled(True)
        self.Linac1_Dipole_Set.setObjectName(_fromUtf8("Linac1_Dipole_Set"))
        self.gridLayout_4.addWidget(self.Linac1_Dipole_Set, 1, 1, 1, 1)
        self.Linac1_Momentum_Set = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.Linac1_Momentum_Set.setObjectName(_fromUtf8("Linac1_Momentum_Set"))
        self.gridLayout_4.addWidget(self.Linac1_Momentum_Set, 1, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_3)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_4.addWidget(self.label_24, 0, 1, 1, 1)
        self.Linac1_EnergySet_Button = QtGui.QPushButton(self.groupBox_3)
        self.Linac1_EnergySet_Button.setObjectName(_fromUtf8("Linac1_EnergySet_Button"))
        self.gridLayout_4.addWidget(self.Linac1_EnergySet_Button, 2, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_3, 4, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/bike.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.linac1_Tab, icon3, _fromUtf8(""))
        self.magnetTab = QtGui.QWidget()
        self.magnetTab.setObjectName(_fromUtf8("magnetTab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.magnetTab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_magnets = QtGui.QGroupBox(self.magnetTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_magnets.sizePolicy().hasHeightForWidth())
        self.groupBox_magnets.setSizePolicy(sizePolicy)
        self.groupBox_magnets.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_magnets.setObjectName(_fromUtf8("groupBox_magnets"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_magnets)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBox_deguassQ = QtGui.QCheckBox(self.groupBox_magnets)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/Quadrupoles.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_deguassQ.setIcon(icon4)
        self.checkBox_deguassQ.setObjectName(_fromUtf8("checkBox_deguassQ"))
        self.verticalLayout_3.addWidget(self.checkBox_deguassQ)
        self.checkBox_deguassD = QtGui.QCheckBox(self.groupBox_magnets)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/Dipoles.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_deguassD.setIcon(icon5)
        self.checkBox_deguassD.setObjectName(_fromUtf8("checkBox_deguassD"))
        self.verticalLayout_3.addWidget(self.checkBox_deguassD)
        self.checkBox_deguassC = QtGui.QCheckBox(self.groupBox_magnets)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/Correctors.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_deguassC.setIcon(icon6)
        self.checkBox_deguassC.setObjectName(_fromUtf8("checkBox_deguassC"))
        self.verticalLayout_3.addWidget(self.checkBox_deguassC)
        self.checkBox_deguassS = QtGui.QCheckBox(self.groupBox_magnets)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/Solenoids.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_deguassS.setIcon(icon7)
        self.checkBox_deguassS.setObjectName(_fromUtf8("checkBox_deguassS"))
        self.verticalLayout_3.addWidget(self.checkBox_deguassS)
        self.checkBox_quadOff = QtGui.QCheckBox(self.groupBox_magnets)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/Quadrupoles_Off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_quadOff.setIcon(icon8)
        self.checkBox_quadOff.setObjectName(_fromUtf8("checkBox_quadOff"))
        self.verticalLayout_3.addWidget(self.checkBox_quadOff)
        self.checkBox_corrOff = QtGui.QCheckBox(self.groupBox_magnets)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/Correctors_Off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_corrOff.setIcon(icon9)
        self.checkBox_corrOff.setObjectName(_fromUtf8("checkBox_corrOff"))
        self.verticalLayout_3.addWidget(self.checkBox_corrOff)
        self.setupMagnetsButton = QtGui.QPushButton(self.groupBox_magnets)
        self.setupMagnetsButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.setupMagnetsButton.setChecked(False)
        self.setupMagnetsButton.setObjectName(_fromUtf8("setupMagnetsButton"))
        self.verticalLayout_3.addWidget(self.setupMagnetsButton)
        self.verticalLayout_7.addWidget(self.groupBox_magnets)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/magnet_greyscale.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.magnetTab, icon10, _fromUtf8(""))
        self.logTab = QtGui.QWidget()
        self.logTab.setObjectName(_fromUtf8("logTab"))
        self.logTabLayout = QtGui.QVBoxLayout(self.logTab)
        self.logTabLayout.setObjectName(_fromUtf8("logTabLayout"))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/log.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.logTab, icon11, _fromUtf8(""))
        self.centralWidgetLayout.addWidget(self.tabWidget, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1040, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSave_Data = QtGui.QMenu(self.menubar)
        self.menuSave_Data.setObjectName(_fromUtf8("menuSave_Data"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_Calibation_Data = QtGui.QAction(MainWindow)
        self.actionSave_Calibation_Data.setObjectName(_fromUtf8("actionSave_Calibation_Data"))
        self.actionAuto_Save_Data = QtGui.QAction(MainWindow)
        self.actionAuto_Save_Data.setCheckable(True)
        self.actionAuto_Save_Data.setChecked(True)
        self.actionAuto_Save_Data.setObjectName(_fromUtf8("actionAuto_Save_Data"))
        self.actionSave_to_Work_Folder = QtGui.QAction(MainWindow)
        self.actionSave_to_Work_Folder.setCheckable(True)
        self.actionSave_to_Work_Folder.setChecked(True)
        self.actionSave_to_Work_Folder.setObjectName(_fromUtf8("actionSave_to_Work_Folder"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionExit)
        self.menuSave_Data.addAction(self.actionAuto_Save_Data)
        self.menuSave_Data.addAction(self.actionSave_to_Work_Folder)
        self.menuSave_Data.addAction(self.actionSave_Calibation_Data)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSave_Data.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.checkBox_deguassQ, self.checkBox_deguassD)
        MainWindow.setTabOrder(self.checkBox_deguassD, self.checkBox_deguassC)
        MainWindow.setTabOrder(self.checkBox_deguassC, self.checkBox_deguassS)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Phase Calibration", None))
        self.groupBox.setTitle(_translate("MainWindow", "Status", None))
        self.label_MODE.setText(_translate("MainWindow", "Mode", None))
        self.Finish_Button.setText(_translate("MainWindow", "Finish Scan", None))
        self.Abort_Button.setText(_translate("MainWindow", "Abort", None))
        self.Gun_Plots_Box.setTitle(_translate("MainWindow", "Phase Calibration Plots", None))
        self.Gun_Startup.setTitle(_translate("MainWindow", "Gun Startup", None))
        self.Gun_TurnOn_Button.setText(_translate("MainWindow", "Turn On Gun", None))
        self.label_13.setText(_translate("MainWindow", "Amp Set", None))
        self.label_14.setText(_translate("MainWindow", "Step Size", None))
        self.Gun_Rough_Crest.setTitle(_translate("MainWindow", "Rough Crest", None))
        self.label.setText(_translate("MainWindow", "Number of Shots (per point)", None))
        self.label_10.setText(_translate("MainWindow", "Point Separation", None))
        self.Gun_Rough_Button.setText(_translate("MainWindow", "Approximately Find Crest with WCM", None))
        self.Gun_Rough_PointSeperation_Set.setSuffix(_translate("MainWindow", "°", None))
        self.Gun_Dipole_Set_Box.setTitle(_translate("MainWindow", "Dipole Set", None))
        self.label_11.setText(_translate("MainWindow", "Starting Current", None))
        self.label_12.setText(_translate("MainWindow", "Final Current", None))
        self.Gun_Dipole_Start_Set.setSuffix(_translate("MainWindow", " A", None))
        self.Gun_Dipole_End_Set.setSuffix(_translate("MainWindow", " A", None))
        self.Gun_Dipole_Button.setText(_translate("MainWindow", "Find Dipole Current", None))
        self.Gun_Fine_Crest.setTitle(_translate("MainWindow", "Fine Crest", None))
        self.label_3.setText(_translate("MainWindow", "Number of Shots (per point)", None))
        self.label_5.setText(_translate("MainWindow", "Point Separation", None))
        self.label_4.setText(_translate("MainWindow", "Range (±)", None))
        self.Gun_Fine_Button.setText(_translate("MainWindow", "Fine Crest Gun with BPM", None))
        self.Gun_Fine_Range_Set.setSuffix(_translate("MainWindow", "°", None))
        self.Gun_Fine_PointSeperation_Set.setSuffix(_translate("MainWindow", "°", None))
        self.Gun_Set_Phase.setTitle(_translate("MainWindow", "Set Final Phase", None))
        self.label_2.setText(_translate("MainWindow", "Off-crest Phase", None))
        self.Gun_SetPhase_Button.setText(_translate("MainWindow", "Set Gun Phase", None))
        self.Gun_OffCrest_Phase_Set.setSuffix(_translate("MainWindow", "°", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Set Momentum", None))
        self.Gun_Dipole_Set.setSuffix(_translate("MainWindow", " A", None))
        self.label_22.setText(_translate("MainWindow", "Dipole Current", None))
        self.label_21.setText(_translate("MainWindow", "Momentum", None))
        self.Gun_Momentum_Set.setSuffix(_translate("MainWindow", " MeV/c", None))
        self.Gun_EnergySet_Button.setText(_translate("MainWindow", "Set Dipole Current", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Gun_Tab), _translate("MainWindow", "Gun", None))
        self.Linac1_Plots_Box.setTitle(_translate("MainWindow", "Phase Calibration Plots", None))
        self.Linac1_Startup.setTitle(_translate("MainWindow", "Linac Startup", None))
        self.Linac1_TurnOn_Button.setText(_translate("MainWindow", "Turn On Linac", None))
        self.label_15.setText(_translate("MainWindow", "Amp Set", None))
        self.label_16.setText(_translate("MainWindow", "Step Size", None))
        self.Linac1_Dipole_Set_Box.setTitle(_translate("MainWindow", "Dipole Set", None))
        self.label_18.setText(_translate("MainWindow", "Starting Current", None))
        self.label_19.setText(_translate("MainWindow", "Final Current", None))
        self.Linac1_Dipole_Start_Set.setSuffix(_translate("MainWindow", " A", None))
        self.Linac1_Dipole_End_Set.setSuffix(_translate("MainWindow", " A", None))
        self.Linac1_Dipole_Button.setText(_translate("MainWindow", "Find Dipole Current", None))
        self.Linac1_Rough_Crest.setTitle(_translate("MainWindow", "Rough Crest", None))
        self.label_6.setText(_translate("MainWindow", "Number of Shots (per point)", None))
        self.label_17.setText(_translate("MainWindow", "Point Separation", None))
        self.Linac1_Rough_Button.setText(_translate("MainWindow", "Approximately Find Crest with BPM", None))
        self.Linac1_Rough_PointSeperation_Set.setSuffix(_translate("MainWindow", "°", None))
        self.Linac1_Fine_Crest.setTitle(_translate("MainWindow", "Fine Crest", None))
        self.label_7.setText(_translate("MainWindow", "Number of Shots (per point)", None))
        self.label_8.setText(_translate("MainWindow", "Point Separation", None))
        self.label_9.setText(_translate("MainWindow", "Range (±)", None))
        self.Linac1_Fine_Button.setText(_translate("MainWindow", "Fine Crest Linac with BPM", None))
        self.Linac1_Fine_PointSeperation_Set.setSuffix(_translate("MainWindow", "°", None))
        self.Linac1_Fine_Range_Set.setSuffix(_translate("MainWindow", "°", None))
        self.Linac1_Set_Phase.setTitle(_translate("MainWindow", "Set Final Phase", None))
        self.label_20.setText(_translate("MainWindow", "Off-crest Phase", None))
        self.Linac1_SetPhase_Button.setText(_translate("MainWindow", "Set Linac Phase", None))
        self.Linac1_OffCrest_Phase_Set.setSuffix(_translate("MainWindow", "°", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Set Momentum", None))
        self.label_23.setText(_translate("MainWindow", "Momentum", None))
        self.Linac1_Dipole_Set.setSuffix(_translate("MainWindow", " A", None))
        self.Linac1_Momentum_Set.setSuffix(_translate("MainWindow", " MeV/c", None))
        self.label_24.setText(_translate("MainWindow", "Dipole Current", None))
        self.Linac1_EnergySet_Button.setText(_translate("MainWindow", "Set Dipole Current", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.linac1_Tab), _translate("MainWindow", "Linac 1", None))
        self.groupBox_magnets.setTitle(_translate("MainWindow", "Magnets", None))
        self.checkBox_deguassQ.setText(_translate("MainWindow", "Deguass Quadruoles", None))
        self.checkBox_deguassD.setText(_translate("MainWindow", "Deguass Dipoles", None))
        self.checkBox_deguassC.setText(_translate("MainWindow", "Deguass Correctors", None))
        self.checkBox_deguassS.setText(_translate("MainWindow", "Deguass Solenoids", None))
        self.checkBox_quadOff.setText(_translate("MainWindow", "Turn Off Quads", None))
        self.checkBox_corrOff.setText(_translate("MainWindow", "Turn Off Correctors", None))
        self.setupMagnetsButton.setText(_translate("MainWindow", "Degauss Magnets", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.magnetTab), _translate("MainWindow", "Magnets", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logTab), _translate("MainWindow", "Log", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSave_Data.setTitle(_translate("MainWindow", "Save Data", None))
        self.actionSave_Calibation_Data.setText(_translate("MainWindow", "Save Calibation Data", None))
        self.actionAuto_Save_Data.setText(_translate("MainWindow", "Auto Save Data", None))
        self.actionSave_to_Work_Folder.setText(_translate("MainWindow", "Save to Work Folder", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
