# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view\view.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1040, 530)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/mountain-summit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.centralWidgetLayout = QtGui.QGridLayout(self.centralwidget)
        self.centralWidgetLayout.setObjectName(_fromUtf8("centralWidgetLayout"))
        self.widget_3 = QtGui.QWidget(self.centralwidget)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_MODE = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_MODE.sizePolicy().hasHeightForWidth())
        self.label_MODE.setSizePolicy(sizePolicy)
        self.label_MODE.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_MODE.setObjectName(_fromUtf8("label_MODE"))
        self.horizontalLayout.addWidget(self.label_MODE)
        self.abortButton = QtGui.QPushButton(self.widget_3)
        self.abortButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.abortButton.setObjectName(_fromUtf8("abortButton"))
        self.horizontalLayout.addWidget(self.abortButton)
        self.centralWidgetLayout.addWidget(self.widget_3, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.gunTab = QtGui.QWidget()
        self.gunTab.setObjectName(_fromUtf8("gunTab"))
        self.gunTabLayout = QtGui.QGridLayout(self.gunTab)
        self.gunTabLayout.setObjectName(_fromUtf8("gunTabLayout"))
        self.groupBox_methodGun = QtGui.QGroupBox(self.gunTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_methodGun.sizePolicy().hasHeightForWidth())
        self.groupBox_methodGun.setSizePolicy(sizePolicy)
        self.groupBox_methodGun.setObjectName(_fromUtf8("groupBox_methodGun"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_methodGun)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.crestGunWCMButton = QtGui.QPushButton(self.groupBox_methodGun)
        self.crestGunWCMButton.setChecked(False)
        self.crestGunWCMButton.setObjectName(_fromUtf8("crestGunWCMButton"))
        self.verticalLayout_5.addWidget(self.crestGunWCMButton)
        self.crestGunBPM = QtGui.QPushButton(self.groupBox_methodGun)
        self.crestGunBPM.setChecked(False)
        self.crestGunBPM.setObjectName(_fromUtf8("crestGunBPM"))
        self.verticalLayout_5.addWidget(self.crestGunBPM)
        self.setGunPhaseButton = QtGui.QPushButton(self.groupBox_methodGun)
        self.setGunPhaseButton.setChecked(False)
        self.setGunPhaseButton.setObjectName(_fromUtf8("setGunPhaseButton"))
        self.verticalLayout_5.addWidget(self.setGunPhaseButton)
        self.gunTabLayout.addWidget(self.groupBox_methodGun, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.gunTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setMinimumSize(QtCore.QSize(150, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.nShotsSetGun = QtGui.QLineEdit(self.groupBox_2)
        self.nShotsSetGun.setObjectName(_fromUtf8("nShotsSetGun"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.nShotsSetGun)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.nScanningSetGun = QtGui.QLineEdit(self.groupBox_2)
        self.nScanningSetGun.setObjectName(_fromUtf8("nScanningSetGun"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.nScanningSetGun)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.rangeSetGun = QtGui.QLineEdit(self.groupBox_2)
        self.rangeSetGun.setObjectName(_fromUtf8("rangeSetGun"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.rangeSetGun)
        self.gunTabLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_plotsGun = QtGui.QGroupBox(self.gunTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_plotsGun.sizePolicy().hasHeightForWidth())
        self.groupBox_plotsGun.setSizePolicy(sizePolicy)
        self.groupBox_plotsGun.setObjectName(_fromUtf8("groupBox_plotsGun"))
        self.plotLayoutGun = QtGui.QVBoxLayout(self.groupBox_plotsGun)
        self.plotLayoutGun.setObjectName(_fromUtf8("plotLayoutGun"))
        self.gunTabLayout.addWidget(self.groupBox_plotsGun, 0, 1, 4, 1)
        self.groupBox = QtGui.QGroupBox(self.gunTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.gunPhaseSet = QtGui.QLineEdit(self.groupBox)
        self.gunPhaseSet.setObjectName(_fromUtf8("gunPhaseSet"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.gunPhaseSet)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.gunTabLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/pistol.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.gunTab, icon1, _fromUtf8(""))
        self.linacTab = QtGui.QWidget()
        self.linacTab.setObjectName(_fromUtf8("linacTab"))
        self.linacTabLayout = QtGui.QGridLayout(self.linacTab)
        self.linacTabLayout.setObjectName(_fromUtf8("linacTabLayout"))
        self.groupBox_plotsLinac = QtGui.QGroupBox(self.linacTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_plotsLinac.sizePolicy().hasHeightForWidth())
        self.groupBox_plotsLinac.setSizePolicy(sizePolicy)
        self.groupBox_plotsLinac.setObjectName(_fromUtf8("groupBox_plotsLinac"))
        self.plotLayoutLinac1 = QtGui.QVBoxLayout(self.groupBox_plotsLinac)
        self.plotLayoutLinac1.setObjectName(_fromUtf8("plotLayoutLinac1"))
        self.linacTabLayout.addWidget(self.groupBox_plotsLinac, 0, 1, 4, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.linacTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.linac1PhaseSet = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linac1PhaseSet.sizePolicy().hasHeightForWidth())
        self.linac1PhaseSet.setSizePolicy(sizePolicy)
        self.linac1PhaseSet.setObjectName(_fromUtf8("linac1PhaseSet"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.linac1PhaseSet)
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(150, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.linacTabLayout.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.linacTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_5)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setMinimumSize(QtCore.QSize(150, 0))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.nShotsSetLinac1 = QtGui.QLineEdit(self.groupBox_5)
        self.nShotsSetLinac1.setObjectName(_fromUtf8("nShotsSetLinac1"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.nShotsSetLinac1)
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.nScanningSetLinac1 = QtGui.QLineEdit(self.groupBox_5)
        self.nScanningSetLinac1.setObjectName(_fromUtf8("nScanningSetLinac1"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.nScanningSetLinac1)
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.rangeSetLinac1 = QtGui.QLineEdit(self.groupBox_5)
        self.rangeSetLinac1.setObjectName(_fromUtf8("rangeSetLinac1"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.rangeSetLinac1)
        self.linacTabLayout.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.groupBox_methodLinac1 = QtGui.QGroupBox(self.linacTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_methodLinac1.sizePolicy().hasHeightForWidth())
        self.groupBox_methodLinac1.setSizePolicy(sizePolicy)
        self.groupBox_methodLinac1.setObjectName(_fromUtf8("groupBox_methodLinac1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_methodLinac1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.crestLinacRoughButton = QtGui.QPushButton(self.groupBox_methodLinac1)
        self.crestLinacRoughButton.setObjectName(_fromUtf8("crestLinacRoughButton"))
        self.verticalLayout_4.addWidget(self.crestLinacRoughButton)
        self.crestLinacButton = QtGui.QPushButton(self.groupBox_methodLinac1)
        self.crestLinacButton.setObjectName(_fromUtf8("crestLinacButton"))
        self.verticalLayout_4.addWidget(self.crestLinacButton)
        self.setLinacPhaseButton = QtGui.QPushButton(self.groupBox_methodLinac1)
        self.setLinacPhaseButton.setObjectName(_fromUtf8("setLinacPhaseButton"))
        self.verticalLayout_4.addWidget(self.setLinacPhaseButton)
        self.linacTabLayout.addWidget(self.groupBox_methodLinac1, 2, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/bike.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.linacTab, icon2, _fromUtf8(""))
        self.magnetTab = QtGui.QWidget()
        self.magnetTab.setObjectName(_fromUtf8("magnetTab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.magnetTab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_magnets = QtGui.QGroupBox(self.magnetTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_magnets.sizePolicy().hasHeightForWidth())
        self.groupBox_magnets.setSizePolicy(sizePolicy)
        self.groupBox_magnets.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_magnets.setObjectName(_fromUtf8("groupBox_magnets"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_magnets)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBox_deguassQ = QtGui.QCheckBox(self.groupBox_magnets)
        self.checkBox_deguassQ.setObjectName(_fromUtf8("checkBox_deguassQ"))
        self.verticalLayout_3.addWidget(self.checkBox_deguassQ)
        self.checkBox_deguassD = QtGui.QCheckBox(self.groupBox_magnets)
        self.checkBox_deguassD.setObjectName(_fromUtf8("checkBox_deguassD"))
        self.verticalLayout_3.addWidget(self.checkBox_deguassD)
        self.checkBox_deguassC = QtGui.QCheckBox(self.groupBox_magnets)
        self.checkBox_deguassC.setObjectName(_fromUtf8("checkBox_deguassC"))
        self.verticalLayout_3.addWidget(self.checkBox_deguassC)
        self.checkBox_deguassS = QtGui.QCheckBox(self.groupBox_magnets)
        self.checkBox_deguassS.setObjectName(_fromUtf8("checkBox_deguassS"))
        self.verticalLayout_3.addWidget(self.checkBox_deguassS)
        self.checkBox_quadOff = QtGui.QCheckBox(self.groupBox_magnets)
        self.checkBox_quadOff.setObjectName(_fromUtf8("checkBox_quadOff"))
        self.verticalLayout_3.addWidget(self.checkBox_quadOff)
        self.checkBox_corrOff = QtGui.QCheckBox(self.groupBox_magnets)
        self.checkBox_corrOff.setObjectName(_fromUtf8("checkBox_corrOff"))
        self.verticalLayout_3.addWidget(self.checkBox_corrOff)
        self.setupMagnetsButton = QtGui.QPushButton(self.groupBox_magnets)
        self.setupMagnetsButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.setupMagnetsButton.setChecked(False)
        self.setupMagnetsButton.setObjectName(_fromUtf8("setupMagnetsButton"))
        self.verticalLayout_3.addWidget(self.setupMagnetsButton)
        self.verticalLayout_7.addWidget(self.groupBox_magnets)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/magnet_greyscale.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.magnetTab, icon3, _fromUtf8(""))
        self.logTab = QtGui.QWidget()
        self.logTab.setObjectName(_fromUtf8("logTab"))
        self.logTabLayout = QtGui.QVBoxLayout(self.logTab)
        self.logTabLayout.setObjectName(_fromUtf8("logTabLayout"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/log.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.logTab, icon4, _fromUtf8(""))
        self.centralWidgetLayout.addWidget(self.tabWidget, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1040, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_Calibation_Data = QtGui.QAction(MainWindow)
        self.actionSave_Calibation_Data.setObjectName(_fromUtf8("actionSave_Calibation_Data"))
        self.menuFile.addAction(self.actionSave_Calibation_Data)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.checkBox_deguassQ, self.checkBox_deguassD)
        MainWindow.setTabOrder(self.checkBox_deguassD, self.checkBox_deguassC)
        MainWindow.setTabOrder(self.checkBox_deguassC, self.checkBox_deguassS)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Phase Calibration", None))
        self.label_MODE.setText(_translate("MainWindow", "Mode", None))
        self.abortButton.setText(_translate("MainWindow", "Abort", None))
        self.groupBox_methodGun.setTitle(_translate("MainWindow", "Method", None))
        self.crestGunWCMButton.setText(_translate("MainWindow", "Aprroximately Find Crest with WCM", None))
        self.crestGunBPM.setText(_translate("MainWindow", "Fine Crest Gun with BPM", None))
        self.setGunPhaseButton.setText(_translate("MainWindow", "Set Gun Phase", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Settings", None))
        self.label_3.setText(_translate("MainWindow", "Number of Shots (per point)", None))
        self.nShotsSetGun.setText(_translate("MainWindow", "10", None))
        self.label_5.setText(_translate("MainWindow", "Number of Scanning Points", None))
        self.nScanningSetGun.setText(_translate("MainWindow", "20", None))
        self.label_4.setText(_translate("MainWindow", "Range (Degrees)", None))
        self.rangeSetGun.setText(_translate("MainWindow", "20", None))
        self.groupBox_plotsGun.setTitle(_translate("MainWindow", "Phase Calibration Plots", None))
        self.groupBox.setTitle(_translate("MainWindow", "Gun Phase", None))
        self.gunPhaseSet.setText(_translate("MainWindow", "-15", None))
        self.label_2.setText(_translate("MainWindow", "Off-crest Phase", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gunTab), _translate("MainWindow", "Gun", None))
        self.groupBox_plotsLinac.setTitle(_translate("MainWindow", "Phase Calibration Plots", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Linac Phase", None))
        self.linac1PhaseSet.setText(_translate("MainWindow", "0", None))
        self.label_6.setText(_translate("MainWindow", "Off-crest Phase", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Settings", None))
        self.label_7.setText(_translate("MainWindow", "Number of Shots (per point)", None))
        self.nShotsSetLinac1.setText(_translate("MainWindow", "10", None))
        self.label_8.setText(_translate("MainWindow", "Number of Scanning Points", None))
        self.nScanningSetLinac1.setText(_translate("MainWindow", "20", None))
        self.label_9.setText(_translate("MainWindow", "Range (Degrees)", None))
        self.rangeSetLinac1.setText(_translate("MainWindow", "15", None))
        self.groupBox_methodLinac1.setTitle(_translate("MainWindow", "Method", None))
        self.crestLinacRoughButton.setText(_translate("MainWindow", "Aprroximately Find Crest with BPM", None))
        self.crestLinacButton.setText(_translate("MainWindow", "Fine Crest Linac with BPM", None))
        self.setLinacPhaseButton.setText(_translate("MainWindow", "Set Linac Phase", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.linacTab), _translate("MainWindow", "Linac 1", None))
        self.groupBox_magnets.setTitle(_translate("MainWindow", "Magnets", None))
        self.checkBox_deguassQ.setText(_translate("MainWindow", "Deguass Quadruoles", None))
        self.checkBox_deguassD.setText(_translate("MainWindow", "Deguass Dipoles", None))
        self.checkBox_deguassC.setText(_translate("MainWindow", "Deguass Correctors", None))
        self.checkBox_deguassS.setText(_translate("MainWindow", "Deguass Solenoids", None))
        self.checkBox_quadOff.setText(_translate("MainWindow", "Turn Off Quads", None))
        self.checkBox_corrOff.setText(_translate("MainWindow", "Turn Off Correctors", None))
        self.setupMagnetsButton.setText(_translate("MainWindow", "Degauss Magnets", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.magnetTab), _translate("MainWindow", "Magnets", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logTab), _translate("MainWindow", "Log", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionSave_Calibation_Data.setText(_translate("MainWindow", "Save Calibation Data", None))
