# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view\view.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1077, 918)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.formLayout_3 = QtGui.QFormLayout(self.centralwidget)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.groupBox_plots = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_plots.sizePolicy().hasHeightForWidth())
        self.groupBox_plots.setSizePolicy(sizePolicy)
        self.groupBox_plots.setObjectName(_fromUtf8("groupBox_plots"))
        self.plotLayout = QtGui.QVBoxLayout(self.groupBox_plots)
        self.plotLayout.setObjectName(_fromUtf8("plotLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.plotLayout.addLayout(self.gridLayout)
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.SpanningRole, self.groupBox_plots)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1077, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(330, 766))
        self.dockWidget.setFloating(False)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_MODE = QtGui.QLabel(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_MODE.sizePolicy().hasHeightForWidth())
        self.label_MODE.setSizePolicy(sizePolicy)
        self.label_MODE.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_MODE.setObjectName(_fromUtf8("label_MODE"))
        self.verticalLayout.addWidget(self.label_MODE)
        self.groupBox_input = QtGui.QGroupBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_input.sizePolicy().hasHeightForWidth())
        self.groupBox_input.setSizePolicy(sizePolicy)
        self.groupBox_input.setObjectName(_fromUtf8("groupBox_input"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_input)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_input)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.nShotsSet = QtGui.QLineEdit(self.groupBox_2)
        self.nShotsSet.setObjectName(_fromUtf8("nShotsSet"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.nShotsSet)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.nScanningSet = QtGui.QLineEdit(self.groupBox_2)
        self.nScanningSet.setObjectName(_fromUtf8("nScanningSet"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.nScanningSet)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.widget = QtGui.QWidget(self.groupBox_2)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.startRangeSet = QtGui.QLineEdit(self.widget)
        self.startRangeSet.setObjectName(_fromUtf8("startRangeSet"))
        self.horizontalLayout.addWidget(self.startRangeSet)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.endRangeSet = QtGui.QLineEdit(self.widget)
        self.endRangeSet.setObjectName(_fromUtf8("endRangeSet"))
        self.horizontalLayout.addWidget(self.endRangeSet)
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.widget)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.rangeSet = QtGui.QLineEdit(self.groupBox_2)
        self.rangeSet.setObjectName(_fromUtf8("rangeSet"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.rangeSet)
        self.gridLayout_2.addWidget(self.groupBox_2, 5, 0, 1, 3)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_input)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout_4 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.linac1PhaseSet = QtGui.QLineEdit(self.groupBox_3)
        self.linac1PhaseSet.setObjectName(_fromUtf8("linac1PhaseSet"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.linac1PhaseSet)
        self.gridLayout_2.addWidget(self.groupBox_3, 4, 0, 1, 3)
        self.groupBox = QtGui.QGroupBox(self.groupBox_input)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.gunPhaseSet = QtGui.QLineEdit(self.groupBox)
        self.gunPhaseSet.setObjectName(_fromUtf8("gunPhaseSet"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.gunPhaseSet)
        self.gridLayout_2.addWidget(self.groupBox, 3, 0, 1, 3)
        self.verticalLayout.addWidget(self.groupBox_input)
        self.groupBox_magnets = QtGui.QGroupBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_magnets.sizePolicy().hasHeightForWidth())
        self.groupBox_magnets.setSizePolicy(sizePolicy)
        self.groupBox_magnets.setObjectName(_fromUtf8("groupBox_magnets"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_magnets)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBox_deguassQ = QtGui.QCheckBox(self.groupBox_magnets)
        self.checkBox_deguassQ.setObjectName(_fromUtf8("checkBox_deguassQ"))
        self.verticalLayout_3.addWidget(self.checkBox_deguassQ)
        self.checkBox_deguassD = QtGui.QCheckBox(self.groupBox_magnets)
        self.checkBox_deguassD.setObjectName(_fromUtf8("checkBox_deguassD"))
        self.verticalLayout_3.addWidget(self.checkBox_deguassD)
        self.checkBox_deguassC = QtGui.QCheckBox(self.groupBox_magnets)
        self.checkBox_deguassC.setObjectName(_fromUtf8("checkBox_deguassC"))
        self.verticalLayout_3.addWidget(self.checkBox_deguassC)
        self.checkBox_deguassS = QtGui.QCheckBox(self.groupBox_magnets)
        self.checkBox_deguassS.setObjectName(_fromUtf8("checkBox_deguassS"))
        self.verticalLayout_3.addWidget(self.checkBox_deguassS)
        self.checkBox_quadOff = QtGui.QCheckBox(self.groupBox_magnets)
        self.checkBox_quadOff.setObjectName(_fromUtf8("checkBox_quadOff"))
        self.verticalLayout_3.addWidget(self.checkBox_quadOff)
        self.checkBox_corrOff = QtGui.QCheckBox(self.groupBox_magnets)
        self.checkBox_corrOff.setObjectName(_fromUtf8("checkBox_corrOff"))
        self.verticalLayout_3.addWidget(self.checkBox_corrOff)
        self.verticalLayout.addWidget(self.groupBox_magnets)
        self.groupBox_method = QtGui.QGroupBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_method.sizePolicy().hasHeightForWidth())
        self.groupBox_method.setSizePolicy(sizePolicy)
        self.groupBox_method.setObjectName(_fromUtf8("groupBox_method"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_method)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.setupMagnetsButton = QtGui.QPushButton(self.groupBox_method)
        self.setupMagnetsButton.setChecked(False)
        self.setupMagnetsButton.setObjectName(_fromUtf8("setupMagnetsButton"))
        self.verticalLayout_4.addWidget(self.setupMagnetsButton)
        self.crestGunWCMButton = QtGui.QPushButton(self.groupBox_method)
        self.crestGunWCMButton.setChecked(False)
        self.crestGunWCMButton.setObjectName(_fromUtf8("crestGunWCMButton"))
        self.verticalLayout_4.addWidget(self.crestGunWCMButton)
        self.crestGunBPM = QtGui.QPushButton(self.groupBox_method)
        self.crestGunBPM.setChecked(False)
        self.crestGunBPM.setObjectName(_fromUtf8("crestGunBPM"))
        self.verticalLayout_4.addWidget(self.crestGunBPM)
        self.setGunPhaseButton = QtGui.QPushButton(self.groupBox_method)
        self.setGunPhaseButton.setChecked(False)
        self.setGunPhaseButton.setObjectName(_fromUtf8("setGunPhaseButton"))
        self.verticalLayout_4.addWidget(self.setGunPhaseButton)
        self.crestLinacButton = QtGui.QPushButton(self.groupBox_method)
        self.crestLinacButton.setObjectName(_fromUtf8("crestLinacButton"))
        self.verticalLayout_4.addWidget(self.crestLinacButton)
        self.setLinacPhaseButton = QtGui.QPushButton(self.groupBox_method)
        self.setLinacPhaseButton.setObjectName(_fromUtf8("setLinacPhaseButton"))
        self.verticalLayout_4.addWidget(self.setLinacPhaseButton)
        self.verticalLayout.addWidget(self.groupBox_method)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionSave_Calibation_Data = QtGui.QAction(MainWindow)
        self.actionSave_Calibation_Data.setObjectName(_fromUtf8("actionSave_Calibation_Data"))
        self.menuFile.addAction(self.actionSave_Calibation_Data)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.checkBox_deguassQ, self.checkBox_deguassD)
        MainWindow.setTabOrder(self.checkBox_deguassD, self.checkBox_deguassC)
        MainWindow.setTabOrder(self.checkBox_deguassC, self.checkBox_deguassS)
        MainWindow.setTabOrder(self.checkBox_deguassS, self.setupMagnetsButton)
        MainWindow.setTabOrder(self.setupMagnetsButton, self.crestGunBPM)
        MainWindow.setTabOrder(self.crestGunBPM, self.setGunPhaseButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Phase Calibration", None))
        self.groupBox_plots.setTitle(_translate("MainWindow", "Phase Calibration Plots", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Phase Calibration Settings", None))
        self.label_MODE.setText(_translate("MainWindow", "Mode", None))
        self.groupBox_input.setTitle(_translate("MainWindow", "Input", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Settings", None))
        self.label_3.setText(_translate("MainWindow", "Number of Shots (per point)", None))
        self.nShotsSet.setText(_translate("MainWindow", "10", None))
        self.label_5.setText(_translate("MainWindow", "Number of Scanning Points", None))
        self.nScanningSet.setText(_translate("MainWindow", "20", None))
        self.label_7.setText(_translate("MainWindow", "Approx. Range (Degrees)", None))
        self.startRangeSet.setText(_translate("MainWindow", "-115", None))
        self.label_8.setText(_translate("MainWindow", "to", None))
        self.endRangeSet.setText(_translate("MainWindow", "-75", None))
        self.label_4.setText(_translate("MainWindow", "Range (Degrees)", None))
        self.rangeSet.setText(_translate("MainWindow", "20", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Linac Phase", None))
        self.label.setText(_translate("MainWindow", "Desired Linac 1 Phase", None))
        self.linac1PhaseSet.setText(_translate("MainWindow", "0", None))
        self.groupBox.setTitle(_translate("MainWindow", "Gun Phase", None))
        self.label_2.setText(_translate("MainWindow", "Desirsed Gun Phase", None))
        self.gunPhaseSet.setText(_translate("MainWindow", "-15", None))
        self.groupBox_magnets.setTitle(_translate("MainWindow", "Magnets", None))
        self.checkBox_deguassQ.setText(_translate("MainWindow", "Deguass Quadruoles", None))
        self.checkBox_deguassD.setText(_translate("MainWindow", "Deguass Dipoles", None))
        self.checkBox_deguassC.setText(_translate("MainWindow", "Deguass Correctors", None))
        self.checkBox_deguassS.setText(_translate("MainWindow", "Deguass Solenoids", None))
        self.checkBox_quadOff.setText(_translate("MainWindow", "Turn Off Quads", None))
        self.checkBox_corrOff.setText(_translate("MainWindow", "Turn Off Correctors", None))
        self.groupBox_method.setTitle(_translate("MainWindow", "Method", None))
        self.setupMagnetsButton.setText(_translate("MainWindow", "1. Setup Magnets", None))
        self.crestGunWCMButton.setText(_translate("MainWindow", "2.Aprroximately Find Crest with WCM", None))
        self.crestGunBPM.setText(_translate("MainWindow", "3. Find Crest Gun with BPM", None))
        self.setGunPhaseButton.setText(_translate("MainWindow", "4. Set Gun Phase", None))
        self.crestLinacButton.setText(_translate("MainWindow", "5. Crest Linac with BPM", None))
        self.setLinacPhaseButton.setText(_translate("MainWindow", "6. Set Linac Phase", None))
        self.actionSave_Calibation_Data.setText(_translate("MainWindow", "Save Calibation Data", None))

