# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conditioning_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1259, 822)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.start_pause_ramp_button = QtGui.QPushButton(self.centralwidget)
        self.start_pause_ramp_button.setObjectName(_fromUtf8("start_pause_ramp_button"))
        self.verticalLayout.addWidget(self.start_pause_ramp_button)
        self.shutdown_rf_button = QtGui.QPushButton(self.centralwidget)
        self.shutdown_rf_button.setCheckable(False)
        self.shutdown_rf_button.setObjectName(_fromUtf8("shutdown_rf_button"))
        self.verticalLayout.addWidget(self.shutdown_rf_button)
        self.copy_to_clipboard_button = QtGui.QPushButton(self.centralwidget)
        self.copy_to_clipboard_button.setCheckable(False)
        self.copy_to_clipboard_button.setObjectName(_fromUtf8("copy_to_clipboard_button"))
        self.verticalLayout.addWidget(self.copy_to_clipboard_button)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pulse_count_outputwidget = QtGui.QLabel(self.centralwidget)
        self.pulse_count_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.pulse_count_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.pulse_count_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.pulse_count_outputwidget.setObjectName(_fromUtf8("pulse_count_outputwidget"))
        self.gridLayout_4.addWidget(self.pulse_count_outputwidget, 4, 1, 1, 1)
        self.pulse_count_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pulse_count_label.setFont(font)
        self.pulse_count_label.setFrameShape(QtGui.QFrame.Box)
        self.pulse_count_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.pulse_count_label.setScaledContents(False)
        self.pulse_count_label.setObjectName(_fromUtf8("pulse_count_label"))
        self.gridLayout_4.addWidget(self.pulse_count_label, 4, 0, 1, 1)
        self.last_106_count_outputwidget = QtGui.QLabel(self.centralwidget)
        self.last_106_count_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.last_106_count_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.last_106_count_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.last_106_count_outputwidget.setObjectName(_fromUtf8("last_106_count_outputwidget"))
        self.gridLayout_4.addWidget(self.last_106_count_outputwidget, 2, 1, 1, 1)
        self.last_106_count_label = QtGui.QLabel(self.centralwidget)
        self.last_106_count_label.setFrameShape(QtGui.QFrame.Box)
        self.last_106_count_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.last_106_count_label.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.last_106_count_label.setObjectName(_fromUtf8("last_106_count_label"))
        self.gridLayout_4.addWidget(self.last_106_count_label, 2, 0, 1, 1)
        self.measured_breakdown_rate_label = QtGui.QLabel(self.centralwidget)
        self.measured_breakdown_rate_label.setFrameShape(QtGui.QFrame.Box)
        self.measured_breakdown_rate_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.measured_breakdown_rate_label.setScaledContents(False)
        self.measured_breakdown_rate_label.setObjectName(_fromUtf8("measured_breakdown_rate_label"))
        self.gridLayout_4.addWidget(self.measured_breakdown_rate_label, 1, 0, 1, 1)
        self.measured_breakdown_rate_outputwidget = QtGui.QLabel(self.centralwidget)
        self.measured_breakdown_rate_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.measured_breakdown_rate_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.measured_breakdown_rate_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.measured_breakdown_rate_outputwidget.setObjectName(_fromUtf8("measured_breakdown_rate_outputwidget"))
        self.gridLayout_4.addWidget(self.measured_breakdown_rate_outputwidget, 1, 1, 1, 1)
        self.breakdown_count_label = QtGui.QLabel(self.centralwidget)
        self.breakdown_count_label.setFrameShape(QtGui.QFrame.Box)
        self.breakdown_count_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.breakdown_count_label.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.breakdown_count_label.setObjectName(_fromUtf8("breakdown_count_label"))
        self.gridLayout_4.addWidget(self.breakdown_count_label, 3, 0, 1, 1)
        self.breakdown_count_outputwidget = QtGui.QLabel(self.centralwidget)
        self.breakdown_count_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.breakdown_count_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.breakdown_count_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.breakdown_count_outputwidget.setObjectName(_fromUtf8("breakdown_count_outputwidget"))
        self.gridLayout_4.addWidget(self.breakdown_count_outputwidget, 3, 1, 1, 1)
        self.breakdown_rate_limit_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.breakdown_rate_limit_label.setFont(font)
        self.breakdown_rate_limit_label.setFrameShape(QtGui.QFrame.Box)
        self.breakdown_rate_limit_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.breakdown_rate_limit_label.setScaledContents(False)
        self.breakdown_rate_limit_label.setObjectName(_fromUtf8("breakdown_rate_limit_label"))
        self.gridLayout_4.addWidget(self.breakdown_rate_limit_label, 0, 0, 1, 1)
        self.breakdown_rate_limit_outputwidget = QtGui.QLabel(self.centralwidget)
        self.breakdown_rate_limit_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.breakdown_rate_limit_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.breakdown_rate_limit_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.breakdown_rate_limit_outputwidget.setObjectName(_fromUtf8("breakdown_rate_limit_outputwidget"))
        self.gridLayout_4.addWidget(self.breakdown_rate_limit_outputwidget, 0, 1, 1, 1)
        self.pulse_count_label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pulse_count_label_2.setFont(font)
        self.pulse_count_label_2.setFrameShape(QtGui.QFrame.Box)
        self.pulse_count_label_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.pulse_count_label_2.setScaledContents(False)
        self.pulse_count_label_2.setObjectName(_fromUtf8("pulse_count_label_2"))
        self.gridLayout_4.addWidget(self.pulse_count_label_2, 5, 0, 1, 1)
        self.duplicate_count_outputwidget = QtGui.QLabel(self.centralwidget)
        self.duplicate_count_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.duplicate_count_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.duplicate_count_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.duplicate_count_outputwidget.setObjectName(_fromUtf8("duplicate_count_outputwidget"))
        self.gridLayout_4.addWidget(self.duplicate_count_outputwidget, 5, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.amp_set_outputwidget = QtGui.QLabel(self.centralwidget)
        self.amp_set_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.amp_set_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.amp_set_outputwidget.setScaledContents(False)
        self.amp_set_outputwidget.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.amp_set_outputwidget.setIndent(-1)
        self.amp_set_outputwidget.setObjectName(_fromUtf8("amp_set_outputwidget"))
        self.gridLayout.addWidget(self.amp_set_outputwidget, 3, 1, 1, 1)
        self.pulse_length_aim_label = QtGui.QLabel(self.centralwidget)
        self.pulse_length_aim_label.setFrameShape(QtGui.QFrame.Box)
        self.pulse_length_aim_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.pulse_length_aim_label.setObjectName(_fromUtf8("pulse_length_aim_label"))
        self.gridLayout.addWidget(self.pulse_length_aim_label, 1, 0, 1, 1)
        self.amp_set_label = QtGui.QLabel(self.centralwidget)
        self.amp_set_label.setFrameShape(QtGui.QFrame.Box)
        self.amp_set_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.amp_set_label.setObjectName(_fromUtf8("amp_set_label"))
        self.gridLayout.addWidget(self.amp_set_label, 3, 0, 1, 1)
        self.power_aim_outputwidget = QtGui.QLabel(self.centralwidget)
        self.power_aim_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.power_aim_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.power_aim_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.power_aim_outputwidget.setObjectName(_fromUtf8("power_aim_outputwidget"))
        self.gridLayout.addWidget(self.power_aim_outputwidget, 0, 1, 1, 1)
        self.pulse_length_aim_outputwidget = QtGui.QLabel(self.centralwidget)
        self.pulse_length_aim_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.pulse_length_aim_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.pulse_length_aim_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.pulse_length_aim_outputwidget.setObjectName(_fromUtf8("pulse_length_aim_outputwidget"))
        self.gridLayout.addWidget(self.pulse_length_aim_outputwidget, 1, 1, 1, 1)
        self.power_aim_label = QtGui.QLabel(self.centralwidget)
        self.power_aim_label.setFrameShape(QtGui.QFrame.Box)
        self.power_aim_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.power_aim_label.setObjectName(_fromUtf8("power_aim_label"))
        self.gridLayout.addWidget(self.power_aim_label, 0, 0, 1, 1)
        self.pulse_length_outputwidget = QtGui.QLabel(self.centralwidget)
        self.pulse_length_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.pulse_length_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.pulse_length_outputwidget.setScaledContents(False)
        self.pulse_length_outputwidget.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.pulse_length_outputwidget.setIndent(-1)
        self.pulse_length_outputwidget.setObjectName(_fromUtf8("pulse_length_outputwidget"))
        self.gridLayout.addWidget(self.pulse_length_outputwidget, 2, 1, 1, 1)
        self.pulse_length_label = QtGui.QLabel(self.centralwidget)
        self.pulse_length_label.setFrameShape(QtGui.QFrame.Box)
        self.pulse_length_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.pulse_length_label.setScaledContents(False)
        self.pulse_length_label.setObjectName(_fromUtf8("pulse_length_label"))
        self.gridLayout.addWidget(self.pulse_length_label, 2, 0, 1, 1)
        self.elapse_time_label = QtGui.QLabel(self.centralwidget)
        self.elapse_time_label.setFrameShape(QtGui.QFrame.Box)
        self.elapse_time_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.elapse_time_label.setScaledContents(False)
        self.elapse_time_label.setObjectName(_fromUtf8("elapse_time_label"))
        self.gridLayout.addWidget(self.elapse_time_label, 4, 0, 1, 1)
        self.elapsed_time_outputwidget = QtGui.QLabel(self.centralwidget)
        self.elapsed_time_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.elapsed_time_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.elapsed_time_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.elapsed_time_outputwidget.setObjectName(_fromUtf8("elapsed_time_outputwidget"))
        self.gridLayout.addWidget(self.elapsed_time_outputwidget, 4, 1, 1, 1)
        self.power_aim_label_2 = QtGui.QLabel(self.centralwidget)
        self.power_aim_label_2.setFrameShape(QtGui.QFrame.Box)
        self.power_aim_label_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.power_aim_label_2.setObjectName(_fromUtf8("power_aim_label_2"))
        self.gridLayout.addWidget(self.power_aim_label_2, 5, 0, 1, 1)
        self.sol_outputwidget = QtGui.QLabel(self.centralwidget)
        self.sol_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.sol_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.sol_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.sol_outputwidget.setObjectName(_fromUtf8("sol_outputwidget"))
        self.gridLayout.addWidget(self.sol_outputwidget, 5, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.current_index_outputwidget = QtGui.QLabel(self.centralwidget)
        self.current_index_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.current_index_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.current_index_outputwidget.setScaledContents(False)
        self.current_index_outputwidget.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.current_index_outputwidget.setIndent(-1)
        self.current_index_outputwidget.setObjectName(_fromUtf8("current_index_outputwidget"))
        self.gridLayout_5.addWidget(self.current_index_outputwidget, 5, 1, 1, 1)
        self.next_power_increase_2 = QtGui.QLabel(self.centralwidget)
        self.next_power_increase_2.setFrameShape(QtGui.QFrame.Box)
        self.next_power_increase_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.next_power_increase_2.setScaledContents(False)
        self.next_power_increase_2.setObjectName(_fromUtf8("next_power_increase_2"))
        self.gridLayout_5.addWidget(self.next_power_increase_2, 5, 0, 1, 1)
        self.next_power_increase_outputwidget = QtGui.QLabel(self.centralwidget)
        self.next_power_increase_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.next_power_increase_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.next_power_increase_outputwidget.setScaledContents(False)
        self.next_power_increase_outputwidget.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.next_power_increase_outputwidget.setIndent(-1)
        self.next_power_increase_outputwidget.setObjectName(_fromUtf8("next_power_increase_outputwidget"))
        self.gridLayout_5.addWidget(self.next_power_increase_outputwidget, 3, 1, 1, 1)
        self.next_sp_decrease = QtGui.QLabel(self.centralwidget)
        self.next_sp_decrease.setFrameShape(QtGui.QFrame.Box)
        self.next_sp_decrease.setFrameShadow(QtGui.QFrame.Sunken)
        self.next_sp_decrease.setScaledContents(False)
        self.next_sp_decrease.setObjectName(_fromUtf8("next_sp_decrease"))
        self.gridLayout_5.addWidget(self.next_sp_decrease, 4, 0, 1, 1)
        self.next_sp_decrease_outputwidget = QtGui.QLabel(self.centralwidget)
        self.next_sp_decrease_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.next_sp_decrease_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.next_sp_decrease_outputwidget.setScaledContents(False)
        self.next_sp_decrease_outputwidget.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.next_sp_decrease_outputwidget.setIndent(-1)
        self.next_sp_decrease_outputwidget.setObjectName(_fromUtf8("next_sp_decrease_outputwidget"))
        self.gridLayout_5.addWidget(self.next_sp_decrease_outputwidget, 4, 1, 1, 1)
        self.last_setpoint_power_outputwidget = QtGui.QLabel(self.centralwidget)
        self.last_setpoint_power_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.last_setpoint_power_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.last_setpoint_power_outputwidget.setScaledContents(False)
        self.last_setpoint_power_outputwidget.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.last_setpoint_power_outputwidget.setIndent(-1)
        self.last_setpoint_power_outputwidget.setObjectName(_fromUtf8("last_setpoint_power_outputwidget"))
        self.gridLayout_5.addWidget(self.last_setpoint_power_outputwidget, 2, 1, 1, 1)
        self.next_power_increase = QtGui.QLabel(self.centralwidget)
        self.next_power_increase.setFrameShape(QtGui.QFrame.Box)
        self.next_power_increase.setFrameShadow(QtGui.QFrame.Sunken)
        self.next_power_increase.setScaledContents(False)
        self.next_power_increase.setObjectName(_fromUtf8("next_power_increase"))
        self.gridLayout_5.addWidget(self.next_power_increase, 3, 0, 1, 1)
        self.last_setpoint_power = QtGui.QLabel(self.centralwidget)
        self.last_setpoint_power.setFrameShape(QtGui.QFrame.Box)
        self.last_setpoint_power.setFrameShadow(QtGui.QFrame.Sunken)
        self.last_setpoint_power.setScaledContents(False)
        self.last_setpoint_power.setObjectName(_fromUtf8("last_setpoint_power"))
        self.gridLayout_5.addWidget(self.last_setpoint_power, 2, 0, 1, 1)
        self.event_pulse_count_label = QtGui.QLabel(self.centralwidget)
        self.event_pulse_count_label.setFrameShape(QtGui.QFrame.Box)
        self.event_pulse_count_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.event_pulse_count_label.setScaledContents(False)
        self.event_pulse_count_label.setObjectName(_fromUtf8("event_pulse_count_label"))
        self.gridLayout_5.addWidget(self.event_pulse_count_label, 1, 0, 1, 1)
        self.event_pulse_count_outputwidget = QtGui.QLabel(self.centralwidget)
        self.event_pulse_count_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.event_pulse_count_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.event_pulse_count_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.event_pulse_count_outputwidget.setObjectName(_fromUtf8("event_pulse_count_outputwidget"))
        self.gridLayout_5.addWidget(self.event_pulse_count_outputwidget, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 1, 1, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.llrf_trigger_label = QtGui.QLabel(self.centralwidget)
        self.llrf_trigger_label.setFrameShape(QtGui.QFrame.Box)
        self.llrf_trigger_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.llrf_trigger_label.setScaledContents(False)
        self.llrf_trigger_label.setObjectName(_fromUtf8("llrf_trigger_label"))
        self.gridLayout_3.addWidget(self.llrf_trigger_label, 1, 0, 1, 1)
        self.rf_mod_label = QtGui.QLabel(self.centralwidget)
        self.rf_mod_label.setFrameShape(QtGui.QFrame.Box)
        self.rf_mod_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.rf_mod_label.setScaledContents(False)
        self.rf_mod_label.setObjectName(_fromUtf8("rf_mod_label"))
        self.gridLayout_3.addWidget(self.rf_mod_label, 5, 0, 1, 1)
        self.llrf_output_label = QtGui.QLabel(self.centralwidget)
        self.llrf_output_label.setFrameShape(QtGui.QFrame.Box)
        self.llrf_output_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.llrf_output_label.setScaledContents(False)
        self.llrf_output_label.setObjectName(_fromUtf8("llrf_output_label"))
        self.gridLayout_3.addWidget(self.llrf_output_label, 6, 0, 1, 1)
        self.llrf_ff_amp_locked_label = QtGui.QLabel(self.centralwidget)
        self.llrf_ff_amp_locked_label.setFrameShape(QtGui.QFrame.Box)
        self.llrf_ff_amp_locked_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.llrf_ff_amp_locked_label.setScaledContents(False)
        self.llrf_ff_amp_locked_label.setObjectName(_fromUtf8("llrf_ff_amp_locked_label"))
        self.gridLayout_3.addWidget(self.llrf_ff_amp_locked_label, 7, 0, 1, 1)
        self.llrf_trigger_outputwidget = QtGui.QLabel(self.centralwidget)
        self.llrf_trigger_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.llrf_trigger_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.llrf_trigger_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.llrf_trigger_outputwidget.setObjectName(_fromUtf8("llrf_trigger_outputwidget"))
        self.gridLayout_3.addWidget(self.llrf_trigger_outputwidget, 1, 1, 1, 1)
        self.llrf_ff_ph_locked_label = QtGui.QLabel(self.centralwidget)
        self.llrf_ff_ph_locked_label.setFrameShape(QtGui.QFrame.Box)
        self.llrf_ff_ph_locked_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.llrf_ff_ph_locked_label.setScaledContents(False)
        self.llrf_ff_ph_locked_label.setObjectName(_fromUtf8("llrf_ff_ph_locked_label"))
        self.gridLayout_3.addWidget(self.llrf_ff_ph_locked_label, 8, 0, 1, 1)
        self.llrf_output_outputwidget = QtGui.QLabel(self.centralwidget)
        self.llrf_output_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.llrf_output_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.llrf_output_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.llrf_output_outputwidget.setObjectName(_fromUtf8("llrf_output_outputwidget"))
        self.gridLayout_3.addWidget(self.llrf_output_outputwidget, 6, 1, 1, 1)
        self.DC_spike_status_outputwidget = QtGui.QLabel(self.centralwidget)
        self.DC_spike_status_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.DC_spike_status_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.DC_spike_status_outputwidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DC_spike_status_outputwidget.setObjectName(_fromUtf8("DC_spike_status_outputwidget"))
        self.gridLayout_3.addWidget(self.DC_spike_status_outputwidget, 2, 1, 1, 1)
        self.vac_valve_status_label = QtGui.QLabel(self.centralwidget)
        self.vac_valve_status_label.setFrameShape(QtGui.QFrame.Box)
        self.vac_valve_status_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_valve_status_label.setScaledContents(False)
        self.vac_valve_status_label.setObjectName(_fromUtf8("vac_valve_status_label"))
        self.gridLayout_3.addWidget(self.vac_valve_status_label, 9, 0, 1, 1)
        self.RF_protection_label = QtGui.QLabel(self.centralwidget)
        self.RF_protection_label.setFrameShape(QtGui.QFrame.Box)
        self.RF_protection_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.RF_protection_label.setScaledContents(False)
        self.RF_protection_label.setObjectName(_fromUtf8("RF_protection_label"))
        self.gridLayout_3.addWidget(self.RF_protection_label, 4, 0, 1, 1)
        self.vac_spike_status_outputwidget = QtGui.QLabel(self.centralwidget)
        self.vac_spike_status_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.vac_spike_status_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_spike_status_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.vac_spike_status_outputwidget.setObjectName(_fromUtf8("vac_spike_status_outputwidget"))
        self.gridLayout_3.addWidget(self.vac_spike_status_outputwidget, 3, 1, 1, 1)
        self.rev_power_spike_label = QtGui.QLabel(self.centralwidget)
        self.rev_power_spike_label.setFrameShape(QtGui.QFrame.Box)
        self.rev_power_spike_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.rev_power_spike_label.setScaledContents(False)
        self.rev_power_spike_label.setObjectName(_fromUtf8("rev_power_spike_label"))
        self.gridLayout_3.addWidget(self.rev_power_spike_label, 0, 0, 1, 1)
        self.vac_valve_status_outputwidget = QtGui.QLabel(self.centralwidget)
        self.vac_valve_status_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.vac_valve_status_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_valve_status_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.vac_valve_status_outputwidget.setObjectName(_fromUtf8("vac_valve_status_outputwidget"))
        self.gridLayout_3.addWidget(self.vac_valve_status_outputwidget, 9, 1, 1, 1)
        self.llrf_ff_ph_locked_outputwidget = QtGui.QLabel(self.centralwidget)
        self.llrf_ff_ph_locked_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.llrf_ff_ph_locked_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.llrf_ff_ph_locked_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.llrf_ff_ph_locked_outputwidget.setObjectName(_fromUtf8("llrf_ff_ph_locked_outputwidget"))
        self.gridLayout_3.addWidget(self.llrf_ff_ph_locked_outputwidget, 8, 1, 1, 1)
        self.rev_power_spike_status_outputwidget = QtGui.QLabel(self.centralwidget)
        self.rev_power_spike_status_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.rev_power_spike_status_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.rev_power_spike_status_outputwidget.setScaledContents(False)
        self.rev_power_spike_status_outputwidget.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.rev_power_spike_status_outputwidget.setIndent(-1)
        self.rev_power_spike_status_outputwidget.setObjectName(_fromUtf8("rev_power_spike_status_outputwidget"))
        self.gridLayout_3.addWidget(self.rev_power_spike_status_outputwidget, 0, 1, 1, 1)
        self.mod_state_outputwidget = QtGui.QLabel(self.centralwidget)
        self.mod_state_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.mod_state_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.mod_state_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.mod_state_outputwidget.setObjectName(_fromUtf8("mod_state_outputwidget"))
        self.gridLayout_3.addWidget(self.mod_state_outputwidget, 5, 1, 1, 1)
        self.vac_spike_label = QtGui.QLabel(self.centralwidget)
        self.vac_spike_label.setFrameShape(QtGui.QFrame.Box)
        self.vac_spike_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_spike_label.setScaledContents(False)
        self.vac_spike_label.setObjectName(_fromUtf8("vac_spike_label"))
        self.gridLayout_3.addWidget(self.vac_spike_label, 3, 0, 1, 1)
        self.llrf_ff_amp_locked_outputwidget = QtGui.QLabel(self.centralwidget)
        self.llrf_ff_amp_locked_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.llrf_ff_amp_locked_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.llrf_ff_amp_locked_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.llrf_ff_amp_locked_outputwidget.setObjectName(_fromUtf8("llrf_ff_amp_locked_outputwidget"))
        self.gridLayout_3.addWidget(self.llrf_ff_amp_locked_outputwidget, 7, 1, 1, 1)
        self.RF_protection_outputwidget = QtGui.QLabel(self.centralwidget)
        self.RF_protection_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.RF_protection_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.RF_protection_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.RF_protection_outputwidget.setObjectName(_fromUtf8("RF_protection_outputwidget"))
        self.gridLayout_3.addWidget(self.RF_protection_outputwidget, 4, 1, 1, 1)
        self.DC_spike_label = QtGui.QLabel(self.centralwidget)
        self.DC_spike_label.setMinimumSize(QtCore.QSize(0, 21))
        self.DC_spike_label.setFrameShape(QtGui.QFrame.Box)
        self.DC_spike_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.DC_spike_label.setScaledContents(False)
        self.DC_spike_label.setObjectName(_fromUtf8("DC_spike_label"))
        self.gridLayout_3.addWidget(self.DC_spike_label, 2, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.vac_level_outputwidget = QtGui.QLabel(self.centralwidget)
        self.vac_level_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.vac_level_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_level_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.vac_level_outputwidget.setObjectName(_fromUtf8("vac_level_outputwidget"))
        self.gridLayout_2.addWidget(self.vac_level_outputwidget, 6, 1, 1, 1)
        self.probe_power_outputwidget = QtGui.QLabel(self.centralwidget)
        self.probe_power_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.probe_power_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.probe_power_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.probe_power_outputwidget.setObjectName(_fromUtf8("probe_power_outputwidget"))
        self.gridLayout_2.addWidget(self.probe_power_outputwidget, 5, 1, 1, 1)
        self.vac_level_label = QtGui.QLabel(self.centralwidget)
        self.vac_level_label.setFrameShape(QtGui.QFrame.Box)
        self.vac_level_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_level_label.setScaledContents(False)
        self.vac_level_label.setObjectName(_fromUtf8("vac_level_label"))
        self.gridLayout_2.addWidget(self.vac_level_label, 6, 0, 1, 1)
        self.cav_temp_outputwidget = QtGui.QLabel(self.centralwidget)
        self.cav_temp_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.cav_temp_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.cav_temp_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.cav_temp_outputwidget.setObjectName(_fromUtf8("cav_temp_outputwidget"))
        self.gridLayout_2.addWidget(self.cav_temp_outputwidget, 9, 1, 1, 1)
        self.cav_temp_label = QtGui.QLabel(self.centralwidget)
        self.cav_temp_label.setFrameShape(QtGui.QFrame.Box)
        self.cav_temp_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.cav_temp_label.setScaledContents(False)
        self.cav_temp_label.setObjectName(_fromUtf8("cav_temp_label"))
        self.gridLayout_2.addWidget(self.cav_temp_label, 9, 0, 1, 1)
        self.rev_cav_power_label = QtGui.QLabel(self.centralwidget)
        self.rev_cav_power_label.setFrameShape(QtGui.QFrame.Box)
        self.rev_cav_power_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.rev_cav_power_label.setScaledContents(False)
        self.rev_cav_power_label.setObjectName(_fromUtf8("rev_cav_power_label"))
        self.gridLayout_2.addWidget(self.rev_cav_power_label, 4, 0, 1, 1)
        self.water_temp_outputwidget = QtGui.QLabel(self.centralwidget)
        self.water_temp_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.water_temp_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.water_temp_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.water_temp_outputwidget.setObjectName(_fromUtf8("water_temp_outputwidget"))
        self.gridLayout_2.addWidget(self.water_temp_outputwidget, 8, 1, 1, 1)
        self.fwd_kly_power_outputwidget = QtGui.QLabel(self.centralwidget)
        self.fwd_kly_power_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.fwd_kly_power_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.fwd_kly_power_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.fwd_kly_power_outputwidget.setObjectName(_fromUtf8("fwd_kly_power_outputwidget"))
        self.gridLayout_2.addWidget(self.fwd_kly_power_outputwidget, 1, 1, 1, 1)
        self.water_temp_label = QtGui.QLabel(self.centralwidget)
        self.water_temp_label.setFrameShape(QtGui.QFrame.Box)
        self.water_temp_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.water_temp_label.setScaledContents(False)
        self.water_temp_label.setObjectName(_fromUtf8("water_temp_label"))
        self.gridLayout_2.addWidget(self.water_temp_label, 8, 0, 1, 1)
        self.rev_kly_power_outputwidget = QtGui.QLabel(self.centralwidget)
        self.rev_kly_power_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.rev_kly_power_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.rev_kly_power_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.rev_kly_power_outputwidget.setObjectName(_fromUtf8("rev_kly_power_outputwidget"))
        self.gridLayout_2.addWidget(self.rev_kly_power_outputwidget, 2, 1, 1, 1)
        self.rev_cav_power_outputwidget = QtGui.QLabel(self.centralwidget)
        self.rev_cav_power_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.rev_cav_power_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.rev_cav_power_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.rev_cav_power_outputwidget.setObjectName(_fromUtf8("rev_cav_power_outputwidget"))
        self.gridLayout_2.addWidget(self.rev_cav_power_outputwidget, 4, 1, 1, 1)
        self.fwd_kly_power_label = QtGui.QLabel(self.centralwidget)
        self.fwd_kly_power_label.setFrameShape(QtGui.QFrame.Box)
        self.fwd_kly_power_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.fwd_kly_power_label.setScaledContents(False)
        self.fwd_kly_power_label.setObjectName(_fromUtf8("fwd_kly_power_label"))
        self.gridLayout_2.addWidget(self.fwd_kly_power_label, 1, 0, 1, 1)
        self.rev_kly_power_label = QtGui.QLabel(self.centralwidget)
        self.rev_kly_power_label.setFrameShape(QtGui.QFrame.Box)
        self.rev_kly_power_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.rev_kly_power_label.setScaledContents(False)
        self.rev_kly_power_label.setObjectName(_fromUtf8("rev_kly_power_label"))
        self.gridLayout_2.addWidget(self.rev_kly_power_label, 2, 0, 1, 1)
        self.fwd_cav_power_outputwidget = QtGui.QLabel(self.centralwidget)
        self.fwd_cav_power_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.fwd_cav_power_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.fwd_cav_power_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.fwd_cav_power_outputwidget.setObjectName(_fromUtf8("fwd_cav_power_outputwidget"))
        self.gridLayout_2.addWidget(self.fwd_cav_power_outputwidget, 3, 1, 1, 1)
        self.fwd_cav_power_label = QtGui.QLabel(self.centralwidget)
        self.fwd_cav_power_label.setFrameShape(QtGui.QFrame.Box)
        self.fwd_cav_power_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.fwd_cav_power_label.setScaledContents(False)
        self.fwd_cav_power_label.setObjectName(_fromUtf8("fwd_cav_power_label"))
        self.gridLayout_2.addWidget(self.fwd_cav_power_label, 3, 0, 1, 1)
        self.probe_power_label = QtGui.QLabel(self.centralwidget)
        self.probe_power_label.setFrameShape(QtGui.QFrame.Box)
        self.probe_power_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.probe_power_label.setScaledContents(False)
        self.probe_power_label.setObjectName(_fromUtf8("probe_power_label"))
        self.gridLayout_2.addWidget(self.probe_power_label, 5, 0, 1, 1)
        self.dc_level_label = QtGui.QLabel(self.centralwidget)
        self.dc_level_label.setFrameShape(QtGui.QFrame.Box)
        self.dc_level_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.dc_level_label.setScaledContents(False)
        self.dc_level_label.setObjectName(_fromUtf8("dc_level_label"))
        self.gridLayout_2.addWidget(self.dc_level_label, 7, 0, 1, 1)
        self.dc_level_outputwidget = QtGui.QLabel(self.centralwidget)
        self.dc_level_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.dc_level_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.dc_level_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.dc_level_outputwidget.setObjectName(_fromUtf8("dc_level_outputwidget"))
        self.gridLayout_2.addWidget(self.dc_level_outputwidget, 7, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 2, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 1, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_7.addWidget(self.textEdit, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_7.addWidget(self.label, 1, 1, 1, 1)
        self.textEdit.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.start_pause_ramp_button.setText(_translate("MainWindow", "Pause ramp", None))
        self.shutdown_rf_button.setText(_translate("MainWindow", "Shut down RF", None))
        self.copy_to_clipboard_button.setToolTip(_translate("MainWindow", "For the log!", None))
        self.copy_to_clipboard_button.setText(_translate("MainWindow", "Copy status to clipboard", None))
        self.pulse_count_outputwidget.setText(_translate("MainWindow", "Terrible", None))
        self.pulse_count_label.setText(_translate("MainWindow", "Active pulse count", None))
        self.last_106_count_outputwidget.setText(_translate("MainWindow", "-1", None))
        self.last_106_count_label.setText(_translate("MainWindow", "Last 10^6 BD count", None))
        self.measured_breakdown_rate_label.setText(_translate("MainWindow", "Measured breakdown rate", None))
        self.measured_breakdown_rate_outputwidget.setText(_translate("MainWindow", "0", None))
        self.breakdown_count_label.setText(_translate("MainWindow", "Breakdown count", None))
        self.breakdown_count_outputwidget.setText(_translate("MainWindow", "-1", None))
        self.breakdown_rate_limit_label.setText(_translate("MainWindow", "Breakdownrate aim (per 10^6)", None))
        self.breakdown_rate_limit_outputwidget.setText(_translate("MainWindow", "0", None))
        self.pulse_count_label_2.setText(_translate("MainWindow", "Duplicate Pulse Count", None))
        self.duplicate_count_outputwidget.setText(_translate("MainWindow", "Terrible", None))
        self.amp_set_outputwidget.setText(_translate("MainWindow", "Nope", None))
        self.pulse_length_aim_label.setText(_translate("MainWindow", "Pulse length aim (us)", None))
        self.amp_set_label.setText(_translate("MainWindow", "Amp Set", None))
        self.power_aim_outputwidget.setText(_translate("MainWindow", "-1", None))
        self.pulse_length_aim_outputwidget.setText(_translate("MainWindow", "-1", None))
        self.power_aim_label.setText(_translate("MainWindow", "Klystron power aim (MW)", None))
        self.pulse_length_outputwidget.setText(_translate("MainWindow", "0", None))
        self.pulse_length_label.setText(_translate("MainWindow", "Pulse length", None))
        self.elapse_time_label.setText(_translate("MainWindow", "Elapsed Time", None))
        self.elapsed_time_outputwidget.setText(_translate("MainWindow", "-9", None))
        self.power_aim_label_2.setText(_translate("MainWindow", "sol current", None))
        self.sol_outputwidget.setText(_translate("MainWindow", "-9", None))
        self.current_index_outputwidget.setText(_translate("MainWindow", "0", None))
        self.next_power_increase_2.setText(_translate("MainWindow", "Current Ramp Index", None))
        self.next_power_increase_outputwidget.setText(_translate("MainWindow", "0", None))
        self.next_sp_decrease.setText(_translate("MainWindow", "Next SP Decrease", None))
        self.next_sp_decrease_outputwidget.setText(_translate("MainWindow", "0", None))
        self.last_setpoint_power_outputwidget.setText(_translate("MainWindow", "0", None))
        self.next_power_increase.setText(_translate("MainWindow", "Next Power Increase", None))
        self.last_setpoint_power.setText(_translate("MainWindow", "Last AmpSet Power", None))
        self.event_pulse_count_label.setText(_translate("MainWindow", "Event Pulse Count", None))
        self.event_pulse_count_outputwidget.setText(_translate("MainWindow", "0", None))
        self.llrf_trigger_label.setText(_translate("MainWindow", "LLRF Trigger", None))
        self.rf_mod_label.setText(_translate("MainWindow", "Mod state", None))
        self.llrf_output_label.setText(_translate("MainWindow", "LLRF Output", None))
        self.llrf_ff_amp_locked_label.setText(_translate("MainWindow", "LLRF Amp Locked", None))
        self.llrf_trigger_outputwidget.setText(_translate("MainWindow", "-9", None))
        self.llrf_ff_ph_locked_label.setText(_translate("MainWindow", "LLRF Phase Locked", None))
        self.llrf_output_outputwidget.setText(_translate("MainWindow", "output?", None))
        self.DC_spike_status_outputwidget.setText(_translate("MainWindow", "Nope", None))
        self.vac_valve_status_label.setText(_translate("MainWindow", "Vacuum valve status", None))
        self.RF_protection_label.setText(_translate("MainWindow", "RF Protection", None))
        self.vac_spike_status_outputwidget.setText(_translate("MainWindow", "RF paused", None))
        self.rev_power_spike_label.setText(_translate("MainWindow", "Cavity Forward Spike", None))
        self.vac_valve_status_outputwidget.setText(_translate("MainWindow", "Open", None))
        self.llrf_ff_ph_locked_outputwidget.setText(_translate("MainWindow", "locked?", None))
        self.rev_power_spike_status_outputwidget.setText(_translate("MainWindow", "Nope", None))
        self.mod_state_outputwidget.setText(_translate("MainWindow", "UK", None))
        self.vac_spike_label.setText(_translate("MainWindow", "Vacuum spike", None))
        self.llrf_ff_amp_locked_outputwidget.setText(_translate("MainWindow", "locked?", None))
        self.RF_protection_outputwidget.setText(_translate("MainWindow", "Unknown", None))
        self.DC_spike_label.setText(_translate("MainWindow", "Dark current spike", None))
        self.vac_level_outputwidget.setText(_translate("MainWindow", "0", None))
        self.probe_power_outputwidget.setText(_translate("MainWindow", "0", None))
        self.vac_level_label.setText(_translate("MainWindow", "Vacuum level on IMG", None))
        self.cav_temp_outputwidget.setText(_translate("MainWindow", "0", None))
        self.cav_temp_label.setText(_translate("MainWindow", "Cavity temperature", None))
        self.rev_cav_power_label.setText(_translate("MainWindow", "Reverse power at cavity", None))
        self.water_temp_outputwidget.setText(_translate("MainWindow", "0", None))
        self.fwd_kly_power_outputwidget.setText(_translate("MainWindow", "0", None))
        self.water_temp_label.setText(_translate("MainWindow", "Water temperature", None))
        self.rev_kly_power_outputwidget.setText(_translate("MainWindow", "0", None))
        self.rev_cav_power_outputwidget.setText(_translate("MainWindow", "0", None))
        self.fwd_kly_power_label.setText(_translate("MainWindow", "Forward power at klystron", None))
        self.rev_kly_power_label.setText(_translate("MainWindow", "Reverse power at klystron", None))
        self.fwd_cav_power_outputwidget.setText(_translate("MainWindow", "No", None))
        self.fwd_cav_power_label.setText(_translate("MainWindow", "Forward power at cavity", None))
        self.probe_power_label.setText(_translate("MainWindow", "Probe power", None))
        self.dc_level_label.setText(_translate("MainWindow", "dc level on scope", None))
        self.dc_level_outputwidget.setText(_translate("MainWindow", "0", None))
        self.label.setText(_translate("MainWindow", "TextLabel", None))

from pyqtgraph import PlotWidget
