#!/usr/bin/env python
# -*- coding: utf-8 -*-
from PyQt4 import QtGui, QtCore
from Ui_magnetFileSave import Ui_SaveMagnetSettings

class GUI_FileSave(QtGui.QMainWindow, Ui_SaveMagnetSettings):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        # startup crap
        self.setupUi(self)
        self.setWindowIcon(QtGui.QIcon('magpic.jpg'))
        self.appPixMap = QtGui.QPixmap('magpic.jpg')