# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_magnetAppMainView.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_magnetAppMainView(object):
    def setupUi(self, magnetAppMainView):
        magnetAppMainView.setObjectName(_fromUtf8("magnetAppMainView"))
        magnetAppMainView.resize(1254, 605)
        self.mainFrame = QtGui.QWidget(magnetAppMainView)
        self.mainFrame.setObjectName(_fromUtf8("mainFrame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.mainFrame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.titleLabel = QtGui.QLabel(self.mainFrame)
        self.titleLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.verticalLayout.addWidget(self.titleLabel)
        self.mainWidgetFrame = QtGui.QFrame(self.mainFrame)
        self.mainWidgetFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mainWidgetFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.mainWidgetFrame.setObjectName(_fromUtf8("mainWidgetFrame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.mainWidgetFrame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.controlButtonFrame = QtGui.QFrame(self.mainWidgetFrame)
        self.controlButtonFrame.setMinimumSize(QtCore.QSize(120, 300))
        self.controlButtonFrame.setMaximumSize(QtCore.QSize(120, 650))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.controlButtonFrame.setFont(font)
        self.controlButtonFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.controlButtonFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.controlButtonFrame.setObjectName(_fromUtf8("controlButtonFrame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.controlButtonFrame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.controlsLabel = QtGui.QLabel(self.controlButtonFrame)
        self.controlsLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.controlsLabel.setFont(font)
        self.controlsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.controlsLabel.setObjectName(_fromUtf8("controlsLabel"))
        self.verticalLayout_2.addWidget(self.controlsLabel)
        self.mainSelectAll = QtGui.QPushButton(self.controlButtonFrame)
        self.mainSelectAll.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mainSelectAll.setFont(font)
        self.mainSelectAll.setObjectName(_fromUtf8("mainSelectAll"))
        self.verticalLayout_2.addWidget(self.mainSelectAll)
        self.selectNone = QtGui.QPushButton(self.controlButtonFrame)
        self.selectNone.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectNone.setFont(font)
        self.selectNone.setObjectName(_fromUtf8("selectNone"))
        self.verticalLayout_2.addWidget(self.selectNone)
        self.selectedOn = QtGui.QPushButton(self.controlButtonFrame)
        self.selectedOn.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectedOn.setFont(font)
        self.selectedOn.setObjectName(_fromUtf8("selectedOn"))
        self.verticalLayout_2.addWidget(self.selectedOn)
        self.allOff = QtGui.QPushButton(self.controlButtonFrame)
        self.allOff.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.allOff.setFont(font)
        self.allOff.setObjectName(_fromUtf8("allOff"))
        self.verticalLayout_2.addWidget(self.allOff)
        self.selectedDegauss = QtGui.QPushButton(self.controlButtonFrame)
        self.selectedDegauss.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectedDegauss.setFont(font)
        self.selectedDegauss.setObjectName(_fromUtf8("selectedDegauss"))
        self.verticalLayout_2.addWidget(self.selectedDegauss)
        self.loadSettings = QtGui.QPushButton(self.controlButtonFrame)
        self.loadSettings.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loadSettings.setFont(font)
        self.loadSettings.setObjectName(_fromUtf8("loadSettings"))
        self.verticalLayout_2.addWidget(self.loadSettings)
        self.saveSettings = QtGui.QPushButton(self.controlButtonFrame)
        self.saveSettings.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saveSettings.setFont(font)
        self.saveSettings.setObjectName(_fromUtf8("saveSettings"))
        self.verticalLayout_2.addWidget(self.saveSettings)
        self.iconLabel = QtGui.QLabel(self.controlButtonFrame)
        self.iconLabel.setMinimumSize(QtCore.QSize(0, 100))
        self.iconLabel.setObjectName(_fromUtf8("iconLabel"))
        self.verticalLayout_2.addWidget(self.iconLabel)
        self.logoLabel = QtGui.QLabel(self.controlButtonFrame)
        self.logoLabel.setMinimumSize(QtCore.QSize(0, 100))
        self.logoLabel.setObjectName(_fromUtf8("logoLabel"))
        self.verticalLayout_2.addWidget(self.logoLabel)
        self.horizontalLayout.addWidget(self.controlButtonFrame)
        self.line = QtGui.QFrame(self.mainWidgetFrame)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.solFrame = QtGui.QFrame(self.mainWidgetFrame)
        self.solFrame.setMinimumSize(QtCore.QSize(0, 300))
        self.solFrame.setMaximumSize(QtCore.QSize(120, 16777215))
        self.solFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.solFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.solFrame.setObjectName(_fromUtf8("solFrame"))
        self.solFrameLayout = QtGui.QVBoxLayout(self.solFrame)
        self.solFrameLayout.setObjectName(_fromUtf8("solFrameLayout"))
        self.solenoidsLabel = QtGui.QLabel(self.solFrame)
        self.solenoidsLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.solenoidsLabel.setFont(font)
        self.solenoidsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.solenoidsLabel.setObjectName(_fromUtf8("solenoidsLabel"))
        self.solFrameLayout.addWidget(self.solenoidsLabel)
        self.solSelectAll = QtGui.QPushButton(self.solFrame)
        self.solSelectAll.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.solSelectAll.setFont(font)
        self.solSelectAll.setObjectName(_fromUtf8("solSelectAll"))
        self.solFrameLayout.addWidget(self.solSelectAll)
        self.solSelectNone = QtGui.QPushButton(self.solFrame)
        self.solSelectNone.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.solSelectNone.setFont(font)
        self.solSelectNone.setObjectName(_fromUtf8("solSelectNone"))
        self.solFrameLayout.addWidget(self.solSelectNone)
        self.sol_Grid_Box = QtGui.QGridLayout()
        self.sol_Grid_Box.setObjectName(_fromUtf8("sol_Grid_Box"))
        self.solFrameLayout.addLayout(self.sol_Grid_Box)
        self.horizontalLayout.addWidget(self.solFrame)
        self.line_2 = QtGui.QFrame(self.mainWidgetFrame)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout.addWidget(self.line_2)
        self.dipFrame = QtGui.QFrame(self.mainWidgetFrame)
        self.dipFrame.setMaximumSize(QtCore.QSize(120, 16777215))
        self.dipFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.dipFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.dipFrame.setObjectName(_fromUtf8("dipFrame"))
        self.dipFrameLayout = QtGui.QVBoxLayout(self.dipFrame)
        self.dipFrameLayout.setObjectName(_fromUtf8("dipFrameLayout"))
        self.dipolesLabel = QtGui.QLabel(self.dipFrame)
        self.dipolesLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dipolesLabel.setFont(font)
        self.dipolesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dipolesLabel.setObjectName(_fromUtf8("dipolesLabel"))
        self.dipFrameLayout.addWidget(self.dipolesLabel)
        self.dipSelectAll = QtGui.QPushButton(self.dipFrame)
        self.dipSelectAll.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dipSelectAll.setFont(font)
        self.dipSelectAll.setObjectName(_fromUtf8("dipSelectAll"))
        self.dipFrameLayout.addWidget(self.dipSelectAll)
        self.dipSelectNone = QtGui.QPushButton(self.dipFrame)
        self.dipSelectNone.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dipSelectNone.setFont(font)
        self.dipSelectNone.setObjectName(_fromUtf8("dipSelectNone"))
        self.dipFrameLayout.addWidget(self.dipSelectNone)
        self.dip_Grid_Box = QtGui.QGridLayout()
        self.dip_Grid_Box.setObjectName(_fromUtf8("dip_Grid_Box"))
        self.dipFrameLayout.addLayout(self.dip_Grid_Box)
        self.horizontalLayout.addWidget(self.dipFrame)
        self.line_3 = QtGui.QFrame(self.mainWidgetFrame)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout.addWidget(self.line_3)
        self.quadFrame = QtGui.QFrame(self.mainWidgetFrame)
        self.quadFrame.setMaximumSize(QtCore.QSize(600, 16777215))
        self.quadFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.quadFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.quadFrame.setObjectName(_fromUtf8("quadFrame"))
        self.quadFrameLayout = QtGui.QVBoxLayout(self.quadFrame)
        self.quadFrameLayout.setObjectName(_fromUtf8("quadFrameLayout"))
        self.quadLabel = QtGui.QLabel(self.quadFrame)
        self.quadLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.quadLabel.setFont(font)
        self.quadLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.quadLabel.setObjectName(_fromUtf8("quadLabel"))
        self.quadFrameLayout.addWidget(self.quadLabel)
        self.quadSelectAll = QtGui.QPushButton(self.quadFrame)
        self.quadSelectAll.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quadSelectAll.setFont(font)
        self.quadSelectAll.setObjectName(_fromUtf8("quadSelectAll"))
        self.quadFrameLayout.addWidget(self.quadSelectAll)
        self.quadSelectNone = QtGui.QPushButton(self.quadFrame)
        self.quadSelectNone.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quadSelectNone.setFont(font)
        self.quadSelectNone.setObjectName(_fromUtf8("quadSelectNone"))
        self.quadFrameLayout.addWidget(self.quadSelectNone)
        self.quad_Grid_Box = QtGui.QGridLayout()
        self.quad_Grid_Box.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.quad_Grid_Box.setContentsMargins(-1, -1, 0, -1)
        self.quad_Grid_Box.setHorizontalSpacing(5)
        self.quad_Grid_Box.setVerticalSpacing(7)
        self.quad_Grid_Box.setObjectName(_fromUtf8("quad_Grid_Box"))
        self.quadFrameLayout.addLayout(self.quad_Grid_Box)
        self.horizontalLayout.addWidget(self.quadFrame)
        self.line_4 = QtGui.QFrame(self.mainWidgetFrame)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout.addWidget(self.line_4)
        self.corrFrame = QtGui.QFrame(self.mainWidgetFrame)
        self.corrFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.corrFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.corrFrame.setObjectName(_fromUtf8("corrFrame"))
        self.corFrameLayout = QtGui.QVBoxLayout(self.corrFrame)
        self.corFrameLayout.setObjectName(_fromUtf8("corFrameLayout"))
        self.corLabel = QtGui.QLabel(self.corrFrame)
        self.corLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.corLabel.setFont(font)
        self.corLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.corLabel.setObjectName(_fromUtf8("corLabel"))
        self.corFrameLayout.addWidget(self.corLabel)
        self.corSelectAll = QtGui.QPushButton(self.corrFrame)
        self.corSelectAll.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.corSelectAll.setFont(font)
        self.corSelectAll.setObjectName(_fromUtf8("corSelectAll"))
        self.corFrameLayout.addWidget(self.corSelectAll)
        self.corSelectNone = QtGui.QPushButton(self.corrFrame)
        self.corSelectNone.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.corSelectNone.setFont(font)
        self.corSelectNone.setObjectName(_fromUtf8("corSelectNone"))
        self.corFrameLayout.addWidget(self.corSelectNone)
        self.cor_Grid_Box = QtGui.QGridLayout()
        self.cor_Grid_Box.setObjectName(_fromUtf8("cor_Grid_Box"))
        self.corFrameLayout.addLayout(self.cor_Grid_Box)
        self.horizontalLayout.addWidget(self.corrFrame)
        self.verticalLayout.addWidget(self.mainWidgetFrame)
        magnetAppMainView.setCentralWidget(self.mainFrame)
        self.menubar = QtGui.QMenuBar(magnetAppMainView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1254, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        magnetAppMainView.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(magnetAppMainView)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        magnetAppMainView.setStatusBar(self.statusbar)

        self.retranslateUi(magnetAppMainView)
        QtCore.QMetaObject.connectSlotsByName(magnetAppMainView)

    def retranslateUi(self, magnetAppMainView):
        magnetAppMainView.setWindowTitle(_translate("magnetAppMainView", "MainWindow", None))
        self.titleLabel.setText(_translate("magnetAppMainView", "The title of this window, which area and mode etc.", None))
        self.controlsLabel.setText(_translate("magnetAppMainView", "Controls", None))
        self.mainSelectAll.setText(_translate("magnetAppMainView", "Select All", None))
        self.selectNone.setText(_translate("magnetAppMainView", "Select None", None))
        self.selectedOn.setText(_translate("magnetAppMainView", "Selected On", None))
        self.allOff.setText(_translate("magnetAppMainView", "All Off", None))
        self.selectedDegauss.setText(_translate("magnetAppMainView", "Degauss", None))
        self.loadSettings.setText(_translate("magnetAppMainView", "Load ", None))
        self.saveSettings.setText(_translate("magnetAppMainView", "Save", None))
        self.iconLabel.setText(_translate("magnetAppMainView", "TextLabel", None))
        self.logoLabel.setText(_translate("magnetAppMainView", "logo", None))
        self.solenoidsLabel.setText(_translate("magnetAppMainView", "Solenoids", None))
        self.solSelectAll.setText(_translate("magnetAppMainView", "Select All", None))
        self.solSelectNone.setText(_translate("magnetAppMainView", "Select None", None))
        self.dipolesLabel.setText(_translate("magnetAppMainView", "Dipoles", None))
        self.dipSelectAll.setText(_translate("magnetAppMainView", "Select All", None))
        self.dipSelectNone.setText(_translate("magnetAppMainView", "Select None", None))
        self.quadLabel.setText(_translate("magnetAppMainView", "Quadrupoles", None))
        self.quadSelectAll.setText(_translate("magnetAppMainView", "Select All", None))
        self.quadSelectNone.setText(_translate("magnetAppMainView", "Select None", None))
        self.corLabel.setText(_translate("magnetAppMainView", "Correctors", None))
        self.corSelectAll.setText(_translate("magnetAppMainView", "Select All", None))
        self.corSelectNone.setText(_translate("magnetAppMainView", "Select None", None))

