# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1040, 699)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../Resources/Icons/mountain-summit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.centralWidgetLayout = QtGui.QGridLayout(self.centralwidget)
        self.centralWidgetLayout.setObjectName(_fromUtf8("centralWidgetLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.TurnOffQuadsButton = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TurnOffQuadsButton.sizePolicy().hasHeightForWidth())
        self.TurnOffQuadsButton.setSizePolicy(sizePolicy)
        self.TurnOffQuadsButton.setObjectName(_fromUtf8("TurnOffQuadsButton"))
        self.verticalLayout.addWidget(self.TurnOffQuadsButton)
        self.DegaussButton = QtGui.QPushButton(self.groupBox_2)
        self.DegaussButton.setObjectName(_fromUtf8("DegaussButton"))
        self.verticalLayout.addWidget(self.DegaussButton)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.nSamples = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nSamples.sizePolicy().hasHeightForWidth())
        self.nSamples.setSizePolicy(sizePolicy)
        self.nSamples.setMinimum(2)
        self.nSamples.setProperty("value", 10)
        self.nSamples.setObjectName(_fromUtf8("nSamples"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.nSamples)
        self.horizontalLayout.addWidget(self.groupBox)
        self.label_MODE = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_MODE.sizePolicy().hasHeightForWidth())
        self.label_MODE.setSizePolicy(sizePolicy)
        self.label_MODE.setMinimumSize(QtCore.QSize(0, 25))
        self.label_MODE.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_MODE.setObjectName(_fromUtf8("label_MODE"))
        self.horizontalLayout.addWidget(self.label_MODE)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.finishButton = QtGui.QPushButton(self.frame)
        self.finishButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.finishButton.setObjectName(_fromUtf8("finishButton"))
        self.horizontalLayout.addWidget(self.finishButton)
        self.abortButton = QtGui.QPushButton(self.frame)
        self.abortButton.setEnabled(True)
        self.abortButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.abortButton.setAutoFillBackground(False)
        self.abortButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.abortButton.setIcon(icon1)
        self.abortButton.setObjectName(_fromUtf8("abortButton"))
        self.horizontalLayout.addWidget(self.abortButton)
        self.centralWidgetLayout.addWidget(self.frame, 1, 0, 2, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.S2Q1Tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S2Q1Tab.sizePolicy().hasHeightForWidth())
        self.S2Q1Tab.setSizePolicy(sizePolicy)
        self.S2Q1Tab.setObjectName(_fromUtf8("S2Q1Tab"))
        self.S2Q1TabLayout = QtGui.QGridLayout(self.S2Q1Tab)
        self.S2Q1TabLayout.setObjectName(_fromUtf8("S2Q1TabLayout"))
        self.groupBox_plotsS2Q1 = QtGui.QGroupBox(self.S2Q1Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_plotsS2Q1.sizePolicy().hasHeightForWidth())
        self.groupBox_plotsS2Q1.setSizePolicy(sizePolicy)
        self.groupBox_plotsS2Q1.setObjectName(_fromUtf8("groupBox_plotsS2Q1"))
        self.plotLayoutS2Q1 = QtGui.QHBoxLayout(self.groupBox_plotsS2Q1)
        self.plotLayoutS2Q1.setObjectName(_fromUtf8("plotLayoutS2Q1"))
        self.S2Q1TabLayout.addWidget(self.groupBox_plotsS2Q1, 0, 1, 4, 1)
        self.groupBox_S2Q1 = QtGui.QGroupBox(self.S2Q1Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_S2Q1.sizePolicy().hasHeightForWidth())
        self.groupBox_S2Q1.setSizePolicy(sizePolicy)
        self.groupBox_S2Q1.setObjectName(_fromUtf8("groupBox_S2Q1"))
        self.formLayout_S2Q1 = QtGui.QFormLayout(self.groupBox_S2Q1)
        self.formLayout_S2Q1.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_S2Q1.setObjectName(_fromUtf8("formLayout_S2Q1"))
        self.label_Lower_S2Q1 = QtGui.QLabel(self.groupBox_S2Q1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Lower_S2Q1.sizePolicy().hasHeightForWidth())
        self.label_Lower_S2Q1.setSizePolicy(sizePolicy)
        self.label_Lower_S2Q1.setMinimumSize(QtCore.QSize(150, 0))
        self.label_Lower_S2Q1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Lower_S2Q1.setObjectName(_fromUtf8("label_Lower_S2Q1"))
        self.formLayout_S2Q1.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_Lower_S2Q1)
        self.S2Q1LowerSet = QtGui.QSpinBox(self.groupBox_S2Q1)
        self.S2Q1LowerSet.setMinimumSize(QtCore.QSize(100, 0))
        self.S2Q1LowerSet.setMinimum(-100)
        self.S2Q1LowerSet.setMaximum(100)
        self.S2Q1LowerSet.setSingleStep(5)
        self.S2Q1LowerSet.setProperty("value", -50)
        self.S2Q1LowerSet.setObjectName(_fromUtf8("S2Q1LowerSet"))
        self.formLayout_S2Q1.setWidget(0, QtGui.QFormLayout.FieldRole, self.S2Q1LowerSet)
        self.label_Upper_S2Q1 = QtGui.QLabel(self.groupBox_S2Q1)
        self.label_Upper_S2Q1.setObjectName(_fromUtf8("label_Upper_S2Q1"))
        self.formLayout_S2Q1.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_Upper_S2Q1)
        self.S2Q1UpperSet = QtGui.QSpinBox(self.groupBox_S2Q1)
        self.S2Q1UpperSet.setMinimumSize(QtCore.QSize(100, 0))
        self.S2Q1UpperSet.setMinimum(-100)
        self.S2Q1UpperSet.setMaximum(100)
        self.S2Q1UpperSet.setSingleStep(5)
        self.S2Q1UpperSet.setProperty("value", 50)
        self.S2Q1UpperSet.setObjectName(_fromUtf8("S2Q1UpperSet"))
        self.formLayout_S2Q1.setWidget(1, QtGui.QFormLayout.FieldRole, self.S2Q1UpperSet)
        self.S2Q1StepSet = QtGui.QSpinBox(self.groupBox_S2Q1)
        self.S2Q1StepSet.setMaximum(50)
        self.S2Q1StepSet.setSingleStep(5)
        self.S2Q1StepSet.setProperty("value", 5)
        self.S2Q1StepSet.setObjectName(_fromUtf8("S2Q1StepSet"))
        self.formLayout_S2Q1.setWidget(2, QtGui.QFormLayout.FieldRole, self.S2Q1StepSet)
        self.label_Step_S2Q1 = QtGui.QLabel(self.groupBox_S2Q1)
        self.label_Step_S2Q1.setObjectName(_fromUtf8("label_Step_S2Q1"))
        self.formLayout_S2Q1.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_Step_S2Q1)
        self.S2Q1TabLayout.addWidget(self.groupBox_S2Q1, 0, 0, 1, 1)
        self.groupBox_methodS2Q1 = QtGui.QGroupBox(self.S2Q1Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_methodS2Q1.sizePolicy().hasHeightForWidth())
        self.groupBox_methodS2Q1.setSizePolicy(sizePolicy)
        self.groupBox_methodS2Q1.setObjectName(_fromUtf8("groupBox_methodS2Q1"))
        self.verticalLayout_S2Q1 = QtGui.QVBoxLayout(self.groupBox_methodS2Q1)
        self.verticalLayout_S2Q1.setObjectName(_fromUtf8("verticalLayout_S2Q1"))
        self.S2Q1StartButton = QtGui.QPushButton(self.groupBox_methodS2Q1)
        self.S2Q1StartButton.setObjectName(_fromUtf8("S2Q1StartButton"))
        self.verticalLayout_S2Q1.addWidget(self.S2Q1StartButton)
        self.S2Q1TabLayout.addWidget(self.groupBox_methodS2Q1, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.S2Q1TabLayout.addItem(spacerItem1, 2, 0, 2, 1)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("None"))
        self.tabWidget.addTab(self.S2Q1Tab, icon, _fromUtf8(""))
        self.S2Q2Tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S2Q2Tab.sizePolicy().hasHeightForWidth())
        self.S2Q2Tab.setSizePolicy(sizePolicy)
        self.S2Q2Tab.setObjectName(_fromUtf8("S2Q2Tab"))
        self.S2Q2TabLayout = QtGui.QGridLayout(self.S2Q2Tab)
        self.S2Q2TabLayout.setObjectName(_fromUtf8("S2Q2TabLayout"))
        self.groupBox_plotsS2Q2 = QtGui.QGroupBox(self.S2Q2Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_plotsS2Q2.sizePolicy().hasHeightForWidth())
        self.groupBox_plotsS2Q2.setSizePolicy(sizePolicy)
        self.groupBox_plotsS2Q2.setObjectName(_fromUtf8("groupBox_plotsS2Q2"))
        self.plotLayoutS2Q2 = QtGui.QHBoxLayout(self.groupBox_plotsS2Q2)
        self.plotLayoutS2Q2.setObjectName(_fromUtf8("plotLayoutS2Q2"))
        self.S2Q2TabLayout.addWidget(self.groupBox_plotsS2Q2, 0, 1, 4, 1)
        self.groupBox_S2Q2 = QtGui.QGroupBox(self.S2Q2Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_S2Q2.sizePolicy().hasHeightForWidth())
        self.groupBox_S2Q2.setSizePolicy(sizePolicy)
        self.groupBox_S2Q2.setObjectName(_fromUtf8("groupBox_S2Q2"))
        self.formLayout_S2Q2 = QtGui.QFormLayout(self.groupBox_S2Q2)
        self.formLayout_S2Q2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_S2Q2.setObjectName(_fromUtf8("formLayout_S2Q2"))
        self.label_Lower_S2Q2 = QtGui.QLabel(self.groupBox_S2Q2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Lower_S2Q2.sizePolicy().hasHeightForWidth())
        self.label_Lower_S2Q2.setSizePolicy(sizePolicy)
        self.label_Lower_S2Q2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_Lower_S2Q2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Lower_S2Q2.setObjectName(_fromUtf8("label_Lower_S2Q2"))
        self.formLayout_S2Q2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_Lower_S2Q2)
        self.S2Q2LowerSet = QtGui.QSpinBox(self.groupBox_S2Q2)
        self.S2Q2LowerSet.setMinimumSize(QtCore.QSize(100, 0))
        self.S2Q2LowerSet.setMinimum(-100)
        self.S2Q2LowerSet.setMaximum(100)
        self.S2Q2LowerSet.setSingleStep(5)
        self.S2Q2LowerSet.setProperty("value", -50)
        self.S2Q2LowerSet.setObjectName(_fromUtf8("S2Q2LowerSet"))
        self.formLayout_S2Q2.setWidget(0, QtGui.QFormLayout.FieldRole, self.S2Q2LowerSet)
        self.label_Upper_S2Q2 = QtGui.QLabel(self.groupBox_S2Q2)
        self.label_Upper_S2Q2.setObjectName(_fromUtf8("label_Upper_S2Q2"))
        self.formLayout_S2Q2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_Upper_S2Q2)
        self.S2Q2UpperSet = QtGui.QSpinBox(self.groupBox_S2Q2)
        self.S2Q2UpperSet.setMinimumSize(QtCore.QSize(100, 0))
        self.S2Q2UpperSet.setMinimum(-100)
        self.S2Q2UpperSet.setMaximum(100)
        self.S2Q2UpperSet.setSingleStep(5)
        self.S2Q2UpperSet.setProperty("value", 50)
        self.S2Q2UpperSet.setObjectName(_fromUtf8("S2Q2UpperSet"))
        self.formLayout_S2Q2.setWidget(1, QtGui.QFormLayout.FieldRole, self.S2Q2UpperSet)
        self.S2Q2StepSet = QtGui.QSpinBox(self.groupBox_S2Q2)
        self.S2Q2StepSet.setMaximum(50)
        self.S2Q2StepSet.setSingleStep(5)
        self.S2Q2StepSet.setProperty("value", 5)
        self.S2Q2StepSet.setObjectName(_fromUtf8("S2Q2StepSet"))
        self.formLayout_S2Q2.setWidget(2, QtGui.QFormLayout.FieldRole, self.S2Q2StepSet)
        self.label_Step_S2Q2 = QtGui.QLabel(self.groupBox_S2Q2)
        self.label_Step_S2Q2.setObjectName(_fromUtf8("label_Step_S2Q2"))
        self.formLayout_S2Q2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_Step_S2Q2)
        self.S2Q2TabLayout.addWidget(self.groupBox_S2Q2, 0, 0, 1, 1)
        self.groupBox_methodS2Q2 = QtGui.QGroupBox(self.S2Q2Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_methodS2Q2.sizePolicy().hasHeightForWidth())
        self.groupBox_methodS2Q2.setSizePolicy(sizePolicy)
        self.groupBox_methodS2Q2.setObjectName(_fromUtf8("groupBox_methodS2Q2"))
        self.verticalLayout_S2Q2 = QtGui.QVBoxLayout(self.groupBox_methodS2Q2)
        self.verticalLayout_S2Q2.setObjectName(_fromUtf8("verticalLayout_S2Q2"))
        self.S2Q2StartButton = QtGui.QPushButton(self.groupBox_methodS2Q2)
        self.S2Q2StartButton.setObjectName(_fromUtf8("S2Q2StartButton"))
        self.verticalLayout_S2Q2.addWidget(self.S2Q2StartButton)
        self.S2Q2TabLayout.addWidget(self.groupBox_methodS2Q2, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.S2Q2TabLayout.addItem(spacerItem2, 2, 0, 2, 1)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("None"))
        self.tabWidget.addTab(self.S2Q2Tab, icon, _fromUtf8(""))
        self.S2Q3Tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S2Q3Tab.sizePolicy().hasHeightForWidth())
        self.S2Q3Tab.setSizePolicy(sizePolicy)
        self.S2Q3Tab.setObjectName(_fromUtf8("S2Q3Tab"))
        self.S2Q3TabLayout = QtGui.QGridLayout(self.S2Q3Tab)
        self.S2Q3TabLayout.setObjectName(_fromUtf8("S2Q3TabLayout"))
        self.groupBox_plotsS2Q3 = QtGui.QGroupBox(self.S2Q3Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_plotsS2Q3.sizePolicy().hasHeightForWidth())
        self.groupBox_plotsS2Q3.setSizePolicy(sizePolicy)
        self.groupBox_plotsS2Q3.setObjectName(_fromUtf8("groupBox_plotsS2Q3"))
        self.plotLayoutS2Q3 = QtGui.QHBoxLayout(self.groupBox_plotsS2Q3)
        self.plotLayoutS2Q3.setObjectName(_fromUtf8("plotLayoutS2Q3"))
        self.S2Q3TabLayout.addWidget(self.groupBox_plotsS2Q3, 0, 1, 4, 1)
        self.groupBox_S2Q3 = QtGui.QGroupBox(self.S2Q3Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_S2Q3.sizePolicy().hasHeightForWidth())
        self.groupBox_S2Q3.setSizePolicy(sizePolicy)
        self.groupBox_S2Q3.setObjectName(_fromUtf8("groupBox_S2Q3"))
        self.formLayout_S2Q3 = QtGui.QFormLayout(self.groupBox_S2Q3)
        self.formLayout_S2Q3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_S2Q3.setObjectName(_fromUtf8("formLayout_S2Q3"))
        self.label_Lower_S2Q3 = QtGui.QLabel(self.groupBox_S2Q3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Lower_S2Q3.sizePolicy().hasHeightForWidth())
        self.label_Lower_S2Q3.setSizePolicy(sizePolicy)
        self.label_Lower_S2Q3.setMinimumSize(QtCore.QSize(150, 0))
        self.label_Lower_S2Q3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Lower_S2Q3.setObjectName(_fromUtf8("label_Lower_S2Q3"))
        self.formLayout_S2Q3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_Lower_S2Q3)
        self.S2Q3LowerSet = QtGui.QSpinBox(self.groupBox_S2Q3)
        self.S2Q3LowerSet.setMinimumSize(QtCore.QSize(100, 0))
        self.S2Q3LowerSet.setMinimum(-100)
        self.S2Q3LowerSet.setMaximum(100)
        self.S2Q3LowerSet.setSingleStep(5)
        self.S2Q3LowerSet.setProperty("value", -50)
        self.S2Q3LowerSet.setObjectName(_fromUtf8("S2Q3LowerSet"))
        self.formLayout_S2Q3.setWidget(0, QtGui.QFormLayout.FieldRole, self.S2Q3LowerSet)
        self.label_Upper_S2Q3 = QtGui.QLabel(self.groupBox_S2Q3)
        self.label_Upper_S2Q3.setObjectName(_fromUtf8("label_Upper_S2Q3"))
        self.formLayout_S2Q3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_Upper_S2Q3)
        self.S2Q3UpperSet = QtGui.QSpinBox(self.groupBox_S2Q3)
        self.S2Q3UpperSet.setMinimumSize(QtCore.QSize(100, 0))
        self.S2Q3UpperSet.setMinimum(-100)
        self.S2Q3UpperSet.setMaximum(100)
        self.S2Q3UpperSet.setSingleStep(5)
        self.S2Q3UpperSet.setProperty("value", 50)
        self.S2Q3UpperSet.setObjectName(_fromUtf8("S2Q3UpperSet"))
        self.formLayout_S2Q3.setWidget(1, QtGui.QFormLayout.FieldRole, self.S2Q3UpperSet)
        self.S2Q3StepSet = QtGui.QSpinBox(self.groupBox_S2Q3)
        self.S2Q3StepSet.setMaximum(50)
        self.S2Q3StepSet.setSingleStep(5)
        self.S2Q3StepSet.setProperty("value", 5)
        self.S2Q3StepSet.setObjectName(_fromUtf8("S2Q3StepSet"))
        self.formLayout_S2Q3.setWidget(2, QtGui.QFormLayout.FieldRole, self.S2Q3StepSet)
        self.label_Step_S2Q3 = QtGui.QLabel(self.groupBox_S2Q3)
        self.label_Step_S2Q3.setObjectName(_fromUtf8("label_Step_S2Q3"))
        self.formLayout_S2Q3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_Step_S2Q3)
        self.S2Q3TabLayout.addWidget(self.groupBox_S2Q3, 0, 0, 1, 1)
        self.groupBox_methodS2Q3 = QtGui.QGroupBox(self.S2Q3Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_methodS2Q3.sizePolicy().hasHeightForWidth())
        self.groupBox_methodS2Q3.setSizePolicy(sizePolicy)
        self.groupBox_methodS2Q3.setObjectName(_fromUtf8("groupBox_methodS2Q3"))
        self.verticalLayout_S2Q3 = QtGui.QVBoxLayout(self.groupBox_methodS2Q3)
        self.verticalLayout_S2Q3.setObjectName(_fromUtf8("verticalLayout_S2Q3"))
        self.S2Q3StartButton = QtGui.QPushButton(self.groupBox_methodS2Q3)
        self.S2Q3StartButton.setObjectName(_fromUtf8("S2Q3StartButton"))
        self.verticalLayout_S2Q3.addWidget(self.S2Q3StartButton)
        self.S2Q3TabLayout.addWidget(self.groupBox_methodS2Q3, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.S2Q3TabLayout.addItem(spacerItem3, 2, 0, 2, 1)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("None"))
        self.tabWidget.addTab(self.S2Q3Tab, icon, _fromUtf8(""))
        self.S2Q4Tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S2Q4Tab.sizePolicy().hasHeightForWidth())
        self.S2Q4Tab.setSizePolicy(sizePolicy)
        self.S2Q4Tab.setObjectName(_fromUtf8("S2Q4Tab"))
        self.S2Q4TabLayout = QtGui.QGridLayout(self.S2Q4Tab)
        self.S2Q4TabLayout.setObjectName(_fromUtf8("S2Q4TabLayout"))
        self.groupBox_plotsS2Q4 = QtGui.QGroupBox(self.S2Q4Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_plotsS2Q4.sizePolicy().hasHeightForWidth())
        self.groupBox_plotsS2Q4.setSizePolicy(sizePolicy)
        self.groupBox_plotsS2Q4.setObjectName(_fromUtf8("groupBox_plotsS2Q4"))
        self.plotLayoutS2Q4 = QtGui.QHBoxLayout(self.groupBox_plotsS2Q4)
        self.plotLayoutS2Q4.setObjectName(_fromUtf8("plotLayoutS2Q4"))
        self.S2Q4TabLayout.addWidget(self.groupBox_plotsS2Q4, 0, 1, 4, 1)
        self.groupBox_S2Q4 = QtGui.QGroupBox(self.S2Q4Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_S2Q4.sizePolicy().hasHeightForWidth())
        self.groupBox_S2Q4.setSizePolicy(sizePolicy)
        self.groupBox_S2Q4.setObjectName(_fromUtf8("groupBox_S2Q4"))
        self.formLayout_S2Q4 = QtGui.QFormLayout(self.groupBox_S2Q4)
        self.formLayout_S2Q4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_S2Q4.setObjectName(_fromUtf8("formLayout_S2Q4"))
        self.label_Lower_S2Q4 = QtGui.QLabel(self.groupBox_S2Q4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Lower_S2Q4.sizePolicy().hasHeightForWidth())
        self.label_Lower_S2Q4.setSizePolicy(sizePolicy)
        self.label_Lower_S2Q4.setMinimumSize(QtCore.QSize(150, 0))
        self.label_Lower_S2Q4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Lower_S2Q4.setObjectName(_fromUtf8("label_Lower_S2Q4"))
        self.formLayout_S2Q4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_Lower_S2Q4)
        self.S2Q4LowerSet = QtGui.QSpinBox(self.groupBox_S2Q4)
        self.S2Q4LowerSet.setMinimumSize(QtCore.QSize(100, 0))
        self.S2Q4LowerSet.setMinimum(-100)
        self.S2Q4LowerSet.setMaximum(100)
        self.S2Q4LowerSet.setSingleStep(5)
        self.S2Q4LowerSet.setProperty("value", -50)
        self.S2Q4LowerSet.setObjectName(_fromUtf8("S2Q4LowerSet"))
        self.formLayout_S2Q4.setWidget(0, QtGui.QFormLayout.FieldRole, self.S2Q4LowerSet)
        self.label_Upper_S2Q4 = QtGui.QLabel(self.groupBox_S2Q4)
        self.label_Upper_S2Q4.setObjectName(_fromUtf8("label_Upper_S2Q4"))
        self.formLayout_S2Q4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_Upper_S2Q4)
        self.S2Q4UpperSet = QtGui.QSpinBox(self.groupBox_S2Q4)
        self.S2Q4UpperSet.setMinimumSize(QtCore.QSize(100, 0))
        self.S2Q4UpperSet.setMinimum(-100)
        self.S2Q4UpperSet.setMaximum(100)
        self.S2Q4UpperSet.setSingleStep(5)
        self.S2Q4UpperSet.setProperty("value", 50)
        self.S2Q4UpperSet.setObjectName(_fromUtf8("S2Q4UpperSet"))
        self.formLayout_S2Q4.setWidget(1, QtGui.QFormLayout.FieldRole, self.S2Q4UpperSet)
        self.S2Q4StepSet = QtGui.QSpinBox(self.groupBox_S2Q4)
        self.S2Q4StepSet.setMaximum(50)
        self.S2Q4StepSet.setSingleStep(5)
        self.S2Q4StepSet.setProperty("value", 5)
        self.S2Q4StepSet.setObjectName(_fromUtf8("S2Q4StepSet"))
        self.formLayout_S2Q4.setWidget(2, QtGui.QFormLayout.FieldRole, self.S2Q4StepSet)
        self.label_Step_S2Q4 = QtGui.QLabel(self.groupBox_S2Q4)
        self.label_Step_S2Q4.setObjectName(_fromUtf8("label_Step_S2Q4"))
        self.formLayout_S2Q4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_Step_S2Q4)
        self.S2Q4TabLayout.addWidget(self.groupBox_S2Q4, 0, 0, 1, 1)
        self.groupBox_methodS2Q4 = QtGui.QGroupBox(self.S2Q4Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_methodS2Q4.sizePolicy().hasHeightForWidth())
        self.groupBox_methodS2Q4.setSizePolicy(sizePolicy)
        self.groupBox_methodS2Q4.setObjectName(_fromUtf8("groupBox_methodS2Q4"))
        self.verticalLayout_S2Q4 = QtGui.QVBoxLayout(self.groupBox_methodS2Q4)
        self.verticalLayout_S2Q4.setObjectName(_fromUtf8("verticalLayout_S2Q4"))
        self.S2Q4StartButton = QtGui.QPushButton(self.groupBox_methodS2Q4)
        self.S2Q4StartButton.setObjectName(_fromUtf8("S2Q4StartButton"))
        self.verticalLayout_S2Q4.addWidget(self.S2Q4StartButton)
        self.S2Q4TabLayout.addWidget(self.groupBox_methodS2Q4, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.S2Q4TabLayout.addItem(spacerItem4, 2, 0, 2, 1)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("None"))
        self.tabWidget.addTab(self.S2Q4Tab, icon, _fromUtf8(""))
        self.logTab = QtGui.QWidget()
        self.logTab.setObjectName(_fromUtf8("logTab"))
        self.logTabLayout = QtGui.QVBoxLayout(self.logTab)
        self.logTabLayout.setObjectName(_fromUtf8("logTabLayout"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/log.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.logTab, icon2, _fromUtf8(""))
        self.centralWidgetLayout.addWidget(self.tabWidget, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1040, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSave_Data = QtGui.QMenu(self.menubar)
        self.menuSave_Data.setObjectName(_fromUtf8("menuSave_Data"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_Calibation_Data = QtGui.QAction(MainWindow)
        self.actionSave_Calibation_Data.setObjectName(_fromUtf8("actionSave_Calibation_Data"))
        self.actionAuto_Save_Data = QtGui.QAction(MainWindow)
        self.actionAuto_Save_Data.setCheckable(True)
        self.actionAuto_Save_Data.setChecked(True)
        self.actionAuto_Save_Data.setObjectName(_fromUtf8("actionAuto_Save_Data"))
        self.actionSave_to_Work_Folder = QtGui.QAction(MainWindow)
        self.actionSave_to_Work_Folder.setCheckable(True)
        self.actionSave_to_Work_Folder.setChecked(True)
        self.actionSave_to_Work_Folder.setObjectName(_fromUtf8("actionSave_to_Work_Folder"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionExit)
        self.menuSave_Data.addAction(self.actionAuto_Save_Data)
        self.menuSave_Data.addAction(self.actionSave_to_Work_Folder)
        self.menuSave_Data.addAction(self.actionSave_Calibation_Data)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSave_Data.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Phase Calibration", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Setup", None))
        self.TurnOffQuadsButton.setText(_translate("MainWindow", "Turn Off Quads\n"
"+ Corrs", None))
        self.DegaussButton.setText(_translate("MainWindow", "Degauss\n"
"Quads", None))
        self.groupBox.setTitle(_translate("MainWindow", "BPM Settings", None))
        self.label_3.setText(_translate("MainWindow", "BPM Samples", None))
        self.label_MODE.setText(_translate("MainWindow", "Mode", None))
        self.finishButton.setText(_translate("MainWindow", "Finish Scan", None))
        self.abortButton.setText(_translate("MainWindow", "Abort", None))
        self.groupBox_plotsS2Q1.setTitle(_translate("MainWindow", "Plots", None))
        self.groupBox_S2Q1.setTitle(_translate("MainWindow", "Quad Settings", None))
        self.label_Lower_S2Q1.setText(_translate("MainWindow", "Lower Amplitude", None))
        self.label_Upper_S2Q1.setText(_translate("MainWindow", "Upper Amplitude", None))
        self.label_Step_S2Q1.setText(_translate("MainWindow", "Step Size", None))
        self.groupBox_methodS2Q1.setTitle(_translate("MainWindow", "Method", None))
        self.S2Q1StartButton.setText(_translate("MainWindow", "Scan Quadrupole", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.S2Q1Tab), _translate("MainWindow", "S02-QUAD-01", None))
        self.groupBox_plotsS2Q2.setTitle(_translate("MainWindow", "Plots", None))
        self.groupBox_S2Q2.setTitle(_translate("MainWindow", "Quad Settings", None))
        self.label_Lower_S2Q2.setText(_translate("MainWindow", "Lower Amplitude", None))
        self.label_Upper_S2Q2.setText(_translate("MainWindow", "Upper Amplitude", None))
        self.label_Step_S2Q2.setText(_translate("MainWindow", "Step Size", None))
        self.groupBox_methodS2Q2.setTitle(_translate("MainWindow", "Method", None))
        self.S2Q2StartButton.setText(_translate("MainWindow", "Scan Quadrupole", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.S2Q2Tab), _translate("MainWindow", "S02-QUAD-02", None))
        self.groupBox_plotsS2Q3.setTitle(_translate("MainWindow", "Plots", None))
        self.groupBox_S2Q3.setTitle(_translate("MainWindow", "Quad Settings", None))
        self.label_Lower_S2Q3.setText(_translate("MainWindow", "Lower Amplitude", None))
        self.label_Upper_S2Q3.setText(_translate("MainWindow", "Upper Amplitude", None))
        self.label_Step_S2Q3.setText(_translate("MainWindow", "Step Size", None))
        self.groupBox_methodS2Q3.setTitle(_translate("MainWindow", "Method", None))
        self.S2Q3StartButton.setText(_translate("MainWindow", "Scan Quadrupole", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.S2Q3Tab), _translate("MainWindow", "S02-QUAD-03", None))
        self.groupBox_plotsS2Q4.setTitle(_translate("MainWindow", "Plots", None))
        self.groupBox_S2Q4.setTitle(_translate("MainWindow", "Quad Settings", None))
        self.label_Lower_S2Q4.setText(_translate("MainWindow", "Lower Amplitude", None))
        self.label_Upper_S2Q4.setText(_translate("MainWindow", "Upper Amplitude", None))
        self.label_Step_S2Q4.setText(_translate("MainWindow", "Step Size", None))
        self.groupBox_methodS2Q4.setTitle(_translate("MainWindow", "Method", None))
        self.S2Q4StartButton.setText(_translate("MainWindow", "Scan Quadrupole", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.S2Q4Tab), _translate("MainWindow", "S02-QUAD-04", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logTab), _translate("MainWindow", "Log", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSave_Data.setTitle(_translate("MainWindow", "Save Data", None))
        self.actionSave_Calibation_Data.setText(_translate("MainWindow", "Save Calibation Data", None))
        self.actionAuto_Save_Data.setText(_translate("MainWindow", "Auto Save Data", None))
        self.actionSave_to_Work_Folder.setText(_translate("MainWindow", "Save to Work Folder", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))

