# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'expert_main_grid.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1096, 760)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(311, 118, 150, 271))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.vac_config = QtGui.QLabel(self.widget)
        self.vac_config.setMinimumSize(QtCore.QSize(0, 20))
        self.vac_config.setMaximumSize(QtCore.QSize(16777215, 20))
        self.vac_config.setFrameShape(QtGui.QFrame.Box)
        self.vac_config.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_config.setScaledContents(False)
        self.vac_config.setObjectName(_fromUtf8("vac_config"))
        self.verticalLayout.addWidget(self.vac_config)
        self.vac_pv_val = QtGui.QLabel(self.widget)
        self.vac_pv_val.setMinimumSize(QtCore.QSize(0, 20))
        self.vac_pv_val.setMaximumSize(QtCore.QSize(16777215, 20))
        self.vac_pv_val.setFrameShape(QtGui.QFrame.Box)
        self.vac_pv_val.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_pv_val.setScaledContents(False)
        self.vac_pv_val.setObjectName(_fromUtf8("vac_pv_val"))
        self.verticalLayout.addWidget(self.vac_pv_val)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.vac_num_samples_to_average = QtGui.QLabel(self.widget)
        self.vac_num_samples_to_average.setMinimumSize(QtCore.QSize(90, 20))
        self.vac_num_samples_to_average.setMaximumSize(QtCore.QSize(90, 20))
        self.vac_num_samples_to_average.setFrameShape(QtGui.QFrame.Box)
        self.vac_num_samples_to_average.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_num_samples_to_average.setScaledContents(False)
        self.vac_num_samples_to_average.setObjectName(_fromUtf8("vac_num_samples_to_average"))
        self.gridLayout.addWidget(self.vac_num_samples_to_average, 0, 0, 1, 1)
        self.vac_num_samples_to_average_val = QtGui.QLabel(self.widget)
        self.vac_num_samples_to_average_val.setMinimumSize(QtCore.QSize(50, 20))
        self.vac_num_samples_to_average_val.setMaximumSize(QtCore.QSize(50, 20))
        self.vac_num_samples_to_average_val.setFrameShape(QtGui.QFrame.Box)
        self.vac_num_samples_to_average_val.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_num_samples_to_average_val.setScaledContents(False)
        self.vac_num_samples_to_average_val.setObjectName(_fromUtf8("vac_num_samples_to_average_val"))
        self.gridLayout.addWidget(self.vac_num_samples_to_average_val, 0, 1, 1, 1)
        self.vac_decay_mode = QtGui.QLabel(self.widget)
        self.vac_decay_mode.setMinimumSize(QtCore.QSize(90, 20))
        self.vac_decay_mode.setMaximumSize(QtCore.QSize(90, 20))
        self.vac_decay_mode.setFrameShape(QtGui.QFrame.Box)
        self.vac_decay_mode.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_decay_mode.setScaledContents(False)
        self.vac_decay_mode.setObjectName(_fromUtf8("vac_decay_mode"))
        self.gridLayout.addWidget(self.vac_decay_mode, 1, 0, 1, 1)
        self.vac_decay_mode_val = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vac_decay_mode_val.sizePolicy().hasHeightForWidth())
        self.vac_decay_mode_val.setSizePolicy(sizePolicy)
        self.vac_decay_mode_val.setMinimumSize(QtCore.QSize(50, 20))
        self.vac_decay_mode_val.setMaximumSize(QtCore.QSize(50, 20))
        self.vac_decay_mode_val.setEditable(True)
        self.vac_decay_mode_val.setObjectName(_fromUtf8("vac_decay_mode_val"))
        self.vac_decay_mode_val.addItem(_fromUtf8(""))
        self.vac_decay_mode_val.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.vac_decay_mode_val, 1, 1, 1, 1)
        self.vac_decay_level = QtGui.QLabel(self.widget)
        self.vac_decay_level.setMinimumSize(QtCore.QSize(90, 20))
        self.vac_decay_level.setMaximumSize(QtCore.QSize(90, 20))
        self.vac_decay_level.setFrameShape(QtGui.QFrame.Box)
        self.vac_decay_level.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_decay_level.setScaledContents(False)
        self.vac_decay_level.setObjectName(_fromUtf8("vac_decay_level"))
        self.gridLayout.addWidget(self.vac_decay_level, 2, 0, 1, 1)
        self.vac_decay_level_val = QtGui.QLabel(self.widget)
        self.vac_decay_level_val.setMinimumSize(QtCore.QSize(50, 20))
        self.vac_decay_level_val.setMaximumSize(QtCore.QSize(50, 20))
        self.vac_decay_level_val.setFrameShape(QtGui.QFrame.Box)
        self.vac_decay_level_val.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_decay_level_val.setScaledContents(False)
        self.vac_decay_level_val.setObjectName(_fromUtf8("vac_decay_level_val"))
        self.gridLayout.addWidget(self.vac_decay_level_val, 2, 1, 1, 1)
        self.vac_decay_time = QtGui.QLabel(self.widget)
        self.vac_decay_time.setMinimumSize(QtCore.QSize(90, 20))
        self.vac_decay_time.setMaximumSize(QtCore.QSize(90, 20))
        self.vac_decay_time.setFrameShape(QtGui.QFrame.Box)
        self.vac_decay_time.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_decay_time.setScaledContents(False)
        self.vac_decay_time.setObjectName(_fromUtf8("vac_decay_time"))
        self.gridLayout.addWidget(self.vac_decay_time, 3, 0, 1, 1)
        self.vac_decay_time_val = QtGui.QLabel(self.widget)
        self.vac_decay_time_val.setMinimumSize(QtCore.QSize(50, 20))
        self.vac_decay_time_val.setMaximumSize(QtCore.QSize(50, 20))
        self.vac_decay_time_val.setFrameShape(QtGui.QFrame.Box)
        self.vac_decay_time_val.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_decay_time_val.setScaledContents(False)
        self.vac_decay_time_val.setObjectName(_fromUtf8("vac_decay_time_val"))
        self.gridLayout.addWidget(self.vac_decay_time_val, 3, 1, 1, 1)
        self.vac_spike_delta = QtGui.QLabel(self.widget)
        self.vac_spike_delta.setMinimumSize(QtCore.QSize(90, 20))
        self.vac_spike_delta.setMaximumSize(QtCore.QSize(90, 20))
        self.vac_spike_delta.setFrameShape(QtGui.QFrame.Box)
        self.vac_spike_delta.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_spike_delta.setScaledContents(False)
        self.vac_spike_delta.setObjectName(_fromUtf8("vac_spike_delta"))
        self.gridLayout.addWidget(self.vac_spike_delta, 4, 0, 1, 1)
        self.vac_spike_delta_val = QtGui.QLabel(self.widget)
        self.vac_spike_delta_val.setMinimumSize(QtCore.QSize(50, 20))
        self.vac_spike_delta_val.setMaximumSize(QtCore.QSize(50, 20))
        self.vac_spike_delta_val.setFrameShape(QtGui.QFrame.Box)
        self.vac_spike_delta_val.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_spike_delta_val.setScaledContents(False)
        self.vac_spike_delta_val.setObjectName(_fromUtf8("vac_spike_delta_val"))
        self.gridLayout.addWidget(self.vac_spike_delta_val, 4, 1, 1, 1)
        self.vac_drop_amp = QtGui.QLabel(self.widget)
        self.vac_drop_amp.setMinimumSize(QtCore.QSize(90, 20))
        self.vac_drop_amp.setMaximumSize(QtCore.QSize(90, 20))
        self.vac_drop_amp.setFrameShape(QtGui.QFrame.Box)
        self.vac_drop_amp.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_drop_amp.setScaledContents(False)
        self.vac_drop_amp.setObjectName(_fromUtf8("vac_drop_amp"))
        self.gridLayout.addWidget(self.vac_drop_amp, 5, 0, 1, 1)
        self.vac_drop_amp_val = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vac_drop_amp_val.sizePolicy().hasHeightForWidth())
        self.vac_drop_amp_val.setSizePolicy(sizePolicy)
        self.vac_drop_amp_val.setMinimumSize(QtCore.QSize(50, 20))
        self.vac_drop_amp_val.setMaximumSize(QtCore.QSize(50, 20))
        self.vac_drop_amp_val.setEditable(True)
        self.vac_drop_amp_val.setObjectName(_fromUtf8("vac_drop_amp_val"))
        self.vac_drop_amp_val.addItem(_fromUtf8(""))
        self.vac_drop_amp_val.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.vac_drop_amp_val, 5, 1, 1, 1)
        self.vac_hi_pressure = QtGui.QLabel(self.widget)
        self.vac_hi_pressure.setMinimumSize(QtCore.QSize(90, 20))
        self.vac_hi_pressure.setMaximumSize(QtCore.QSize(90, 20))
        self.vac_hi_pressure.setFrameShape(QtGui.QFrame.Box)
        self.vac_hi_pressure.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_hi_pressure.setScaledContents(False)
        self.vac_hi_pressure.setObjectName(_fromUtf8("vac_hi_pressure"))
        self.gridLayout.addWidget(self.vac_hi_pressure, 6, 0, 1, 1)
        self.vac_hi_pressure_val = QtGui.QLabel(self.widget)
        self.vac_hi_pressure_val.setMinimumSize(QtCore.QSize(50, 20))
        self.vac_hi_pressure_val.setMaximumSize(QtCore.QSize(50, 20))
        self.vac_hi_pressure_val.setFrameShape(QtGui.QFrame.Box)
        self.vac_hi_pressure_val.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_hi_pressure_val.setScaledContents(False)
        self.vac_hi_pressure_val.setObjectName(_fromUtf8("vac_hi_pressure_val"))
        self.gridLayout.addWidget(self.vac_hi_pressure_val, 6, 1, 1, 1)
        self.ramp_when_hi = QtGui.QLabel(self.widget)
        self.ramp_when_hi.setMinimumSize(QtCore.QSize(90, 20))
        self.ramp_when_hi.setMaximumSize(QtCore.QSize(90, 20))
        self.ramp_when_hi.setFrameShape(QtGui.QFrame.Box)
        self.ramp_when_hi.setFrameShadow(QtGui.QFrame.Sunken)
        self.ramp_when_hi.setScaledContents(False)
        self.ramp_when_hi.setObjectName(_fromUtf8("ramp_when_hi"))
        self.gridLayout.addWidget(self.ramp_when_hi, 7, 0, 1, 1)
        self.ramp_when_hi_val = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ramp_when_hi_val.sizePolicy().hasHeightForWidth())
        self.ramp_when_hi_val.setSizePolicy(sizePolicy)
        self.ramp_when_hi_val.setMinimumSize(QtCore.QSize(50, 20))
        self.ramp_when_hi_val.setMaximumSize(QtCore.QSize(50, 20))
        self.ramp_when_hi_val.setEditable(True)
        self.ramp_when_hi_val.setObjectName(_fromUtf8("ramp_when_hi_val"))
        self.ramp_when_hi_val.addItem(_fromUtf8(""))
        self.ramp_when_hi_val.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.ramp_when_hi_val, 7, 1, 1, 1)
        self.vac_spike_check_time = QtGui.QLabel(self.widget)
        self.vac_spike_check_time.setMinimumSize(QtCore.QSize(90, 20))
        self.vac_spike_check_time.setMaximumSize(QtCore.QSize(90, 20))
        self.vac_spike_check_time.setFrameShape(QtGui.QFrame.Box)
        self.vac_spike_check_time.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_spike_check_time.setScaledContents(False)
        self.vac_spike_check_time.setObjectName(_fromUtf8("vac_spike_check_time"))
        self.gridLayout.addWidget(self.vac_spike_check_time, 8, 0, 1, 1)
        self.vac_spike_check_time_val = QtGui.QLabel(self.widget)
        self.vac_spike_check_time_val.setMinimumSize(QtCore.QSize(50, 20))
        self.vac_spike_check_time_val.setMaximumSize(QtCore.QSize(50, 20))
        self.vac_spike_check_time_val.setFrameShape(QtGui.QFrame.Box)
        self.vac_spike_check_time_val.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_spike_check_time_val.setScaledContents(False)
        self.vac_spike_check_time_val.setObjectName(_fromUtf8("vac_spike_check_time_val"))
        self.gridLayout.addWidget(self.vac_spike_check_time_val, 8, 1, 1, 1)
        self.trace_buffer_size = QtGui.QLabel(self.widget)
        self.trace_buffer_size.setMinimumSize(QtCore.QSize(90, 20))
        self.trace_buffer_size.setMaximumSize(QtCore.QSize(90, 20))
        self.trace_buffer_size.setFrameShape(QtGui.QFrame.Box)
        self.trace_buffer_size.setFrameShadow(QtGui.QFrame.Sunken)
        self.trace_buffer_size.setScaledContents(False)
        self.trace_buffer_size.setObjectName(_fromUtf8("trace_buffer_size"))
        self.gridLayout.addWidget(self.trace_buffer_size, 9, 0, 1, 1)
        self.trace_buffer_size_val = QtGui.QLabel(self.widget)
        self.trace_buffer_size_val.setMinimumSize(QtCore.QSize(50, 20))
        self.trace_buffer_size_val.setMaximumSize(QtCore.QSize(50, 20))
        self.trace_buffer_size_val.setFrameShape(QtGui.QFrame.Box)
        self.trace_buffer_size_val.setFrameShadow(QtGui.QFrame.Sunken)
        self.trace_buffer_size_val.setScaledContents(False)
        self.trace_buffer_size_val.setObjectName(_fromUtf8("trace_buffer_size_val"))
        self.gridLayout.addWidget(self.trace_buffer_size_val, 9, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.vac_config.setText(_translate("MainWindow", "Vacuum Spike", None))
        self.vac_pv_val.setText(_translate("MainWindow", "CLA-LRG1-VAC-IMG-01:P", None))
        self.vac_num_samples_to_average.setText(_translate("MainWindow", "Num Samples", None))
        self.vac_num_samples_to_average_val.setText(_translate("MainWindow", "7", None))
        self.vac_decay_mode.setText(_translate("MainWindow", "Decay Mode", None))
        self.vac_decay_mode_val.setItemText(0, _translate("MainWindow", "TIME", None))
        self.vac_decay_mode_val.setItemText(1, _translate("MainWindow", "LEVEL", None))
        self.vac_decay_level.setText(_translate("MainWindow", "Decay Level", None))
        self.vac_decay_level_val.setText(_translate("MainWindow", "1.2", None))
        self.vac_decay_time.setText(_translate("MainWindow", "Decay Time", None))
        self.vac_decay_time_val.setText(_translate("MainWindow", "2000", None))
        self.vac_spike_delta.setText(_translate("MainWindow", "Spike Delta", None))
        self.vac_spike_delta_val.setText(_translate("MainWindow", "2e-8", None))
        self.vac_drop_amp.setText(_translate("MainWindow", "Drop Amp", None))
        self.vac_drop_amp_val.setItemText(0, _translate("MainWindow", "TRUE", None))
        self.vac_drop_amp_val.setItemText(1, _translate("MainWindow", "FALSE", None))
        self.vac_hi_pressure.setText(_translate("MainWindow", "Hi Pressure", None))
        self.vac_hi_pressure_val.setText(_translate("MainWindow", "5e-9", None))
        self.ramp_when_hi.setText(_translate("MainWindow", "Ramp When Hi", None))
        self.ramp_when_hi_val.setItemText(0, _translate("MainWindow", "TRUE", None))
        self.ramp_when_hi_val.setItemText(1, _translate("MainWindow", "FALSE", None))
        self.vac_spike_check_time.setText(_translate("MainWindow", "Check Time", None))
        self.vac_spike_check_time_val.setText(_translate("MainWindow", "200", None))
        self.trace_buffer_size.setText(_translate("MainWindow", "Trace Buffer Size", None))
        self.trace_buffer_size_val.setText(_translate("MainWindow", "500", None))

