# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rf_condition_view_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_rf_condition_mainWindow(object):
    def setupUi(self, rf_condition_mainWindow):
        rf_condition_mainWindow.setObjectName(_fromUtf8("rf_condition_mainWindow"))
        rf_condition_mainWindow.resize(1178, 824)
        self.centralwidget = QtGui.QWidget(rf_condition_mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 1159, 780))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.fwd_kly_power_outputwidget = QtGui.QLabel(self.tab_3)
        self.fwd_kly_power_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.fwd_kly_power_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.fwd_kly_power_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.fwd_kly_power_outputwidget.setObjectName(_fromUtf8("fwd_kly_power_outputwidget"))
        self.gridLayout.addWidget(self.fwd_kly_power_outputwidget, 28, 1, 1, 1)
        self.probe_power_label = QtGui.QLabel(self.tab_3)
        self.probe_power_label.setFrameShape(QtGui.QFrame.Box)
        self.probe_power_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.probe_power_label.setScaledContents(False)
        self.probe_power_label.setObjectName(_fromUtf8("probe_power_label"))
        self.gridLayout.addWidget(self.probe_power_label, 32, 0, 1, 1)
        self.fwd_cav_power_outputwidget = QtGui.QLabel(self.tab_3)
        self.fwd_cav_power_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.fwd_cav_power_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.fwd_cav_power_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.fwd_cav_power_outputwidget.setObjectName(_fromUtf8("fwd_cav_power_outputwidget"))
        self.gridLayout.addWidget(self.fwd_cav_power_outputwidget, 30, 1, 1, 1)
        self.llrf_interlock_label = QtGui.QLabel(self.tab_3)
        self.llrf_interlock_label.setFrameShape(QtGui.QFrame.Box)
        self.llrf_interlock_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.llrf_interlock_label.setScaledContents(False)
        self.llrf_interlock_label.setObjectName(_fromUtf8("llrf_interlock_label"))
        self.gridLayout.addWidget(self.llrf_interlock_label, 19, 0, 1, 1)
        self.llrf_output_label = QtGui.QLabel(self.tab_3)
        self.llrf_output_label.setFrameShape(QtGui.QFrame.Box)
        self.llrf_output_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.llrf_output_label.setScaledContents(False)
        self.llrf_output_label.setObjectName(_fromUtf8("llrf_output_label"))
        self.gridLayout.addWidget(self.llrf_output_label, 21, 0, 1, 1)
        self.llrf_output_outputwidget = QtGui.QLabel(self.tab_3)
        self.llrf_output_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.llrf_output_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.llrf_output_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.llrf_output_outputwidget.setObjectName(_fromUtf8("llrf_output_outputwidget"))
        self.gridLayout.addWidget(self.llrf_output_outputwidget, 21, 1, 1, 1)
        self.DC_spike_label = QtGui.QLabel(self.tab_3)
        self.DC_spike_label.setMinimumSize(QtCore.QSize(0, 21))
        self.DC_spike_label.setFrameShape(QtGui.QFrame.Box)
        self.DC_spike_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.DC_spike_label.setScaledContents(False)
        self.DC_spike_label.setObjectName(_fromUtf8("DC_spike_label"))
        self.gridLayout.addWidget(self.DC_spike_label, 25, 0, 1, 1)
        self.DC_spike_status_outputwidget = QtGui.QLabel(self.tab_3)
        self.DC_spike_status_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.DC_spike_status_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.DC_spike_status_outputwidget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DC_spike_status_outputwidget.setObjectName(_fromUtf8("DC_spike_status_outputwidget"))
        self.gridLayout.addWidget(self.DC_spike_status_outputwidget, 25, 1, 1, 1)
        self.vac_valve_status_label = QtGui.QLabel(self.tab_3)
        self.vac_valve_status_label.setFrameShape(QtGui.QFrame.Box)
        self.vac_valve_status_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_valve_status_label.setScaledContents(False)
        self.vac_valve_status_label.setObjectName(_fromUtf8("vac_valve_status_label"))
        self.gridLayout.addWidget(self.vac_valve_status_label, 27, 0, 1, 1)
        self.llrf_ff_ph_locked_label = QtGui.QLabel(self.tab_3)
        self.llrf_ff_ph_locked_label.setFrameShape(QtGui.QFrame.Box)
        self.llrf_ff_ph_locked_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.llrf_ff_ph_locked_label.setScaledContents(False)
        self.llrf_ff_ph_locked_label.setObjectName(_fromUtf8("llrf_ff_ph_locked_label"))
        self.gridLayout.addWidget(self.llrf_ff_ph_locked_label, 24, 0, 1, 1)
        self.vac_spike_status_outputwidget = QtGui.QLabel(self.tab_3)
        self.vac_spike_status_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.vac_spike_status_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_spike_status_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.vac_spike_status_outputwidget.setObjectName(_fromUtf8("vac_spike_status_outputwidget"))
        self.gridLayout.addWidget(self.vac_spike_status_outputwidget, 26, 1, 1, 1)
        self.vac_valve_status_outputwidget = QtGui.QLabel(self.tab_3)
        self.vac_valve_status_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.vac_valve_status_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_valve_status_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.vac_valve_status_outputwidget.setObjectName(_fromUtf8("vac_valve_status_outputwidget"))
        self.gridLayout.addWidget(self.vac_valve_status_outputwidget, 27, 1, 1, 1)
        self.llrf_trigger_label = QtGui.QLabel(self.tab_3)
        self.llrf_trigger_label.setFrameShape(QtGui.QFrame.Box)
        self.llrf_trigger_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.llrf_trigger_label.setScaledContents(False)
        self.llrf_trigger_label.setObjectName(_fromUtf8("llrf_trigger_label"))
        self.gridLayout.addWidget(self.llrf_trigger_label, 20, 0, 1, 1)
        self.llrf_interlock_outputwidget = QtGui.QLabel(self.tab_3)
        self.llrf_interlock_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.llrf_interlock_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.llrf_interlock_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.llrf_interlock_outputwidget.setObjectName(_fromUtf8("llrf_interlock_outputwidget"))
        self.gridLayout.addWidget(self.llrf_interlock_outputwidget, 19, 1, 1, 1)
        self.vac_spike_label = QtGui.QLabel(self.tab_3)
        self.vac_spike_label.setFrameShape(QtGui.QFrame.Box)
        self.vac_spike_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_spike_label.setScaledContents(False)
        self.vac_spike_label.setObjectName(_fromUtf8("vac_spike_label"))
        self.gridLayout.addWidget(self.vac_spike_label, 26, 0, 1, 1)
        self.llrf_ff_amp_locked_outputwidget = QtGui.QLabel(self.tab_3)
        self.llrf_ff_amp_locked_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.llrf_ff_amp_locked_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.llrf_ff_amp_locked_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.llrf_ff_amp_locked_outputwidget.setObjectName(_fromUtf8("llrf_ff_amp_locked_outputwidget"))
        self.gridLayout.addWidget(self.llrf_ff_amp_locked_outputwidget, 23, 1, 1, 1)
        self.probe_power_outputwidget = QtGui.QLabel(self.tab_3)
        self.probe_power_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.probe_power_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.probe_power_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.probe_power_outputwidget.setObjectName(_fromUtf8("probe_power_outputwidget"))
        self.gridLayout.addWidget(self.probe_power_outputwidget, 32, 1, 1, 1)
        self.rev_cav_power_outputwidget = QtGui.QLabel(self.tab_3)
        self.rev_cav_power_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.rev_cav_power_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.rev_cav_power_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.rev_cav_power_outputwidget.setObjectName(_fromUtf8("rev_cav_power_outputwidget"))
        self.gridLayout.addWidget(self.rev_cav_power_outputwidget, 31, 1, 1, 1)
        self.rev_kly_power_outputwidget = QtGui.QLabel(self.tab_3)
        self.rev_kly_power_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.rev_kly_power_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.rev_kly_power_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.rev_kly_power_outputwidget.setObjectName(_fromUtf8("rev_kly_power_outputwidget"))
        self.gridLayout.addWidget(self.rev_kly_power_outputwidget, 29, 1, 1, 1)
        self.fwd_kly_power_label = QtGui.QLabel(self.tab_3)
        self.fwd_kly_power_label.setFrameShape(QtGui.QFrame.Box)
        self.fwd_kly_power_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.fwd_kly_power_label.setScaledContents(False)
        self.fwd_kly_power_label.setObjectName(_fromUtf8("fwd_kly_power_label"))
        self.gridLayout.addWidget(self.fwd_kly_power_label, 28, 0, 1, 1)
        self.copy_to_clipboard_button_3 = QtGui.QPushButton(self.tab_3)
        self.copy_to_clipboard_button_3.setMinimumSize(QtCore.QSize(225, 0))
        self.copy_to_clipboard_button_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.copy_to_clipboard_button_3.setCheckable(False)
        self.copy_to_clipboard_button_3.setObjectName(_fromUtf8("copy_to_clipboard_button_3"))
        self.gridLayout.addWidget(self.copy_to_clipboard_button_3, 8, 0, 1, 2)
        self.llrf_enable_button_3 = QtGui.QPushButton(self.tab_3)
        self.llrf_enable_button_3.setMinimumSize(QtCore.QSize(225, 0))
        self.llrf_enable_button_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.llrf_enable_button_3.setCheckable(False)
        self.llrf_enable_button_3.setObjectName(_fromUtf8("llrf_enable_button_3"))
        self.gridLayout.addWidget(self.llrf_enable_button_3, 10, 0, 1, 2)
        self.start_pause_ramp_button_3 = QtGui.QPushButton(self.tab_3)
        self.start_pause_ramp_button_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.start_pause_ramp_button_3.setObjectName(_fromUtf8("start_pause_ramp_button_3"))
        self.gridLayout.addWidget(self.start_pause_ramp_button_3, 9, 0, 1, 2)
        self.last_106_count_label = QtGui.QLabel(self.tab_3)
        self.last_106_count_label.setFrameShape(QtGui.QFrame.Box)
        self.last_106_count_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.last_106_count_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.last_106_count_label.setObjectName(_fromUtf8("last_106_count_label"))
        self.gridLayout.addWidget(self.last_106_count_label, 16, 0, 1, 1)
        self.llrf_output_label_2 = QtGui.QLabel(self.tab_3)
        self.llrf_output_label_2.setFrameShape(QtGui.QFrame.Box)
        self.llrf_output_label_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.llrf_output_label_2.setScaledContents(False)
        self.llrf_output_label_2.setObjectName(_fromUtf8("llrf_output_label_2"))
        self.gridLayout.addWidget(self.llrf_output_label_2, 22, 0, 1, 1)
        self.trace_rep_rate_outpuwidget = QtGui.QLabel(self.tab_3)
        self.trace_rep_rate_outpuwidget.setFrameShape(QtGui.QFrame.Box)
        self.trace_rep_rate_outpuwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.trace_rep_rate_outpuwidget.setScaledContents(False)
        self.trace_rep_rate_outpuwidget.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.trace_rep_rate_outpuwidget.setIndent(-1)
        self.trace_rep_rate_outpuwidget.setObjectName(_fromUtf8("trace_rep_rate_outpuwidget"))
        self.gridLayout.addWidget(self.trace_rep_rate_outpuwidget, 22, 1, 1, 1)
        self.llrf_ff_ph_locked_outputwidget = QtGui.QLabel(self.tab_3)
        self.llrf_ff_ph_locked_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.llrf_ff_ph_locked_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.llrf_ff_ph_locked_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.llrf_ff_ph_locked_outputwidget.setObjectName(_fromUtf8("llrf_ff_ph_locked_outputwidget"))
        self.gridLayout.addWidget(self.llrf_ff_ph_locked_outputwidget, 24, 1, 1, 1)
        self.last_106_count_outputwidget = QtGui.QLabel(self.tab_3)
        self.last_106_count_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.last_106_count_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.last_106_count_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.last_106_count_outputwidget.setObjectName(_fromUtf8("last_106_count_outputwidget"))
        self.gridLayout.addWidget(self.last_106_count_outputwidget, 16, 1, 1, 1)
        self.RF_protection_label = QtGui.QLabel(self.tab_3)
        self.RF_protection_label.setFrameShape(QtGui.QFrame.Box)
        self.RF_protection_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.RF_protection_label.setScaledContents(False)
        self.RF_protection_label.setObjectName(_fromUtf8("RF_protection_label"))
        self.gridLayout.addWidget(self.RF_protection_label, 17, 0, 1, 1)
        self.llrf_trigger_outputwidget = QtGui.QLabel(self.tab_3)
        self.llrf_trigger_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.llrf_trigger_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.llrf_trigger_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.llrf_trigger_outputwidget.setObjectName(_fromUtf8("llrf_trigger_outputwidget"))
        self.gridLayout.addWidget(self.llrf_trigger_outputwidget, 20, 1, 1, 1)
        self.mod_state_outputwidget = QtGui.QLabel(self.tab_3)
        self.mod_state_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.mod_state_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.mod_state_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.mod_state_outputwidget.setObjectName(_fromUtf8("mod_state_outputwidget"))
        self.gridLayout.addWidget(self.mod_state_outputwidget, 18, 1, 1, 1)
        self.rf_mod_label = QtGui.QLabel(self.tab_3)
        self.rf_mod_label.setFrameShape(QtGui.QFrame.Box)
        self.rf_mod_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.rf_mod_label.setScaledContents(False)
        self.rf_mod_label.setObjectName(_fromUtf8("rf_mod_label"))
        self.gridLayout.addWidget(self.rf_mod_label, 18, 0, 1, 1)
        self.llrf_ff_amp_locked_label = QtGui.QLabel(self.tab_3)
        self.llrf_ff_amp_locked_label.setFrameShape(QtGui.QFrame.Box)
        self.llrf_ff_amp_locked_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.llrf_ff_amp_locked_label.setScaledContents(False)
        self.llrf_ff_amp_locked_label.setObjectName(_fromUtf8("llrf_ff_amp_locked_label"))
        self.gridLayout.addWidget(self.llrf_ff_amp_locked_label, 23, 0, 1, 1)
        self.RF_protection_outputwidget = QtGui.QLabel(self.tab_3)
        self.RF_protection_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.RF_protection_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.RF_protection_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.RF_protection_outputwidget.setObjectName(_fromUtf8("RF_protection_outputwidget"))
        self.gridLayout.addWidget(self.RF_protection_outputwidget, 17, 1, 1, 1)
        self.rev_cav_power_label = QtGui.QLabel(self.tab_3)
        self.rev_cav_power_label.setFrameShape(QtGui.QFrame.Box)
        self.rev_cav_power_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.rev_cav_power_label.setScaledContents(False)
        self.rev_cav_power_label.setObjectName(_fromUtf8("rev_cav_power_label"))
        self.gridLayout.addWidget(self.rev_cav_power_label, 31, 0, 1, 1)
        self.rev_kly_power_label = QtGui.QLabel(self.tab_3)
        self.rev_kly_power_label.setFrameShape(QtGui.QFrame.Box)
        self.rev_kly_power_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.rev_kly_power_label.setScaledContents(False)
        self.rev_kly_power_label.setObjectName(_fromUtf8("rev_kly_power_label"))
        self.gridLayout.addWidget(self.rev_kly_power_label, 29, 0, 1, 1)
        self.fwd_cav_power_label = QtGui.QLabel(self.tab_3)
        self.fwd_cav_power_label.setFrameShape(QtGui.QFrame.Box)
        self.fwd_cav_power_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.fwd_cav_power_label.setScaledContents(False)
        self.fwd_cav_power_label.setObjectName(_fromUtf8("fwd_cav_power_label"))
        self.gridLayout.addWidget(self.fwd_cav_power_label, 30, 0, 1, 1)
        self.event_pulse_count_outputwidget = QtGui.QLabel(self.tab_3)
        self.event_pulse_count_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.event_pulse_count_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.event_pulse_count_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.event_pulse_count_outputwidget.setObjectName(_fromUtf8("event_pulse_count_outputwidget"))
        self.gridLayout.addWidget(self.event_pulse_count_outputwidget, 13, 1, 1, 1)
        self.event_pulse_count_label = QtGui.QLabel(self.tab_3)
        self.event_pulse_count_label.setFrameShape(QtGui.QFrame.Box)
        self.event_pulse_count_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.event_pulse_count_label.setScaledContents(False)
        self.event_pulse_count_label.setObjectName(_fromUtf8("event_pulse_count_label"))
        self.gridLayout.addWidget(self.event_pulse_count_label, 13, 0, 1, 1)
        self.cav_temp_label = QtGui.QLabel(self.tab_3)
        self.cav_temp_label.setFrameShape(QtGui.QFrame.Box)
        self.cav_temp_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.cav_temp_label.setScaledContents(False)
        self.cav_temp_label.setObjectName(_fromUtf8("cav_temp_label"))
        self.gridLayout.addWidget(self.cav_temp_label, 33, 0, 1, 1)
        self.pulse_count_label = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pulse_count_label.setFont(font)
        self.pulse_count_label.setFrameShape(QtGui.QFrame.Box)
        self.pulse_count_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.pulse_count_label.setScaledContents(False)
        self.pulse_count_label.setObjectName(_fromUtf8("pulse_count_label"))
        self.gridLayout.addWidget(self.pulse_count_label, 12, 0, 1, 1)
        self.pulse_count_outputwidget = QtGui.QLabel(self.tab_3)
        self.pulse_count_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.pulse_count_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.pulse_count_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.pulse_count_outputwidget.setObjectName(_fromUtf8("pulse_count_outputwidget"))
        self.gridLayout.addWidget(self.pulse_count_outputwidget, 12, 1, 1, 1)
        self.breakdown_count_label = QtGui.QLabel(self.tab_3)
        self.breakdown_count_label.setFrameShape(QtGui.QFrame.Box)
        self.breakdown_count_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.breakdown_count_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.breakdown_count_label.setObjectName(_fromUtf8("breakdown_count_label"))
        self.gridLayout.addWidget(self.breakdown_count_label, 14, 0, 1, 1)
        self.cav_temp_outputwidget = QtGui.QLabel(self.tab_3)
        self.cav_temp_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.cav_temp_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.cav_temp_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.cav_temp_outputwidget.setObjectName(_fromUtf8("cav_temp_outputwidget"))
        self.gridLayout.addWidget(self.cav_temp_outputwidget, 33, 1, 1, 1)
        self.measured_breakdown_rate_label = QtGui.QLabel(self.tab_3)
        self.measured_breakdown_rate_label.setFrameShape(QtGui.QFrame.Box)
        self.measured_breakdown_rate_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.measured_breakdown_rate_label.setScaledContents(False)
        self.measured_breakdown_rate_label.setObjectName(_fromUtf8("measured_breakdown_rate_label"))
        self.gridLayout.addWidget(self.measured_breakdown_rate_label, 15, 0, 1, 1)
        self.breakdown_count_outputwidget = QtGui.QLabel(self.tab_3)
        self.breakdown_count_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.breakdown_count_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.breakdown_count_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.breakdown_count_outputwidget.setObjectName(_fromUtf8("breakdown_count_outputwidget"))
        self.gridLayout.addWidget(self.breakdown_count_outputwidget, 14, 1, 1, 1)
        self.measured_breakdown_rate_outputwidget = QtGui.QLabel(self.tab_3)
        self.measured_breakdown_rate_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.measured_breakdown_rate_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.measured_breakdown_rate_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.measured_breakdown_rate_outputwidget.setObjectName(_fromUtf8("measured_breakdown_rate_outputwidget"))
        self.gridLayout.addWidget(self.measured_breakdown_rate_outputwidget, 15, 1, 1, 1)
        self.power_aim_label_2 = QtGui.QLabel(self.tab_3)
        self.power_aim_label_2.setFrameShape(QtGui.QFrame.Box)
        self.power_aim_label_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.power_aim_label_2.setObjectName(_fromUtf8("power_aim_label_2"))
        self.gridLayout.addWidget(self.power_aim_label_2, 34, 0, 1, 1)
        self.sol_outputwidget = QtGui.QLabel(self.tab_3)
        self.sol_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.sol_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.sol_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.sol_outputwidget.setObjectName(_fromUtf8("sol_outputwidget"))
        self.gridLayout.addWidget(self.sol_outputwidget, 34, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.graphicsView = PlotWidget(self.tab_3)
        self.graphicsView.setMinimumSize(QtCore.QSize(900, 525))
        self.graphicsView.setMaximumSize(QtCore.QSize(900, 525))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout.addWidget(self.graphicsView)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.message_pad = QtGui.QTextEdit(self.tab_3)
        self.message_pad.setMinimumSize(QtCore.QSize(580, 0))
        self.message_pad.setMaximumSize(QtCore.QSize(580, 200))
        self.message_pad.setObjectName(_fromUtf8("message_pad"))
        self.horizontalLayout.addWidget(self.message_pad)
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setMinimumSize(QtCore.QSize(300, 200))
        self.label.setMaximumSize(QtCore.QSize(300, 200))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.breakdown_graphicsView = PlotWidget(self.tab_4)
        self.breakdown_graphicsView.setMinimumSize(QtCore.QSize(900, 0))
        self.breakdown_graphicsView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.breakdown_graphicsView.setObjectName(_fromUtf8("breakdown_graphicsView"))
        self.verticalLayout_2.addWidget(self.breakdown_graphicsView)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        rf_condition_mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(rf_condition_mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1178, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        rf_condition_mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(rf_condition_mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        rf_condition_mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(rf_condition_mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(rf_condition_mainWindow)

    def retranslateUi(self, rf_condition_mainWindow):
        rf_condition_mainWindow.setWindowTitle(_translate("rf_condition_mainWindow", "MainWindow", None))
        self.fwd_kly_power_outputwidget.setText(_translate("rf_condition_mainWindow", "0", None))
        self.probe_power_label.setText(_translate("rf_condition_mainWindow", "Probe power", None))
        self.fwd_cav_power_outputwidget.setText(_translate("rf_condition_mainWindow", "0", None))
        self.llrf_interlock_label.setText(_translate("rf_condition_mainWindow", "LLRF Interlock", None))
        self.llrf_output_label.setText(_translate("rf_condition_mainWindow", "LLRF Output", None))
        self.llrf_output_outputwidget.setText(_translate("rf_condition_mainWindow", "output?", None))
        self.DC_spike_label.setText(_translate("rf_condition_mainWindow", "Dark current spike", None))
        self.DC_spike_status_outputwidget.setText(_translate("rf_condition_mainWindow", "No", None))
        self.vac_valve_status_label.setText(_translate("rf_condition_mainWindow", "Vacuum valve status", None))
        self.llrf_ff_ph_locked_label.setText(_translate("rf_condition_mainWindow", "LLRF Phase Locked", None))
        self.vac_spike_status_outputwidget.setText(_translate("rf_condition_mainWindow", "No", None))
        self.vac_valve_status_outputwidget.setText(_translate("rf_condition_mainWindow", "Open", None))
        self.llrf_trigger_label.setText(_translate("rf_condition_mainWindow", "LLRF Trigger", None))
        self.llrf_interlock_outputwidget.setText(_translate("rf_condition_mainWindow", "UK", None))
        self.vac_spike_label.setText(_translate("rf_condition_mainWindow", "Vacuum Level / Spike ", None))
        self.llrf_ff_amp_locked_outputwidget.setText(_translate("rf_condition_mainWindow", "locked?", None))
        self.probe_power_outputwidget.setText(_translate("rf_condition_mainWindow", "0", None))
        self.rev_cav_power_outputwidget.setText(_translate("rf_condition_mainWindow", "0", None))
        self.rev_kly_power_outputwidget.setText(_translate("rf_condition_mainWindow", "0", None))
        self.fwd_kly_power_label.setText(_translate("rf_condition_mainWindow", "klystron forward power ", None))
        self.copy_to_clipboard_button_3.setToolTip(_translate("rf_condition_mainWindow", "For the log!", None))
        self.copy_to_clipboard_button_3.setText(_translate("rf_condition_mainWindow", "Copy status to clipboard", None))
        self.llrf_enable_button_3.setText(_translate("rf_condition_mainWindow", "ENABLE / DISABLE LLRF RF", None))
        self.start_pause_ramp_button_3.setText(_translate("rf_condition_mainWindow", "Pause ramp", None))
        self.last_106_count_label.setText(_translate("rf_condition_mainWindow", "Last 10^6 BD count", None))
        self.llrf_output_label_2.setText(_translate("rf_condition_mainWindow", "Trace Rep-Rate", None))
        self.trace_rep_rate_outpuwidget.setText(_translate("rf_condition_mainWindow", "0", None))
        self.llrf_ff_ph_locked_outputwidget.setText(_translate("rf_condition_mainWindow", "locked?", None))
        self.last_106_count_outputwidget.setText(_translate("rf_condition_mainWindow", "-1", None))
        self.RF_protection_label.setText(_translate("rf_condition_mainWindow", "RF Protection", None))
        self.llrf_trigger_outputwidget.setText(_translate("rf_condition_mainWindow", "-9", None))
        self.mod_state_outputwidget.setText(_translate("rf_condition_mainWindow", "UK", None))
        self.rf_mod_label.setText(_translate("rf_condition_mainWindow", "Modulator state", None))
        self.llrf_ff_amp_locked_label.setText(_translate("rf_condition_mainWindow", "LLRF Amp Locked", None))
        self.RF_protection_outputwidget.setText(_translate("rf_condition_mainWindow", "UK", None))
        self.rev_cav_power_label.setText(_translate("rf_condition_mainWindow", "cavity reverse power ", None))
        self.rev_kly_power_label.setText(_translate("rf_condition_mainWindow", "klystron reverse power", None))
        self.fwd_cav_power_label.setText(_translate("rf_condition_mainWindow", "Cavity forward power ", None))
        self.event_pulse_count_outputwidget.setText(_translate("rf_condition_mainWindow", "0", None))
        self.event_pulse_count_label.setText(_translate("rf_condition_mainWindow", "Event Pulse Count", None))
        self.cav_temp_label.setText(_translate("rf_condition_mainWindow", "Cavity temperature", None))
        self.pulse_count_label.setText(_translate("rf_condition_mainWindow", "Active pulse count", None))
        self.pulse_count_outputwidget.setText(_translate("rf_condition_mainWindow", "Terrible", None))
        self.breakdown_count_label.setText(_translate("rf_condition_mainWindow", "Breakdown count", None))
        self.cav_temp_outputwidget.setText(_translate("rf_condition_mainWindow", "0", None))
        self.measured_breakdown_rate_label.setText(_translate("rf_condition_mainWindow", "Measured breakdown rate", None))
        self.breakdown_count_outputwidget.setText(_translate("rf_condition_mainWindow", "-1", None))
        self.measured_breakdown_rate_outputwidget.setText(_translate("rf_condition_mainWindow", "0", None))
        self.power_aim_label_2.setText(_translate("rf_condition_mainWindow", "solenoid current", None))
        self.sol_outputwidget.setText(_translate("rf_condition_mainWindow", "-9", None))
        self.label.setText(_translate("rf_condition_mainWindow", "TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("rf_condition_mainWindow", "Tab 1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("rf_condition_mainWindow", "Tab 2", None))

from pyqtgraph import PlotWidget
