# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1140, 800)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1140, 800))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("ctr.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.centralWidgetLayout = QtGui.QGridLayout(self.centralwidget)
        self.centralWidgetLayout.setObjectName(_fromUtf8("centralWidgetLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 65))
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_MODE = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_MODE.sizePolicy().hasHeightForWidth())
        self.label_MODE.setSizePolicy(sizePolicy)
        self.label_MODE.setMinimumSize(QtCore.QSize(200, 40))
        self.label_MODE.setMaximumSize(QtCore.QSize(200, 40))
        self.label_MODE.setTextFormat(QtCore.Qt.RichText)
        self.label_MODE.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_MODE.setWordWrap(True)
        self.label_MODE.setObjectName(_fromUtf8("label_MODE"))
        self.horizontalLayout.addWidget(self.label_MODE)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.widget_5 = QtGui.QWidget(self.groupBox)
        self.widget_5.setMinimumSize(QtCore.QSize(600, 0))
        self.widget_5.setMaximumSize(QtCore.QSize(600, 400))
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.gridLayout_10 = QtGui.QGridLayout(self.widget_5)
        self.gridLayout_10.setContentsMargins(9, 0, 9, 0)
        self.gridLayout_10.setHorizontalSpacing(6)
        self.gridLayout_10.setVerticalSpacing(2)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.Linac1_Amp_Monitor = QtGui.QSpinBox(self.widget_5)
        self.Linac1_Amp_Monitor.setEnabled(False)
        self.Linac1_Amp_Monitor.setMinimumSize(QtCore.QSize(70, 0))
        self.Linac1_Amp_Monitor.setAlignment(QtCore.Qt.AlignCenter)
        self.Linac1_Amp_Monitor.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.Linac1_Amp_Monitor.setPrefix(_fromUtf8(""))
        self.Linac1_Amp_Monitor.setMaximum(100000)
        self.Linac1_Amp_Monitor.setObjectName(_fromUtf8("Linac1_Amp_Monitor"))
        self.gridLayout_10.addWidget(self.Linac1_Amp_Monitor, 2, 2, 1, 1)
        self.C2V_BPM_Monitor = QtGui.QDoubleSpinBox(self.widget_5)
        self.C2V_BPM_Monitor.setEnabled(False)
        self.C2V_BPM_Monitor.setAlignment(QtCore.Qt.AlignCenter)
        self.C2V_BPM_Monitor.setReadOnly(True)
        self.C2V_BPM_Monitor.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.C2V_BPM_Monitor.setMinimum(-250.0)
        self.C2V_BPM_Monitor.setMaximum(250.0)
        self.C2V_BPM_Monitor.setObjectName(_fromUtf8("C2V_BPM_Monitor"))
        self.gridLayout_10.addWidget(self.C2V_BPM_Monitor, 2, 5, 1, 1)
        self.Gun_Phase_Monitor = QtGui.QDoubleSpinBox(self.widget_5)
        self.Gun_Phase_Monitor.setEnabled(False)
        self.Gun_Phase_Monitor.setMinimumSize(QtCore.QSize(70, 0))
        self.Gun_Phase_Monitor.setAlignment(QtCore.Qt.AlignCenter)
        self.Gun_Phase_Monitor.setReadOnly(True)
        self.Gun_Phase_Monitor.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.Gun_Phase_Monitor.setMinimum(-180.0)
        self.Gun_Phase_Monitor.setMaximum(180.0)
        self.Gun_Phase_Monitor.setObjectName(_fromUtf8("Gun_Phase_Monitor"))
        self.gridLayout_10.addWidget(self.Gun_Phase_Monitor, 2, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.widget_5)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_10.addWidget(self.label_31, 1, 5, 1, 1)
        self.Progress_Monitor = QtGui.QProgressBar(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Progress_Monitor.sizePolicy().hasHeightForWidth())
        self.Progress_Monitor.setSizePolicy(sizePolicy)
        self.Progress_Monitor.setMinimumSize(QtCore.QSize(70, 0))
        self.Progress_Monitor.setProperty("value", 0)
        self.Progress_Monitor.setTextVisible(False)
        self.Progress_Monitor.setObjectName(_fromUtf8("Progress_Monitor"))
        self.gridLayout_10.addWidget(self.Progress_Monitor, 2, 6, 1, 1)
        self.label_27 = QtGui.QLabel(self.widget_5)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_10.addWidget(self.label_27, 1, 0, 1, 2)
        self.label_30 = QtGui.QLabel(self.widget_5)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_10.addWidget(self.label_30, 1, 2, 1, 2)
        self.Gun_Amp_Monitor = QtGui.QSpinBox(self.widget_5)
        self.Gun_Amp_Monitor.setEnabled(False)
        self.Gun_Amp_Monitor.setMinimumSize(QtCore.QSize(70, 0))
        self.Gun_Amp_Monitor.setAlignment(QtCore.Qt.AlignCenter)
        self.Gun_Amp_Monitor.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.Gun_Amp_Monitor.setPrefix(_fromUtf8(""))
        self.Gun_Amp_Monitor.setMaximum(100000)
        self.Gun_Amp_Monitor.setObjectName(_fromUtf8("Gun_Amp_Monitor"))
        self.gridLayout_10.addWidget(self.Gun_Amp_Monitor, 2, 0, 1, 1)
        self.Linac1_Phase_Monitor = QtGui.QDoubleSpinBox(self.widget_5)
        self.Linac1_Phase_Monitor.setEnabled(False)
        self.Linac1_Phase_Monitor.setMinimumSize(QtCore.QSize(70, 0))
        self.Linac1_Phase_Monitor.setAlignment(QtCore.Qt.AlignCenter)
        self.Linac1_Phase_Monitor.setReadOnly(True)
        self.Linac1_Phase_Monitor.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.Linac1_Phase_Monitor.setMinimum(-180.0)
        self.Linac1_Phase_Monitor.setMaximum(180.0)
        self.Linac1_Phase_Monitor.setObjectName(_fromUtf8("Linac1_Phase_Monitor"))
        self.gridLayout_10.addWidget(self.Linac1_Phase_Monitor, 2, 3, 1, 1)
        self.label_32 = QtGui.QLabel(self.widget_5)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_10.addWidget(self.label_32, 1, 6, 1, 1)
        self.Linac1_Timing_Monitor = QtGui.QPushButton(self.widget_5)
        self.Linac1_Timing_Monitor.setEnabled(False)
        self.Linac1_Timing_Monitor.setText(_fromUtf8(""))
        self.Linac1_Timing_Monitor.setFlat(False)
        self.Linac1_Timing_Monitor.setObjectName(_fromUtf8("Linac1_Timing_Monitor"))
        self.gridLayout_10.addWidget(self.Linac1_Timing_Monitor, 2, 4, 1, 1)
        self.horizontalLayout.addWidget(self.widget_5)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.topbutton_widget = QtGui.QWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topbutton_widget.sizePolicy().hasHeightForWidth())
        self.topbutton_widget.setSizePolicy(sizePolicy)
        self.topbutton_widget.setMinimumSize(QtCore.QSize(175, 0))
        self.topbutton_widget.setStyleSheet(_fromUtf8("background: grey"))
        self.topbutton_widget.setObjectName(_fromUtf8("topbutton_widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.topbutton_widget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.Save_Data_Buttons = QtGui.QDialogButtonBox(self.topbutton_widget)
        self.Save_Data_Buttons.setEnabled(True)
        self.Save_Data_Buttons.setStyleSheet(_fromUtf8(""))
        self.Save_Data_Buttons.setOrientation(QtCore.Qt.Horizontal)
        self.Save_Data_Buttons.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.Save_Data_Buttons.setCenterButtons(True)
        self.Save_Data_Buttons.setObjectName(_fromUtf8("Save_Data_Buttons"))
        self.horizontalLayout_2.addWidget(self.Save_Data_Buttons)
        self.Finish_Button = QtGui.QPushButton(self.topbutton_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Finish_Button.sizePolicy().hasHeightForWidth())
        self.Finish_Button.setSizePolicy(sizePolicy)
        self.Finish_Button.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Finish_Button.setObjectName(_fromUtf8("Finish_Button"))
        self.horizontalLayout_2.addWidget(self.Finish_Button)
        self.Abort_Button = QtGui.QPushButton(self.topbutton_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Abort_Button.sizePolicy().hasHeightForWidth())
        self.Abort_Button.setSizePolicy(sizePolicy)
        self.Abort_Button.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Abort_Button.setAutoFillBackground(False)
        self.Abort_Button.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Abort_Button.setIcon(icon1)
        self.Abort_Button.setObjectName(_fromUtf8("Abort_Button"))
        self.horizontalLayout_2.addWidget(self.Abort_Button)
        self.horizontalLayout.addWidget(self.topbutton_widget)
        self.centralWidgetLayout.addWidget(self.groupBox, 0, 0, 2, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.CTR_Tab = QtGui.QWidget()
        self.CTR_Tab.setObjectName(_fromUtf8("CTR_Tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.CTR_Tab)
        self.gridLayout_2.setContentsMargins(0, 8, 0, 10)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.widget = QtGui.QWidget(self.CTR_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 600))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 600))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.CTR_Crests_Box = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CTR_Crests_Box.sizePolicy().hasHeightForWidth())
        self.CTR_Crests_Box.setSizePolicy(sizePolicy)
        self.CTR_Crests_Box.setObjectName(_fromUtf8("CTR_Crests_Box"))
        self.gridLayout = QtGui.QGridLayout(self.CTR_Crests_Box)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(self.CTR_Crests_Box)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.CTR_Gun_Crest_Set = QtGui.QDoubleSpinBox(self.CTR_Crests_Box)
        self.CTR_Gun_Crest_Set.setDecimals(1)
        self.CTR_Gun_Crest_Set.setMinimum(-180.0)
        self.CTR_Gun_Crest_Set.setMaximum(180.0)
        self.CTR_Gun_Crest_Set.setObjectName(_fromUtf8("CTR_Gun_Crest_Set"))
        self.gridLayout.addWidget(self.CTR_Gun_Crest_Set, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.CTR_Crests_Box)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.CTR_Gun_Load_Crest_Button = QtGui.QPushButton(self.CTR_Crests_Box)
        self.CTR_Gun_Load_Crest_Button.setObjectName(_fromUtf8("CTR_Gun_Load_Crest_Button"))
        self.gridLayout.addWidget(self.CTR_Gun_Load_Crest_Button, 3, 0, 1, 2)
        self.label_13 = QtGui.QLabel(self.CTR_Crests_Box)
        self.label_13.setMinimumSize(QtCore.QSize(130, 0))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 4, 0, 1, 1)
        self.CTR_Linac1_Crest_Set = QtGui.QDoubleSpinBox(self.CTR_Crests_Box)
        self.CTR_Linac1_Crest_Set.setDecimals(1)
        self.CTR_Linac1_Crest_Set.setMinimum(-180.0)
        self.CTR_Linac1_Crest_Set.setMaximum(180.0)
        self.CTR_Linac1_Crest_Set.setObjectName(_fromUtf8("CTR_Linac1_Crest_Set"))
        self.gridLayout.addWidget(self.CTR_Linac1_Crest_Set, 4, 1, 1, 1)
        self.CTR_Linac_Load_Crest_Button = QtGui.QPushButton(self.CTR_Crests_Box)
        self.CTR_Linac_Load_Crest_Button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.CTR_Linac_Load_Crest_Button.setObjectName(_fromUtf8("CTR_Linac_Load_Crest_Button"))
        self.gridLayout.addWidget(self.CTR_Linac_Load_Crest_Button, 5, 0, 1, 2)
        self.CTR_Gun_OffCrest_Set = QtGui.QDoubleSpinBox(self.CTR_Crests_Box)
        self.CTR_Gun_OffCrest_Set.setDecimals(1)
        self.CTR_Gun_OffCrest_Set.setMinimum(-180.0)
        self.CTR_Gun_OffCrest_Set.setMaximum(180.0)
        self.CTR_Gun_OffCrest_Set.setObjectName(_fromUtf8("CTR_Gun_OffCrest_Set"))
        self.gridLayout.addWidget(self.CTR_Gun_OffCrest_Set, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.CTR_Crests_Box)
        self.CTR_Momentum_Box = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CTR_Momentum_Box.sizePolicy().hasHeightForWidth())
        self.CTR_Momentum_Box.setSizePolicy(sizePolicy)
        self.CTR_Momentum_Box.setObjectName(_fromUtf8("CTR_Momentum_Box"))
        self.formLayout_5 = QtGui.QFormLayout(self.CTR_Momentum_Box)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_33 = QtGui.QLabel(self.CTR_Momentum_Box)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_33)
        self.CTR_Auto_Correct_Set = QtGui.QCheckBox(self.CTR_Momentum_Box)
        self.CTR_Auto_Correct_Set.setText(_fromUtf8(""))
        self.CTR_Auto_Correct_Set.setChecked(True)
        self.CTR_Auto_Correct_Set.setObjectName(_fromUtf8("CTR_Auto_Correct_Set"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.CTR_Auto_Correct_Set)
        self.label = QtGui.QLabel(self.CTR_Momentum_Box)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.CTR_C2V_Position_Set = QtGui.QDoubleSpinBox(self.CTR_Momentum_Box)
        self.CTR_C2V_Position_Set.setMinimum(-8.0)
        self.CTR_C2V_Position_Set.setMaximum(8.0)
        self.CTR_C2V_Position_Set.setSingleStep(0.1)
        self.CTR_C2V_Position_Set.setObjectName(_fromUtf8("CTR_C2V_Position_Set"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.CTR_C2V_Position_Set)
        self.label_10 = QtGui.QLabel(self.CTR_Momentum_Box)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_10)
        self.CTR_Max_Linac_Set = QtGui.QSpinBox(self.CTR_Momentum_Box)
        self.CTR_Max_Linac_Set.setMaximum(60000)
        self.CTR_Max_Linac_Set.setSingleStep(500)
        self.CTR_Max_Linac_Set.setProperty("value", 60000)
        self.CTR_Max_Linac_Set.setObjectName(_fromUtf8("CTR_Max_Linac_Set"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.CTR_Max_Linac_Set)
        self.CTR_Correct_Momentum_Button = QtGui.QPushButton(self.CTR_Momentum_Box)
        self.CTR_Correct_Momentum_Button.setChecked(False)
        self.CTR_Correct_Momentum_Button.setObjectName(_fromUtf8("CTR_Correct_Momentum_Button"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.SpanningRole, self.CTR_Correct_Momentum_Button)
        self.label_5 = QtGui.QLabel(self.CTR_Momentum_Box)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.CTR_Linac_Step_Set = QtGui.QSpinBox(self.CTR_Momentum_Box)
        self.CTR_Linac_Step_Set.setMinimum(10)
        self.CTR_Linac_Step_Set.setMaximum(1000)
        self.CTR_Linac_Step_Set.setSingleStep(10)
        self.CTR_Linac_Step_Set.setProperty("value", 250)
        self.CTR_Linac_Step_Set.setObjectName(_fromUtf8("CTR_Linac_Step_Set"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.CTR_Linac_Step_Set)
        self.verticalLayout.addWidget(self.CTR_Momentum_Box)
        self.CTR_Scan_Box = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CTR_Scan_Box.sizePolicy().hasHeightForWidth())
        self.CTR_Scan_Box.setSizePolicy(sizePolicy)
        self.CTR_Scan_Box.setMinimumSize(QtCore.QSize(0, 190))
        self.CTR_Scan_Box.setMaximumSize(QtCore.QSize(16777215, 190))
        self.CTR_Scan_Box.setObjectName(_fromUtf8("CTR_Scan_Box"))
        self.formLayout = QtGui.QFormLayout(self.CTR_Scan_Box)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_11 = QtGui.QLabel(self.CTR_Scan_Box)
        self.label_11.setMinimumSize(QtCore.QSize(150, 0))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_11)
        self.CTR_Phase_Start_Set = QtGui.QSpinBox(self.CTR_Scan_Box)
        self.CTR_Phase_Start_Set.setMinimum(-180)
        self.CTR_Phase_Start_Set.setMaximum(180)
        self.CTR_Phase_Start_Set.setProperty("value", -15)
        self.CTR_Phase_Start_Set.setObjectName(_fromUtf8("CTR_Phase_Start_Set"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.CTR_Phase_Start_Set)
        self.label_12 = QtGui.QLabel(self.CTR_Scan_Box)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_12)
        self.CTR_Phase_End_Set = QtGui.QSpinBox(self.CTR_Scan_Box)
        self.CTR_Phase_End_Set.setMinimum(-180)
        self.CTR_Phase_End_Set.setMaximum(180)
        self.CTR_Phase_End_Set.setProperty("value", 0)
        self.CTR_Phase_End_Set.setObjectName(_fromUtf8("CTR_Phase_End_Set"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.CTR_Phase_End_Set)
        self.label_28 = QtGui.QLabel(self.CTR_Scan_Box)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_28)
        self.CTR_Phase_Step_Set = QtGui.QDoubleSpinBox(self.CTR_Scan_Box)
        self.CTR_Phase_Step_Set.setDecimals(1)
        self.CTR_Phase_Step_Set.setMinimum(0.1)
        self.CTR_Phase_Step_Set.setMaximum(5.0)
        self.CTR_Phase_Step_Set.setProperty("value", 1.0)
        self.CTR_Phase_Step_Set.setObjectName(_fromUtf8("CTR_Phase_Step_Set"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.CTR_Phase_Step_Set)
        self.label_3 = QtGui.QLabel(self.CTR_Scan_Box)
        self.label_3.setMinimumSize(QtCore.QSize(150, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.CTR_NShots_Set = QtGui.QSpinBox(self.CTR_Scan_Box)
        self.CTR_NShots_Set.setMinimum(1)
        self.CTR_NShots_Set.setMaximum(100)
        self.CTR_NShots_Set.setProperty("value", 25)
        self.CTR_NShots_Set.setObjectName(_fromUtf8("CTR_NShots_Set"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.CTR_NShots_Set)
        self.line = QtGui.QFrame(self.CTR_Scan_Box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(0, 10))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.SpanningRole, self.line)
        self.label_4 = QtGui.QLabel(self.CTR_Scan_Box)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_4)
        self.widget_4 = QtGui.QWidget(self.CTR_Scan_Box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(35, 25))
        self.widget_4.setMaximumSize(QtCore.QSize(220, 16777215))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.CTR_Detector_Sensitivity_1 = QtGui.QPushButton(self.widget_4)
        self.CTR_Detector_Sensitivity_1.setStyleSheet(_fromUtf8("background-color: rgb(255, 252, 206);"))
        self.CTR_Detector_Sensitivity_1.setText(_fromUtf8(""))
        self.CTR_Detector_Sensitivity_1.setObjectName(_fromUtf8("CTR_Detector_Sensitivity_1"))
        self.horizontalLayout_4.addWidget(self.CTR_Detector_Sensitivity_1)
        self.CTR_Detector_Sensitivity_2 = QtGui.QPushButton(self.widget_4)
        self.CTR_Detector_Sensitivity_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 127);"))
        self.CTR_Detector_Sensitivity_2.setText(_fromUtf8(""))
        self.CTR_Detector_Sensitivity_2.setObjectName(_fromUtf8("CTR_Detector_Sensitivity_2"))
        self.horizontalLayout_4.addWidget(self.CTR_Detector_Sensitivity_2)
        self.CTR_Detector_Sensitivity_3 = QtGui.QPushButton(self.widget_4)
        self.CTR_Detector_Sensitivity_3.setStyleSheet(_fromUtf8("background-color: rgb(236, 194, 26);"))
        self.CTR_Detector_Sensitivity_3.setText(_fromUtf8(""))
        self.CTR_Detector_Sensitivity_3.setObjectName(_fromUtf8("CTR_Detector_Sensitivity_3"))
        self.horizontalLayout_4.addWidget(self.CTR_Detector_Sensitivity_3)
        self.CTR_Detector_Sensitivity_4 = QtGui.QPushButton(self.widget_4)
        self.CTR_Detector_Sensitivity_4.setStyleSheet(_fromUtf8("background-color: rgb(175, 127, 44);"))
        self.CTR_Detector_Sensitivity_4.setText(_fromUtf8(""))
        self.CTR_Detector_Sensitivity_4.setObjectName(_fromUtf8("CTR_Detector_Sensitivity_4"))
        self.horizontalLayout_4.addWidget(self.CTR_Detector_Sensitivity_4)
        self.CTR_Detector_Sensitivity_5 = QtGui.QPushButton(self.widget_4)
        self.CTR_Detector_Sensitivity_5.setStyleSheet(_fromUtf8("background-color: rgb(121, 89, 14);"))
        self.CTR_Detector_Sensitivity_5.setText(_fromUtf8(""))
        self.CTR_Detector_Sensitivity_5.setObjectName(_fromUtf8("CTR_Detector_Sensitivity_5"))
        self.horizontalLayout_4.addWidget(self.CTR_Detector_Sensitivity_5)
        self.formLayout.setWidget(6, QtGui.QFormLayout.SpanningRole, self.widget_4)
        self.verticalLayout.addWidget(self.CTR_Scan_Box)
        self.Gun_Fine_Crest = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gun_Fine_Crest.sizePolicy().hasHeightForWidth())
        self.Gun_Fine_Crest.setSizePolicy(sizePolicy)
        self.Gun_Fine_Crest.setMinimumSize(QtCore.QSize(0, 80))
        self.Gun_Fine_Crest.setMaximumSize(QtCore.QSize(16777215, 80))
        self.Gun_Fine_Crest.setObjectName(_fromUtf8("Gun_Fine_Crest"))
        self.gridLayout_5 = QtGui.QGridLayout(self.Gun_Fine_Crest)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.CTR_Do_Scan_Button = QtGui.QPushButton(self.Gun_Fine_Crest)
        self.CTR_Do_Scan_Button.setMinimumSize(QtCore.QSize(0, 23))
        self.CTR_Do_Scan_Button.setChecked(False)
        self.CTR_Do_Scan_Button.setObjectName(_fromUtf8("CTR_Do_Scan_Button"))
        self.gridLayout_5.addWidget(self.CTR_Do_Scan_Button, 1, 0, 1, 1)
        self.CTR_Save_Button = QtGui.QPushButton(self.Gun_Fine_Crest)
        self.CTR_Save_Button.setMinimumSize(QtCore.QSize(0, 23))
        self.CTR_Save_Button.setObjectName(_fromUtf8("CTR_Save_Button"))
        self.gridLayout_5.addWidget(self.CTR_Save_Button, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.Gun_Fine_Crest)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 2, 0, 1, 1)
        self.CTR_Max_Compression = QtGui.QDoubleSpinBox(self.Gun_Fine_Crest)
        self.CTR_Max_Compression.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CTR_Max_Compression.setFont(font)
        self.CTR_Max_Compression.setAlignment(QtCore.Qt.AlignCenter)
        self.CTR_Max_Compression.setReadOnly(True)
        self.CTR_Max_Compression.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.CTR_Max_Compression.setDecimals(1)
        self.CTR_Max_Compression.setMinimum(-180.0)
        self.CTR_Max_Compression.setMaximum(180.0)
        self.CTR_Max_Compression.setObjectName(_fromUtf8("CTR_Max_Compression"))
        self.gridLayout_5.addWidget(self.CTR_Max_Compression, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.Gun_Fine_Crest)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.CTR_Plots_Box = QtGui.QGroupBox(self.CTR_Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CTR_Plots_Box.sizePolicy().hasHeightForWidth())
        self.CTR_Plots_Box.setSizePolicy(sizePolicy)
        self.CTR_Plots_Box.setMinimumSize(QtCore.QSize(0, 550))
        self.CTR_Plots_Box.setMaximumSize(QtCore.QSize(16777215, 630))
        self.CTR_Plots_Box.setObjectName(_fromUtf8("CTR_Plots_Box"))
        self.CTR_Plots_Layout = QtGui.QVBoxLayout(self.CTR_Plots_Box)
        self.CTR_Plots_Layout.setObjectName(_fromUtf8("CTR_Plots_Layout"))
        self.gridLayout_2.addWidget(self.CTR_Plots_Box, 0, 1, 2, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 2, 1, 1, 1)
        self.tabWidget.addTab(self.CTR_Tab, icon, _fromUtf8(""))
        self.linac1_Tab = QtGui.QWidget()
        self.linac1_Tab.setEnabled(False)
        self.linac1_Tab.setObjectName(_fromUtf8("linac1_Tab"))
        self.gridLayout_11 = QtGui.QGridLayout(self.linac1_Tab)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.widget_3 = QtGui.QWidget(self.linac1_Tab)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.gridLayout_11.addWidget(self.widget_3, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("spread.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.linac1_Tab, icon2, _fromUtf8(""))
        self.logTab = QtGui.QWidget()
        self.logTab.setObjectName(_fromUtf8("logTab"))
        self.logTabLayout = QtGui.QVBoxLayout(self.logTab)
        self.logTabLayout.setObjectName(_fromUtf8("logTabLayout"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/log.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.logTab, icon3, _fromUtf8(""))
        self.centralWidgetLayout.addWidget(self.tabWidget, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1140, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSave_Data = QtGui.QMenu(self.menubar)
        self.menuSave_Data.setObjectName(_fromUtf8("menuSave_Data"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_Calibation_Data = QtGui.QAction(MainWindow)
        self.actionSave_Calibation_Data.setObjectName(_fromUtf8("actionSave_Calibation_Data"))
        self.actionAuto_Save_Data = QtGui.QAction(MainWindow)
        self.actionAuto_Save_Data.setCheckable(True)
        self.actionAuto_Save_Data.setChecked(True)
        self.actionAuto_Save_Data.setObjectName(_fromUtf8("actionAuto_Save_Data"))
        self.actionSave_to_Work_Folder = QtGui.QAction(MainWindow)
        self.actionSave_to_Work_Folder.setCheckable(True)
        self.actionSave_to_Work_Folder.setChecked(True)
        self.actionSave_to_Work_Folder.setObjectName(_fromUtf8("actionSave_to_Work_Folder"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSave_Defaults = QtGui.QAction(MainWindow)
        self.actionSave_Defaults.setObjectName(_fromUtf8("actionSave_Defaults"))
        self.actionReload_Defaults = QtGui.QAction(MainWindow)
        self.actionReload_Defaults.setObjectName(_fromUtf8("actionReload_Defaults"))
        self.actionApply_Default_Settings = QtGui.QAction(MainWindow)
        self.actionApply_Default_Settings.setObjectName(_fromUtf8("actionApply_Default_Settings"))
        self.menuFile.addAction(self.actionReload_Defaults)
        self.menuFile.addAction(self.actionSave_Defaults)
        self.menuFile.addAction(self.actionApply_Default_Settings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSave_Data.addAction(self.actionAuto_Save_Data)
        self.menuSave_Data.addAction(self.actionSave_to_Work_Folder)
        self.menuSave_Data.addAction(self.actionSave_Calibation_Data)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSave_Data.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.CTR_C2V_Position_Set, self.CTR_Max_Linac_Set)
        MainWindow.setTabOrder(self.CTR_Max_Linac_Set, self.CTR_Correct_Momentum_Button)
        MainWindow.setTabOrder(self.CTR_Correct_Momentum_Button, self.CTR_Phase_Start_Set)
        MainWindow.setTabOrder(self.CTR_Phase_Start_Set, self.CTR_Phase_End_Set)
        MainWindow.setTabOrder(self.CTR_Phase_End_Set, self.CTR_Phase_Step_Set)
        MainWindow.setTabOrder(self.CTR_Phase_Step_Set, self.CTR_Do_Scan_Button)
        MainWindow.setTabOrder(self.CTR_Do_Scan_Button, self.Finish_Button)
        MainWindow.setTabOrder(self.Finish_Button, self.Abort_Button)
        MainWindow.setTabOrder(self.Abort_Button, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.C2V_BPM_Monitor)
        MainWindow.setTabOrder(self.C2V_BPM_Monitor, self.Gun_Phase_Monitor)
        MainWindow.setTabOrder(self.Gun_Phase_Monitor, self.Linac1_Amp_Monitor)
        MainWindow.setTabOrder(self.Linac1_Amp_Monitor, self.Gun_Amp_Monitor)
        MainWindow.setTabOrder(self.Gun_Amp_Monitor, self.Linac1_Phase_Monitor)
        MainWindow.setTabOrder(self.Linac1_Phase_Monitor, self.Linac1_Timing_Monitor)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "C(T)RApp", None))
        self.groupBox.setTitle(_translate("MainWindow", "Status", None))
        self.label_MODE.setText(_translate("MainWindow", "Mode", None))
        self.Linac1_Amp_Monitor.setToolTip(_translate("MainWindow", "Linac 1 AMP set", None))
        self.Linac1_Amp_Monitor.setSuffix(_translate("MainWindow", " SET", None))
        self.C2V_BPM_Monitor.setToolTip(_translate("MainWindow", "C2V X position", None))
        self.C2V_BPM_Monitor.setSuffix(_translate("MainWindow", " mm", None))
        self.Gun_Phase_Monitor.setToolTip(_translate("MainWindow", "Gun PHASE set", None))
        self.Gun_Phase_Monitor.setSuffix(_translate("MainWindow", "°", None))
        self.label_31.setText(_translate("MainWindow", "C2V BPM X", None))
        self.Progress_Monitor.setToolTip(_translate("MainWindow", "Progress of the running scan", None))
        self.label_27.setText(_translate("MainWindow", "Gun", None))
        self.label_30.setText(_translate("MainWindow", "Linac1", None))
        self.Gun_Amp_Monitor.setToolTip(_translate("MainWindow", "Gun AMP set", None))
        self.Gun_Amp_Monitor.setSuffix(_translate("MainWindow", " SET", None))
        self.Linac1_Phase_Monitor.setToolTip(_translate("MainWindow", "Linac 1 PHASE set", None))
        self.Linac1_Phase_Monitor.setSuffix(_translate("MainWindow", "°", None))
        self.label_32.setText(_translate("MainWindow", "Progress", None))
        self.Linac1_Timing_Monitor.setToolTip(_translate("MainWindow", "Alter the linac timings (GREEN: Linacs timed with beam, RED: Linacs timed away from beam)", None))
        self.Save_Data_Buttons.setToolTip(_translate("MainWindow", "Save/Discard cresting data to the work folder", None))
        self.Finish_Button.setToolTip(_translate("MainWindow", "Stop the current scan and analyse", None))
        self.Finish_Button.setText(_translate("MainWindow", "Finish Scan", None))
        self.Abort_Button.setToolTip(_translate("MainWindow", "Abort the current scan", None))
        self.Abort_Button.setText(_translate("MainWindow", "Abort", None))
        self.CTR_Crests_Box.setTitle(_translate("MainWindow", "Define Crests", None))
        self.label_6.setText(_translate("MainWindow", "Gun Off-crest", None))
        self.CTR_Gun_Crest_Set.setToolTip(_translate("MainWindow", "Nominal Gun crest", None))
        self.CTR_Gun_Crest_Set.setSuffix(_translate("MainWindow", "°", None))
        self.label_14.setText(_translate("MainWindow", "Gun Crest", None))
        self.CTR_Gun_Load_Crest_Button.setToolTip(_translate("MainWindow", "Load the latest Gun auto-crester data", None))
        self.CTR_Gun_Load_Crest_Button.setText(_translate("MainWindow", "Load Gun Crest", None))
        self.label_13.setText(_translate("MainWindow", "Linac Crest", None))
        self.CTR_Linac1_Crest_Set.setToolTip(_translate("MainWindow", "Nominal Linac 1 crest", None))
        self.CTR_Linac1_Crest_Set.setSuffix(_translate("MainWindow", "°", None))
        self.CTR_Linac_Load_Crest_Button.setToolTip(_translate("MainWindow", "Load the latest Linac 1 auto-crester data", None))
        self.CTR_Linac_Load_Crest_Button.setText(_translate("MainWindow", "Load Linac Crest", None))
        self.CTR_Gun_OffCrest_Set.setSuffix(_translate("MainWindow", "°", None))
        self.CTR_Momentum_Box.setTitle(_translate("MainWindow", "Fix Momentum", None))
        self.label_33.setText(_translate("MainWindow", "Auto Correct Momentum", None))
        self.CTR_Auto_Correct_Set.setToolTip(_translate("MainWindow", "Auto-correct the momentum with phase change?", None))
        self.label.setText(_translate("MainWindow", "C2V Position", None))
        self.CTR_C2V_Position_Set.setToolTip(_translate("MainWindow", "Nominal CSV X position to correct to", None))
        self.CTR_C2V_Position_Set.setSuffix(_translate("MainWindow", " mm", None))
        self.label_10.setText(_translate("MainWindow", "Max. Linac Set Value", None))
        self.CTR_Max_Linac_Set.setToolTip(_translate("MainWindow", "Maximum linac amplitude allowed", None))
        self.CTR_Correct_Momentum_Button.setToolTip(_translate("MainWindow", "Perform a momentum correction", None))
        self.CTR_Correct_Momentum_Button.setText(_translate("MainWindow", "Correct Momentum", None))
        self.label_5.setText(_translate("MainWindow", "Linac Amp. Step Size", None))
        self.CTR_Linac_Step_Set.setToolTip(_translate("MainWindow", "Step size for the momentum correction", None))
        self.CTR_Scan_Box.setTitle(_translate("MainWindow", "Scan Parameters", None))
        self.label_11.setText(_translate("MainWindow", "Phase Minimum", None))
        self.CTR_Phase_Start_Set.setToolTip(_translate("MainWindow", "Starting phase for the scan", None))
        self.CTR_Phase_Start_Set.setSuffix(_translate("MainWindow", "°", None))
        self.label_12.setText(_translate("MainWindow", "Phase Maximum", None))
        self.CTR_Phase_End_Set.setToolTip(_translate("MainWindow", "Final phase for the scan", None))
        self.CTR_Phase_End_Set.setSuffix(_translate("MainWindow", "°", None))
        self.label_28.setText(_translate("MainWindow", "Phase Step Size", None))
        self.CTR_Phase_Step_Set.setToolTip(_translate("MainWindow", "Step size for the linac phase", None))
        self.CTR_Phase_Step_Set.setSuffix(_translate("MainWindow", "°", None))
        self.label_3.setText(_translate("MainWindow", "Number of Shots (per point)", None))
        self.CTR_NShots_Set.setToolTip(_translate("MainWindow", "Number of BPM readings to average for the BPM phase scan", None))
        self.label_4.setText(_translate("MainWindow", "Detector Sensitivity", None))
        self.Gun_Fine_Crest.setTitle(_translate("MainWindow", "Do Scan", None))
        self.CTR_Do_Scan_Button.setToolTip(_translate("MainWindow", "Run CTR Scan", None))
        self.CTR_Do_Scan_Button.setText(_translate("MainWindow", "Scan", None))
        self.CTR_Save_Button.setToolTip(_translate("MainWindow", "Save data arrays", None))
        self.CTR_Save_Button.setText(_translate("MainWindow", "Save", None))
        self.label_2.setText(_translate("MainWindow", "Maximum Compression", None))
        self.CTR_Max_Compression.setToolTip(_translate("MainWindow", "Calculated phase of maximum compression", None))
        self.CTR_Max_Compression.setSuffix(_translate("MainWindow", "°", None))
        self.CTR_Plots_Box.setTitle(_translate("MainWindow", "CTR Measurement Plots", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CTR_Tab), _translate("MainWindow", "CTR", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.linac1_Tab), _translate("MainWindow", "Del E", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logTab), _translate("MainWindow", "Log", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSave_Data.setTitle(_translate("MainWindow", "Save Data", None))
        self.actionSave_Calibation_Data.setText(_translate("MainWindow", "Save Calibation Data", None))
        self.actionAuto_Save_Data.setText(_translate("MainWindow", "Auto Save Data", None))
        self.actionSave_to_Work_Folder.setText(_translate("MainWindow", "Save to Work Folder", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionSave_Defaults.setText(_translate("MainWindow", "Save Settings", None))
        self.actionReload_Defaults.setText(_translate("MainWindow", "Reload Settings", None))
        self.actionApply_Default_Settings.setText(_translate("MainWindow", "Apply Default Settings", None))

