# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/qfi29231/Documents/VELA_CLARA_repository/IMG_GUI/img_gui_view.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1331, 807)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1311, 761))
        self.tabWidget.setObjectName("tabWidget")
        self.IMGPressure_tab = QtWidgets.QWidget()
        self.IMGPressure_tab.setObjectName("IMGPressure_tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.IMGPressure_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 1291, 144))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.IMGTitleLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.IMGTitleLayout.setContentsMargins(0, 0, 0, 0)
        self.IMGTitleLayout.setObjectName("IMGTitleLayout")
        self.IMGTitleLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.IMGTitleLabel.setFont(font)
        self.IMGTitleLabel.setObjectName("IMGTitleLabel")
        self.IMGTitleLayout.addWidget(self.IMGTitleLabel, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.IMGPressure_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 650, 1291, 81))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.IMGButtonGridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.IMGButtonGridLayout.setContentsMargins(0, 0, 0, 0)
        self.IMGButtonGridLayout.setObjectName("IMGButtonGridLayout")
        self.IMGpushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.IMGpushButton.setObjectName("IMGpushButton")
        self.IMGButtonGridLayout.addWidget(self.IMGpushButton, 0, 2, 1, 1)
        self.IMGButtonLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(14)
        self.IMGButtonLabel.setFont(font)
        self.IMGButtonLabel.setObjectName("IMGButtonLabel")
        self.IMGButtonGridLayout.addWidget(self.IMGButtonLabel, 0, 1, 1, 1)
        self.IMGVirtual_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(14)
        self.IMGVirtual_checkBox.setFont(font)
        self.IMGVirtual_checkBox.setObjectName("IMGVirtual_checkBox")
        self.IMGButtonGridLayout.addWidget(self.IMGVirtual_checkBox, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.IMGPressure_tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 160, 1297, 457))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.IMGPressuregridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.IMGPressuregridLayout.setContentsMargins(0, 0, 0, 0)
        self.IMGPressuregridLayout.setObjectName("IMGPressuregridLayout")
        self.IMG01_lcdNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.IMG01_lcdNumber.setObjectName("IMG01_lcdNumber")
        self.IMGPressuregridLayout.addWidget(self.IMG01_lcdNumber, 0, 1, 1, 1)
        self.IMG02_lcdNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.IMG02_lcdNumber.setSmallDecimalPoint(True)
        self.IMG02_lcdNumber.setProperty("intValue", 0)
        self.IMG02_lcdNumber.setObjectName("IMG02_lcdNumber")
        self.IMGPressuregridLayout.addWidget(self.IMG02_lcdNumber, 1, 1, 1, 1)
        self.IMG03_lcdNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.IMG03_lcdNumber.setSmallDecimalPoint(True)
        self.IMG03_lcdNumber.setProperty("intValue", 0)
        self.IMG03_lcdNumber.setObjectName("IMG03_lcdNumber")
        self.IMGPressuregridLayout.addWidget(self.IMG03_lcdNumber, 2, 1, 1, 1)
        self.IMG04_lcdNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.IMG04_lcdNumber.setSmallDecimalPoint(True)
        self.IMG04_lcdNumber.setProperty("intValue", 0)
        self.IMG04_lcdNumber.setObjectName("IMG04_lcdNumber")
        self.IMGPressuregridLayout.addWidget(self.IMG04_lcdNumber, 3, 1, 1, 1)
        self.IMG05_lcdNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.IMG05_lcdNumber.setSmallDecimalPoint(True)
        self.IMG05_lcdNumber.setProperty("intValue", 0)
        self.IMG05_lcdNumber.setObjectName("IMG05_lcdNumber")
        self.IMGPressuregridLayout.addWidget(self.IMG05_lcdNumber, 0, 3, 1, 1)
        self.IMG06_lcdNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.IMG06_lcdNumber.setSmallDecimalPoint(True)
        self.IMG06_lcdNumber.setProperty("intValue", 0)
        self.IMG06_lcdNumber.setObjectName("IMG06_lcdNumber")
        self.IMGPressuregridLayout.addWidget(self.IMG06_lcdNumber, 1, 3, 1, 1)
        self.IMG07_lcdNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.IMG07_lcdNumber.setSmallDecimalPoint(True)
        self.IMG07_lcdNumber.setProperty("intValue", 0)
        self.IMG07_lcdNumber.setObjectName("IMG07_lcdNumber")
        self.IMGPressuregridLayout.addWidget(self.IMG07_lcdNumber, 2, 3, 1, 1)
        self.IMG08_lcdNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.IMG08_lcdNumber.setSmallDecimalPoint(True)
        self.IMG08_lcdNumber.setProperty("intValue", 0)
        self.IMG08_lcdNumber.setObjectName("IMG08_lcdNumber")
        self.IMGPressuregridLayout.addWidget(self.IMG08_lcdNumber, 3, 3, 1, 1)
        self.IMG09_lcdNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.IMG09_lcdNumber.setSmallDecimalPoint(True)
        self.IMG09_lcdNumber.setProperty("intValue", 0)
        self.IMG09_lcdNumber.setObjectName("IMG09_lcdNumber")
        self.IMGPressuregridLayout.addWidget(self.IMG09_lcdNumber, 0, 5, 1, 1)
        self.IMG10_lcdNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.IMG10_lcdNumber.setSmallDecimalPoint(True)
        self.IMG10_lcdNumber.setProperty("intValue", 0)
        self.IMG10_lcdNumber.setObjectName("IMG10_lcdNumber")
        self.IMGPressuregridLayout.addWidget(self.IMG10_lcdNumber, 1, 5, 1, 1)
        self.IMG11_lcdNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.IMG11_lcdNumber.setSmallDecimalPoint(True)
        self.IMG11_lcdNumber.setProperty("intValue", 0)
        self.IMG11_lcdNumber.setObjectName("IMG11_lcdNumber")
        self.IMGPressuregridLayout.addWidget(self.IMG11_lcdNumber, 2, 5, 1, 1)

        self.IMG01_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(12)
        self.IMG01_label.setFont(font)
        self.IMG01_label.setObjectName("IMG01_label")
        self.IMGPressuregridLayout.addWidget(self.IMG01_label, 0, 0, 1, 1)
        self.IMG02_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(12)
        self.IMG02_label.setFont(font)
        self.IMG02_label.setObjectName("IMG02_label")
        self.IMGPressuregridLayout.addWidget(self.IMG02_label, 1, 0, 1, 1)
        self.IMG03_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(12)
        self.IMG03_label.setFont(font)
        self.IMG03_label.setObjectName("IMG03_label")
        self.IMGPressuregridLayout.addWidget(self.IMG03_label, 2, 0, 1, 1)
        self.IMG04_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(12)
        self.IMG04_label.setFont(font)
        self.IMG04_label.setObjectName("IMG04_label")
        self.IMGPressuregridLayout.addWidget(self.IMG04_label, 3, 0, 1, 1)
        self.IMG05_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(12)
        self.IMG05_label.setFont(font)
        self.IMG05_label.setObjectName("IMG05_label")
        self.IMGPressuregridLayout.addWidget(self.IMG05_label, 0, 2, 1, 1)
        self.IMG06_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(12)
        self.IMG06_label.setFont(font)
        self.IMG06_label.setObjectName("IMG06_label")
        self.IMGPressuregridLayout.addWidget(self.IMG06_label, 1, 2, 1, 1)
        self.IMG07_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(12)
        self.IMG07_label.setFont(font)
        self.IMG07_label.setObjectName("IMG07_label")
        self.IMGPressuregridLayout.addWidget(self.IMG07_label, 2, 2, 1, 1)
        self.IMG08_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(12)
        self.IMG08_label.setFont(font)
        self.IMG08_label.setObjectName("IMG08_label")
        self.IMGPressuregridLayout.addWidget(self.IMG08_label, 3, 2, 1, 1)
        self.IMG09_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(12)
        self.IMG09_label.setFont(font)
        self.IMG09_label.setObjectName("IMG09_label")
        self.IMGPressuregridLayout.addWidget(self.IMG09_label, 0, 4, 1, 1)
        self.IMG10_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(12)
        self.IMG10_label.setFont(font)
        self.IMG10_label.setObjectName("IMG10_label")
        self.IMGPressuregridLayout.addWidget(self.IMG10_label, 1, 4, 1, 1)
        self.IMG11_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(12)
        self.IMG11_label.setFont(font)
        self.IMG11_label.setObjectName("IMG11_label")
        self.IMGPressuregridLayout.addWidget(self.IMG11_label, 2, 4, 1, 1)
        self.tabWidget.addTab(self.IMGPressure_tab, "")
        self.tabWidget.setCurrentIndex(1)
        self.IMGPlotting_tab = QtWidgets.QWidget()
        self.IMGPlotting_tab.setObjectName("IMGPlotting_tab")
        self.graphicsView = QtWidgets.QGraphicsView(self.IMGPlotting_tab)
        self.graphicsView.setGeometry(QtCore.QRect(20, 20, 1221, 681))
        self.graphicsView.setObjectName("graphicsView")
        self.tabWidget.addTab(self.IMGPlotting_tab, "")
        self.scene = QtWidgets.QGraphicsScene(self.IMGPlotting_tab)
        self.graphicsView.setObjectName("graphicsView")
        self.tabWidget.addTab(self.IMGPlotting_tab, "")
        self.tabWidget.setCurrentIndex(2)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1331, 31))
        self.menubar.setObjectName("menubar")
        self.menuIMG_Pressure_retriever = QtWidgets.QMenu(self.menubar)
        self.menuIMG_Pressure_retriever.setObjectName("menuIMG_Pressure_retriever")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuIMG_Pressure_retriever.menuAction())

        self.retranslateUi(MainWindow)
        #self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.IMGTitleLabel.setText(_translate("MainWindow", "                                                                    Pressures for all different IMGs\n"
""))
        self.IMGpushButton.setText(_translate("MainWindow", "OK"))
        self.IMGButtonLabel.setText(_translate("MainWindow", "Retrieve pressures from all IMGs"))
        self.IMGVirtual_checkBox.setText(_translate("MainWindow", " Virtual "))
        self.IMG01_label.setText(_translate("MainWindow", "EBT-INJ-VAC-IMG-01"))
        self.IMG02_label.setText(_translate("MainWindow", "EBT-INJ-VAC-IMG-02"))
        self.IMG03_label.setText(_translate("MainWindow", "EBT-INJ-VAC-IMG-03"))
        self.IMG04_label.setText(_translate("MainWindow", "EBT-INJ-VAC-IMG-04"))
        self.IMG05_label.setText(_translate("MainWindow", "EBT-INJ-VAC-IMG-05"))
        self.IMG06_label.setText(_translate("MainWindow", "EBT-INJ-VAC-IMG-06"))
        self.IMG07_label.setText(_translate("MainWindow", "EBT-INJ-VAC-IMG-07"))
        self.IMG08_label.setText(_translate("MainWindow", "EBT-INJ-VAC-IMG-08"))
        self.IMG09_label.setText(_translate("MainWindow", "EBT-INJ-VAC-IMG-09"))
        self.IMG10_label.setText(_translate("MainWindow", "EBT-INJ-VAC-IMG-10"))
        self.IMG11_label.setText(_translate("MainWindow", "EBT-INJ-VAC-IMG-11"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.IMGPressure_tab), _translate("MainWindow", "Pressure IMGs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.IMGPlotting_tab), _translate("MainWindow", "Pressure Plots"))
        self.menuIMG_Pressure_retriever.setTitle(_translate("MainWindow", "IMG Pressure retriever"))
