# This file was generated by Nuitka and describes the types of the
# created shared library.

# At this time it lists only the imports made and can be used by the
# tools that bundle libraries, including Nuitka itself. For instance
# standalone mode usage of the created library will need it.

# In the future, this will also contain type information for values
# in the module, so IDEs will use this. Therfore please include it
# when you make software releases of the extension module that it
# describes.

import copy
import tables
import datetime
import scrollingPlot
import signal
import signalRecord
import scatterPlot
import histogramPlot
import xlsxwriter
import PyQt5.QtGui
import logging
import PyQt4.QtCore
import PyQt4.QtGui
import os
import plotLegend
import fftPlot
import numpy
import time
import PyQt5.QtCore
import PyQt5.QtWidgets

# This is not Python source even if it looks so. Make it clear for
# now. This was decided by PEP 484 designers.
__name__ = ...

