# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_FileLoad.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FileLoad(object):
    def setupUi(self, FileLoad):
        FileLoad.setObjectName("FileLoad")
        FileLoad.resize(978, 582)
        self.verticalLayout = QtWidgets.QVBoxLayout(FileLoad)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(FileLoad)
        self.groupBox.setMinimumSize(QtCore.QSize(400, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.allMagnets = QtWidgets.QRadioButton(self.groupBox)
        self.allMagnets.setChecked(True)
        self.allMagnets.setObjectName("allMagnets")
        self.horizontalLayout.addWidget(self.allMagnets)
        self.quadMagnets = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quadMagnets.setFont(font)
        self.quadMagnets.setObjectName("quadMagnets")
        self.horizontalLayout.addWidget(self.quadMagnets)
        self.corrMagnets = QtWidgets.QRadioButton(self.groupBox)
        self.corrMagnets.setObjectName("corrMagnets")
        self.horizontalLayout.addWidget(self.corrMagnets)
        self.verticalLayout.addWidget(self.groupBox)
        self.label = QtWidgets.QLabel(FileLoad)
        self.label.setMinimumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame_2 = QtWidgets.QFrame(FileLoad)
        self.frame_2.setMinimumSize(QtCore.QSize(400, 300))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.treeView = QtWidgets.QTreeView(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeView.setFont(font)
        self.treeView.setObjectName("treeView")
        self.horizontalLayout_3.addWidget(self.treeView)
        self.listView = QtWidgets.QListView(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listView.setFont(font)
        self.listView.setObjectName("listView")
        self.horizontalLayout_3.addWidget(self.listView)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 4)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(FileLoad)
        self.frame.setMinimumSize(QtCore.QSize(400, 30))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.selectButton = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectButton.setFont(font)
        self.selectButton.setObjectName("selectButton")
        self.horizontalLayout_2.addWidget(self.selectButton)
        self.cancelButton = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.viewButton = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.viewButton.setFont(font)
        self.viewButton.setObjectName("viewButton")
        self.horizontalLayout_2.addWidget(self.viewButton)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(FileLoad)
        QtCore.QMetaObject.connectSlotsByName(FileLoad)

    def retranslateUi(self, FileLoad):
        _translate = QtCore.QCoreApplication.translate
        FileLoad.setWindowTitle(_translate("FileLoad", "Dialog"))
        self.groupBox.setTitle(_translate("FileLoad", "Which Magnets To Apply File To?"))
        self.allMagnets.setText(_translate("FileLoad", "All"))
        self.quadMagnets.setText(_translate("FileLoad", "Quads"))
        self.corrMagnets.setText(_translate("FileLoad", "Correctors"))
        self.label.setText(_translate("FileLoad", "Choose File To Load Magnet Settings"))
        self.selectButton.setText(_translate("FileLoad", "Select"))
        self.cancelButton.setText(_translate("FileLoad", "Cancel"))
        self.viewButton.setText(_translate("FileLoad", "View File"))
