# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_FileSave.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FileSave(object):
    def setupUi(self, FileSave):
        FileSave.setObjectName("FileSave")
        FileSave.resize(992, 425)
        self.centralwidget = QtWidgets.QWidget(FileSave)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.keywordFrame = QtWidgets.QFrame(self.centralwidget)
        self.keywordFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.keywordFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.keywordFrame.setObjectName("keywordFrame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.keywordFrame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.keywordFrame)
        self.label_6.setMinimumSize(QtCore.QSize(90, 0))
        self.label_6.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.areaCombo = QtWidgets.QComboBox(self.keywordFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.areaCombo.setFont(font)
        self.areaCombo.setObjectName("areaCombo")
        self.horizontalLayout_8.addWidget(self.areaCombo)
        self.comboBox1 = QtWidgets.QComboBox(self.keywordFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox1.setFont(font)
        self.comboBox1.setObjectName("comboBox1")
        self.horizontalLayout_8.addWidget(self.comboBox1)
        self.comboBox2 = QtWidgets.QComboBox(self.keywordFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox2.setFont(font)
        self.comboBox2.setObjectName("comboBox2")
        self.horizontalLayout_8.addWidget(self.comboBox2)
        self.comboBox3 = QtWidgets.QComboBox(self.keywordFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox3.setFont(font)
        self.comboBox3.setObjectName("comboBox3")
        self.horizontalLayout_8.addWidget(self.comboBox3)
        self.verticalLayout.addWidget(self.keywordFrame)
        self.commentFrame = QtWidgets.QFrame(self.centralwidget)
        self.commentFrame.setMinimumSize(QtCore.QSize(0, 200))
        self.commentFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.commentFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.commentFrame.setObjectName("commentFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.commentFrame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.commentFrame)
        self.label_5.setMinimumSize(QtCore.QSize(90, 0))
        self.label_5.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_5.setBaseSize(QtCore.QSize(0, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.commentsSection = QtWidgets.QPlainTextEdit(self.commentFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.commentsSection.setFont(font)
        self.commentsSection.setObjectName("commentsSection")
        self.horizontalLayout_7.addWidget(self.commentsSection)
        self.verticalLayout.addWidget(self.commentFrame)
        self.filenameFrame = QtWidgets.QFrame(self.centralwidget)
        self.filenameFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filenameFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filenameFrame.setObjectName("filenameFrame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.filenameFrame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.filenameFrame)
        self.label_4.setMinimumSize(QtCore.QSize(90, 0))
        self.label_4.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.file_name_entry = QtWidgets.QLineEdit(self.filenameFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.file_name_entry.setFont(font)
        self.file_name_entry.setObjectName("file_name_entry")
        self.horizontalLayout_6.addWidget(self.file_name_entry)
        self.verticalLayout.addWidget(self.filenameFrame)
        self.burronFrame = QtWidgets.QFrame(self.centralwidget)
        self.burronFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.burronFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.burronFrame.setObjectName("burronFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.burronFrame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.saveNowButton_2 = QtWidgets.QPushButton(self.burronFrame)
        self.saveNowButton_2.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saveNowButton_2.setFont(font)
        self.saveNowButton_2.setObjectName("saveNowButton_2")
        self.horizontalLayout_5.addWidget(self.saveNowButton_2)
        self.cancelButton_2 = QtWidgets.QPushButton(self.burronFrame)
        self.cancelButton_2.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancelButton_2.setFont(font)
        self.cancelButton_2.setObjectName("cancelButton_2")
        self.horizontalLayout_5.addWidget(self.cancelButton_2)
        self.verticalLayout.addWidget(self.burronFrame)
        FileSave.setCentralWidget(self.centralwidget)

        self.retranslateUi(FileSave)
        QtCore.QMetaObject.connectSlotsByName(FileSave)

    def retranslateUi(self, FileSave):
        _translate = QtCore.QCoreApplication.translate
        FileSave.setWindowTitle(_translate("FileSave", "MainWindow"))
        self.label_6.setText(_translate("FileSave", "KEYWORDS:"))
        self.label_5.setText(_translate("FileSave", "COMMENTS:"))
        self.label_4.setText(_translate("FileSave", "FILENAME:"))
        self.saveNowButton_2.setText(_translate("FileSave", "SAVE NOW"))
        self.cancelButton_2.setText(_translate("FileSave", "CANCEL"))
