# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_magnetAppMainView.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_magnetAppMainView(object):
    def setupUi(self, magnetAppMainView):
        magnetAppMainView.setObjectName("magnetAppMainView")
        magnetAppMainView.resize(1305, 606)
        self.mainFrame = QtWidgets.QWidget(magnetAppMainView)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(self.mainFrame)
        self.titleLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.mainWidgetFrame = QtWidgets.QFrame(self.mainFrame)
        self.mainWidgetFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainWidgetFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainWidgetFrame.setObjectName("mainWidgetFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mainWidgetFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.controlButtonFrame = QtWidgets.QFrame(self.mainWidgetFrame)
        self.controlButtonFrame.setMinimumSize(QtCore.QSize(120, 300))
        self.controlButtonFrame.setMaximumSize(QtCore.QSize(120, 650))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.controlButtonFrame.setFont(font)
        self.controlButtonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controlButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controlButtonFrame.setObjectName("controlButtonFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.controlButtonFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.controlsLabel = QtWidgets.QLabel(self.controlButtonFrame)
        self.controlsLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.controlsLabel.setFont(font)
        self.controlsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.controlsLabel.setObjectName("controlsLabel")
        self.verticalLayout_2.addWidget(self.controlsLabel)
        self.mainSelectAll = QtWidgets.QPushButton(self.controlButtonFrame)
        self.mainSelectAll.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mainSelectAll.setFont(font)
        self.mainSelectAll.setObjectName("mainSelectAll")
        self.verticalLayout_2.addWidget(self.mainSelectAll)
        self.selectNone = QtWidgets.QPushButton(self.controlButtonFrame)
        self.selectNone.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectNone.setFont(font)
        self.selectNone.setObjectName("selectNone")
        self.verticalLayout_2.addWidget(self.selectNone)
        self.selectedOn = QtWidgets.QPushButton(self.controlButtonFrame)
        self.selectedOn.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectedOn.setFont(font)
        self.selectedOn.setObjectName("selectedOn")
        self.verticalLayout_2.addWidget(self.selectedOn)
        self.selectedOff = QtWidgets.QPushButton(self.controlButtonFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectedOff.setFont(font)
        self.selectedOff.setObjectName("selectedOff")
        self.verticalLayout_2.addWidget(self.selectedOff)
        self.selectedDegauss = QtWidgets.QPushButton(self.controlButtonFrame)
        self.selectedDegauss.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectedDegauss.setFont(font)
        self.selectedDegauss.setObjectName("selectedDegauss")
        self.verticalLayout_2.addWidget(self.selectedDegauss)
        self.selectedDegaussToZero = QtWidgets.QPushButton(self.controlButtonFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectedDegaussToZero.setFont(font)
        self.selectedDegaussToZero.setObjectName("selectedDegaussToZero")
        self.verticalLayout_2.addWidget(self.selectedDegaussToZero)
        self.allOn = QtWidgets.QPushButton(self.controlButtonFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.allOn.setFont(font)
        self.allOn.setObjectName("allOn")
        self.verticalLayout_2.addWidget(self.allOn)
        self.allOff = QtWidgets.QPushButton(self.controlButtonFrame)
        self.allOff.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.allOff.setFont(font)
        self.allOff.setObjectName("allOff")
        self.verticalLayout_2.addWidget(self.allOff)
        self.allZero = QtWidgets.QPushButton(self.controlButtonFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.allZero.setFont(font)
        self.allZero.setObjectName("allZero")
        self.verticalLayout_2.addWidget(self.allZero)
        self.loadSettings = QtWidgets.QPushButton(self.controlButtonFrame)
        self.loadSettings.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loadSettings.setFont(font)
        self.loadSettings.setObjectName("loadSettings")
        self.verticalLayout_2.addWidget(self.loadSettings)
        self.saveSettings = QtWidgets.QPushButton(self.controlButtonFrame)
        self.saveSettings.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saveSettings.setFont(font)
        self.saveSettings.setObjectName("saveSettings")
        self.verticalLayout_2.addWidget(self.saveSettings)
        self.iconLabel = QtWidgets.QLabel(self.controlButtonFrame)
        self.iconLabel.setMinimumSize(QtCore.QSize(0, 100))
        self.iconLabel.setObjectName("iconLabel")
        self.verticalLayout_2.addWidget(self.iconLabel)
        self.logoLabel = QtWidgets.QLabel(self.controlButtonFrame)
        self.logoLabel.setMinimumSize(QtCore.QSize(0, 100))
        self.logoLabel.setObjectName("logoLabel")
        self.verticalLayout_2.addWidget(self.logoLabel)
        self.horizontalLayout.addWidget(self.controlButtonFrame)
        self.line = QtWidgets.QFrame(self.mainWidgetFrame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.solFrame = QtWidgets.QFrame(self.mainWidgetFrame)
        self.solFrame.setMinimumSize(QtCore.QSize(120, 300))
        self.solFrame.setMaximumSize(QtCore.QSize(120, 16777215))
        self.solFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.solFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.solFrame.setObjectName("solFrame")
        self.solFrameLayout = QtWidgets.QVBoxLayout(self.solFrame)
        self.solFrameLayout.setObjectName("solFrameLayout")
        self.solenoidsLabel = QtWidgets.QLabel(self.solFrame)
        self.solenoidsLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.solenoidsLabel.setFont(font)
        self.solenoidsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.solenoidsLabel.setObjectName("solenoidsLabel")
        self.solFrameLayout.addWidget(self.solenoidsLabel)
        self.solSelectAll = QtWidgets.QPushButton(self.solFrame)
        self.solSelectAll.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.solSelectAll.setFont(font)
        self.solSelectAll.setObjectName("solSelectAll")
        self.solFrameLayout.addWidget(self.solSelectAll)
        self.solSelectNone = QtWidgets.QPushButton(self.solFrame)
        self.solSelectNone.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.solSelectNone.setFont(font)
        self.solSelectNone.setObjectName("solSelectNone")
        self.solFrameLayout.addWidget(self.solSelectNone)
        self.sol_Grid_Box = QtWidgets.QGridLayout()
        self.sol_Grid_Box.setObjectName("sol_Grid_Box")
        self.solFrameLayout.addLayout(self.sol_Grid_Box)
        self.horizontalLayout.addWidget(self.solFrame)
        self.line_2 = QtWidgets.QFrame(self.mainWidgetFrame)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.dipFrame = QtWidgets.QFrame(self.mainWidgetFrame)
        self.dipFrame.setMinimumSize(QtCore.QSize(120, 0))
        self.dipFrame.setMaximumSize(QtCore.QSize(120, 16777215))
        self.dipFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dipFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dipFrame.setObjectName("dipFrame")
        self.dipFrameLayout = QtWidgets.QVBoxLayout(self.dipFrame)
        self.dipFrameLayout.setObjectName("dipFrameLayout")
        self.dipolesLabel = QtWidgets.QLabel(self.dipFrame)
        self.dipolesLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dipolesLabel.setFont(font)
        self.dipolesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dipolesLabel.setObjectName("dipolesLabel")
        self.dipFrameLayout.addWidget(self.dipolesLabel)
        self.dipSelectAll = QtWidgets.QPushButton(self.dipFrame)
        self.dipSelectAll.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dipSelectAll.setFont(font)
        self.dipSelectAll.setObjectName("dipSelectAll")
        self.dipFrameLayout.addWidget(self.dipSelectAll)
        self.dipSelectNone = QtWidgets.QPushButton(self.dipFrame)
        self.dipSelectNone.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dipSelectNone.setFont(font)
        self.dipSelectNone.setObjectName("dipSelectNone")
        self.dipFrameLayout.addWidget(self.dipSelectNone)
        self.dip_Grid_Box = QtWidgets.QGridLayout()
        self.dip_Grid_Box.setObjectName("dip_Grid_Box")
        self.dipFrameLayout.addLayout(self.dip_Grid_Box)
        self.horizontalLayout.addWidget(self.dipFrame)
        self.line_3 = QtWidgets.QFrame(self.mainWidgetFrame)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.quadFrame = QtWidgets.QFrame(self.mainWidgetFrame)
        self.quadFrame.setMinimumSize(QtCore.QSize(500, 0))
        self.quadFrame.setMaximumSize(QtCore.QSize(550, 16777215))
        self.quadFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.quadFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.quadFrame.setObjectName("quadFrame")
        self.quadFrameLayout = QtWidgets.QVBoxLayout(self.quadFrame)
        self.quadFrameLayout.setObjectName("quadFrameLayout")
        self.quadLabel = QtWidgets.QLabel(self.quadFrame)
        self.quadLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.quadLabel.setFont(font)
        self.quadLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.quadLabel.setObjectName("quadLabel")
        self.quadFrameLayout.addWidget(self.quadLabel)
        self.quadSelectAll = QtWidgets.QPushButton(self.quadFrame)
        self.quadSelectAll.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quadSelectAll.setFont(font)
        self.quadSelectAll.setObjectName("quadSelectAll")
        self.quadFrameLayout.addWidget(self.quadSelectAll)
        self.quadSelectNone = QtWidgets.QPushButton(self.quadFrame)
        self.quadSelectNone.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quadSelectNone.setFont(font)
        self.quadSelectNone.setObjectName("quadSelectNone")
        self.quadFrameLayout.addWidget(self.quadSelectNone)
        self.quad_Grid_Box = QtWidgets.QGridLayout()
        self.quad_Grid_Box.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.quad_Grid_Box.setContentsMargins(-1, -1, 0, -1)
        self.quad_Grid_Box.setHorizontalSpacing(5)
        self.quad_Grid_Box.setVerticalSpacing(7)
        self.quad_Grid_Box.setObjectName("quad_Grid_Box")
        self.quadFrameLayout.addLayout(self.quad_Grid_Box)
        self.horizontalLayout.addWidget(self.quadFrame)
        self.line_4 = QtWidgets.QFrame(self.mainWidgetFrame)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.corrFrame = QtWidgets.QFrame(self.mainWidgetFrame)
        self.corrFrame.setMaximumSize(QtCore.QSize(600, 16777215))
        self.corrFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.corrFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.corrFrame.setObjectName("corrFrame")
        self.corFrameLayout = QtWidgets.QVBoxLayout(self.corrFrame)
        self.corFrameLayout.setObjectName("corFrameLayout")
        self.corLabel = QtWidgets.QLabel(self.corrFrame)
        self.corLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.corLabel.setFont(font)
        self.corLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.corLabel.setObjectName("corLabel")
        self.corFrameLayout.addWidget(self.corLabel)
        self.corSelectAll = QtWidgets.QPushButton(self.corrFrame)
        self.corSelectAll.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.corSelectAll.setFont(font)
        self.corSelectAll.setObjectName("corSelectAll")
        self.corFrameLayout.addWidget(self.corSelectAll)
        self.corSelectNone = QtWidgets.QPushButton(self.corrFrame)
        self.corSelectNone.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.corSelectNone.setFont(font)
        self.corSelectNone.setObjectName("corSelectNone")
        self.corFrameLayout.addWidget(self.corSelectNone)
        self.cor_Grid_Box = QtWidgets.QGridLayout()
        self.cor_Grid_Box.setObjectName("cor_Grid_Box")
        self.corFrameLayout.addLayout(self.cor_Grid_Box)
        self.horizontalLayout.addWidget(self.corrFrame)
        self.verticalLayout.addWidget(self.mainWidgetFrame)
        magnetAppMainView.setCentralWidget(self.mainFrame)
        self.menubar = QtWidgets.QMenuBar(magnetAppMainView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1305, 21))
        self.menubar.setObjectName("menubar")
        magnetAppMainView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(magnetAppMainView)
        self.statusbar.setObjectName("statusbar")
        magnetAppMainView.setStatusBar(self.statusbar)

        self.retranslateUi(magnetAppMainView)
        QtCore.QMetaObject.connectSlotsByName(magnetAppMainView)

    def retranslateUi(self, magnetAppMainView):
        _translate = QtCore.QCoreApplication.translate
        magnetAppMainView.setWindowTitle(_translate("magnetAppMainView", "MainWindow"))
        self.titleLabel.setText(_translate("magnetAppMainView", "The title of this window, which area and mode etc."))
        self.controlsLabel.setText(_translate("magnetAppMainView", "Controls"))
        self.mainSelectAll.setText(_translate("magnetAppMainView", "Select All"))
        self.selectNone.setText(_translate("magnetAppMainView", "Select None"))
        self.selectedOn.setText(_translate("magnetAppMainView", "Selected On"))
        self.selectedOff.setText(_translate("magnetAppMainView", "Selected Off"))
        self.selectedDegauss.setText(_translate("magnetAppMainView", "Degauss"))
        self.selectedDegaussToZero.setText(_translate("magnetAppMainView", "Deg To 0"))
        self.allOn.setText(_translate("magnetAppMainView", "All On"))
        self.allOff.setText(_translate("magnetAppMainView", "All Off"))
        self.allZero.setText(_translate("magnetAppMainView", "All Zero"))
        self.loadSettings.setText(_translate("magnetAppMainView", "Load "))
        self.saveSettings.setText(_translate("magnetAppMainView", "Save"))
        self.iconLabel.setText(_translate("magnetAppMainView", "TextLabel"))
        self.logoLabel.setText(_translate("magnetAppMainView", "logo"))
        self.solenoidsLabel.setText(_translate("magnetAppMainView", "Solenoids"))
        self.solSelectAll.setText(_translate("magnetAppMainView", "Select All"))
        self.solSelectNone.setText(_translate("magnetAppMainView", "Select None"))
        self.dipolesLabel.setText(_translate("magnetAppMainView", "Dipoles"))
        self.dipSelectAll.setText(_translate("magnetAppMainView", "Select All"))
        self.dipSelectNone.setText(_translate("magnetAppMainView", "Select None"))
        self.quadLabel.setText(_translate("magnetAppMainView", "Quadrupoles"))
        self.quadSelectAll.setText(_translate("magnetAppMainView", "Select All"))
        self.quadSelectNone.setText(_translate("magnetAppMainView", "Select None"))
        self.corLabel.setText(_translate("magnetAppMainView", "Correctors"))
        self.corSelectAll.setText(_translate("magnetAppMainView", "Select All"))
        self.corSelectNone.setText(_translate("magnetAppMainView", "Select None"))
