# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_screen_status_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_screen_status_view(object):
    def setupUi(self, screen_status_view):
        screen_status_view.setObjectName("screen_status_view")
        screen_status_view.resize(796, 715)
        self.centralwidget = QtWidgets.QWidget(screen_status_view)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(9, 9, 142, 149))
        self.widget.setObjectName("widget")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(9, 127, 124, 16))
        self.groupBox.setObjectName("groupBox")
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(180, 0, 248, 161))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget1)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.allout_Button = QtWidgets.QPushButton(self.groupBox_2)
        self.allout_Button.setMinimumSize(QtCore.QSize(100, 25))
        self.allout_Button.setObjectName("allout_Button")
        self.verticalLayout.addWidget(self.allout_Button)
        self.vela_led_button = QtWidgets.QPushButton(self.groupBox_2)
        self.vela_led_button.setObjectName("vela_led_button")
        self.verticalLayout.addWidget(self.vela_led_button)
        self.checkDevices_Button = QtWidgets.QPushButton(self.groupBox_2)
        self.checkDevices_Button.setObjectName("checkDevices_Button")
        self.verticalLayout.addWidget(self.checkDevices_Button)
        self.clara_led_button = QtWidgets.QPushButton(self.groupBox_2)
        self.clara_led_button.setObjectName("clara_led_button")
        self.verticalLayout.addWidget(self.clara_led_button)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget1)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stopButton = QtWidgets.QPushButton(self.groupBox_3)
        self.stopButton.setMinimumSize(QtCore.QSize(100, 25))
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout_2.addWidget(self.stopButton)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout.addWidget(self.groupBox_3)
        screen_status_view.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(screen_status_view)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 796, 21))
        self.menuBar.setObjectName("menuBar")
        screen_status_view.setMenuBar(self.menuBar)

        self.retranslateUi(screen_status_view)
        QtCore.QMetaObject.connectSlotsByName(screen_status_view)

    def retranslateUi(self, screen_status_view):
        _translate = QtCore.QCoreApplication.translate
        screen_status_view.setWindowTitle(_translate("screen_status_view", "Screen State"))
        self.groupBox.setTitle(_translate("screen_status_view", "Screens And Cameras"))
        self.groupBox_2.setTitle(_translate("screen_status_view", "Screen"))
        self.allout_Button.setText(_translate("screen_status_view", "ALL OUT"))
        self.vela_led_button.setText(_translate("screen_status_view", "VELA-LED"))
        self.checkDevices_Button.setText(_translate("screen_status_view", "Check Devices"))
        self.clara_led_button.setText(_translate("screen_status_view", "CLARA- LED"))
        self.groupBox_3.setTitle(_translate("screen_status_view", "Cameras"))
        self.stopButton.setText(_translate("screen_status_view", "STOP ALL"))
        self.pushButton.setText(_translate("screen_status_view", "Capture"))
        self.pushButton_2.setText(_translate("screen_status_view", "Take HDF5-Image"))
        self.label.setText(_translate("screen_status_view", "TextLabel"))
