# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_view.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SolAdjuster(object):
    def setupUi(self, SolAdjuster):
        SolAdjuster.setObjectName(_fromUtf8("SolAdjuster"))
        SolAdjuster.resize(211, 445)
        self.centralwidget = QtGui.QWidget(SolAdjuster)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.rf_prot_state = QtGui.QPushButton(self.widget)
        self.rf_prot_state.setMinimumSize(QtCore.QSize(45, 45))
        self.rf_prot_state.setMaximumSize(QtCore.QSize(45, 45))
        self.rf_prot_state.setText(_fromUtf8(""))
        self.rf_prot_state.setObjectName(_fromUtf8("rf_prot_state"))
        self.horizontalLayout_5.addWidget(self.rf_prot_state)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.degauss_sol_0 = QtGui.QPushButton(self.widget)
        self.degauss_sol_0.setMinimumSize(QtCore.QSize(100, 25))
        self.degauss_sol_0.setMaximumSize(QtCore.QSize(175, 16777215))
        self.degauss_sol_0.setObjectName(_fromUtf8("degauss_sol_0"))
        self.verticalLayout_6.addWidget(self.degauss_sol_0)
        self.degauss_bsol_0 = QtGui.QPushButton(self.widget)
        self.degauss_bsol_0.setObjectName(_fromUtf8("degauss_bsol_0"))
        self.verticalLayout_6.addWidget(self.degauss_bsol_0)
        self.degauss_sol = QtGui.QPushButton(self.widget)
        self.degauss_sol.setObjectName(_fromUtf8("degauss_sol"))
        self.verticalLayout_6.addWidget(self.degauss_sol)
        self.degauss_bsol = QtGui.QPushButton(self.widget)
        self.degauss_bsol.setObjectName(_fromUtf8("degauss_bsol"))
        self.verticalLayout_6.addWidget(self.degauss_bsol)
        self.groupBox_2 = QtGui.QGroupBox(self.widget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(175, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.BSol_PSU_State = QtGui.QPushButton(self.groupBox_2)
        self.BSol_PSU_State.setMinimumSize(QtCore.QSize(50, 50))
        self.BSol_PSU_State.setMaximumSize(QtCore.QSize(50, 50))
        self.BSol_PSU_State.setAutoDefault(False)
        self.BSol_PSU_State.setDefault(False)
        self.BSol_PSU_State.setObjectName(_fromUtf8("BSol_PSU_State"))
        self.horizontalLayout.addWidget(self.BSol_PSU_State)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.bsol_stepsize = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.bsol_stepsize.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.bsol_stepsize.setDecimals(3)
        self.bsol_stepsize.setMinimum(-250.0)
        self.bsol_stepsize.setMaximum(250.0)
        self.bsol_stepsize.setObjectName(_fromUtf8("bsol_stepsize"))
        self.horizontalLayout.addWidget(self.bsol_stepsize)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setMaximumSize(QtCore.QSize(45, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.bsol_seti = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.bsol_seti.setMinimumSize(QtCore.QSize(10, 10))
        self.bsol_seti.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.bsol_seti.setDecimals(3)
        self.bsol_seti.setMinimum(-250.0)
        self.bsol_seti.setMaximum(250.0)
        self.bsol_seti.setSingleStep(0.001)
        self.bsol_seti.setObjectName(_fromUtf8("bsol_seti"))
        self.horizontalLayout_2.addWidget(self.bsol_seti)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.widget)
        self.groupBox_3.setMaximumSize(QtCore.QSize(175, 16777215))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.Sol_PSU_State = QtGui.QPushButton(self.groupBox_3)
        self.Sol_PSU_State.setMinimumSize(QtCore.QSize(50, 50))
        self.Sol_PSU_State.setMaximumSize(QtCore.QSize(50, 50))
        self.Sol_PSU_State.setAutoDefault(False)
        self.Sol_PSU_State.setDefault(False)
        self.Sol_PSU_State.setObjectName(_fromUtf8("Sol_PSU_State"))
        self.horizontalLayout_3.addWidget(self.Sol_PSU_State)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.sol_stepsize = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.sol_stepsize.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.sol_stepsize.setDecimals(3)
        self.sol_stepsize.setMinimum(-250.0)
        self.sol_stepsize.setMaximum(250.0)
        self.sol_stepsize.setObjectName(_fromUtf8("sol_stepsize"))
        self.horizontalLayout_3.addWidget(self.sol_stepsize)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setMaximumSize(QtCore.QSize(45, 16777215))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.sol_seti = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.sol_seti.setMinimumSize(QtCore.QSize(10, 10))
        self.sol_seti.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.sol_seti.setDecimals(3)
        self.sol_seti.setMinimum(-250.0)
        self.sol_seti.setMaximum(1000.0)
        self.sol_seti.setSingleStep(0.001)
        self.sol_seti.setObjectName(_fromUtf8("sol_seti"))
        self.horizontalLayout_4.addWidget(self.sol_seti)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.verticalLayout.addWidget(self.widget)
        SolAdjuster.setCentralWidget(self.centralwidget)

        self.retranslateUi(SolAdjuster)
        QtCore.QMetaObject.connectSlotsByName(SolAdjuster)

    def retranslateUi(self, SolAdjuster):
        SolAdjuster.setWindowTitle(_translate("SolAdjuster", "Sol Adjuster", None))
        self.label_2.setText(_translate("SolAdjuster", "RF Protection", None))
        self.degauss_sol_0.setText(_translate("SolAdjuster", "Degauss SOL to zero", None))
        self.degauss_bsol_0.setText(_translate("SolAdjuster", "Degauss BSOL to zero", None))
        self.degauss_sol.setText(_translate("SolAdjuster", "Degauss SOL and reset current ", None))
        self.degauss_bsol.setText(_translate("SolAdjuster", "Degauss BSOL and reset current ", None))
        self.groupBox_2.setTitle(_translate("SolAdjuster", "Bucking Solenoid", None))
        self.BSol_PSU_State.setText(_translate("SolAdjuster", "ERR", None))
        self.label_6.setText(_translate("SolAdjuster", "Step Size", None))
        self.label_5.setText(_translate("SolAdjuster", "Set Value", None))
        self.groupBox_3.setTitle(_translate("SolAdjuster", "Main Solenoid", None))
        self.Sol_PSU_State.setText(_translate("SolAdjuster", "ERR", None))
        self.label_7.setText(_translate("SolAdjuster", "Step Size", None))
        self.label_8.setText(_translate("SolAdjuster", "Set Value", None))

