# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(250, 445)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("resources/rawImageViewer/icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox_showBVNFit = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_showBVNFit.setObjectName(_fromUtf8("checkBox_showBVNFit"))
        self.gridLayout.addWidget(self.checkBox_showBVNFit, 5, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 19, 0, 1, 3)
        self.pushButton_loadImage = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_loadImage.sizePolicy().hasHeightForWidth())
        self.pushButton_loadImage.setSizePolicy(sizePolicy)
        self.pushButton_loadImage.setObjectName(_fromUtf8("pushButton_loadImage"))
        self.gridLayout.addWidget(self.pushButton_loadImage, 0, 0, 1, 3)
        self.pushButton_loadBkgrnd = QtGui.QPushButton(self.centralwidget)
        self.pushButton_loadBkgrnd.setObjectName(_fromUtf8("pushButton_loadBkgrnd"))
        self.gridLayout.addWidget(self.pushButton_loadBkgrnd, 1, 0, 1, 3)
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 25, 0, 1, 1)
        self.label_cxyMLE = QtGui.QLabel(self.centralwidget)
        self.label_cxyMLE.setObjectName(_fromUtf8("label_cxyMLE"))
        self.gridLayout.addWidget(self.label_cxyMLE, 26, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 24, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 26, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 22, 0, 1, 1)
        self.checkBox_showMLEFit = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_showMLEFit.setObjectName(_fromUtf8("checkBox_showMLEFit"))
        self.gridLayout.addWidget(self.checkBox_showMLEFit, 6, 0, 1, 1)
        self.label_cxyBVN = QtGui.QLabel(self.centralwidget)
        self.label_cxyBVN.setObjectName(_fromUtf8("label_cxyBVN"))
        self.gridLayout.addWidget(self.label_cxyBVN, 26, 1, 1, 1)
        self.label_sxBVN = QtGui.QLabel(self.centralwidget)
        self.label_sxBVN.setObjectName(_fromUtf8("label_sxBVN"))
        self.gridLayout.addWidget(self.label_sxBVN, 24, 1, 1, 1)
        self.pushButton_analyse = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_analyse.sizePolicy().hasHeightForWidth())
        self.pushButton_analyse.setSizePolicy(sizePolicy)
        self.pushButton_analyse.setObjectName(_fromUtf8("pushButton_analyse"))
        self.gridLayout.addWidget(self.pushButton_analyse, 4, 0, 1, 3)
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 23, 0, 1, 1)
        self.label_syMLE = QtGui.QLabel(self.centralwidget)
        self.label_syMLE.setObjectName(_fromUtf8("label_syMLE"))
        self.gridLayout.addWidget(self.label_syMLE, 25, 2, 1, 1)
        self.label_sxMLE = QtGui.QLabel(self.centralwidget)
        self.label_sxMLE.setObjectName(_fromUtf8("label_sxMLE"))
        self.gridLayout.addWidget(self.label_sxMLE, 24, 2, 1, 1)
        self.label_syBVN = QtGui.QLabel(self.centralwidget)
        self.label_syBVN.setObjectName(_fromUtf8("label_syBVN"))
        self.gridLayout.addWidget(self.label_syBVN, 25, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 21, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 21, 2, 1, 1)
        self.label_xMLE = QtGui.QLabel(self.centralwidget)
        self.label_xMLE.setObjectName(_fromUtf8("label_xMLE"))
        self.gridLayout.addWidget(self.label_xMLE, 22, 2, 1, 1)
        self.label_xBVN = QtGui.QLabel(self.centralwidget)
        self.label_xBVN.setObjectName(_fromUtf8("label_xBVN"))
        self.gridLayout.addWidget(self.label_xBVN, 22, 1, 1, 1)
        self.label_yBVN = QtGui.QLabel(self.centralwidget)
        self.label_yBVN.setObjectName(_fromUtf8("label_yBVN"))
        self.gridLayout.addWidget(self.label_yBVN, 23, 1, 1, 1)
        self.label_yMLE = QtGui.QLabel(self.centralwidget)
        self.label_yMLE.setObjectName(_fromUtf8("label_yMLE"))
        self.gridLayout.addWidget(self.label_yMLE, 23, 2, 1, 1)
        self.checkBox_useBackground = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_useBackground.setObjectName(_fromUtf8("checkBox_useBackground"))
        self.gridLayout.addWidget(self.checkBox_useBackground, 2, 0, 1, 1)
        self.checkBox_useManuaCrop = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_useManuaCrop.setObjectName(_fromUtf8("checkBox_useManuaCrop"))
        self.gridLayout.addWidget(self.checkBox_useManuaCrop, 3, 0, 1, 1)
        self.checkBox_showSaturatedPixels = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_showSaturatedPixels.setObjectName(_fromUtf8("checkBox_showSaturatedPixels"))
        self.gridLayout.addWidget(self.checkBox_showSaturatedPixels, 7, 0, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 8, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 8, 1, 1, 2)
        self.spinBox_max = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_max.setMaximum(65535)
        self.spinBox_max.setProperty("value", 65535)
        self.spinBox_max.setObjectName(_fromUtf8("spinBox_max"))
        self.gridLayout.addWidget(self.spinBox_max, 9, 1, 1, 2)
        self.spinBox_min = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_min.setMaximum(65535)
        self.spinBox_min.setObjectName(_fromUtf8("spinBox_min"))
        self.gridLayout.addWidget(self.spinBox_min, 9, 0, 1, 1)
        self.pushButton_expertSettings = QtGui.QPushButton(self.centralwidget)
        self.pushButton_expertSettings.setObjectName(_fromUtf8("pushButton_expertSettings"))
        self.gridLayout.addWidget(self.pushButton_expertSettings, 18, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSingle = QtGui.QAction(MainWindow)
        self.actionSingle.setObjectName(_fromUtf8("actionSingle"))
        self.actionBatch = QtGui.QAction(MainWindow)
        self.actionBatch.setObjectName(_fromUtf8("actionBatch"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Raw Image Viewer", None))
        self.checkBox_showBVNFit.setText(_translate("MainWindow", "Show Bivariant Normal Fit", None))
        self.label_3.setText(_translate("MainWindow", "Results", None))
        self.pushButton_loadImage.setText(_translate("MainWindow", "Load Image", None))
        self.pushButton_loadBkgrnd.setText(_translate("MainWindow", "Load Background", None))
        self.label_19.setText(_translate("MainWindow", "SigmaY:", None))
        self.label_cxyMLE.setText(_translate("MainWindow", "--", None))
        self.label_18.setText(_translate("MainWindow", "Sigma X:", None))
        self.label_20.setText(_translate("MainWindow", "Covariance XY:", None))
        self.label_16.setText(_translate("MainWindow", "X Position:", None))
        self.checkBox_showMLEFit.setText(_translate("MainWindow", "Show MLE Fit", None))
        self.label_cxyBVN.setText(_translate("MainWindow", "--", None))
        self.label_sxBVN.setText(_translate("MainWindow", "--", None))
        self.pushButton_analyse.setText(_translate("MainWindow", "Analyse", None))
        self.label_17.setText(_translate("MainWindow", "Y Position:", None))
        self.label_syMLE.setText(_translate("MainWindow", "--", None))
        self.label_sxMLE.setText(_translate("MainWindow", "--", None))
        self.label_syBVN.setText(_translate("MainWindow", "--", None))
        self.label_4.setText(_translate("MainWindow", "BVN", None))
        self.label_5.setText(_translate("MainWindow", "MLE", None))
        self.label_xMLE.setText(_translate("MainWindow", "--", None))
        self.label_xBVN.setText(_translate("MainWindow", "--", None))
        self.label_yBVN.setText(_translate("MainWindow", "--", None))
        self.label_yMLE.setText(_translate("MainWindow", "--", None))
        self.checkBox_useBackground.setText(_translate("MainWindow", "Use Background Image", None))
        self.checkBox_useManuaCrop.setText(_translate("MainWindow", "Use Manual Crop", None))
        self.checkBox_showSaturatedPixels.setText(_translate("MainWindow", "Show Saturated Pixels", None))
        self.label.setText(_translate("MainWindow", "Min. Level:", None))
        self.label_2.setText(_translate("MainWindow", "Max.Level:", None))
        self.pushButton_expertSettings.setText(_translate("MainWindow", "Expert Settings", None))
        self.actionSingle.setText(_translate("MainWindow", "Single", None))
        self.actionBatch.setText(_translate("MainWindow", "Batch", None))

