# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1040, 530)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../Resources/Icons/mountain-summit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.centralWidgetLayout = QtGui.QGridLayout(self.centralwidget)
        self.centralWidgetLayout.setObjectName(_fromUtf8("centralWidgetLayout"))
        self.widget_3 = QtGui.QWidget(self.centralwidget)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_MODE = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_MODE.sizePolicy().hasHeightForWidth())
        self.label_MODE.setSizePolicy(sizePolicy)
        self.label_MODE.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_MODE.setObjectName(_fromUtf8("label_MODE"))
        self.horizontalLayout.addWidget(self.label_MODE)
        self.finishButton = QtGui.QPushButton(self.widget_3)
        self.finishButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.finishButton.setObjectName(_fromUtf8("finishButton"))
        self.horizontalLayout.addWidget(self.finishButton)
        self.abortButton = QtGui.QPushButton(self.widget_3)
        self.abortButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.abortButton.setAutoFillBackground(False)
        self.abortButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.abortButton.setIcon(icon1)
        self.abortButton.setObjectName(_fromUtf8("abortButton"))
        self.horizontalLayout.addWidget(self.abortButton)
        self.centralWidgetLayout.addWidget(self.widget_3, 1, 0, 1, 1)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_5)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.approxStepSetCorrector = QtGui.QLineEdit(self.groupBox_5)
        self.approxStepSetCorrector.setObjectName(_fromUtf8("approxStepSetCorrector"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.approxStepSetCorrector)
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.fineStepSetCorrector = QtGui.QLineEdit(self.groupBox_5)
        self.fineStepSetCorrector.setObjectName(_fromUtf8("fineStepSetCorrector"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.fineStepSetCorrector)
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.rangeSetCorrector = QtGui.QLineEdit(self.groupBox_5)
        self.rangeSetCorrector.setObjectName(_fromUtf8("rangeSetCorrector"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.rangeSetCorrector)
        self.horizontalLayout_2.addWidget(self.groupBox_5)
        self.groupBox = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.nSamples = QtGui.QLineEdit(self.groupBox)
        self.nSamples.setObjectName(_fromUtf8("nSamples"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.nSamples)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.centralWidgetLayout.addWidget(self.widget, 2, 0, 2, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.linacTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linacTab.sizePolicy().hasHeightForWidth())
        self.linacTab.setSizePolicy(sizePolicy)
        self.linacTab.setObjectName(_fromUtf8("linacTab"))
        self.linacTabLayout = QtGui.QGridLayout(self.linacTab)
        self.linacTabLayout.setObjectName(_fromUtf8("linacTabLayout"))
        self.groupBox_plotsLinac1 = QtGui.QGroupBox(self.linacTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_plotsLinac1.sizePolicy().hasHeightForWidth())
        self.groupBox_plotsLinac1.setSizePolicy(sizePolicy)
        self.groupBox_plotsLinac1.setObjectName(_fromUtf8("groupBox_plotsLinac1"))
        self.plotLayoutLinac1 = QtGui.QHBoxLayout(self.groupBox_plotsLinac1)
        self.plotLayoutLinac1.setObjectName(_fromUtf8("plotLayoutLinac1"))
        self.linacTabLayout.addWidget(self.groupBox_plotsLinac1, 0, 1, 6, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.linacTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(150, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.linac1LowerSet = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linac1LowerSet.sizePolicy().hasHeightForWidth())
        self.linac1LowerSet.setSizePolicy(sizePolicy)
        self.linac1LowerSet.setObjectName(_fromUtf8("linac1LowerSet"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.linac1LowerSet)
        self.label = QtGui.QLabel(self.groupBox_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.linac1UpperSet = QtGui.QLineEdit(self.groupBox_4)
        self.linac1UpperSet.setObjectName(_fromUtf8("linac1UpperSet"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.linac1UpperSet)
        self.linacTabLayout.addWidget(self.groupBox_4, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.linacTabLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.groupBox_methodLinac1 = QtGui.QGroupBox(self.linacTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_methodLinac1.sizePolicy().hasHeightForWidth())
        self.groupBox_methodLinac1.setSizePolicy(sizePolicy)
        self.groupBox_methodLinac1.setObjectName(_fromUtf8("groupBox_methodLinac1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_methodLinac1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.linac1StartRoughScanButton = QtGui.QPushButton(self.groupBox_methodLinac1)
        self.linac1StartRoughScanButton.setObjectName(_fromUtf8("linac1StartRoughScanButton"))
        self.verticalLayout_4.addWidget(self.linac1StartRoughScanButton)
        self.linac1StartFineScanButton = QtGui.QPushButton(self.groupBox_methodLinac1)
        self.linac1StartFineScanButton.setObjectName(_fromUtf8("linac1StartFineScanButton"))
        self.verticalLayout_4.addWidget(self.linac1StartFineScanButton)
        self.linacTabLayout.addWidget(self.groupBox_methodLinac1, 1, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/bike.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.linacTab, icon2, _fromUtf8(""))
        self.SOL1Tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SOL1Tab.sizePolicy().hasHeightForWidth())
        self.SOL1Tab.setSizePolicy(sizePolicy)
        self.SOL1Tab.setObjectName(_fromUtf8("SOL1Tab"))
        self.gridLayout = QtGui.QGridLayout(self.SOL1Tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.SOL1Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setMinimumSize(QtCore.QSize(150, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.sol1LowerSet = QtGui.QLineEdit(self.groupBox_2)
        self.sol1LowerSet.setObjectName(_fromUtf8("sol1LowerSet"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.sol1LowerSet)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.sol1UpperSet = QtGui.QLineEdit(self.groupBox_2)
        self.sol1UpperSet.setObjectName(_fromUtf8("sol1UpperSet"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.sol1UpperSet)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.SOL1Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.sol1XStartRoughScanButton = QtGui.QPushButton(self.groupBox_6)
        self.sol1XStartRoughScanButton.setObjectName(_fromUtf8("sol1XStartRoughScanButton"))
        self.verticalLayout.addWidget(self.sol1XStartRoughScanButton)
        self.sol1YStartRoughScanButton = QtGui.QPushButton(self.groupBox_6)
        self.sol1YStartRoughScanButton.setObjectName(_fromUtf8("sol1YStartRoughScanButton"))
        self.verticalLayout.addWidget(self.sol1YStartRoughScanButton)
        self.gridLayout.addWidget(self.groupBox_6, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.groupBox_plotsSol1 = QtGui.QGroupBox(self.SOL1Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_plotsSol1.sizePolicy().hasHeightForWidth())
        self.groupBox_plotsSol1.setSizePolicy(sizePolicy)
        self.groupBox_plotsSol1.setObjectName(_fromUtf8("groupBox_plotsSol1"))
        self.plotLayoutSOL1 = QtGui.QHBoxLayout(self.groupBox_plotsSol1)
        self.plotLayoutSOL1.setObjectName(_fromUtf8("plotLayoutSOL1"))
        self.gridLayout.addWidget(self.groupBox_plotsSol1, 0, 1, 3, 1)
        self.tabWidget.addTab(self.SOL1Tab, _fromUtf8(""))
        self.SOL2Tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SOL2Tab.sizePolicy().hasHeightForWidth())
        self.SOL2Tab.setSizePolicy(sizePolicy)
        self.SOL2Tab.setObjectName(_fromUtf8("SOL2Tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.SOL2Tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.SOL2Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout_5 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setMinimumSize(QtCore.QSize(150, 0))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.sol2LowerSet = QtGui.QLineEdit(self.groupBox_3)
        self.sol2LowerSet.setObjectName(_fromUtf8("sol2LowerSet"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.sol2LowerSet)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.sol2UpperSet = QtGui.QLineEdit(self.groupBox_3)
        self.sol2UpperSet.setObjectName(_fromUtf8("sol2UpperSet"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.sol2UpperSet)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.SOL2Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.sol2XStartRoughScanButton = QtGui.QPushButton(self.groupBox_7)
        self.sol2XStartRoughScanButton.setObjectName(_fromUtf8("sol2XStartRoughScanButton"))
        self.verticalLayout_2.addWidget(self.sol2XStartRoughScanButton)
        self.sol2YStartRoughScanButton = QtGui.QPushButton(self.groupBox_7)
        self.sol2YStartRoughScanButton.setObjectName(_fromUtf8("sol2YStartRoughScanButton"))
        self.verticalLayout_2.addWidget(self.sol2YStartRoughScanButton)
        self.gridLayout_2.addWidget(self.groupBox_7, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 2, 0, 1, 1)
        self.groupBox_plotsSol2 = QtGui.QGroupBox(self.SOL2Tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_plotsSol2.sizePolicy().hasHeightForWidth())
        self.groupBox_plotsSol2.setSizePolicy(sizePolicy)
        self.groupBox_plotsSol2.setObjectName(_fromUtf8("groupBox_plotsSol2"))
        self.plotLayoutSOL2 = QtGui.QHBoxLayout(self.groupBox_plotsSol2)
        self.plotLayoutSOL2.setObjectName(_fromUtf8("plotLayoutSOL2"))
        self.gridLayout_2.addWidget(self.groupBox_plotsSol2, 0, 1, 3, 1)
        self.tabWidget.addTab(self.SOL2Tab, _fromUtf8(""))
        self.logTab = QtGui.QWidget()
        self.logTab.setObjectName(_fromUtf8("logTab"))
        self.logTabLayout = QtGui.QVBoxLayout(self.logTab)
        self.logTabLayout.setObjectName(_fromUtf8("logTabLayout"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/log.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.logTab, icon3, _fromUtf8(""))
        self.centralWidgetLayout.addWidget(self.tabWidget, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1040, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_Calibation_Data = QtGui.QAction(MainWindow)
        self.actionSave_Calibation_Data.setObjectName(_fromUtf8("actionSave_Calibation_Data"))
        self.menuFile.addAction(self.actionSave_Calibation_Data)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Phase Calibration", None))
        self.label_MODE.setText(_translate("MainWindow", "Mode", None))
        self.finishButton.setText(_translate("MainWindow", "Finish Scan", None))
        self.abortButton.setText(_translate("MainWindow", "Abort", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Corrector Settings", None))
        self.label_8.setText(_translate("MainWindow", "Approx. StepSize (A)", None))
        self.approxStepSetCorrector.setText(_translate("MainWindow", "1", None))
        self.label_2.setText(_translate("MainWindow", "Fine StepSize (A)", None))
        self.fineStepSetCorrector.setText(_translate("MainWindow", "0.1", None))
        self.label_9.setText(_translate("MainWindow", "Range (A) ±", None))
        self.rangeSetCorrector.setText(_translate("MainWindow", "5", None))
        self.groupBox.setTitle(_translate("MainWindow", "BPM Settings", None))
        self.label_3.setText(_translate("MainWindow", "BPM Samples", None))
        self.nSamples.setText(_translate("MainWindow", "10", None))
        self.groupBox_plotsLinac1.setTitle(_translate("MainWindow", "Corrector Steering", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Linac Settings", None))
        self.label_6.setText(_translate("MainWindow", "Lower Amplitude", None))
        self.linac1LowerSet.setText(_translate("MainWindow", "3500", None))
        self.label.setText(_translate("MainWindow", "Upper Amplitude", None))
        self.linac1UpperSet.setText(_translate("MainWindow", "12000", None))
        self.groupBox_methodLinac1.setTitle(_translate("MainWindow", "Method", None))
        self.linac1StartRoughScanButton.setText(_translate("MainWindow", "Scan RF centre (Approx)", None))
        self.linac1StartFineScanButton.setText(_translate("MainWindow", "Scan RF centre (Fine)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.linacTab), _translate("MainWindow", "Linac 1", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Solenoid Settings", None))
        self.label_4.setText(_translate("MainWindow", "Lower", None))
        self.sol1LowerSet.setText(_translate("MainWindow", "0", None))
        self.label_5.setText(_translate("MainWindow", "Upper", None))
        self.sol1UpperSet.setText(_translate("MainWindow", "50", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Method", None))
        self.sol1XStartRoughScanButton.setText(_translate("MainWindow", "Scan SOL centre (Approx) - HORIZONTAL", None))
        self.sol1YStartRoughScanButton.setText(_translate("MainWindow", "Scan SOL centre (Approx) - VERTICAL", None))
        self.groupBox_plotsSol1.setTitle(_translate("MainWindow", "Plots", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SOL1Tab), _translate("MainWindow", "SOL1", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Solenoid Settings", None))
        self.label_7.setText(_translate("MainWindow", "Lower", None))
        self.sol2LowerSet.setText(_translate("MainWindow", "0", None))
        self.label_10.setText(_translate("MainWindow", "Upper", None))
        self.sol2UpperSet.setText(_translate("MainWindow", "50", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Method", None))
        self.sol2XStartRoughScanButton.setText(_translate("MainWindow", "Scan SOL centre (Approx) - HORIZONTAL", None))
        self.sol2YStartRoughScanButton.setText(_translate("MainWindow", "Scan SOL centre (Approx) - VERTICAL", None))
        self.groupBox_plotsSol2.setTitle(_translate("MainWindow", "Plots", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SOL2Tab), _translate("MainWindow", "SOL2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logTab), _translate("MainWindow", "Log", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionSave_Calibation_Data.setText(_translate("MainWindow", "Save Calibation Data", None))

