# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled1.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import pyqtgraph

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        self.TabWidget = TabWidget
        self.TabWidget.setObjectName(_fromUtf8("BPM Master App"))
        self.TabWidget.resize(699, 602)
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.mainBox = QtGui.QHBoxLayout(self.tab)
        self.labelBox = QtGui.QVBoxLayout()
        self.midVBox = QtGui.QVBoxLayout()
        self.appListVBox = QtGui.QVBoxLayout()
        self.launchATTButton = QtGui.QPushButton()
        self.launchATTButton.setObjectName(_fromUtf8("launchATTButton"))
        self.launchDLYButton = QtGui.QPushButton()
        self.launchDLYButton.setObjectName(_fromUtf8("launchDLYButton"))
        self.launchTrajButton = QtGui.QPushButton()
        self.launchTrajButton.setObjectName(_fromUtf8("launchTrajButton"))
        self.launchMonButton = QtGui.QPushButton()
        self.launchMonButton.setObjectName(_fromUtf8("launchMonButton"))
        self.launchATTButton.setMinimumSize(QtCore.QSize(100,100))
        self.launchDLYButton.setMinimumSize(QtCore.QSize(100,100))
        self.launchTrajButton.setMinimumSize(QtCore.QSize(100,100))
        self.launchMonButton.setMinimumSize(QtCore.QSize(100,100))
        self.appListVBox.addWidget(self.launchATTButton)
        self.appListVBox.addWidget(self.launchDLYButton)
        self.appListVBox.addWidget(self.launchTrajButton)
        self.appListVBox.addWidget(self.launchMonButton)
        self.beamlineButton = QtGui.QGroupBox()
        self.beamlineButton.setObjectName(_fromUtf8("beamlineButton"))
        self.velaINJButton = QtGui.QRadioButton(self.beamlineButton)
        self.velaINJButton.setObjectName(_fromUtf8("velaINJButton"))
        self.velaBA1Button = QtGui.QRadioButton(self.beamlineButton)
        self.velaBA1Button.setObjectName(_fromUtf8("velaBA1Button"))
        self.velaBA2Button = QtGui.QRadioButton(self.beamlineButton)
        self.velaBA2Button.setObjectName(_fromUtf8("velaBA2Button"))
        self.claraButton = QtGui.QRadioButton(self.beamlineButton)
        self.claraButton.setObjectName(_fromUtf8("claraPH1Button"))
        self.c2vButton = QtGui.QRadioButton(self.beamlineButton)
        self.c2vButton.setObjectName(_fromUtf8("c2vButton"))
        self.radioButtonVBoxLayout = QtGui.QVBoxLayout(self.tab)
        self.radioButtonVBoxLayout.setObjectName(_fromUtf8("radioButtonVBoxLayout"))
        self.velaINJButton.setAutoExclusive(True)
        self.velaINJButton.setCheckable(True)
        self.velaBA1Button.setAutoExclusive(True)
        self.velaBA1Button.setCheckable(True)
        self.velaBA2Button.setAutoExclusive(True)
        self.velaBA2Button.setCheckable(True)
        self.claraButton.setAutoExclusive(True)
        self.claraButton.setCheckable(True)
        self.c2vButton.setAutoExclusive(True)
        self.c2vButton.setCheckable(True)
        self.radioButtonVBoxLayout.addWidget(self.velaINJButton)
        self.radioButtonVBoxLayout.addWidget(self.velaBA1Button)
        self.radioButtonVBoxLayout.addWidget(self.velaBA2Button)
        self.radioButtonVBoxLayout.addWidget(self.claraButton)
        self.radioButtonVBoxLayout.addWidget(self.c2vButton)
        self.beamlineButton.setLayout(self.radioButtonVBoxLayout)
        self.velaINJButton.setChecked(True)
        self.matrixButton = QtGui.QGroupBox(self.tab)
        self.matrixButton.setObjectName(_fromUtf8("matrixButton"))
        self.controllerTypeVBoxLayout = QtGui.QVBoxLayout(self.tab)
        self.controllerTypeVBoxLayout.setObjectName(_fromUtf8("controllerTypeVBoxLayout"))
        self.physicalButton = QtGui.QRadioButton(self.matrixButton)
        self.physicalButton.setObjectName(_fromUtf8("physicalButton"))
        self.virtualButton = QtGui.QRadioButton(self.matrixButton)
        self.virtualButton.setObjectName(_fromUtf8("virtualButton"))
        self.offlineButton = QtGui.QRadioButton(self.matrixButton)
        self.offlineButton.setObjectName(_fromUtf8("offlineButton"))
        self.controllerTypeVBoxLayout.addWidget(self.physicalButton)
        self.controllerTypeVBoxLayout.addWidget(self.virtualButton)
        self.controllerTypeVBoxLayout.addWidget(self.offlineButton)
        self.matrixButton.setLayout(self.controllerTypeVBoxLayout)
        self.physicalButton.setAutoExclusive(True)
        self.physicalButton.setCheckable(True)
        self.virtualButton.setAutoExclusive(True)
        self.virtualButton.setCheckable(True)
        self.offlineButton.setAutoExclusive(True)
        self.offlineButton.setCheckable(True)
        self.virtualButton.setChecked(True)
        self.midVBox.addWidget(self.beamlineButton)
        self.midVBox.addWidget(self.matrixButton)
        self.iconLabel = QtGui.QLabel(self.tab)
        self.appPixMap = QtGui.QPixmap("bpmSchematic.jpg")
        self.iconLabel.setPixmap(self.appPixMap)
        self.titleLabel = QtGui.QLabel()
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.infoLabel = QtGui.QLabel()
        self.infoLabel.setObjectName(_fromUtf8("infoLabel"))
        self.dialogBox = QtGui.QLabel()
        self.dialogBox.setObjectName(_fromUtf8("dialogBox"))
        self.randomVariableHBox = QtGui.QHBoxLayout()
        self.randomVariableCheckBox = QtGui.QCheckBox()
        self.randomVariableCheckBox.setObjectName(_fromUtf8("randomVariableCheckBox"))
        self.randomVariableCheckBox.setAutoExclusive(True)
        self.randomVariableCheckBox.setCheckable(True)
        self.randomVariableLabel = QtGui.QLabel()
        self.randomVariableLabel.setObjectName(_fromUtf8("randomVariableLabel"))
        self.randomVariableButton = QtGui.QPushButton()
        self.randomVariableButton.setObjectName(_fromUtf8("randomVariableButton"))
        self.repRateHBox = QtGui.QHBoxLayout()
        self.repRateValue = QtGui.QPlainTextEdit()
        self.repRateValue.setObjectName(_fromUtf8("repRateValue"))
        self.repRateValue.setMaximumSize(QtCore.QSize(50,30))
        self.repRateLabel = QtGui.QLabel()
        self.repRateLabel.setObjectName(_fromUtf8("repRateLabel"))
        self.repRateHBox.addWidget(self.repRateLabel)
        self.repRateHBox.addWidget(self.repRateValue)
        self.repRateHBox.addStretch()
        self.randomVariableHBox.addWidget(self.randomVariableLabel)
        self.randomVariableHBox.addWidget(self.randomVariableCheckBox)
        self.randomVariableHBox.addWidget(self.randomVariableButton)
        self.randomVariableHBox.addStretch()
        #self.bottomVBox = QtGui.QVBoxLayout()
        #self.bottomVBox.addLayout(self.repRateHBox)
        #self.bottomVBox.addLayout(self.randomVariableHBox)
        self.labelBox.addWidget(self.titleLabel)
        self.labelBox.addWidget(self.infoLabel)
        self.labelBox.addWidget(self.dialogBox)
        self.labelBox.addLayout(self.repRateHBox)
        self.labelBox.addLayout(self.randomVariableHBox)
        self.mainBox.addLayout(self.labelBox)
        self.mainBox.addLayout(self.midVBox)
        self.mainBox.addLayout(self.appListVBox)
        self.TabWidget.addTab(self.tab, _fromUtf8(""))

        self.retranslateUi(self.TabWidget)
        QtCore.QMetaObject.connectSlotsByName(self.TabWidget)

    def retranslateUi(self, TabWidget):
        self.TabWidget.setWindowTitle(_translate("TabWidget", "BPM Master App", None))
        self.launchATTButton.setText(_translate("TabWidget", "Calibrate Attenuation", None))
        self.launchDLYButton.setText(_translate("TabWidget", "Calibrate Delays", None))
        self.launchTrajButton.setText(_translate("TabWidget", "Trajectory Plot", None))
        self.launchMonButton.setText(_translate("TabWidget", "Monitor GUI", None))
        self.beamlineButton.setTitle(_translate("MainWindow", "Choose Beamline", None))
        self.velaINJButton.setText(_translate("MainWindow", "VELA-INJ", None))
        self.velaBA1Button.setText(_translate("MainWindow", "VELA-BA1", None))
        self.velaBA2Button.setText(_translate("MainWindow", "VELA-BA2", None))
        self.claraButton.setText(_translate("MainWindow", "CLARA PH1", None))
        #self.iconLabel.setText(_translate("MainWindow", "iconLabel", None))
        self.c2vButton.setText(_translate("MainWindow", "CLARA-2-VELA", None))
        self.matrixButton.setTitle(_translate("MainWindow", "Choose Controller Type", None))
        self.physicalButton.setText(_translate("MainWindow", "Physical", None))
        self.virtualButton.setText(_translate("MainWindow", "Virtual", None))
        self.offlineButton.setText(_translate("MainWindow", "Offline", None))
        self.newFont = QtGui.QFont("Comic Sans", 20, QtGui.QFont.Bold)
        self.titleLabel.setFont(self.newFont)
        self.titleLabel.setText(_translate("TabWidget", "VELA/CLARA Beam \nPosition Monitor \nMaster App", None))
        self.infoText = "All applications related to calibrating and monitoring \nBPMs can be found here. First choose the beamline"
        self.infoText2 = self.infoText+"\nto initialise the controllers, and the controller type - "
        self.infoText3 = self.infoText2+"\nphysical, virtual or offline. Then select the app you \nwould like to launch using the buttons."
        self.infoLabel.setText(_translate("TabWidget", self.infoText3, None))
        self.randomVariableLabel.setText(_translate("TabWidget", "Set random PVs?", None))
        self.randomVariableButton.setText(_translate("TabWidget", "Go", None))
        self.repRateLabel.setText(_translate("TabWidget", "Set repetition rate", None))
        self.repRateValue.setPlainText(_translate("TabWidget", "1", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.tab), _translate("TabWidget", "BPM Master", None))
