# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_v2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(973, 947)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("resources/imageCollector/icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.left_panel = QtGui.QVBoxLayout()
        self.left_panel.setObjectName(_fromUtf8("left_panel"))
        self.cameras_treeview = QtGui.QTreeView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameras_treeview.sizePolicy().hasHeightForWidth())
        self.cameras_treeview.setSizePolicy(sizePolicy)
        self.cameras_treeview.setMaximumSize(QtCore.QSize(161, 16777215))
        self.cameras_treeview.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.cameras_treeview.setIndentation(10)
        self.cameras_treeview.setRootIsDecorated(False)
        self.cameras_treeview.setHeaderHidden(True)
        self.cameras_treeview.setObjectName(_fromUtf8("cameras_treeview"))
        self.left_panel.addWidget(self.cameras_treeview)
        self.live_stream_label = QtGui.QLabel(self.centralwidget)
        self.live_stream_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.live_stream_label.setObjectName(_fromUtf8("live_stream_label"))
        self.left_panel.addWidget(self.live_stream_label)
        self.leds_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.leds_checkbox.setObjectName(_fromUtf8("leds_checkbox"))
        self.left_panel.addWidget(self.leds_checkbox)
        self.screen_hbox = QtGui.QHBoxLayout()
        self.screen_hbox.setObjectName(_fromUtf8("screen_hbox"))
        self.screen_label = QtGui.QLabel(self.centralwidget)
        self.screen_label.setObjectName(_fromUtf8("screen_label"))
        self.screen_hbox.addWidget(self.screen_label)
        self.screen_in_button = QtGui.QToolButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("resources/imageCollector/in.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.screen_in_button.setIcon(icon1)
        self.screen_in_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.screen_in_button.setObjectName(_fromUtf8("screen_in_button"))
        self.screen_hbox.addWidget(self.screen_in_button)
        self.screen_out_button = QtGui.QToolButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("resources/imageCollector/out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.screen_out_button.setIcon(icon2)
        self.screen_out_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.screen_out_button.setObjectName(_fromUtf8("screen_out_button"))
        self.screen_hbox.addWidget(self.screen_out_button)
        self.left_panel.addLayout(self.screen_hbox)
        self.screen_progress = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.screen_progress.sizePolicy().hasHeightForWidth())
        self.screen_progress.setSizePolicy(sizePolicy)
        self.screen_progress.setMinimumSize(QtCore.QSize(105, 0))
        self.screen_progress.setProperty("value", 100)
        self.screen_progress.setAlignment(QtCore.Qt.AlignCenter)
        self.screen_progress.setTextVisible(True)
        self.screen_progress.setObjectName(_fromUtf8("screen_progress"))
        self.left_panel.addWidget(self.screen_progress)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.left_panel.addWidget(self.line)
        self.colour_map_hbox = QtGui.QHBoxLayout()
        self.colour_map_hbox.setObjectName(_fromUtf8("colour_map_hbox"))
        self.colour_map_label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colour_map_label.sizePolicy().hasHeightForWidth())
        self.colour_map_label.setSizePolicy(sizePolicy)
        self.colour_map_label.setObjectName(_fromUtf8("colour_map_label"))
        self.colour_map_hbox.addWidget(self.colour_map_label)
        self.colour_map_dropdown = QtGui.QComboBox(self.centralwidget)
        self.colour_map_dropdown.setObjectName(_fromUtf8("colour_map_dropdown"))
        self.colour_map_hbox.addWidget(self.colour_map_dropdown)
        self.left_panel.addLayout(self.colour_map_hbox)
        self.level_auto_hbox = QtGui.QHBoxLayout()
        self.level_auto_hbox.setObjectName(_fromUtf8("level_auto_hbox"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.level_auto_hbox.addWidget(self.label_3)
        self.auto_level_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.auto_level_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.auto_level_checkbox.setObjectName(_fromUtf8("auto_level_checkbox"))
        self.level_auto_hbox.addWidget(self.auto_level_checkbox)
        self.left_panel.addLayout(self.level_auto_hbox)
        self.level_ctrl_hbox = QtGui.QHBoxLayout()
        self.level_ctrl_hbox.setObjectName(_fromUtf8("level_ctrl_hbox"))
        self.max_level_slider = QtGui.QSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_level_slider.sizePolicy().hasHeightForWidth())
        self.max_level_slider.setSizePolicy(sizePolicy)
        self.max_level_slider.setMinimum(1)
        self.max_level_slider.setMaximum(16)
        self.max_level_slider.setProperty("value", 10)
        self.max_level_slider.setOrientation(QtCore.Qt.Horizontal)
        self.max_level_slider.setObjectName(_fromUtf8("max_level_slider"))
        self.level_ctrl_hbox.addWidget(self.max_level_slider)
        self.max_level_spin = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_level_spin.sizePolicy().hasHeightForWidth())
        self.max_level_spin.setSizePolicy(sizePolicy)
        self.max_level_spin.setMinimum(1)
        self.max_level_spin.setMaximum(65535)
        self.max_level_spin.setSingleStep(1000)
        self.max_level_spin.setProperty("value", 1023)
        self.max_level_spin.setObjectName(_fromUtf8("max_level_spin"))
        self.level_ctrl_hbox.addWidget(self.max_level_spin)
        self.left_panel.addLayout(self.level_ctrl_hbox)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.left_panel.addWidget(self.line_2)
        self.save_hbox = QtGui.QHBoxLayout()
        self.save_hbox.setObjectName(_fromUtf8("save_hbox"))
        self.save_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_pushButton.sizePolicy().hasHeightForWidth())
        self.save_pushButton.setSizePolicy(sizePolicy)
        self.save_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.save_pushButton.setObjectName(_fromUtf8("save_pushButton"))
        self.save_hbox.addWidget(self.save_pushButton)
        self.numImages_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.numImages_spinBox.setMinimum(1)
        self.numImages_spinBox.setObjectName(_fromUtf8("numImages_spinBox"))
        self.save_hbox.addWidget(self.numImages_spinBox)
        self.numImages_label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numImages_label.sizePolicy().hasHeightForWidth())
        self.numImages_label.setSizePolicy(sizePolicy)
        self.numImages_label.setObjectName(_fromUtf8("numImages_label"))
        self.save_hbox.addWidget(self.numImages_label)
        self.left_panel.addLayout(self.save_hbox)
        self.image_folder_label = QtGui.QLabel(self.centralwidget)
        self.image_folder_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.image_folder_label.setObjectName(_fromUtf8("image_folder_label"))
        self.left_panel.addWidget(self.image_folder_label)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.left_panel.addWidget(self.line_3)
        self.resetBackground_pushButton = QtGui.QPushButton(self.centralwidget)
        self.resetBackground_pushButton.setObjectName(_fromUtf8("resetBackground_pushButton"))
        self.left_panel.addWidget(self.resetBackground_pushButton)
        self.useBackground_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.useBackground_checkBox.setObjectName(_fromUtf8("useBackground_checkBox"))
        self.left_panel.addWidget(self.useBackground_checkBox)
        self.useNPoint_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.useNPoint_checkBox.setObjectName(_fromUtf8("useNPoint_checkBox"))
        self.left_panel.addWidget(self.useNPoint_checkBox)
        self.feedback_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.feedback_checkbox.setObjectName(_fromUtf8("feedback_checkbox"))
        self.left_panel.addWidget(self.feedback_checkbox)
        self.reset_averages_button = QtGui.QPushButton(self.centralwidget)
        self.reset_averages_button.setObjectName(_fromUtf8("reset_averages_button"))
        self.left_panel.addWidget(self.reset_averages_button)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.step_size_label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_size_label.sizePolicy().hasHeightForWidth())
        self.step_size_label.setSizePolicy(sizePolicy)
        self.step_size_label.setObjectName(_fromUtf8("step_size_label"))
        self.horizontalLayout_2.addWidget(self.step_size_label)
        self.stepSize_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.stepSize_spinBox.setMinimum(1)
        self.stepSize_spinBox.setMaximum(10)
        self.stepSize_spinBox.setSingleStep(1)
        self.stepSize_spinBox.setProperty("value", 1)
        self.stepSize_spinBox.setObjectName(_fromUtf8("stepSize_spinBox"))
        self.horizontalLayout_2.addWidget(self.stepSize_spinBox)
        self.left_panel.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.left_panel)
        self.right_panel = QtGui.QVBoxLayout()
        self.right_panel.setObjectName(_fromUtf8("right_panel"))
        self.monitor = GraphicsView(self.centralwidget)
        self.monitor.setObjectName(_fromUtf8("monitor"))
        self.right_panel.addWidget(self.monitor)
        self.horizontalLayout.addLayout(self.right_panel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 973, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Collector", None))
        self.live_stream_label.setText(_translate("MainWindow", "<a href=\"thing\">Live Stream</a>", None))
        self.leds_checkbox.setText(_translate("MainWindow", "LEDs", None))
        self.screen_label.setText(_translate("MainWindow", "Screen", None))
        self.screen_in_button.setText(_translate("MainWindow", "In", None))
        self.screen_out_button.setText(_translate("MainWindow", "Out", None))
        self.screen_progress.setFormat(_translate("MainWindow", "UNKNOWN_SCREEN", None))
        self.colour_map_label.setText(_translate("MainWindow", "Colour map", None))
        self.label_3.setText(_translate("MainWindow", "Max level", None))
        self.auto_level_checkbox.setText(_translate("MainWindow", "Auto", None))
        self.save_pushButton.setText(_translate("MainWindow", "Save", None))
        self.numImages_label.setText(_translate("MainWindow", "image", None))
        self.image_folder_label.setText(_translate("MainWindow", "<a href=\"folder\">Image Folder</a>", None))
        self.resetBackground_pushButton.setText(_translate("MainWindow", "Reset Background Image", None))
        self.useBackground_checkBox.setText(_translate("MainWindow", "Use Background", None))
        self.useNPoint_checkBox.setText(_translate("MainWindow", "Use N-Point Scaling", None))
        self.feedback_checkbox.setText(_translate("MainWindow", "Feedback", None))
        self.reset_averages_button.setText(_translate("MainWindow", "Reset averages", None))
        self.step_size_label.setText(_translate("MainWindow", "Step Size:", None))

from pyqtgraph import GraphicsView
