# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1034, 836)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("solenoidEnergy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.centralWidgetLayout = QtGui.QGridLayout(self.centralwidget)
        self.centralWidgetLayout.setObjectName(_fromUtf8("centralWidgetLayout"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_MODE = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_MODE.sizePolicy().hasHeightForWidth())
        self.label_MODE.setSizePolicy(sizePolicy)
        self.label_MODE.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_MODE.setObjectName(_fromUtf8("label_MODE"))
        self.horizontalLayout.addWidget(self.label_MODE)
        self.Linac1_Timing_Monitor = QtGui.QPushButton(self.groupBox_3)
        self.Linac1_Timing_Monitor.setEnabled(False)
        self.Linac1_Timing_Monitor.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Linac1_Timing_Monitor.setText(_fromUtf8(""))
        self.Linac1_Timing_Monitor.setFlat(False)
        self.Linac1_Timing_Monitor.setObjectName(_fromUtf8("Linac1_Timing_Monitor"))
        self.horizontalLayout.addWidget(self.Linac1_Timing_Monitor)
        self.Progress_Monitor = QtGui.QProgressBar(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Progress_Monitor.sizePolicy().hasHeightForWidth())
        self.Progress_Monitor.setSizePolicy(sizePolicy)
        self.Progress_Monitor.setMinimumSize(QtCore.QSize(70, 0))
        self.Progress_Monitor.setProperty("value", 0)
        self.Progress_Monitor.setTextVisible(False)
        self.Progress_Monitor.setObjectName(_fromUtf8("Progress_Monitor"))
        self.horizontalLayout.addWidget(self.Progress_Monitor)
        self.abortButton = QtGui.QPushButton(self.groupBox_3)
        self.abortButton.setObjectName(_fromUtf8("abortButton"))
        self.horizontalLayout.addWidget(self.abortButton)
        self.centralWidgetLayout.addWidget(self.groupBox_3, 1, 0, 1, 2)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.bpmTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bpmTab.sizePolicy().hasHeightForWidth())
        self.bpmTab.setSizePolicy(sizePolicy)
        self.bpmTab.setObjectName(_fromUtf8("bpmTab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.bpmTab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_8 = QtGui.QGroupBox(self.bpmTab)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_11 = QtGui.QLabel(self.groupBox_8)
        self.label_11.setMinimumSize(QtCore.QSize(50, 0))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_6.addWidget(self.label_11)
        self.BPMCombo = QtGui.QComboBox(self.groupBox_8)
        self.BPMCombo.setMinimumSize(QtCore.QSize(100, 0))
        self.BPMCombo.setObjectName(_fromUtf8("BPMCombo"))
        self.BPMCombo.addItem(_fromUtf8(""))
        self.BPMCombo.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.BPMCombo)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_7.addWidget(self.groupBox_8)
        self.BPMPlots_Box = QtGui.QGroupBox(self.bpmTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BPMPlots_Box.sizePolicy().hasHeightForWidth())
        self.BPMPlots_Box.setSizePolicy(sizePolicy)
        self.BPMPlots_Box.setObjectName(_fromUtf8("BPMPlots_Box"))
        self.BPM_Plots_Layout = QtGui.QVBoxLayout(self.BPMPlots_Box)
        self.BPM_Plots_Layout.setObjectName(_fromUtf8("BPM_Plots_Layout"))
        self.verticalLayout_7.addWidget(self.BPMPlots_Box)
        self.groupBox_5 = QtGui.QGroupBox(self.bpmTab)
        self.groupBox_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 1, 0, 1, 1)
        self.frame_5 = QtGui.QFrame(self.groupBox_5)
        self.frame_5.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.frame_5)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.negativeMomentumBox = QtGui.QDoubleSpinBox(self.frame_5)
        self.negativeMomentumBox.setReadOnly(True)
        self.negativeMomentumBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.negativeMomentumBox.setObjectName(_fromUtf8("negativeMomentumBox"))
        self.horizontalLayout_4.addWidget(self.negativeMomentumBox)
        self.label_2 = QtGui.QLabel(self.frame_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.positiveMomentumBox = QtGui.QDoubleSpinBox(self.frame_5)
        self.positiveMomentumBox.setReadOnly(True)
        self.positiveMomentumBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.positiveMomentumBox.setObjectName(_fromUtf8("positiveMomentumBox"))
        self.horizontalLayout_4.addWidget(self.positiveMomentumBox)
        self.gridLayout_4.addWidget(self.frame_5, 1, 1, 1, 1)
        self.widget = QtGui.QWidget(self.groupBox_5)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.meanMomentumBox = QtGui.QDoubleSpinBox(self.widget)
        self.meanMomentumBox.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.meanMomentumBox.setFont(font)
        self.meanMomentumBox.setReadOnly(True)
        self.meanMomentumBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.meanMomentumBox.setObjectName(_fromUtf8("meanMomentumBox"))
        self.horizontalLayout_5.addWidget(self.meanMomentumBox)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.gridLayout_4.addWidget(self.widget, 3, 0, 1, 3)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.bpmTab, _fromUtf8(""))
        self.screenTab = QtGui.QWidget()
        self.screenTab.setEnabled(False)
        self.screenTab.setObjectName(_fromUtf8("screenTab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.screenTab)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_9 = QtGui.QGroupBox(self.screenTab)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_12 = QtGui.QLabel(self.groupBox_9)
        self.label_12.setMinimumSize(QtCore.QSize(50, 0))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_7.addWidget(self.label_12)
        self.ScreenCombo = QtGui.QComboBox(self.groupBox_9)
        self.ScreenCombo.setMinimumSize(QtCore.QSize(100, 0))
        self.ScreenCombo.setObjectName(_fromUtf8("ScreenCombo"))
        self.ScreenCombo.addItem(_fromUtf8(""))
        self.ScreenCombo.addItem(_fromUtf8(""))
        self.ScreenCombo.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.ScreenCombo)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_6.addWidget(self.groupBox_9)
        self.ScreenPlots_Box = QtGui.QGroupBox(self.screenTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScreenPlots_Box.sizePolicy().hasHeightForWidth())
        self.ScreenPlots_Box.setSizePolicy(sizePolicy)
        self.ScreenPlots_Box.setObjectName(_fromUtf8("ScreenPlots_Box"))
        self.Screen_Plots_Layout = QtGui.QVBoxLayout(self.ScreenPlots_Box)
        self.Screen_Plots_Layout.setObjectName(_fromUtf8("Screen_Plots_Layout"))
        self.verticalLayout_6.addWidget(self.ScreenPlots_Box)
        self.groupBox_10 = QtGui.QGroupBox(self.screenTab)
        self.groupBox_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem7, 1, 0, 1, 1)
        self.frame_6 = QtGui.QFrame(self.groupBox_10)
        self.frame_6.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_13 = QtGui.QLabel(self.frame_6)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_8.addWidget(self.label_13)
        self.negativeMomentumBox_Screen = QtGui.QDoubleSpinBox(self.frame_6)
        self.negativeMomentumBox_Screen.setReadOnly(True)
        self.negativeMomentumBox_Screen.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.negativeMomentumBox_Screen.setObjectName(_fromUtf8("negativeMomentumBox_Screen"))
        self.horizontalLayout_8.addWidget(self.negativeMomentumBox_Screen)
        self.label_14 = QtGui.QLabel(self.frame_6)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_8.addWidget(self.label_14)
        self.positiveMomentumBox_Screen = QtGui.QDoubleSpinBox(self.frame_6)
        self.positiveMomentumBox_Screen.setReadOnly(True)
        self.positiveMomentumBox_Screen.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.positiveMomentumBox_Screen.setObjectName(_fromUtf8("positiveMomentumBox_Screen"))
        self.horizontalLayout_8.addWidget(self.positiveMomentumBox_Screen)
        self.gridLayout_5.addWidget(self.frame_6, 1, 1, 1, 1)
        self.widget_3 = QtGui.QWidget(self.groupBox_10)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.label_15 = QtGui.QLabel(self.widget_3)
        self.label_15.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_9.addWidget(self.label_15)
        self.meanMomentumBox_Screen = QtGui.QDoubleSpinBox(self.widget_3)
        self.meanMomentumBox_Screen.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.meanMomentumBox_Screen.setFont(font)
        self.meanMomentumBox_Screen.setReadOnly(True)
        self.meanMomentumBox_Screen.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.meanMomentumBox_Screen.setObjectName(_fromUtf8("meanMomentumBox_Screen"))
        self.horizontalLayout_9.addWidget(self.meanMomentumBox_Screen)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.gridLayout_5.addWidget(self.widget_3, 3, 0, 1, 3)
        self.verticalLayout_6.addWidget(self.groupBox_10)
        self.tabWidget.addTab(self.screenTab, _fromUtf8(""))
        self.logTab = QtGui.QWidget()
        self.logTab.setObjectName(_fromUtf8("logTab"))
        self.logTabLayout = QtGui.QVBoxLayout(self.logTab)
        self.logTabLayout.setObjectName(_fromUtf8("logTabLayout"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../Resources/Icons/log.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.logTab, icon1, _fromUtf8(""))
        self.centralWidgetLayout.addWidget(self.tabWidget, 2, 1, 1, 1)
        self.widget_2 = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox = QtGui.QGroupBox(self.widget_2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.HCORRRange = QtGui.QDoubleSpinBox(self.groupBox)
        self.HCORRRange.setSingleStep(1.0)
        self.HCORRRange.setProperty("value", 1.0)
        self.HCORRRange.setObjectName(_fromUtf8("HCORRRange"))
        self.gridLayout_2.addWidget(self.HCORRRange, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.VCORRStartValue = QtGui.QDoubleSpinBox(self.groupBox)
        self.VCORRStartValue.setMinimum(-99.0)
        self.VCORRStartValue.setObjectName(_fromUtf8("VCORRStartValue"))
        self.gridLayout_2.addWidget(self.VCORRStartValue, 1, 1, 1, 1)
        self.VCORRRange = QtGui.QDoubleSpinBox(self.groupBox)
        self.VCORRRange.setProperty("value", 1.0)
        self.VCORRRange.setObjectName(_fromUtf8("VCORRRange"))
        self.gridLayout_2.addWidget(self.VCORRRange, 1, 3, 1, 1)
        self.NSteps = QtGui.QSpinBox(self.groupBox)
        self.NSteps.setMinimum(1)
        self.NSteps.setSingleStep(2)
        self.NSteps.setProperty("value", 10)
        self.NSteps.setObjectName(_fromUtf8("NSteps"))
        self.gridLayout_2.addWidget(self.NSteps, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 2, 1, 1)
        self.HCORRStartValue = QtGui.QDoubleSpinBox(self.groupBox)
        self.HCORRStartValue.setMinimum(-99.0)
        self.HCORRStartValue.setObjectName(_fromUtf8("HCORRStartValue"))
        self.gridLayout_2.addWidget(self.HCORRStartValue, 0, 1, 1, 1)
        self.HCORRButton = QtGui.QPushButton(self.groupBox)
        self.HCORRButton.setFlat(True)
        self.HCORRButton.setObjectName(_fromUtf8("HCORRButton"))
        self.gridLayout_2.addWidget(self.HCORRButton, 0, 0, 1, 1)
        self.VCORRButton = QtGui.QPushButton(self.groupBox)
        self.VCORRButton.setFlat(True)
        self.VCORRButton.setObjectName(_fromUtf8("VCORRButton"))
        self.gridLayout_2.addWidget(self.VCORRButton, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.line_5 = QtGui.QFrame(self.widget_2)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_4.addWidget(self.line_5)
        self.groupBox_2 = QtGui.QGroupBox(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_7)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_7)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.Sol1CurrentNegative = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.Sol1CurrentNegative.setMinimum(-250.0)
        self.Sol1CurrentNegative.setMaximum(0.0)
        self.Sol1CurrentNegative.setSingleStep(5.0)
        self.Sol1CurrentNegative.setProperty("value", -100.0)
        self.Sol1CurrentNegative.setObjectName(_fromUtf8("Sol1CurrentNegative"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.Sol1CurrentNegative)
        self.label_10 = QtGui.QLabel(self.groupBox_7)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.Sol2CurrentNegative = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.Sol2CurrentNegative.setMinimum(-250.0)
        self.Sol2CurrentNegative.setMaximum(0.0)
        self.Sol2CurrentNegative.setSingleStep(5.0)
        self.Sol2CurrentNegative.setProperty("value", 0.0)
        self.Sol2CurrentNegative.setObjectName(_fromUtf8("Sol2CurrentNegative"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.Sol2CurrentNegative)
        self.verticalLayout_5.addWidget(self.groupBox_7)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_4 = QtGui.QLabel(self.groupBox_6)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.Sol1CurrentPositive = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.Sol1CurrentPositive.setMinimum(0.0)
        self.Sol1CurrentPositive.setMaximum(250.0)
        self.Sol1CurrentPositive.setSingleStep(5.0)
        self.Sol1CurrentPositive.setProperty("value", 100.0)
        self.Sol1CurrentPositive.setObjectName(_fromUtf8("Sol1CurrentPositive"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.Sol1CurrentPositive)
        self.label_9 = QtGui.QLabel(self.groupBox_6)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.Sol2CurrentPositive = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.Sol2CurrentPositive.setMinimum(0.0)
        self.Sol2CurrentPositive.setMaximum(250.0)
        self.Sol2CurrentPositive.setSingleStep(5.0)
        self.Sol2CurrentPositive.setProperty("value", 0.0)
        self.Sol2CurrentPositive.setObjectName(_fromUtf8("Sol2CurrentPositive"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.Sol2CurrentPositive)
        self.verticalLayout_5.addWidget(self.groupBox_6)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.line_3 = QtGui.QFrame(self.widget_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_4.addWidget(self.line_3)
        self.groupBox1 = QtGui.QGroupBox(self.widget_2)
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.LinacTiming_Off_Button = QtGui.QPushButton(self.groupBox1)
        self.LinacTiming_Off_Button.setObjectName(_fromUtf8("LinacTiming_Off_Button"))
        self.verticalLayout.addWidget(self.LinacTiming_Off_Button)
        self.verticalLayout_4.addWidget(self.groupBox1)
        self.line_2 = QtGui.QFrame(self.widget_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_4.addWidget(self.line_2)
        self.groupBox_4 = QtGui.QGroupBox(self.widget_2)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.scanWidget = QtGui.QWidget(self.groupBox_4)
        self.scanWidget.setObjectName(_fromUtf8("scanWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.scanWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.runScanButton = QtGui.QPushButton(self.scanWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runScanButton.sizePolicy().hasHeightForWidth())
        self.runScanButton.setSizePolicy(sizePolicy)
        self.runScanButton.setMinimumSize(QtCore.QSize(150, 0))
        self.runScanButton.setObjectName(_fromUtf8("runScanButton"))
        self.horizontalLayout_3.addWidget(self.runScanButton)
        self.showIndividualScansButton = QtGui.QToolButton(self.scanWidget)
        self.showIndividualScansButton.setMaximumSize(QtCore.QSize(20, 16777215))
        self.showIndividualScansButton.setText(_fromUtf8(""))
        self.showIndividualScansButton.setObjectName(_fromUtf8("showIndividualScansButton"))
        self.horizontalLayout_3.addWidget(self.showIndividualScansButton)
        self.verticalLayout_3.addWidget(self.scanWidget)
        self.individualScanWidget = QtGui.QWidget(self.groupBox_4)
        self.individualScanWidget.setEnabled(True)
        self.individualScanWidget.setObjectName(_fromUtf8("individualScanWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.individualScanWidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.runNegativeScanButton = QtGui.QPushButton(self.individualScanWidget)
        self.runNegativeScanButton.setObjectName(_fromUtf8("runNegativeScanButton"))
        self.horizontalLayout_2.addWidget(self.runNegativeScanButton)
        self.runPositiveScanButton = QtGui.QPushButton(self.individualScanWidget)
        self.runPositiveScanButton.setObjectName(_fromUtf8("runPositiveScanButton"))
        self.horizontalLayout_2.addWidget(self.runPositiveScanButton)
        self.verticalLayout_3.addWidget(self.individualScanWidget)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.line = QtGui.QFrame(self.widget_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_4.addWidget(self.line)
        self.groupBox_21 = QtGui.QGroupBox(self.widget_2)
        self.groupBox_21.setObjectName(_fromUtf8("groupBox_21"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_21)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.LinacTiming_On_Button = QtGui.QPushButton(self.groupBox_21)
        self.LinacTiming_On_Button.setObjectName(_fromUtf8("LinacTiming_On_Button"))
        self.verticalLayout_2.addWidget(self.LinacTiming_On_Button)
        self.verticalLayout_4.addWidget(self.groupBox_21)
        self.line_4 = QtGui.QFrame(self.widget_2)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_4.addWidget(self.line_4)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.centralWidgetLayout.addWidget(self.widget_2, 2, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1034, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSave_Data = QtGui.QMenu(self.menubar)
        self.menuSave_Data.setObjectName(_fromUtf8("menuSave_Data"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_Calibation_Data = QtGui.QAction(MainWindow)
        self.actionSave_Calibation_Data.setObjectName(_fromUtf8("actionSave_Calibation_Data"))
        self.actionSave_to_Work_Folder = QtGui.QAction(MainWindow)
        self.actionSave_to_Work_Folder.setCheckable(True)
        self.actionSave_to_Work_Folder.setChecked(True)
        self.actionSave_to_Work_Folder.setObjectName(_fromUtf8("actionSave_to_Work_Folder"))
        self.actionAuto_Save_Data = QtGui.QAction(MainWindow)
        self.actionAuto_Save_Data.setCheckable(True)
        self.actionAuto_Save_Data.setChecked(True)
        self.actionAuto_Save_Data.setObjectName(_fromUtf8("actionAuto_Save_Data"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSave_Data = QtGui.QAction(MainWindow)
        self.actionSave_Data.setObjectName(_fromUtf8("actionSave_Data"))
        self.menuFile.addAction(self.actionExit)
        self.menuSave_Data.addAction(self.actionSave_Data)
        self.menuSave_Data.addSeparator()
        self.menuSave_Data.addAction(self.actionAuto_Save_Data)
        self.menuSave_Data.addAction(self.actionSave_to_Work_Folder)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSave_Data.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Solenoid Energy Scan", None))
        self.label_MODE.setText(_translate("MainWindow", "Mode", None))
        self.Linac1_Timing_Monitor.setToolTip(_translate("MainWindow", "Alter the linac timings (GREEN: Linacs timed with beam, RED: Linacs timed away from beam)", None))
        self.Progress_Monitor.setToolTip(_translate("MainWindow", "Progress of the running scan", None))
        self.abortButton.setText(_translate("MainWindow", "Abort", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Select BPM", None))
        self.label_11.setText(_translate("MainWindow", "BPM", None))
        self.BPMCombo.setItemText(0, _translate("MainWindow", "S02-BPM01", None))
        self.BPMCombo.setItemText(1, _translate("MainWindow", "S02-BPM02", None))
        self.BPMPlots_Box.setTitle(_translate("MainWindow", "Solenoid Scan Results", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Momentum", None))
        self.label.setText(_translate("MainWindow", "Negative Solenoid Momentum", None))
        self.negativeMomentumBox.setSuffix(_translate("MainWindow", " MeV/c", None))
        self.label_2.setText(_translate("MainWindow", "Positive Solenoid Momentum", None))
        self.positiveMomentumBox.setSuffix(_translate("MainWindow", " MeV/c", None))
        self.label_8.setText(_translate("MainWindow", "Average Momentum", None))
        self.meanMomentumBox.setSuffix(_translate("MainWindow", " MeV/c", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bpmTab), _translate("MainWindow", "BPM Scan", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Select Screen", None))
        self.label_12.setText(_translate("MainWindow", "Screen", None))
        self.ScreenCombo.setItemText(0, _translate("MainWindow", "S02-SCR-01", None))
        self.ScreenCombo.setItemText(1, _translate("MainWindow", "S02-SCR-02", None))
        self.ScreenCombo.setItemText(2, _translate("MainWindow", "S02-SCR-03", None))
        self.ScreenPlots_Box.setTitle(_translate("MainWindow", "Solenoid Scan Results", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Momentum", None))
        self.label_13.setText(_translate("MainWindow", "Negative Solenoid Momentum", None))
        self.negativeMomentumBox_Screen.setSuffix(_translate("MainWindow", " MeV/c", None))
        self.label_14.setText(_translate("MainWindow", "Positive Solenoid Momentum", None))
        self.positiveMomentumBox_Screen.setSuffix(_translate("MainWindow", " MeV/c", None))
        self.label_15.setText(_translate("MainWindow", "Average Momentum", None))
        self.meanMomentumBox_Screen.setSuffix(_translate("MainWindow", " MeV/c", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.screenTab), _translate("MainWindow", "Screen Scan", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logTab), _translate("MainWindow", "Log", None))
        self.groupBox.setTitle(_translate("MainWindow", "Corrector Settings", None))
        self.label_3.setText(_translate("MainWindow", "Number of Steps", None))
        self.HCORRRange.setSuffix(_translate("MainWindow", " A", None))
        self.label_6.setText(_translate("MainWindow", "±", None))
        self.VCORRRange.setSuffix(_translate("MainWindow", " A", None))
        self.label_7.setText(_translate("MainWindow", "±", None))
        self.HCORRButton.setText(_translate("MainWindow", "HCORR Range", None))
        self.VCORRButton.setText(_translate("MainWindow", "VCORR Range", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Solenoid Settings", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Negative Scan", None))
        self.label_5.setText(_translate("MainWindow", "Linac Solenoid 1", None))
        self.Sol1CurrentNegative.setSuffix(_translate("MainWindow", " A", None))
        self.label_10.setText(_translate("MainWindow", "Linac Solenoid 2", None))
        self.Sol2CurrentNegative.setSuffix(_translate("MainWindow", " A", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Positive Scan", None))
        self.label_4.setText(_translate("MainWindow", "Linac Solenoid 1", None))
        self.Sol1CurrentPositive.setSuffix(_translate("MainWindow", " A", None))
        self.label_9.setText(_translate("MainWindow", "Linac Solenoid 2", None))
        self.Sol2CurrentPositive.setSuffix(_translate("MainWindow", " A", None))
        self.groupBox1.setTitle(_translate("MainWindow", "Linac Timing", None))
        self.LinacTiming_Off_Button.setText(_translate("MainWindow", "Set Linac Timing Away", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Solenoid Scan", None))
        self.runScanButton.setText(_translate("MainWindow", "Run Full Scan", None))
        self.runNegativeScanButton.setText(_translate("MainWindow", "Run -ve Scan", None))
        self.runPositiveScanButton.setText(_translate("MainWindow", "Run +ve Scan", None))
        self.groupBox_21.setTitle(_translate("MainWindow", "Linac Timing", None))
        self.LinacTiming_On_Button.setText(_translate("MainWindow", "Set Linac Timing Normal", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSave_Data.setTitle(_translate("MainWindow", "Save Data", None))
        self.actionSave_Calibation_Data.setText(_translate("MainWindow", "Save Calibation Data", None))
        self.actionSave_to_Work_Folder.setText(_translate("MainWindow", "Save to Work Folder", None))
        self.actionAuto_Save_Data.setText(_translate("MainWindow", "Auto Save Data", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionSave_Data.setText(_translate("MainWindow", "Save Data", None))

