# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_view(object):
    def setupUi(self, view):
        view.setObjectName("view")
        view.resize(211, 347)
        self.centralwidget = QtWidgets.QWidget(view)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.closeButton = QtWidgets.QPushButton(self.widget)
        self.closeButton.setMinimumSize(QtCore.QSize(100, 25))
        self.closeButton.setObjectName("closeButton")
        self.verticalLayout_2.addWidget(self.closeButton)
        self.openButton = QtWidgets.QPushButton(self.widget)
        self.openButton.setMinimumSize(QtCore.QSize(100, 25))
        self.openButton.setObjectName("openButton")
        self.verticalLayout_2.addWidget(self.openButton)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.widget)
        view.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(view)
        self.statusbar.setObjectName("statusbar")
        view.setStatusBar(self.statusbar)

        self.retranslateUi(view)
        QtCore.QMetaObject.connectSlotsByName(view)

    def retranslateUi(self, view):
        _translate = QtCore.QCoreApplication.translate
        view.setWindowTitle(_translate("view", "Valve State"))
        self.closeButton.setText(_translate("view", "CLOSE ALL"))
        self.openButton.setText(_translate("view", "OPEN ALL"))
        self.groupBox.setTitle(_translate("view", "Valves"))
