# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_view(object):
    def setupUi(self, view):
        view.setObjectName("view")
        view.resize(1111, 733)
        self.centralwidget = QtWidgets.QWidget(view)
        self.centralwidget.setObjectName("centralwidget")
        self.graphics_area_full = GraphicsView(self.centralwidget)
        self.graphics_area_full.setGeometry(QtCore.QRect(10, 10, 501, 571))
        self.graphics_area_full.setObjectName("graphics_area_full")
        self.get_roi_data_button = QtWidgets.QPushButton(self.centralwidget)
        self.get_roi_data_button.setGeometry(QtCore.QRect(550, 600, 256, 23))
        self.get_roi_data_button.setObjectName("get_roi_data_button")
        self.analyse_button = QtWidgets.QPushButton(self.centralwidget)
        self.analyse_button.setGeometry(QtCore.QRect(550, 640, 256, 23))
        self.analyse_button.setObjectName("analyse_button")
        self.print_button = QtWidgets.QPushButton(self.centralwidget)
        self.print_button.setGeometry(QtCore.QRect(270, 670, 181, 23))
        self.print_button.setObjectName("print_button")
        self.graphics_area_ROI = GraphicsView(self.centralwidget)
        self.graphics_area_ROI.setGeometry(QtCore.QRect(530, 10, 501, 571))
        self.graphics_area_ROI.setObjectName("graphics_area_ROI")
        self.get_image_data_button = QtWidgets.QPushButton(self.centralwidget)
        self.get_image_data_button.setGeometry(QtCore.QRect(10, 600, 256, 23))
        self.get_image_data_button.setObjectName("get_image_data_button")
        view.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(view)
        self.statusbar.setObjectName("statusbar")
        view.setStatusBar(self.statusbar)

        self.retranslateUi(view)
        QtCore.QMetaObject.connectSlotsByName(view)

    def retranslateUi(self, view):
        _translate = QtCore.QCoreApplication.translate
        view.setWindowTitle(_translate("view", "Laser Transverse Profile Decomposition"))
        self.get_roi_data_button.setText(_translate("view", "Get ROI Data"))
        self.analyse_button.setText(_translate("view", "Analyse Image"))
        self.print_button.setText(_translate("view", "print mask ROI values "))
        self.get_image_data_button.setText(_translate("view", "Get Image  Data"))
from pyqtgraph import GraphicsView
