# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_v6.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(707, 967)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 70))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout.addWidget(self.textEdit, 2, 0, 1, 1)
        self.groupBox_10 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_10.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_10.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_19 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.label_14 = QtGui.QLabel(self.groupBox_10)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_19.addWidget(self.label_14, 0, 0, 1, 1)
        self.doubleSpinBox_I = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_I.setObjectName(_fromUtf8("doubleSpinBox_I"))
        self.gridLayout_19.addWidget(self.doubleSpinBox_I, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_10)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_19.addWidget(self.label_13, 0, 1, 1, 1)
        self.doubleSpinBox_p = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_p.setObjectName(_fromUtf8("doubleSpinBox_p"))
        self.gridLayout_19.addWidget(self.doubleSpinBox_p, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_10, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 71))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.toolBox = QtGui.QToolBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.toolBox.setFont(font)
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setStyleSheet(_fromUtf8(""))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_7 = QtGui.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 661, 577))
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.gridLayout_20 = QtGui.QGridLayout(self.page_7)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.label = QtGui.QLabel(self.page_7)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_20.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.toolBox.addItem(self.page_7, _fromUtf8(""))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 661, 577))
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_11 = QtGui.QGridLayout(self.page)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.doubleSpinBox_I_predict = QtGui.QDoubleSpinBox(self.page)
        self.doubleSpinBox_I_predict.setObjectName(_fromUtf8("doubleSpinBox_I_predict"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_I_predict, 1, 1, 1, 1)
        self.pushButton_useCurrent = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_useCurrent.sizePolicy().hasHeightForWidth())
        self.pushButton_useCurrent.setSizePolicy(sizePolicy)
        self.pushButton_useCurrent.setMinimumSize(QtCore.QSize(140, 22))
        self.pushButton_useCurrent.setMaximumSize(QtCore.QSize(371, 16777215))
        self.pushButton_useCurrent.setChecked(False)
        self.pushButton_useCurrent.setObjectName(_fromUtf8("pushButton_useCurrent"))
        self.gridLayout_4.addWidget(self.pushButton_useCurrent, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 2, 1, 1)
        self.doubleSpinBox_p_predict = QtGui.QDoubleSpinBox(self.page)
        self.doubleSpinBox_p_predict.setObjectName(_fromUtf8("doubleSpinBox_p_predict"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_p_predict, 1, 2, 1, 1)
        self.pushButton_useRF = QtGui.QPushButton(self.page)
        self.pushButton_useRF.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_useRF.sizePolicy().hasHeightForWidth())
        self.pushButton_useRF.setSizePolicy(sizePolicy)
        self.pushButton_useRF.setMinimumSize(QtCore.QSize(140, 22))
        self.pushButton_useRF.setMaximumSize(QtCore.QSize(371, 16777215))
        font = QtGui.QFont()
        self.pushButton_useRF.setFont(font)
        self.pushButton_useRF.setChecked(False)
        self.pushButton_useRF.setObjectName(_fromUtf8("pushButton_useRF"))
        self.gridLayout_4.addWidget(self.pushButton_useRF, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_4, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.page)
        self.label_6.setMinimumSize(QtCore.QSize(0, 270))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_11.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_I = QtGui.QLabel(self.page)
        self.label_I.setMinimumSize(QtCore.QSize(120, 0))
        self.label_I.setObjectName(_fromUtf8("label_I"))
        self.gridLayout_11.addWidget(self.label_I, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_11.addWidget(self.label_2, 0, 0, 1, 1)
        self.line = QtGui.QFrame(self.page)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_11.addWidget(self.line, 1, 0, 1, 1)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 661, 577))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.page_2)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.toolBox_2 = QtGui.QToolBox(self.tab)
        self.toolBox_2.setObjectName(_fromUtf8("toolBox_2"))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 611, 403))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.gridLayout_13 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_16 = QtGui.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_7.addWidget(self.label_16, 0, 0, 1, 4)
        self.label_15 = QtGui.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_7.addWidget(self.label_15, 1, 0, 1, 1)
        self.doubleSpinBox_step_1 = QtGui.QDoubleSpinBox(self.page_5)
        self.doubleSpinBox_step_1.setDecimals(3)
        self.doubleSpinBox_step_1.setSingleStep(0.1)
        self.doubleSpinBox_step_1.setProperty("value", 0.2)
        self.doubleSpinBox_step_1.setObjectName(_fromUtf8("doubleSpinBox_step_1"))
        self.gridLayout_7.addWidget(self.doubleSpinBox_step_1, 1, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_7.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_dipole_set = QtGui.QLabel(self.page_5)
        self.label_dipole_set.setMinimumSize(QtCore.QSize(100, 0))
        self.label_dipole_set.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_dipole_set.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_dipole_set.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_dipole_set.setText(_fromUtf8(""))
        self.label_dipole_set.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_dipole_set.setObjectName(_fromUtf8("label_dipole_set"))
        self.gridLayout_7.addWidget(self.label_dipole_set, 2, 1, 1, 1)
        self.pushButton_x_up_1 = QtGui.QPushButton(self.page_5)
        self.pushButton_x_up_1.setMinimumSize(QtCore.QSize(20, 12))
        self.pushButton_x_up_1.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(5)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_x_up_1.setFont(font)
        self.pushButton_x_up_1.setStyleSheet(_fromUtf8("QPushButton{ color: rgb(0, 0, 0);font: 75 5pt \"MS Shell Dlg 2\";}\n"
""))
        self.pushButton_x_up_1.setAutoDefault(False)
        self.pushButton_x_up_1.setObjectName(_fromUtf8("pushButton_x_up_1"))
        self.gridLayout_7.addWidget(self.pushButton_x_up_1, 2, 2, 1, 1)
        self.pushButton_x_down_1 = QtGui.QPushButton(self.page_5)
        self.pushButton_x_down_1.setMinimumSize(QtCore.QSize(20, 12))
        self.pushButton_x_down_1.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(5)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_x_down_1.setFont(font)
        self.pushButton_x_down_1.setStyleSheet(_fromUtf8("QPushButton{ color: rgb(0, 0, 0);font: 75 5pt \"MS Shell Dlg 2\";}"))
        self.pushButton_x_down_1.setObjectName(_fromUtf8("pushButton_x_down_1"))
        self.gridLayout_7.addWidget(self.pushButton_x_down_1, 2, 3, 1, 1)
        self.pushButton_get_p_rough = QtGui.QPushButton(self.page_5)
        self.pushButton_get_p_rough.setObjectName(_fromUtf8("pushButton_get_p_rough"))
        self.gridLayout_7.addWidget(self.pushButton_get_p_rough, 3, 0, 1, 1)
        self.label_p_rough = QtGui.QLabel(self.page_5)
        self.label_p_rough.setMinimumSize(QtCore.QSize(100, 0))
        self.label_p_rough.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_p_rough.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_p_rough.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_p_rough.setText(_fromUtf8(""))
        self.label_p_rough.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_p_rough.setObjectName(_fromUtf8("label_p_rough"))
        self.gridLayout_7.addWidget(self.label_p_rough, 3, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 254, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.page_5)
        self.groupBox_3.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_13.addWidget(self.groupBox_3, 0, 1, 2, 1)
        self.toolBox_2.addItem(self.page_5, _fromUtf8(""))
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 611, 403))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.gridLayout_14 = QtGui.QGridLayout(self.page_6)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.pushButton_roughGetCurrentRange = QtGui.QPushButton(self.page_6)
        self.pushButton_roughGetCurrentRange.setChecked(False)
        self.pushButton_roughGetCurrentRange.setObjectName(_fromUtf8("pushButton_roughGetCurrentRange"))
        self.gridLayout_12.addWidget(self.pushButton_roughGetCurrentRange, 0, 0, 1, 1)
        self.doubleSpinBox_roughIMin = QtGui.QDoubleSpinBox(self.page_6)
        self.doubleSpinBox_roughIMin.setObjectName(_fromUtf8("doubleSpinBox_roughIMin"))
        self.gridLayout_12.addWidget(self.doubleSpinBox_roughIMin, 0, 1, 1, 1)
        self.doubleSpinBox_roughIMax = QtGui.QDoubleSpinBox(self.page_6)
        self.doubleSpinBox_roughIMax.setObjectName(_fromUtf8("doubleSpinBox_roughIMax"))
        self.gridLayout_12.addWidget(self.doubleSpinBox_roughIMax, 0, 2, 1, 1)
        self.doubleSpinBox_roughIStep = QtGui.QDoubleSpinBox(self.page_6)
        self.doubleSpinBox_roughIStep.setObjectName(_fromUtf8("doubleSpinBox_roughIStep"))
        self.gridLayout_12.addWidget(self.doubleSpinBox_roughIStep, 0, 3, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.page_6)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gridLayout_12.addWidget(self.groupBox_2, 2, 0, 1, 4)
        self.pushButton_roughCentreC2VCurrent = QtGui.QPushButton(self.page_6)
        self.pushButton_roughCentreC2VCurrent.setChecked(False)
        self.pushButton_roughCentreC2VCurrent.setObjectName(_fromUtf8("pushButton_roughCentreC2VCurrent"))
        self.gridLayout_12.addWidget(self.pushButton_roughCentreC2VCurrent, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem1, 1, 1, 1, 3)
        self.gridLayout_14.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.toolBox_2.addItem(self.page_6, _fromUtf8(""))
        self.gridLayout_6.addWidget(self.toolBox_2, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_16 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_16.addWidget(self.label_7, 0, 0, 1, 1)
        self.toolBox_3 = QtGui.QToolBox(self.tab_2)
        self.toolBox_3.setObjectName(_fromUtf8("toolBox_3"))
        self.page_8 = QtGui.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 611, 403))
        self.page_8.setObjectName(_fromUtf8("page_8"))
        self.gridLayout_18 = QtGui.QGridLayout(self.page_8)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        spacerItem2 = QtGui.QSpacerItem(20, 100, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 175, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem3, 3, 0, 1, 1)
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.label_18 = QtGui.QLabel(self.page_8)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_17.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_I_rough = QtGui.QLabel(self.page_8)
        self.label_I_rough.setMinimumSize(QtCore.QSize(50, 0))
        self.label_I_rough.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_I_rough.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_I_rough.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_I_rough.setText(_fromUtf8(""))
        self.label_I_rough.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_I_rough.setObjectName(_fromUtf8("label_I_rough"))
        self.gridLayout_17.addWidget(self.label_I_rough, 4, 1, 1, 2)
        self.label_28 = QtGui.QLabel(self.page_8)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_17.addWidget(self.label_28, 4, 0, 1, 1)
        self.pushButton_set_I_rough = QtGui.QPushButton(self.page_8)
        self.pushButton_set_I_rough.setObjectName(_fromUtf8("pushButton_set_I_rough"))
        self.gridLayout_17.addWidget(self.pushButton_set_I_rough, 3, 1, 1, 2)
        self.doubleSpinBox_p_rough_set = QtGui.QDoubleSpinBox(self.page_8)
        self.doubleSpinBox_p_rough_set.setObjectName(_fromUtf8("doubleSpinBox_p_rough_set"))
        self.gridLayout_17.addWidget(self.doubleSpinBox_p_rough_set, 1, 0, 1, 1)
        self.doubleSpinBox_I_2 = QtGui.QDoubleSpinBox(self.page_8)
        self.doubleSpinBox_I_2.setEnabled(False)
        self.doubleSpinBox_I_2.setObjectName(_fromUtf8("doubleSpinBox_I_2"))
        self.gridLayout_17.addWidget(self.doubleSpinBox_I_2, 1, 1, 1, 2)
        self.label_27 = QtGui.QLabel(self.page_8)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_17.addWidget(self.label_27, 0, 1, 1, 2)
        self.gridLayout_18.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.page_8)
        self.groupBox_4.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_18.addWidget(self.groupBox_4, 0, 1, 4, 1)
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.label_19 = QtGui.QLabel(self.page_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_15.addWidget(self.label_19, 0, 0, 1, 1)
        self.pushButton_select_gun = QtGui.QPushButton(self.page_8)
        self.pushButton_select_gun.setAutoFillBackground(False)
        self.pushButton_select_gun.setObjectName(_fromUtf8("pushButton_select_gun"))
        self.gridLayout_15.addWidget(self.pushButton_select_gun, 1, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.page_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_15.addWidget(self.label_20, 2, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.page_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_15.addWidget(self.label_21, 3, 0, 1, 1)
        self.label_RF_rough = QtGui.QLabel(self.page_8)
        self.label_RF_rough.setMinimumSize(QtCore.QSize(100, 0))
        self.label_RF_rough.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_RF_rough.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_RF_rough.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_RF_rough.setText(_fromUtf8(""))
        self.label_RF_rough.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RF_rough.setObjectName(_fromUtf8("label_RF_rough"))
        self.gridLayout_15.addWidget(self.label_RF_rough, 3, 1, 1, 1)
        self.pushButton_x_up_2 = QtGui.QPushButton(self.page_8)
        self.pushButton_x_up_2.setMinimumSize(QtCore.QSize(20, 12))
        self.pushButton_x_up_2.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(5)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_x_up_2.setFont(font)
        self.pushButton_x_up_2.setStyleSheet(_fromUtf8("QPushButton{ color: rgb(0, 0, 0);font: 75 5pt \"MS Shell Dlg 2\";}\n"
""))
        self.pushButton_x_up_2.setAutoDefault(False)
        self.pushButton_x_up_2.setObjectName(_fromUtf8("pushButton_x_up_2"))
        self.gridLayout_15.addWidget(self.pushButton_x_up_2, 3, 2, 1, 1)
        self.pushButton_x_down_2 = QtGui.QPushButton(self.page_8)
        self.pushButton_x_down_2.setMinimumSize(QtCore.QSize(20, 12))
        self.pushButton_x_down_2.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(5)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_x_down_2.setFont(font)
        self.pushButton_x_down_2.setStyleSheet(_fromUtf8("QPushButton{ color: rgb(0, 0, 0);font: 75 5pt \"MS Shell Dlg 2\";}"))
        self.pushButton_x_down_2.setObjectName(_fromUtf8("pushButton_x_down_2"))
        self.gridLayout_15.addWidget(self.pushButton_x_down_2, 3, 3, 1, 1)
        self.doubleSpinBox_step_2 = QtGui.QDoubleSpinBox(self.page_8)
        self.doubleSpinBox_step_2.setSuffix(_fromUtf8(""))
        self.doubleSpinBox_step_2.setDecimals(2)
        self.doubleSpinBox_step_2.setMaximum(1000.0)
        self.doubleSpinBox_step_2.setSingleStep(10.0)
        self.doubleSpinBox_step_2.setProperty("value", 100.0)
        self.doubleSpinBox_step_2.setObjectName(_fromUtf8("doubleSpinBox_step_2"))
        self.gridLayout_15.addWidget(self.doubleSpinBox_step_2, 2, 1, 1, 1)
        self.pushButton_select_linac = QtGui.QPushButton(self.page_8)
        self.pushButton_select_linac.setObjectName(_fromUtf8("pushButton_select_linac"))
        self.gridLayout_15.addWidget(self.pushButton_select_linac, 1, 1, 1, 1)
        self.lineEdit_RFmode_rough = QtGui.QLineEdit(self.page_8)
        self.lineEdit_RFmode_rough.setObjectName(_fromUtf8("lineEdit_RFmode_rough"))
        self.gridLayout_15.addWidget(self.lineEdit_RFmode_rough, 1, 2, 1, 2)
        self.gridLayout_18.addLayout(self.gridLayout_15, 2, 0, 1, 1)
        self.pushButton_select_linac.raise_()
        self.label_18.raise_()
        self.doubleSpinBox_p_rough_set.raise_()
        self.pushButton_select_gun.raise_()
        self.pushButton_set_I_rough.raise_()
        self.label_I_rough.raise_()
        self.groupBox_4.raise_()
        self.doubleSpinBox_I_2.raise_()
        self.label_27.raise_()
        self.label_I_rough.raise_()
        self.label_28.raise_()
        self.toolBox_3.addItem(self.page_8, _fromUtf8(""))
        self.page_9 = QtGui.QWidget()
        self.page_9.setGeometry(QtCore.QRect(0, 0, 611, 403))
        self.page_9.setObjectName(_fromUtf8("page_9"))
        self.toolBox_3.addItem(self.page_9, _fromUtf8(""))
        self.gridLayout_16.addWidget(self.toolBox_3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 661, 577))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_8 = QtGui.QLabel(self.page_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.tabWidget_2 = QtGui.QTabWidget(self.page_3)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_9)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_24 = QtGui.QLabel(self.tab_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_7.addWidget(self.label_24)
        self.doubleSpinBox_x_2 = QtGui.QDoubleSpinBox(self.tab_9)
        self.doubleSpinBox_x_2.setMinimum(-100.0)
        self.doubleSpinBox_x_2.setMaximum(100.0)
        self.doubleSpinBox_x_2.setSingleStep(0.1)
        self.doubleSpinBox_x_2.setObjectName(_fromUtf8("doubleSpinBox_x_2"))
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_x_2)
        self.label_25 = QtGui.QLabel(self.tab_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_7.addWidget(self.label_25)
        self.doubleSpinBox_tol_2 = QtGui.QDoubleSpinBox(self.tab_9)
        self.doubleSpinBox_tol_2.setSingleStep(0.1)
        self.doubleSpinBox_tol_2.setProperty("value", 0.5)
        self.doubleSpinBox_tol_2.setObjectName(_fromUtf8("doubleSpinBox_tol_2"))
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_tol_2)
        self.label_26 = QtGui.QLabel(self.tab_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_7.addWidget(self.label_26)
        self.label_H_2 = QtGui.QLabel(self.tab_9)
        self.label_H_2.setMinimumSize(QtCore.QSize(70, 0))
        self.label_H_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_H_2.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_H_2.setText(_fromUtf8(""))
        self.label_H_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_H_2.setObjectName(_fromUtf8("label_H_2"))
        self.horizontalLayout_7.addWidget(self.label_H_2)
        self.gridLayout_8.addLayout(self.horizontalLayout_7, 7, 0, 1, 2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_22 = QtGui.QLabel(self.tab_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_6.addWidget(self.label_22)
        self.doubleSpinBox_x_1 = QtGui.QDoubleSpinBox(self.tab_9)
        self.doubleSpinBox_x_1.setMinimum(-100.0)
        self.doubleSpinBox_x_1.setMaximum(100.0)
        self.doubleSpinBox_x_1.setSingleStep(0.1)
        self.doubleSpinBox_x_1.setObjectName(_fromUtf8("doubleSpinBox_x_1"))
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_x_1)
        self.label_12 = QtGui.QLabel(self.tab_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_6.addWidget(self.label_12)
        self.doubleSpinBox_tol_1 = QtGui.QDoubleSpinBox(self.tab_9)
        self.doubleSpinBox_tol_1.setSingleStep(0.1)
        self.doubleSpinBox_tol_1.setProperty("value", 0.5)
        self.doubleSpinBox_tol_1.setObjectName(_fromUtf8("doubleSpinBox_tol_1"))
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_tol_1)
        self.label_23 = QtGui.QLabel(self.tab_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_6.addWidget(self.label_23)
        self.label_H_1 = QtGui.QLabel(self.tab_9)
        self.label_H_1.setMinimumSize(QtCore.QSize(70, 0))
        self.label_H_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_H_1.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_H_1.setText(_fromUtf8(""))
        self.label_H_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_H_1.setObjectName(_fromUtf8("label_H_1"))
        self.horizontalLayout_6.addWidget(self.label_H_1)
        self.gridLayout_8.addLayout(self.horizontalLayout_6, 2, 0, 1, 2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pushButton_Align_1 = QtGui.QPushButton(self.tab_9)
        self.pushButton_Align_1.setChecked(False)
        self.pushButton_Align_1.setObjectName(_fromUtf8("pushButton_Align_1"))
        self.horizontalLayout_8.addWidget(self.pushButton_Align_1)
        self.pushButton_x_up_6 = QtGui.QPushButton(self.tab_9)
        self.pushButton_x_up_6.setMinimumSize(QtCore.QSize(20, 12))
        self.pushButton_x_up_6.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(5)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_x_up_6.setFont(font)
        self.pushButton_x_up_6.setStyleSheet(_fromUtf8("QPushButton{ color: rgb(0, 0, 0);font: 75 5pt \"MS Shell Dlg 2\";}\n"
""))
        self.pushButton_x_up_6.setAutoDefault(False)
        self.pushButton_x_up_6.setObjectName(_fromUtf8("pushButton_x_up_6"))
        self.horizontalLayout_8.addWidget(self.pushButton_x_up_6)
        self.pushButton_x_down_6 = QtGui.QPushButton(self.tab_9)
        self.pushButton_x_down_6.setMinimumSize(QtCore.QSize(20, 12))
        self.pushButton_x_down_6.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(5)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_x_down_6.setFont(font)
        self.pushButton_x_down_6.setStyleSheet(_fromUtf8("QPushButton{ color: rgb(0, 0, 0);font: 75 5pt \"MS Shell Dlg 2\";}"))
        self.pushButton_x_down_6.setObjectName(_fromUtf8("pushButton_x_down_6"))
        self.horizontalLayout_8.addWidget(self.pushButton_x_down_6)
        self.gridLayout_8.addLayout(self.horizontalLayout_8, 1, 0, 1, 2)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.pushButton_Align_3 = QtGui.QPushButton(self.tab_9)
        self.pushButton_Align_3.setChecked(False)
        self.pushButton_Align_3.setObjectName(_fromUtf8("pushButton_Align_3"))
        self.horizontalLayout_9.addWidget(self.pushButton_Align_3)
        self.pushButton_x_up_5 = QtGui.QPushButton(self.tab_9)
        self.pushButton_x_up_5.setMinimumSize(QtCore.QSize(20, 12))
        self.pushButton_x_up_5.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(5)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_x_up_5.setFont(font)
        self.pushButton_x_up_5.setStyleSheet(_fromUtf8("QPushButton{ color: rgb(0, 0, 0);font: 75 5pt \"MS Shell Dlg 2\";}\n"
""))
        self.pushButton_x_up_5.setAutoDefault(False)
        self.pushButton_x_up_5.setObjectName(_fromUtf8("pushButton_x_up_5"))
        self.horizontalLayout_9.addWidget(self.pushButton_x_up_5)
        self.pushButton_x_down_5 = QtGui.QPushButton(self.tab_9)
        self.pushButton_x_down_5.setMinimumSize(QtCore.QSize(20, 12))
        self.pushButton_x_down_5.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(5)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_x_down_5.setFont(font)
        self.pushButton_x_down_5.setStyleSheet(_fromUtf8("QPushButton{ color: rgb(0, 0, 0);font: 75 5pt \"MS Shell Dlg 2\";}"))
        self.pushButton_x_down_5.setObjectName(_fromUtf8("pushButton_x_down_5"))
        self.horizontalLayout_9.addWidget(self.pushButton_x_down_5)
        self.gridLayout_8.addLayout(self.horizontalLayout_9, 6, 0, 1, 2)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_9)
        self.groupBox_6.setMinimumSize(QtCore.QSize(230, 0))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout_8.addWidget(self.groupBox_6, 6, 2, 4, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        self.checkBox_3.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_3.setStyleSheet(_fromUtf8(""))
        self.checkBox_3.setCheckable(False)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_8.addWidget(self.checkBox_3, 3, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 78, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem4, 9, 1, 1, 1)
        self.pushButton_Prelim_3 = QtGui.QPushButton(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Prelim_3.sizePolicy().hasHeightForWidth())
        self.pushButton_Prelim_3.setSizePolicy(sizePolicy)
        self.pushButton_Prelim_3.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_Prelim_3.setMaximumSize(QtCore.QSize(378, 16777215))
        self.pushButton_Prelim_3.setChecked(False)
        self.pushButton_Prelim_3.setObjectName(_fromUtf8("pushButton_Prelim_3"))
        self.gridLayout_8.addWidget(self.pushButton_Prelim_3, 0, 0, 1, 2)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_9)
        self.groupBox_5.setMinimumSize(QtCore.QSize(230, 0))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout_8.addWidget(self.groupBox_5, 1, 2, 4, 1)
        self.pushButton_Align_4 = QtGui.QPushButton(self.tab_9)
        self.pushButton_Align_4.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_Align_4.setMaximumSize(QtCore.QSize(378, 16777215))
        self.pushButton_Align_4.setChecked(False)
        self.pushButton_Align_4.setObjectName(_fromUtf8("pushButton_Align_4"))
        self.gridLayout_8.addWidget(self.pushButton_Align_4, 11, 0, 1, 2)
        spacerItem5 = QtGui.QSpacerItem(20, 65, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem5, 4, 0, 1, 1)
        self.pushButton_Align_2 = QtGui.QPushButton(self.tab_9)
        self.pushButton_Align_2.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_Align_2.setMaximumSize(QtCore.QSize(378, 16777215))
        self.pushButton_Align_2.setChecked(False)
        self.pushButton_Align_2.setObjectName(_fromUtf8("pushButton_Align_2"))
        self.gridLayout_8.addWidget(self.pushButton_Align_2, 5, 0, 1, 2)
        self.checkBox_5 = QtGui.QCheckBox(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_5.sizePolicy().hasHeightForWidth())
        self.checkBox_5.setSizePolicy(sizePolicy)
        self.checkBox_5.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_5.setStyleSheet(_fromUtf8(""))
        self.checkBox_5.setCheckable(False)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.gridLayout_8.addWidget(self.checkBox_5, 8, 0, 1, 2)
        self.checkBox_4 = QtGui.QCheckBox(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        self.checkBox_4.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_4.setStyleSheet(_fromUtf8(""))
        self.checkBox_4.setCheckable(False)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout_8.addWidget(self.checkBox_4, 11, 2, 1, 1)
        self.pushButton_Align_3.raise_()
        self.pushButton_Align_1.raise_()
        self.pushButton_Prelim_3.raise_()
        self.pushButton_Align_2.raise_()
        self.pushButton_Align_4.raise_()
        self.groupBox_5.raise_()
        self.groupBox_6.raise_()
        self.pushButton_x_down_5.raise_()
        self.pushButton_x_up_5.raise_()
        self.doubleSpinBox_x_1.raise_()
        self.doubleSpinBox_tol_1.raise_()
        self.label_22.raise_()
        self.label_12.raise_()
        self.label_H_1.raise_()
        self.label_23.raise_()
        self.checkBox_3.raise_()
        self.checkBox_5.raise_()
        self.pushButton_x_up_6.raise_()
        self.pushButton_x_down_6.raise_()
        self.checkBox_4.raise_()
        self.tabWidget_2.addTab(self.tab_9, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_26 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.gridLayout_24 = QtGui.QGridLayout()
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.pushButton_fineGetCurrentRange_2 = QtGui.QPushButton(self.tab_3)
        self.pushButton_fineGetCurrentRange_2.setChecked(False)
        self.pushButton_fineGetCurrentRange_2.setObjectName(_fromUtf8("pushButton_fineGetCurrentRange_2"))
        self.gridLayout_24.addWidget(self.pushButton_fineGetCurrentRange_2, 0, 0, 1, 3)
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_24.addWidget(self.label_9, 1, 0, 1, 1)
        self.lineEdit_fineCurrentMin = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_fineCurrentMin.setObjectName(_fromUtf8("lineEdit_fineCurrentMin"))
        self.gridLayout_24.addWidget(self.lineEdit_fineCurrentMin, 1, 1, 1, 1)
        self.lineEdit_fineCurrentMax = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_fineCurrentMax.setObjectName(_fromUtf8("lineEdit_fineCurrentMax"))
        self.gridLayout_24.addWidget(self.lineEdit_fineCurrentMax, 1, 2, 1, 1)
        self.gridLayout_26.addLayout(self.gridLayout_24, 0, 0, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_8.setMinimumSize(QtCore.QSize(230, 200))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.gridLayout_26.addWidget(self.groupBox_8, 0, 1, 3, 1)
        self.gridLayout_25 = QtGui.QGridLayout()
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.pushButton_fineCentreC2VCurrent = QtGui.QPushButton(self.tab_3)
        self.pushButton_fineCentreC2VCurrent.setChecked(False)
        self.pushButton_fineCentreC2VCurrent.setObjectName(_fromUtf8("pushButton_fineCentreC2VCurrent"))
        self.gridLayout_25.addWidget(self.pushButton_fineCentreC2VCurrent, 0, 0, 1, 6)
        self.label_39 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_25.addWidget(self.label_39, 1, 0, 1, 1)
        self.doubleSpinBox_x_3 = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_x_3.setMaximumSize(QtCore.QSize(75, 16777215))
        self.doubleSpinBox_x_3.setReadOnly(True)
        self.doubleSpinBox_x_3.setMinimum(-100.0)
        self.doubleSpinBox_x_3.setMaximum(100.0)
        self.doubleSpinBox_x_3.setSingleStep(0.1)
        self.doubleSpinBox_x_3.setProperty("value", 0.0)
        self.doubleSpinBox_x_3.setObjectName(_fromUtf8("doubleSpinBox_x_3"))
        self.gridLayout_25.addWidget(self.doubleSpinBox_x_3, 1, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_25.addWidget(self.label_40, 1, 2, 1, 1)
        self.doubleSpinBox_tol_3 = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_tol_3.setMaximumSize(QtCore.QSize(75, 16777215))
        self.doubleSpinBox_tol_3.setSingleStep(0.1)
        self.doubleSpinBox_tol_3.setProperty("value", 0.1)
        self.doubleSpinBox_tol_3.setObjectName(_fromUtf8("doubleSpinBox_tol_3"))
        self.gridLayout_25.addWidget(self.doubleSpinBox_tol_3, 1, 3, 1, 1)
        self.label_38 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_25.addWidget(self.label_38, 1, 4, 1, 1)
        self.label_H_3 = QtGui.QLabel(self.tab_3)
        self.label_H_3.setMinimumSize(QtCore.QSize(70, 0))
        self.label_H_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_H_3.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_H_3.setText(_fromUtf8(""))
        self.label_H_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_H_3.setObjectName(_fromUtf8("label_H_3"))
        self.gridLayout_25.addWidget(self.label_H_3, 1, 5, 1, 1)
        self.gridLayout_26.addLayout(self.gridLayout_25, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 103, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_26.addItem(spacerItem6, 2, 0, 1, 1)
        self.groupBox_11 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_11.setMinimumSize(QtCore.QSize(0, 220))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.gridLayout_26.addWidget(self.groupBox_11, 3, 0, 1, 2)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_23 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.gridLayout_22 = QtGui.QGridLayout()
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.label_32 = QtGui.QLabel(self.tab_4)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_22.addWidget(self.label_32, 0, 0, 1, 1)
        self.label_I_fine = QtGui.QLabel(self.tab_4)
        self.label_I_fine.setMinimumSize(QtCore.QSize(50, 0))
        self.label_I_fine.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_I_fine.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_I_fine.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_I_fine.setText(_fromUtf8(""))
        self.label_I_fine.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_I_fine.setObjectName(_fromUtf8("label_I_fine"))
        self.gridLayout_22.addWidget(self.label_I_fine, 4, 1, 1, 2)
        self.label_33 = QtGui.QLabel(self.tab_4)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_22.addWidget(self.label_33, 4, 0, 1, 1)
        self.pushButton_set_I_rough_2 = QtGui.QPushButton(self.tab_4)
        self.pushButton_set_I_rough_2.setObjectName(_fromUtf8("pushButton_set_I_rough_2"))
        self.gridLayout_22.addWidget(self.pushButton_set_I_rough_2, 3, 1, 1, 2)
        self.doubleSpinBox_p_fine_set = QtGui.QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_p_fine_set.setObjectName(_fromUtf8("doubleSpinBox_p_fine_set"))
        self.gridLayout_22.addWidget(self.doubleSpinBox_p_fine_set, 1, 0, 1, 1)
        self.doubleSpinBox_I_3 = QtGui.QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_I_3.setEnabled(False)
        self.doubleSpinBox_I_3.setObjectName(_fromUtf8("doubleSpinBox_I_3"))
        self.gridLayout_22.addWidget(self.doubleSpinBox_I_3, 1, 1, 1, 2)
        self.label_34 = QtGui.QLabel(self.tab_4)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_22.addWidget(self.label_34, 0, 1, 1, 2)
        self.gridLayout_23.addLayout(self.gridLayout_22, 0, 0, 1, 2)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_7.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_7.setAutoFillBackground(False)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.gridLayout_23.addWidget(self.groupBox_7, 0, 2, 4, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 72, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_23.addItem(spacerItem7, 1, 0, 1, 1)
        self.gridLayout_21 = QtGui.QGridLayout()
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.label_29 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_21.addWidget(self.label_29, 0, 0, 1, 1)
        self.pushButton_select_gun_2 = QtGui.QPushButton(self.tab_4)
        self.pushButton_select_gun_2.setAutoFillBackground(False)
        self.pushButton_select_gun_2.setObjectName(_fromUtf8("pushButton_select_gun_2"))
        self.gridLayout_21.addWidget(self.pushButton_select_gun_2, 1, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_21.addWidget(self.label_30, 2, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_21.addWidget(self.label_31, 3, 0, 1, 1)
        self.label_RF_fine = QtGui.QLabel(self.tab_4)
        self.label_RF_fine.setMinimumSize(QtCore.QSize(100, 0))
        self.label_RF_fine.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_RF_fine.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_RF_fine.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_RF_fine.setText(_fromUtf8(""))
        self.label_RF_fine.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_RF_fine.setObjectName(_fromUtf8("label_RF_fine"))
        self.gridLayout_21.addWidget(self.label_RF_fine, 3, 1, 1, 1)
        self.pushButton_x_up_3 = QtGui.QPushButton(self.tab_4)
        self.pushButton_x_up_3.setMinimumSize(QtCore.QSize(20, 12))
        self.pushButton_x_up_3.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(5)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_x_up_3.setFont(font)
        self.pushButton_x_up_3.setStyleSheet(_fromUtf8("QPushButton{ color: rgb(0, 0, 0);font: 75 5pt \"MS Shell Dlg 2\";}\n"
""))
        self.pushButton_x_up_3.setAutoDefault(False)
        self.pushButton_x_up_3.setObjectName(_fromUtf8("pushButton_x_up_3"))
        self.gridLayout_21.addWidget(self.pushButton_x_up_3, 3, 2, 1, 1)
        self.pushButton_x_down_3 = QtGui.QPushButton(self.tab_4)
        self.pushButton_x_down_3.setMinimumSize(QtCore.QSize(20, 12))
        self.pushButton_x_down_3.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(5)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_x_down_3.setFont(font)
        self.pushButton_x_down_3.setStyleSheet(_fromUtf8("QPushButton{ color: rgb(0, 0, 0);font: 75 5pt \"MS Shell Dlg 2\";}"))
        self.pushButton_x_down_3.setObjectName(_fromUtf8("pushButton_x_down_3"))
        self.gridLayout_21.addWidget(self.pushButton_x_down_3, 3, 3, 1, 1)
        self.doubleSpinBox_step_3 = QtGui.QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_step_3.setSuffix(_fromUtf8(""))
        self.doubleSpinBox_step_3.setDecimals(2)
        self.doubleSpinBox_step_3.setMaximum(1000.0)
        self.doubleSpinBox_step_3.setSingleStep(10.0)
        self.doubleSpinBox_step_3.setProperty("value", 100.0)
        self.doubleSpinBox_step_3.setObjectName(_fromUtf8("doubleSpinBox_step_3"))
        self.gridLayout_21.addWidget(self.doubleSpinBox_step_3, 2, 1, 1, 1)
        self.pushButton_select_linac_2 = QtGui.QPushButton(self.tab_4)
        self.pushButton_select_linac_2.setObjectName(_fromUtf8("pushButton_select_linac_2"))
        self.gridLayout_21.addWidget(self.pushButton_select_linac_2, 1, 1, 1, 1)
        self.lineEdit_RFmode_fine = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_RFmode_fine.setObjectName(_fromUtf8("lineEdit_RFmode_fine"))
        self.gridLayout_21.addWidget(self.lineEdit_RFmode_fine, 1, 2, 1, 2)
        self.gridLayout_23.addLayout(self.gridLayout_21, 2, 0, 1, 2)
        spacerItem8 = QtGui.QSpacerItem(20, 148, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_23.addItem(spacerItem8, 3, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget_2, 4, 0, 1, 1)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 661, 577))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.label_10 = QtGui.QLabel(self.page_4)
        self.label_10.setGeometry(QtCore.QRect(10, 0, 639, 32))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.pushButton_MinBeta = QtGui.QPushButton(self.page_4)
        self.pushButton_MinBeta.setGeometry(QtCore.QRect(10, 142, 235, 22))
        self.pushButton_MinBeta.setChecked(False)
        self.pushButton_MinBeta.setObjectName(_fromUtf8("pushButton_MinBeta"))
        self.pushButton_Calc = QtGui.QPushButton(self.page_4)
        self.pushButton_Calc.setGeometry(QtCore.QRect(10, 454, 235, 22))
        self.pushButton_Calc.setChecked(False)
        self.pushButton_Calc.setObjectName(_fromUtf8("pushButton_Calc"))
        self.pushButton_SetDispSize = QtGui.QPushButton(self.page_4)
        self.pushButton_SetDispSize.setGeometry(QtCore.QRect(10, 246, 235, 22))
        self.pushButton_SetDispSize.setObjectName(_fromUtf8("pushButton_SetDispSize"))
        self.pushButton_Checks = QtGui.QPushButton(self.page_4)
        self.pushButton_Checks.setGeometry(QtCore.QRect(10, 38, 235, 22))
        self.pushButton_Checks.setChecked(False)
        self.pushButton_Checks.setObjectName(_fromUtf8("pushButton_Checks"))
        self.pushButton_CalcDisp = QtGui.QPushButton(self.page_4)
        self.pushButton_CalcDisp.setGeometry(QtCore.QRect(10, 350, 235, 22))
        self.pushButton_CalcDisp.setChecked(False)
        self.pushButton_CalcDisp.setObjectName(_fromUtf8("pushButton_CalcDisp"))
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.toolBox, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(3)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox_2.setCurrentIndex(1)
        self.toolBox_3.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Quick converter", None))
        self.label_14.setText(_translate("MainWindow", "Dipole current", None))
        self.doubleSpinBox_I.setSuffix(_translate("MainWindow", " A", None))
        self.label_13.setText(_translate("MainWindow", "Momentum", None))
        self.doubleSpinBox_p.setSuffix(_translate("MainWindow", " MeV/c", None))
        self.label.setText(_translate("MainWindow", "Work from top to bottom through the steps below to measure momentum and momentum spread.", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), _translate("MainWindow", "Introduction", None))
        self.doubleSpinBox_I_predict.setSuffix(_translate("MainWindow", " A", None))
        self.pushButton_useCurrent.setText(_translate("MainWindow", "Use current from dipole", None))
        self.label_3.setText(_translate("MainWindow", "Predicted Momentum", None))
        self.doubleSpinBox_p_predict.setSuffix(_translate("MainWindow", " MeV/c", None))
        self.pushButton_useRF.setText(_translate("MainWindow", "Predict momentum from RF", None))
        self.label_4.setText(_translate("MainWindow", "Dipole current", None))
        self.label_I.setText(_translate("MainWindow", "...", None))
        self.label_2.setText(_translate("MainWindow", "Skip this step if beam already on C2V BPM\n"
"Otherwise use either magnet or RF settings to predict the momentum", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Predicted Momentum", None))
        self.label_5.setText(_translate("MainWindow", "If beam is already on C2V BPM then centre it to get a rough momentum measurement\n"
"Otherwise scan dipole to find C2V BPM signal, then do centering", None))
        self.label_16.setText(_translate("MainWindow", "S02-DIP-01 adjustment", None))
        self.label_15.setText(_translate("MainWindow", "Step size [A]", None))
        self.doubleSpinBox_step_1.setSuffix(_translate("MainWindow", " A", None))
        self.label_17.setText(_translate("MainWindow", "Set value [A]", None))
        self.pushButton_x_up_1.setText(_translate("MainWindow", "▲", None))
        self.pushButton_x_down_1.setText(_translate("MainWindow", "▼", None))
        self.pushButton_get_p_rough.setText(_translate("MainWindow", "Get Momentum", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "C2V BPM", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_5), _translate("MainWindow", "Centre beam on C2V BPM", None))
        self.pushButton_roughGetCurrentRange.setText(_translate("MainWindow", "Get scan range from predicted mom. (min/max/step):", None))
        self.doubleSpinBox_roughIMin.setSuffix(_translate("MainWindow", " A", None))
        self.doubleSpinBox_roughIMax.setSuffix(_translate("MainWindow", " A", None))
        self.doubleSpinBox_roughIStep.setSuffix(_translate("MainWindow", " A", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "C2V BPM x-pos vs dipole setting", None))
        self.pushButton_roughCentreC2VCurrent.setText(_translate("MainWindow", "Scan dipole", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_6), _translate("MainWindow", "Scan dipole to find beam on C2V BPM", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Measure", None))
        self.label_7.setText(_translate("MainWindow", "Confirm whether gun only or gun + linac. Select momentum then set current.\n"
"Set RF amplitude to centre on C2V", None))
        self.label_18.setText(_translate("MainWindow", "Set target momentum:", None))
        self.label_28.setText(_translate("MainWindow", "Dipole current set [A]", None))
        self.pushButton_set_I_rough.setText(_translate("MainWindow", "Set Current", None))
        self.doubleSpinBox_p_rough_set.setSuffix(_translate("MainWindow", " MeV/c", None))
        self.doubleSpinBox_I_2.setSuffix(_translate("MainWindow", " A", None))
        self.label_27.setText(_translate("MainWindow", "Dipole current", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "C2V BPM", None))
        self.label_19.setText(_translate("MainWindow", "RF adjustment", None))
        self.pushButton_select_gun.setText(_translate("MainWindow", "Vary gun", None))
        self.label_20.setText(_translate("MainWindow", "Step size", None))
        self.label_21.setText(_translate("MainWindow", "Set value", None))
        self.pushButton_x_up_2.setText(_translate("MainWindow", "▲", None))
        self.pushButton_x_down_2.setText(_translate("MainWindow", "▼", None))
        self.pushButton_select_linac.setText(_translate("MainWindow", "Vary linac", None))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_8), _translate("MainWindow", "Centre beam on C2V BPM", None))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_9), _translate("MainWindow", "Scan RF to find beam on C2V BPM", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Set", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Rough Momentum Measure/Set", None))
        self.label_8.setText(_translate("MainWindow", "Need to have completed rough measurement to continue\n"
"Need to align beam through dipole for both fine measure and fine set", None))
        self.label_24.setText(_translate("MainWindow", "Target", None))
        self.doubleSpinBox_x_2.setSuffix(_translate("MainWindow", " mm", None))
        self.label_25.setText(_translate("MainWindow", "Tol.", None))
        self.doubleSpinBox_tol_2.setSuffix(_translate("MainWindow", " mm", None))
        self.label_26.setText(_translate("MainWindow", "Δx", None))
        self.label_22.setText(_translate("MainWindow", "Target", None))
        self.doubleSpinBox_x_1.setSuffix(_translate("MainWindow", " mm", None))
        self.label_12.setText(_translate("MainWindow", "Tol.", None))
        self.doubleSpinBox_tol_1.setSuffix(_translate("MainWindow", " mm", None))
        self.label_23.setText(_translate("MainWindow", "Δx", None))
        self.pushButton_Align_1.setText(_translate("MainWindow", "2. Align on S02-BPM02 using S02-HCOR02", None))
        self.pushButton_x_up_6.setText(_translate("MainWindow", "▲", None))
        self.pushButton_x_down_6.setText(_translate("MainWindow", "▼", None))
        self.pushButton_Align_3.setText(_translate("MainWindow", "4. Align on S02-YAG02 using S02-HCOR01", None))
        self.pushButton_x_up_5.setText(_translate("MainWindow", "▲", None))
        self.pushButton_x_down_5.setText(_translate("MainWindow", "▼", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "S02-YAG02", None))
        self.checkBox_3.setText(_translate("MainWindow", "Aligned on S02-BPM02", None))
        self.pushButton_Prelim_3.setText(_translate("MainWindow", "1. Degauss to zero: S02-DIP01, Q-03,04,05", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "S02-BPM02", None))
        self.pushButton_Align_4.setText(_translate("MainWindow", "5. Retract S02-YAG02 and test alignment", None))
        self.pushButton_Align_2.setText(_translate("MainWindow", "3. Insert S02-YAG02", None))
        self.checkBox_5.setText(_translate("MainWindow", "Aligned on S02-YAG02", None))
        self.checkBox_4.setText(_translate("MainWindow", "Still aligned on S02-BPM02 ?", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "Align through dipole", None))
        self.pushButton_fineGetCurrentRange_2.setText(_translate("MainWindow", "1. Get scan range from rough measurement", None))
        self.label_9.setText(_translate("MainWindow", "Dipole min/max:", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "C2V BPM", None))
        self.pushButton_fineCentreC2VCurrent.setText(_translate("MainWindow", "2. Start scan", None))
        self.label_39.setText(_translate("MainWindow", "Target", None))
        self.doubleSpinBox_x_3.setSuffix(_translate("MainWindow", " mm", None))
        self.label_40.setText(_translate("MainWindow", "Tol.", None))
        self.doubleSpinBox_tol_3.setSuffix(_translate("MainWindow", " mm", None))
        self.label_38.setText(_translate("MainWindow", "Δx", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "C2V BPM x-pos vs dipole setting", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Measure", None))
        self.label_32.setText(_translate("MainWindow", "Set target momentum:", None))
        self.label_33.setText(_translate("MainWindow", "Dipole current set", None))
        self.pushButton_set_I_rough_2.setText(_translate("MainWindow", "Set Current", None))
        self.doubleSpinBox_p_fine_set.setSuffix(_translate("MainWindow", " MeV/c", None))
        self.doubleSpinBox_I_3.setSuffix(_translate("MainWindow", " A", None))
        self.label_34.setText(_translate("MainWindow", "Dipole current", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "C2V BPM", None))
        self.label_29.setText(_translate("MainWindow", "RF adjustment", None))
        self.pushButton_select_gun_2.setText(_translate("MainWindow", "Vary gun", None))
        self.label_30.setText(_translate("MainWindow", "Step size", None))
        self.label_31.setText(_translate("MainWindow", "Set value", None))
        self.pushButton_x_up_3.setText(_translate("MainWindow", "▲", None))
        self.pushButton_x_down_3.setText(_translate("MainWindow", "▼", None))
        self.pushButton_select_linac_2.setText(_translate("MainWindow", "Vary linac", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Set", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Fine Momentum Measure/Set", None))
        self.label_10.setText(_translate("MainWindow", "Need to have completed rough measurement to continue", None))
        self.pushButton_MinBeta.setText(_translate("MainWindow", "2. Minimise Beta", None))
        self.pushButton_Calc.setText(_translate("MainWindow", "4. Calculate Momentum Spread", None))
        self.pushButton_SetDispSize.setText(_translate("MainWindow", "3. Set Dispersion Size", None))
        self.pushButton_Checks.setText(_translate("MainWindow", "1. Checks", None))
        self.pushButton_CalcDisp.setText(_translate("MainWindow", "3. Calculate Dispersion", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "Momentum Spread Measure", None))

