# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_v1.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(647, 830)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_10 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_10.setMinimumSize(QtCore.QSize(0, 71))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_19 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.label_14 = QtGui.QLabel(self.groupBox_10)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_19.addWidget(self.label_14, 0, 0, 1, 1)
        self.doubleSpinBox_I = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_I.setObjectName(_fromUtf8("doubleSpinBox_I"))
        self.gridLayout_19.addWidget(self.doubleSpinBox_I, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_10)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_19.addWidget(self.label_13, 0, 1, 1, 1)
        self.doubleSpinBox_p = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_p.setObjectName(_fromUtf8("doubleSpinBox_p"))
        self.gridLayout_19.addWidget(self.doubleSpinBox_p, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_10, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 71))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.toolBox = QtGui.QToolBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.toolBox.setFont(font)
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setStyleSheet(_fromUtf8(""))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.gridLayout_20 = QtGui.QGridLayout(self.page_7)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.label = QtGui.QLabel(self.page_7)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_20.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.toolBox.addItem(self.page_7, _fromUtf8(""))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 601, 512))
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_7 = QtGui.QGridLayout(self.page)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.groupBox_5 = QtGui.QGroupBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_4 = QtGui.QLabel(self.groupBox_5)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 2, 1, 1)
        self.pushButton_useCurrent = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_useCurrent.sizePolicy().hasHeightForWidth())
        self.pushButton_useCurrent.setSizePolicy(sizePolicy)
        self.pushButton_useCurrent.setMinimumSize(QtCore.QSize(140, 22))
        self.pushButton_useCurrent.setMaximumSize(QtCore.QSize(371, 16777215))
        self.pushButton_useCurrent.setChecked(False)
        self.pushButton_useCurrent.setObjectName(_fromUtf8("pushButton_useCurrent"))
        self.gridLayout_4.addWidget(self.pushButton_useCurrent, 1, 0, 1, 1)
        self.doubleSpinBox_I_2 = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.doubleSpinBox_I_2.setObjectName(_fromUtf8("doubleSpinBox_I_2"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_I_2, 1, 1, 1, 1)
        self.doubleSpinBox_p_2 = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.doubleSpinBox_p_2.setObjectName(_fromUtf8("doubleSpinBox_p_2"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_p_2, 1, 2, 1, 1)
        self.pushButton_useRF = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_useRF.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_useRF.sizePolicy().hasHeightForWidth())
        self.pushButton_useRF.setSizePolicy(sizePolicy)
        self.pushButton_useRF.setMinimumSize(QtCore.QSize(140, 22))
        self.pushButton_useRF.setMaximumSize(QtCore.QSize(371, 16777215))
        font = QtGui.QFont()
        self.pushButton_useRF.setFont(font)
        self.pushButton_useRF.setChecked(False)
        self.pushButton_useRF.setObjectName(_fromUtf8("pushButton_useRF"))
        self.gridLayout_4.addWidget(self.pushButton_useRF, 1, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.page)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_18 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_18.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.page)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_7.addWidget(self.label_7, 2, 0, 1, 1, QtCore.Qt.AlignTop)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 601, 512))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.page_2)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tab)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_7.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_7.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.label_6 = QtGui.QLabel(self.groupBox_7)
        self.label_6.setStyleSheet(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_14.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.toolBox_2 = QtGui.QToolBox(self.tab)
        self.toolBox_2.setObjectName(_fromUtf8("toolBox_2"))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 551, 298))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.gridLayout_17 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.label_12 = QtGui.QLabel(self.page_5)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_16.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.page_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_16.addWidget(self.label_11, 0, 1, 1, 1)
        self.doubleSpinBox_I_3 = QtGui.QDoubleSpinBox(self.page_5)
        self.doubleSpinBox_I_3.setObjectName(_fromUtf8("doubleSpinBox_I_3"))
        self.gridLayout_16.addWidget(self.doubleSpinBox_I_3, 1, 0, 1, 1)
        self.doubleSpinBox_p_3 = QtGui.QDoubleSpinBox(self.page_5)
        self.doubleSpinBox_p_3.setObjectName(_fromUtf8("doubleSpinBox_p_3"))
        self.gridLayout_16.addWidget(self.doubleSpinBox_p_3, 1, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.page_5)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_16.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.toolBox_2.addItem(self.page_5, _fromUtf8(""))
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 655, 362))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.gridLayout_13 = QtGui.QGridLayout(self.page_6)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.groupBox_2 = QtGui.QGroupBox(self.page_6)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_12.addWidget(self.groupBox_2, 2, 0, 1, 4)
        self.lineEdit_roughCurrentMax = QtGui.QLineEdit(self.page_6)
        self.lineEdit_roughCurrentMax.setObjectName(_fromUtf8("lineEdit_roughCurrentMax"))
        self.gridLayout_12.addWidget(self.lineEdit_roughCurrentMax, 0, 2, 1, 1)
        self.lineEdit_roughCurrentMin = QtGui.QLineEdit(self.page_6)
        self.lineEdit_roughCurrentMin.setObjectName(_fromUtf8("lineEdit_roughCurrentMin"))
        self.gridLayout_12.addWidget(self.lineEdit_roughCurrentMin, 0, 1, 1, 1)
        self.pushButton_roughCentreC2VCurrent = QtGui.QPushButton(self.page_6)
        self.pushButton_roughCentreC2VCurrent.setChecked(False)
        self.pushButton_roughCentreC2VCurrent.setObjectName(_fromUtf8("pushButton_roughCentreC2VCurrent"))
        self.gridLayout_12.addWidget(self.pushButton_roughCentreC2VCurrent, 1, 0, 1, 4)
        self.lineEdit_roughCurrentMax_2 = QtGui.QLineEdit(self.page_6)
        self.lineEdit_roughCurrentMax_2.setObjectName(_fromUtf8("lineEdit_roughCurrentMax_2"))
        self.gridLayout_12.addWidget(self.lineEdit_roughCurrentMax_2, 0, 3, 1, 1)
        self.pushButton_roughGetCurrentRange = QtGui.QPushButton(self.page_6)
        self.pushButton_roughGetCurrentRange.setChecked(False)
        self.pushButton_roughGetCurrentRange.setObjectName(_fromUtf8("pushButton_roughGetCurrentRange"))
        self.gridLayout_12.addWidget(self.pushButton_roughGetCurrentRange, 0, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.toolBox_2.addItem(self.page_6, _fromUtf8(""))
        self.gridLayout_11.addWidget(self.toolBox_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 10, 661, 90))
        self.groupBox_8.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_8.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.label_8 = QtGui.QLabel(self.groupBox_8)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_15.addWidget(self.label_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 601, 512))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget_2 = QtGui.QTabWidget(self.page_3)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget_2, 2, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.page_3)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 70))
        self.groupBox_6.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_6)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_8.addWidget(self.label_9, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.tabWidget_3 = QtGui.QTabWidget(self.page_3)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tabWidget_3.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget_3, 1, 0, 1, 1)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 601, 512))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.gridLayout_10 = QtGui.QGridLayout(self.page_4)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.groupBox_9 = QtGui.QGroupBox(self.page_4)
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 70))
        self.groupBox_9.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_9)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_9.addWidget(self.label_10, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_9, 0, 0, 1, 1)
        self.tabWidget_4 = QtGui.QTabWidget(self.page_4)
        self.tabWidget_4.setObjectName(_fromUtf8("tabWidget_4"))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tabWidget_4.addTab(self.tab_6, _fromUtf8(""))
        self.gridLayout_10.addWidget(self.tabWidget_4, 1, 0, 1, 1)
        self.tabWidget_5 = QtGui.QTabWidget(self.page_4)
        self.tabWidget_5.setObjectName(_fromUtf8("tabWidget_5"))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.tabWidget_5.addTab(self.tab_7, _fromUtf8(""))
        self.gridLayout_10.addWidget(self.tabWidget_5, 2, 0, 1, 1)
        self.tabWidget_6 = QtGui.QTabWidget(self.page_4)
        self.tabWidget_6.setObjectName(_fromUtf8("tabWidget_6"))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.tabWidget_6.addTab(self.tab_8, _fromUtf8(""))
        self.gridLayout_10.addWidget(self.tabWidget_6, 3, 0, 1, 1)
        self.tabWidget_7 = QtGui.QTabWidget(self.page_4)
        self.tabWidget_7.setObjectName(_fromUtf8("tabWidget_7"))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.tabWidget_7.addTab(self.tab_10, _fromUtf8(""))
        self.gridLayout_10.addWidget(self.tabWidget_7, 4, 0, 1, 1)
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.toolBox, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox_2.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        self.tabWidget_6.setCurrentIndex(0)
        self.tabWidget_7.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Quick converter", None))
        self.label_14.setText(_translate("MainWindow", "Dipole current", None))
        self.doubleSpinBox_I.setSuffix(_translate("MainWindow", " A", None))
        self.label_13.setText(_translate("MainWindow", "Momentum", None))
        self.doubleSpinBox_p.setSuffix(_translate("MainWindow", " MeV/c", None))
        self.label.setText(_translate("MainWindow", "Work from top to bottom through the steps below to measure momentum and momentum spread.", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), _translate("MainWindow", "Introduction", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Get estimate", None))
        self.label_4.setText(_translate("MainWindow", "Dipole current", None))
        self.label_3.setText(_translate("MainWindow", "Predicted Momentum", None))
        self.pushButton_useCurrent.setText(_translate("MainWindow", "Use current from dipole", None))
        self.doubleSpinBox_I_2.setSuffix(_translate("MainWindow", " A", None))
        self.doubleSpinBox_p_2.setSuffix(_translate("MainWindow", " MeV/c", None))
        self.pushButton_useRF.setText(_translate("MainWindow", "Predict momentum from RF", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Instructions", None))
        self.label_5.setText(_translate("MainWindow", "Use either magnet or RF settings to predict the momentum", None))
        self.label_7.setText(_translate("MainWindow", "Show C2V BPM readout and live/not live\n"
"Show relevant RF settings\n"
"Show dipole current\n"
"Show latest measured value?", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Predicted Momentum", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Instructions", None))
        self.label_6.setText(_translate("MainWindow", "If beam is already on C2V BPM then centre it to get rough momentum measurement\n"
"Otherwise scan dipole to find C2V BPM signal, then centre it if necessary", None))
        self.label_12.setText(_translate("MainWindow", "Dipole current", None))
        self.label_11.setText(_translate("MainWindow", "Rough Momentum", None))
        self.doubleSpinBox_I_3.setSuffix(_translate("MainWindow", " A", None))
        self.doubleSpinBox_p_3.setSuffix(_translate("MainWindow", " MeV/c", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "C2V BPM", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_5), _translate("MainWindow", "Centre beam on C2V BPM, calculate momentum", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "C2V BPM x-pos vs dipole setting", None))
        self.pushButton_roughCentreC2VCurrent.setText(_translate("MainWindow", "Scan dipole", None))
        self.pushButton_roughGetCurrentRange.setText(_translate("MainWindow", "Get scan range from initial estimate (min/max/step):", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_6), _translate("MainWindow", "Scan dipole to find beam on C2V BPM", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Measure", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Instructions", None))
        self.label_8.setText(_translate("MainWindow", "Confirm whether gun only or gun + linac\n"
"Select momentum - current will be automatically set\n"
"Set RF amplitude to centre on C2V", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Set", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Rough Momentum Measure/Set", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Measure", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Set", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Instructions", None))
        self.label_9.setText(_translate("MainWindow", "Need to have completed rough measurement to continue\n"
"Need to align beam through dipole for both fine measure and fine set", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("MainWindow", "Align beam through dipole", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Fine Momentum Measure/Set", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Show relevant information", None))
        self.label_10.setText(_translate("MainWindow", "Need to have done fine momentum measurement to continue", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_6), _translate("MainWindow", "Beta minimisation", None))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_7), _translate("MainWindow", "Set dispersion size", None))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_8), _translate("MainWindow", "Calculate dispersion", None))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_10), _translate("MainWindow", "Calculate Momentum Spread", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "Momentum Spread Measure", None))

