# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_mainView.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainView(object):
    def setupUi(self, mainView):
        mainView.setObjectName(_fromUtf8("mainView"))
        mainView.resize(1201, 871)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainView.sizePolicy().hasHeightForWidth())
        mainView.setSizePolicy(sizePolicy)
        mainView.setMinimumSize(QtCore.QSize(1038, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainView.setWindowIcon(icon)
        mainView.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(mainView)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.acquire_pushButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acquire_pushButton.sizePolicy().hasHeightForWidth())
        self.acquire_pushButton.setSizePolicy(sizePolicy)
        self.acquire_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.acquire_pushButton.setObjectName(_fromUtf8("acquire_pushButton"))
        self.horizontalLayout_10.addWidget(self.acquire_pushButton)
        self.analyse_pushButton_2 = QtGui.QPushButton(self.tab)
        self.analyse_pushButton_2.setObjectName(_fromUtf8("analyse_pushButton_2"))
        self.horizontalLayout_10.addWidget(self.analyse_pushButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.collectAndSave_pushButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collectAndSave_pushButton.sizePolicy().hasHeightForWidth())
        self.collectAndSave_pushButton.setSizePolicy(sizePolicy)
        self.collectAndSave_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.collectAndSave_pushButton.setObjectName(_fromUtf8("collectAndSave_pushButton"))
        self.verticalLayout_3.addWidget(self.collectAndSave_pushButton)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.numImages_spinBox = QtGui.QSpinBox(self.tab)
        self.numImages_spinBox.setMinimum(1)
        self.numImages_spinBox.setObjectName(_fromUtf8("numImages_spinBox"))
        self.horizontalLayout_8.addWidget(self.numImages_spinBox)
        self.copy_path_pushButton = QtGui.QPushButton(self.tab)
        self.copy_path_pushButton.setMinimumSize(QtCore.QSize(60, 0))
        self.copy_path_pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.copy_path_pushButton.setObjectName(_fromUtf8("copy_path_pushButton"))
        self.horizontalLayout_8.addWidget(self.copy_path_pushButton)
        self.open_path_push_button = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_path_push_button.sizePolicy().hasHeightForWidth())
        self.open_path_push_button.setSizePolicy(sizePolicy)
        self.open_path_push_button.setMinimumSize(QtCore.QSize(60, 0))
        self.open_path_push_button.setMaximumSize(QtCore.QSize(50, 16777215))
        self.open_path_push_button.setObjectName(_fromUtf8("open_path_push_button"))
        self.horizontalLayout_8.addWidget(self.open_path_push_button)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.last_filename = QtGui.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.last_filename.setFont(font)
        self.last_filename.setReadOnly(True)
        self.last_filename.setObjectName(_fromUtf8("last_filename"))
        self.verticalLayout_2.addWidget(self.last_filename)
        self.last_directory = QtGui.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.last_directory.setFont(font)
        self.last_directory.setReadOnly(True)
        self.last_directory.setObjectName(_fromUtf8("last_directory"))
        self.verticalLayout_2.addWidget(self.last_directory)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.avPixIntensity_label_9 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.avPixIntensity_label_9.setFont(font)
        self.avPixIntensity_label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.avPixIntensity_label_9.setObjectName(_fromUtf8("avPixIntensity_label_9"))
        self.gridLayout_2.addWidget(self.avPixIntensity_label_9, 0, 0, 1, 1)
        self.H_step_read = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.H_step_read.setFont(font)
        self.H_step_read.setObjectName(_fromUtf8("H_step_read"))
        self.gridLayout_2.addWidget(self.H_step_read, 0, 1, 1, 1)
        self.mirror_h_step_set_spinBox = QtGui.QDoubleSpinBox(self.tab)
        self.mirror_h_step_set_spinBox.setObjectName(_fromUtf8("mirror_h_step_set_spinBox"))
        self.gridLayout_2.addWidget(self.mirror_h_step_set_spinBox, 0, 2, 1, 1)
        self.move_H_left_pushButton = QtGui.QPushButton(self.tab)
        self.move_H_left_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.move_H_left_pushButton.setObjectName(_fromUtf8("move_H_left_pushButton"))
        self.gridLayout_2.addWidget(self.move_H_left_pushButton, 0, 3, 1, 1)
        self.move_H_right_pushButton = QtGui.QPushButton(self.tab)
        self.move_H_right_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.move_H_right_pushButton.setObjectName(_fromUtf8("move_H_right_pushButton"))
        self.gridLayout_2.addWidget(self.move_H_right_pushButton, 0, 4, 1, 1)
        self.avPixIntensity_label_10 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.avPixIntensity_label_10.setFont(font)
        self.avPixIntensity_label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.avPixIntensity_label_10.setObjectName(_fromUtf8("avPixIntensity_label_10"))
        self.gridLayout_2.addWidget(self.avPixIntensity_label_10, 1, 0, 1, 1)
        self.V_step_read = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.V_step_read.setFont(font)
        self.V_step_read.setObjectName(_fromUtf8("V_step_read"))
        self.gridLayout_2.addWidget(self.V_step_read, 1, 1, 1, 1)
        self.mirror_v_step_set_spinBox = QtGui.QDoubleSpinBox(self.tab)
        self.mirror_v_step_set_spinBox.setObjectName(_fromUtf8("mirror_v_step_set_spinBox"))
        self.gridLayout_2.addWidget(self.mirror_v_step_set_spinBox, 1, 2, 1, 1)
        self.move_V_down_pushButton = QtGui.QPushButton(self.tab)
        self.move_V_down_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.move_V_down_pushButton.setObjectName(_fromUtf8("move_V_down_pushButton"))
        self.gridLayout_2.addWidget(self.move_V_down_pushButton, 1, 3, 1, 1)
        self.move_V_up_pushButton = QtGui.QPushButton(self.tab)
        self.move_V_up_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.move_V_up_pushButton.setObjectName(_fromUtf8("move_V_up_pushButton"))
        self.gridLayout_2.addWidget(self.move_V_up_pushButton, 1, 4, 1, 1)
        self.avPixIntensity_label_21 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.avPixIntensity_label_21.setFont(font)
        self.avPixIntensity_label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.avPixIntensity_label_21.setObjectName(_fromUtf8("avPixIntensity_label_21"))
        self.gridLayout_2.addWidget(self.avPixIntensity_label_21, 2, 0, 1, 1)
        self.hwp_read = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.hwp_read.setFont(font)
        self.hwp_read.setObjectName(_fromUtf8("hwp_read"))
        self.gridLayout_2.addWidget(self.hwp_read, 2, 1, 1, 1)
        self.hwp_set_spinBox = QtGui.QDoubleSpinBox(self.tab)
        self.hwp_set_spinBox.setProperty("value", 1.0)
        self.hwp_set_spinBox.setObjectName(_fromUtf8("hwp_set_spinBox"))
        self.gridLayout_2.addWidget(self.hwp_set_spinBox, 2, 2, 1, 1)
        self.hwp_down_pushButton = QtGui.QPushButton(self.tab)
        self.hwp_down_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.hwp_down_pushButton.setObjectName(_fromUtf8("hwp_down_pushButton"))
        self.gridLayout_2.addWidget(self.hwp_down_pushButton, 2, 3, 1, 1)
        self.hwp_up_pushButton = QtGui.QPushButton(self.tab)
        self.hwp_up_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.hwp_up_pushButton.setObjectName(_fromUtf8("hwp_up_pushButton"))
        self.gridLayout_2.addWidget(self.hwp_up_pushButton, 2, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.line_2 = QtGui.QFrame(self.tab)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_3.addWidget(self.line_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.wcm_spinBox = QtGui.QDoubleSpinBox(self.tab)
        self.wcm_spinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.wcm_spinBox.setMaximum(500.0)
        self.wcm_spinBox.setObjectName(_fromUtf8("wcm_spinBox"))
        self.gridLayout.addWidget(self.wcm_spinBox, 1, 2, 1, 1)
        self.wcm_val_2 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.wcm_val_2.setFont(font)
        self.wcm_val_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wcm_val_2.setObjectName(_fromUtf8("wcm_val_2"))
        self.gridLayout.addWidget(self.wcm_val_2, 1, 1, 1, 1)
        self.avPixIntensity_label_11 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.avPixIntensity_label_11.setFont(font)
        self.avPixIntensity_label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.avPixIntensity_label_11.setObjectName(_fromUtf8("avPixIntensity_label_11"))
        self.gridLayout.addWidget(self.avPixIntensity_label_11, 1, 0, 1, 1)
        self.setInt_pushButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setInt_pushButton.sizePolicy().hasHeightForWidth())
        self.setInt_pushButton.setSizePolicy(sizePolicy)
        self.setInt_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.setInt_pushButton.setObjectName(_fromUtf8("setInt_pushButton"))
        self.gridLayout.addWidget(self.setInt_pushButton, 0, 3, 1, 1)
        self.intensity_spinBox = QtGui.QDoubleSpinBox(self.tab)
        self.intensity_spinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.intensity_spinBox.setMaximum(10.0)
        self.intensity_spinBox.setSingleStep(0.1)
        self.intensity_spinBox.setObjectName(_fromUtf8("intensity_spinBox"))
        self.gridLayout.addWidget(self.intensity_spinBox, 0, 2, 1, 1)
        self.int_val_2 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.int_val_2.setFont(font)
        self.int_val_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.int_val_2.setObjectName(_fromUtf8("int_val_2"))
        self.gridLayout.addWidget(self.int_val_2, 0, 1, 1, 1)
        self.avPixIntensity_label_6 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.avPixIntensity_label_6.setFont(font)
        self.avPixIntensity_label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.avPixIntensity_label_6.setObjectName(_fromUtf8("avPixIntensity_label_6"))
        self.gridLayout.addWidget(self.avPixIntensity_label_6, 0, 0, 1, 1)
        self.setWCM_pushButton = QtGui.QPushButton(self.tab)
        self.setWCM_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.setWCM_pushButton.setObjectName(_fromUtf8("setWCM_pushButton"))
        self.gridLayout.addWidget(self.setWCM_pushButton, 1, 3, 1, 1)
        self.avPixIntensity_label_8 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.avPixIntensity_label_8.setFont(font)
        self.avPixIntensity_label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.avPixIntensity_label_8.setObjectName(_fromUtf8("avPixIntensity_label_8"))
        self.gridLayout.addWidget(self.avPixIntensity_label_8, 2, 0, 1, 1)
        self.x_val_2 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.x_val_2.setFont(font)
        self.x_val_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x_val_2.setObjectName(_fromUtf8("x_val_2"))
        self.gridLayout.addWidget(self.x_val_2, 2, 1, 1, 1)
        self.xpos_spinBox = QtGui.QDoubleSpinBox(self.tab)
        self.xpos_spinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.xpos_spinBox.setMaximum(10.0)
        self.xpos_spinBox.setSingleStep(0.1)
        self.xpos_spinBox.setObjectName(_fromUtf8("xpos_spinBox"))
        self.gridLayout.addWidget(self.xpos_spinBox, 2, 2, 1, 1)
        self.set_xpos_pushButton = QtGui.QPushButton(self.tab)
        self.set_xpos_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.set_xpos_pushButton.setObjectName(_fromUtf8("set_xpos_pushButton"))
        self.gridLayout.addWidget(self.set_xpos_pushButton, 2, 3, 1, 1)
        self.avPixIntensity_label_7 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.avPixIntensity_label_7.setFont(font)
        self.avPixIntensity_label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.avPixIntensity_label_7.setObjectName(_fromUtf8("avPixIntensity_label_7"))
        self.gridLayout.addWidget(self.avPixIntensity_label_7, 3, 0, 1, 1)
        self.y_val_2 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.y_val_2.setFont(font)
        self.y_val_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.y_val_2.setObjectName(_fromUtf8("y_val_2"))
        self.gridLayout.addWidget(self.y_val_2, 3, 1, 1, 1)
        self.ypos_spinBox = QtGui.QDoubleSpinBox(self.tab)
        self.ypos_spinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.ypos_spinBox.setMaximum(10.0)
        self.ypos_spinBox.setSingleStep(0.1)
        self.ypos_spinBox.setObjectName(_fromUtf8("ypos_spinBox"))
        self.gridLayout.addWidget(self.ypos_spinBox, 3, 2, 1, 1)
        self.set_ypos_pushButton = QtGui.QPushButton(self.tab)
        self.set_ypos_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.set_ypos_pushButton.setObjectName(_fromUtf8("set_ypos_pushButton"))
        self.gridLayout.addWidget(self.set_ypos_pushButton, 3, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.load_pushButton = QtGui.QPushButton(self.tab)
        self.load_pushButton.setObjectName(_fromUtf8("load_pushButton"))
        self.horizontalLayout_6.addWidget(self.load_pushButton)
        self.save_pushButton = QtGui.QPushButton(self.tab)
        self.save_pushButton.setObjectName(_fromUtf8("save_pushButton"))
        self.horizontalLayout_6.addWidget(self.save_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.line_8 = QtGui.QFrame(self.tab)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_3.addWidget(self.line_8)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.blank_header = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.blank_header.setFont(font)
        self.blank_header.setText(_fromUtf8(""))
        self.blank_header.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.blank_header.setObjectName(_fromUtf8("blank_header"))
        self.verticalLayout_5.addWidget(self.blank_header)
        self.avPixIntensity_label_12 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.avPixIntensity_label_12.setFont(font)
        self.avPixIntensity_label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.avPixIntensity_label_12.setObjectName(_fromUtf8("avPixIntensity_label_12"))
        self.verticalLayout_5.addWidget(self.avPixIntensity_label_12)
        self.avPixIntensity_label_13 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.avPixIntensity_label_13.setFont(font)
        self.avPixIntensity_label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.avPixIntensity_label_13.setObjectName(_fromUtf8("avPixIntensity_label_13"))
        self.verticalLayout_5.addWidget(self.avPixIntensity_label_13)
        self.avPixIntensity_label_5 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.avPixIntensity_label_5.setFont(font)
        self.avPixIntensity_label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.avPixIntensity_label_5.setObjectName(_fromUtf8("avPixIntensity_label_5"))
        self.verticalLayout_5.addWidget(self.avPixIntensity_label_5)
        self.label_15 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_5.addWidget(self.label_15)
        self.label_16 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_5.addWidget(self.label_16)
        self.label_17 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_5.addWidget(self.label_17)
        self.label_18 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_5.addWidget(self.label_18)
        self.label_19 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_5.addWidget(self.label_19)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.value_header = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.value_header.setFont(font)
        self.value_header.setAlignment(QtCore.Qt.AlignCenter)
        self.value_header.setObjectName(_fromUtf8("value_header"))
        self.verticalLayout_6.addWidget(self.value_header)
        self.int_val = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.int_val.setFont(font)
        self.int_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.int_val.setObjectName(_fromUtf8("int_val"))
        self.verticalLayout_6.addWidget(self.int_val)
        self.wcm_val = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.wcm_val.setFont(font)
        self.wcm_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wcm_val.setObjectName(_fromUtf8("wcm_val"))
        self.verticalLayout_6.addWidget(self.wcm_val)
        self.avg_pix_val = QtGui.QLabel(self.tab)
        self.avg_pix_val.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.avg_pix_val.setFont(font)
        self.avg_pix_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.avg_pix_val.setObjectName(_fromUtf8("avg_pix_val"))
        self.verticalLayout_6.addWidget(self.avg_pix_val)
        self.x_val = QtGui.QLabel(self.tab)
        self.x_val.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.x_val.setFont(font)
        self.x_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x_val.setObjectName(_fromUtf8("x_val"))
        self.verticalLayout_6.addWidget(self.x_val)
        self.y_val = QtGui.QLabel(self.tab)
        self.y_val.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.y_val.setFont(font)
        self.y_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.y_val.setObjectName(_fromUtf8("y_val"))
        self.verticalLayout_6.addWidget(self.y_val)
        self.sx_val = QtGui.QLabel(self.tab)
        self.sx_val.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.sx_val.setFont(font)
        self.sx_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sx_val.setObjectName(_fromUtf8("sx_val"))
        self.verticalLayout_6.addWidget(self.sx_val)
        self.sy_val = QtGui.QLabel(self.tab)
        self.sy_val.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.sy_val.setFont(font)
        self.sy_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sy_val.setObjectName(_fromUtf8("sy_val"))
        self.verticalLayout_6.addWidget(self.sy_val)
        self.cov_val = QtGui.QLabel(self.tab)
        self.cov_val.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.cov_val.setFont(font)
        self.cov_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cov_val.setObjectName(_fromUtf8("cov_val"))
        self.verticalLayout_6.addWidget(self.cov_val)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.mean_header = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.mean_header.setFont(font)
        self.mean_header.setAlignment(QtCore.Qt.AlignCenter)
        self.mean_header.setObjectName(_fromUtf8("mean_header"))
        self.verticalLayout_7.addWidget(self.mean_header)
        self.int_mean = QtGui.QLabel(self.tab)
        self.int_mean.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.int_mean.setFont(font)
        self.int_mean.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.int_mean.setObjectName(_fromUtf8("int_mean"))
        self.verticalLayout_7.addWidget(self.int_mean)
        self.wcm_mean = QtGui.QLabel(self.tab)
        self.wcm_mean.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.wcm_mean.setFont(font)
        self.wcm_mean.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wcm_mean.setObjectName(_fromUtf8("wcm_mean"))
        self.verticalLayout_7.addWidget(self.wcm_mean)
        self.avg_pix_mean = QtGui.QLabel(self.tab)
        self.avg_pix_mean.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.avg_pix_mean.setFont(font)
        self.avg_pix_mean.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.avg_pix_mean.setObjectName(_fromUtf8("avg_pix_mean"))
        self.verticalLayout_7.addWidget(self.avg_pix_mean)
        self.x_mean = QtGui.QLabel(self.tab)
        self.x_mean.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.x_mean.setFont(font)
        self.x_mean.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x_mean.setObjectName(_fromUtf8("x_mean"))
        self.verticalLayout_7.addWidget(self.x_mean)
        self.y_mean = QtGui.QLabel(self.tab)
        self.y_mean.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.y_mean.setFont(font)
        self.y_mean.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.y_mean.setObjectName(_fromUtf8("y_mean"))
        self.verticalLayout_7.addWidget(self.y_mean)
        self.sx_mean = QtGui.QLabel(self.tab)
        self.sx_mean.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.sx_mean.setFont(font)
        self.sx_mean.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sx_mean.setObjectName(_fromUtf8("sx_mean"))
        self.verticalLayout_7.addWidget(self.sx_mean)
        self.sy_mean = QtGui.QLabel(self.tab)
        self.sy_mean.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.sy_mean.setFont(font)
        self.sy_mean.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sy_mean.setObjectName(_fromUtf8("sy_mean"))
        self.verticalLayout_7.addWidget(self.sy_mean)
        self.cov_mean = QtGui.QLabel(self.tab)
        self.cov_mean.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.cov_mean.setFont(font)
        self.cov_mean.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cov_mean.setObjectName(_fromUtf8("cov_mean"))
        self.verticalLayout_7.addWidget(self.cov_mean)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.sigma_header = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.sigma_header.setFont(font)
        self.sigma_header.setAlignment(QtCore.Qt.AlignCenter)
        self.sigma_header.setObjectName(_fromUtf8("sigma_header"))
        self.verticalLayout_8.addWidget(self.sigma_header)
        self.int_sd = QtGui.QLabel(self.tab)
        self.int_sd.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.int_sd.setFont(font)
        self.int_sd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.int_sd.setObjectName(_fromUtf8("int_sd"))
        self.verticalLayout_8.addWidget(self.int_sd)
        self.wcm_sd = QtGui.QLabel(self.tab)
        self.wcm_sd.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.wcm_sd.setFont(font)
        self.wcm_sd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wcm_sd.setObjectName(_fromUtf8("wcm_sd"))
        self.verticalLayout_8.addWidget(self.wcm_sd)
        self.avg_pix_sd = QtGui.QLabel(self.tab)
        self.avg_pix_sd.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.avg_pix_sd.setFont(font)
        self.avg_pix_sd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.avg_pix_sd.setObjectName(_fromUtf8("avg_pix_sd"))
        self.verticalLayout_8.addWidget(self.avg_pix_sd)
        self.x_sd = QtGui.QLabel(self.tab)
        self.x_sd.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.x_sd.setFont(font)
        self.x_sd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x_sd.setObjectName(_fromUtf8("x_sd"))
        self.verticalLayout_8.addWidget(self.x_sd)
        self.y_sd = QtGui.QLabel(self.tab)
        self.y_sd.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.y_sd.setFont(font)
        self.y_sd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.y_sd.setObjectName(_fromUtf8("y_sd"))
        self.verticalLayout_8.addWidget(self.y_sd)
        self.sx_sd = QtGui.QLabel(self.tab)
        self.sx_sd.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.sx_sd.setFont(font)
        self.sx_sd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sx_sd.setObjectName(_fromUtf8("sx_sd"))
        self.verticalLayout_8.addWidget(self.sx_sd)
        self.sy_sd = QtGui.QLabel(self.tab)
        self.sy_sd.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.sy_sd.setFont(font)
        self.sy_sd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sy_sd.setObjectName(_fromUtf8("sy_sd"))
        self.verticalLayout_8.addWidget(self.sy_sd)
        self.cov_sd = QtGui.QLabel(self.tab)
        self.cov_sd.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.cov_sd.setFont(font)
        self.cov_sd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cov_sd.setObjectName(_fromUtf8("cov_sd"))
        self.verticalLayout_8.addWidget(self.cov_sd)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.resetMeanSD_pushButton = QtGui.QPushButton(self.tab)
        self.resetMeanSD_pushButton.setObjectName(_fromUtf8("resetMeanSD_pushButton"))
        self.verticalLayout_3.addWidget(self.resetMeanSD_pushButton)
        self.line_7 = QtGui.QFrame(self.tab)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_3.addWidget(self.line_7)
        self.opencloseShut1_pushButton = QtGui.QPushButton(self.tab)
        self.opencloseShut1_pushButton.setObjectName(_fromUtf8("opencloseShut1_pushButton"))
        self.verticalLayout_3.addWidget(self.opencloseShut1_pushButton)
        self.opencloseShut2_pushButton = QtGui.QPushButton(self.tab)
        self.opencloseShut2_pushButton.setObjectName(_fromUtf8("opencloseShut2_pushButton"))
        self.verticalLayout_3.addWidget(self.opencloseShut2_pushButton)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.pix_gridlines_checkBox_2 = QtGui.QCheckBox(self.tab)
        self.pix_gridlines_checkBox_2.setObjectName(_fromUtf8("pix_gridlines_checkBox_2"))
        self.horizontalLayout_12.addWidget(self.pix_gridlines_checkBox_2)
        self.mm_gridlines_checkBox_2 = QtGui.QCheckBox(self.tab)
        self.mm_gridlines_checkBox_2.setObjectName(_fromUtf8("mm_gridlines_checkBox_2"))
        self.horizontalLayout_12.addWidget(self.mm_gridlines_checkBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.collectAndSave_pushButton.raise_()
        self.opencloseShut1_pushButton.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_7.raise_()
        self.resetMeanSD_pushButton.raise_()
        self.line_8.raise_()
        self.opencloseShut2_pushButton.raise_()
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.analyse_pushButton = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyse_pushButton.sizePolicy().hasHeightForWidth())
        self.analyse_pushButton.setSizePolicy(sizePolicy)
        self.analyse_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.analyse_pushButton.setObjectName(_fromUtf8("analyse_pushButton"))
        self.verticalLayout.addWidget(self.analyse_pushButton)
        self.resetBackground_pushButton = QtGui.QPushButton(self.tab_2)
        self.resetBackground_pushButton.setObjectName(_fromUtf8("resetBackground_pushButton"))
        self.verticalLayout.addWidget(self.resetBackground_pushButton)
        self.useBackground_pushButton = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useBackground_pushButton.sizePolicy().hasHeightForWidth())
        self.useBackground_pushButton.setSizePolicy(sizePolicy)
        self.useBackground_pushButton.setMinimumSize(QtCore.QSize(50, 0))
        self.useBackground_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.useBackground_pushButton.setObjectName(_fromUtf8("useBackground_pushButton"))
        self.verticalLayout.addWidget(self.useBackground_pushButton)
        self.useNPoint_pushButton = QtGui.QPushButton(self.tab_2)
        self.useNPoint_pushButton.setMinimumSize(QtCore.QSize(50, 0))
        self.useNPoint_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.useNPoint_pushButton.setObjectName(_fromUtf8("useNPoint_pushButton"))
        self.verticalLayout.addWidget(self.useNPoint_pushButton)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.setStepSize_pushButton = QtGui.QPushButton(self.tab_2)
        self.setStepSize_pushButton.setObjectName(_fromUtf8("setStepSize_pushButton"))
        self.horizontalLayout_5.addWidget(self.setStepSize_pushButton)
        self.step_size_read = QtGui.QLabel(self.tab_2)
        self.step_size_read.setAlignment(QtCore.Qt.AlignCenter)
        self.step_size_read.setObjectName(_fromUtf8("step_size_read"))
        self.horizontalLayout_5.addWidget(self.step_size_read)
        self.stepSize_spinBox = QtGui.QSpinBox(self.tab_2)
        self.stepSize_spinBox.setMinimum(1)
        self.stepSize_spinBox.setMaximum(10)
        self.stepSize_spinBox.setSingleStep(1)
        self.stepSize_spinBox.setProperty("value", 1)
        self.stepSize_spinBox.setObjectName(_fromUtf8("stepSize_spinBox"))
        self.horizontalLayout_5.addWidget(self.stepSize_spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.mask_x_read = QtGui.QLabel(self.tab_2)
        self.mask_x_read.setObjectName(_fromUtf8("mask_x_read"))
        self.gridLayout_6.addWidget(self.mask_x_read, 0, 1, 1, 1)
        self.maskX_spinBox = QtGui.QSpinBox(self.tab_2)
        self.maskX_spinBox.setMaximum(9999)
        self.maskX_spinBox.setObjectName(_fromUtf8("maskX_spinBox"))
        self.gridLayout_6.addWidget(self.maskX_spinBox, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 1, 0, 1, 1)
        self.mask_y_read = QtGui.QLabel(self.tab_2)
        self.mask_y_read.setObjectName(_fromUtf8("mask_y_read"))
        self.gridLayout_6.addWidget(self.mask_y_read, 1, 1, 1, 1)
        self.maskY_spinBox = QtGui.QSpinBox(self.tab_2)
        self.maskY_spinBox.setMaximum(9999)
        self.maskY_spinBox.setObjectName(_fromUtf8("maskY_spinBox"))
        self.gridLayout_6.addWidget(self.maskY_spinBox, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 2, 0, 1, 1)
        self.mask_x_rad_read = QtGui.QLabel(self.tab_2)
        self.mask_x_rad_read.setObjectName(_fromUtf8("mask_x_rad_read"))
        self.gridLayout_6.addWidget(self.mask_x_rad_read, 2, 1, 1, 1)
        self.maskXRadius_spinBox = QtGui.QSpinBox(self.tab_2)
        self.maskXRadius_spinBox.setMaximum(9999)
        self.maskXRadius_spinBox.setObjectName(_fromUtf8("maskXRadius_spinBox"))
        self.gridLayout_6.addWidget(self.maskXRadius_spinBox, 2, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 3, 0, 1, 1)
        self.mask_y_rad_read = QtGui.QLabel(self.tab_2)
        self.mask_y_rad_read.setObjectName(_fromUtf8("mask_y_rad_read"))
        self.gridLayout_6.addWidget(self.mask_y_rad_read, 3, 1, 1, 1)
        self.maskYRadius_spinBox = QtGui.QSpinBox(self.tab_2)
        self.maskYRadius_spinBox.setMaximum(9999)
        self.maskYRadius_spinBox.setObjectName(_fromUtf8("maskYRadius_spinBox"))
        self.gridLayout_6.addWidget(self.maskYRadius_spinBox, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.center_mask_pushButton = QtGui.QPushButton(self.tab_2)
        self.center_mask_pushButton.setObjectName(_fromUtf8("center_mask_pushButton"))
        self.horizontalLayout.addWidget(self.center_mask_pushButton)
        self.feed_back_check = QtGui.QCheckBox(self.tab_2)
        self.feed_back_check.setObjectName(_fromUtf8("feed_back_check"))
        self.horizontalLayout.addWidget(self.feed_back_check)
        self.setMask_pushButton = QtGui.QPushButton(self.tab_2)
        self.setMask_pushButton.setObjectName(_fromUtf8("setMask_pushButton"))
        self.horizontalLayout.addWidget(self.setMask_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 1)
        self.spinBox_maxLevel = QtGui.QSpinBox(self.tab_2)
        self.spinBox_maxLevel.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_maxLevel.setMaximum(65536)
        self.spinBox_maxLevel.setSingleStep(100)
        self.spinBox_maxLevel.setProperty("value", 65536)
        self.spinBox_maxLevel.setObjectName(_fromUtf8("spinBox_maxLevel"))
        self.gridLayout_5.addWidget(self.spinBox_maxLevel, 1, 2, 1, 1)
        self.spinBox_minLevel = QtGui.QSpinBox(self.tab_2)
        self.spinBox_minLevel.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_minLevel.setMaximum(65536)
        self.spinBox_minLevel.setSingleStep(100)
        self.spinBox_minLevel.setObjectName(_fromUtf8("spinBox_minLevel"))
        self.gridLayout_5.addWidget(self.spinBox_minLevel, 0, 2, 1, 1)
        self.minPixValue = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.minPixValue.setFont(font)
        self.minPixValue.setObjectName(_fromUtf8("minPixValue"))
        self.gridLayout_5.addWidget(self.minPixValue, 0, 1, 1, 1)
        self.maxPixValue = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.maxPixValue.setFont(font)
        self.maxPixValue.setObjectName(_fromUtf8("maxPixValue"))
        self.gridLayout_5.addWidget(self.maxPixValue, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.autoLevel_pushButton = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoLevel_pushButton.sizePolicy().hasHeightForWidth())
        self.autoLevel_pushButton.setSizePolicy(sizePolicy)
        self.autoLevel_pushButton.setMinimumSize(QtCore.QSize(40, 0))
        self.autoLevel_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.autoLevel_pushButton.setObjectName(_fromUtf8("autoLevel_pushButton"))
        self.horizontalLayout_3.addWidget(self.autoLevel_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.pix_gridlines_checkBox = QtGui.QCheckBox(self.tab_2)
        self.pix_gridlines_checkBox.setObjectName(_fromUtf8("pix_gridlines_checkBox"))
        self.horizontalLayout_11.addWidget(self.pix_gridlines_checkBox)
        self.mm_gridlines_checkBox = QtGui.QCheckBox(self.tab_2)
        self.mm_gridlines_checkBox.setObjectName(_fromUtf8("mm_gridlines_checkBox"))
        self.horizontalLayout_11.addWidget(self.mm_gridlines_checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.analyse_pushButton.raise_()
        self.resetBackground_pushButton.raise_()
        self.label.raise_()
        self.useBackground_pushButton.raise_()
        self.useNPoint_pushButton.raise_()
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.tabWidget)
        self.imageLayout = QtGui.QGridLayout()
        self.imageLayout.setVerticalSpacing(14)
        self.imageLayout.setObjectName(_fromUtf8("imageLayout"))
        self.graphics_view = ImageView(self.centralwidget)
        self.graphics_view.setToolTip(_fromUtf8(""))
        self.graphics_view.setObjectName(_fromUtf8("graphics_view"))
        self.imageLayout.addWidget(self.graphics_view, 0, 0, 1, 1)
        self.horizontalLayout_9.addLayout(self.imageLayout)
        self.horizontalLayout_9.setStretch(1, 10)
        mainView.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainView)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(mainView)
        mainView.setTabOrder(self.analyse_pushButton, self.resetBackground_pushButton)
        mainView.setTabOrder(self.resetBackground_pushButton, self.maskX_spinBox)
        mainView.setTabOrder(self.maskX_spinBox, self.maskY_spinBox)
        mainView.setTabOrder(self.maskY_spinBox, self.maskXRadius_spinBox)
        mainView.setTabOrder(self.maskXRadius_spinBox, self.maskYRadius_spinBox)

    def retranslateUi(self, mainView):
        mainView.setWindowTitle(_translate("mainView", "Image Collector", None))
        self.acquire_pushButton.setText(_translate("mainView", "Acquire", None))
        self.analyse_pushButton_2.setText(_translate("mainView", "Analyse", None))
        self.collectAndSave_pushButton.setText(_translate("mainView", "Collect and Save Image", None))
        self.label_5.setText(_translate("mainView", "Images:", None))
        self.copy_path_pushButton.setText(_translate("mainView", "Copy Path", None))
        self.open_path_push_button.setText(_translate("mainView", "Open Path", None))
        self.avPixIntensity_label_9.setText(_translate("mainView", "Mirror H step:", None))
        self.H_step_read.setText(_translate("mainView", "Read", None))
        self.move_H_left_pushButton.setText(_translate("mainView", "Left", None))
        self.move_H_right_pushButton.setText(_translate("mainView", "Right", None))
        self.avPixIntensity_label_10.setText(_translate("mainView", "Mirror V step:", None))
        self.V_step_read.setText(_translate("mainView", "Read", None))
        self.move_V_down_pushButton.setText(_translate("mainView", "Down", None))
        self.move_V_up_pushButton.setText(_translate("mainView", "Up", None))
        self.avPixIntensity_label_21.setText(_translate("mainView", "HWP:", None))
        self.hwp_read.setText(_translate("mainView", "Read", None))
        self.hwp_down_pushButton.setText(_translate("mainView", "Down", None))
        self.hwp_up_pushButton.setText(_translate("mainView", "Up", None))
        self.wcm_val_2.setText(_translate("mainView", "Read WCM", None))
        self.avPixIntensity_label_11.setText(_translate("mainView", "WCM:", None))
        self.setInt_pushButton.setText(_translate("mainView", "Set", None))
        self.int_val_2.setText(_translate("mainView", "Read I", None))
        self.avPixIntensity_label_6.setText(_translate("mainView", "Intensity:", None))
        self.setWCM_pushButton.setText(_translate("mainView", "Set", None))
        self.avPixIntensity_label_8.setText(_translate("mainView", "X pos:", None))
        self.x_val_2.setText(_translate("mainView", "Read X", None))
        self.set_xpos_pushButton.setText(_translate("mainView", "Set", None))
        self.avPixIntensity_label_7.setText(_translate("mainView", "Y pos:", None))
        self.y_val_2.setText(_translate("mainView", "Read Y", None))
        self.set_ypos_pushButton.setText(_translate("mainView", "Set", None))
        self.load_pushButton.setText(_translate("mainView", "Load Settings", None))
        self.save_pushButton.setText(_translate("mainView", "Save Settings", None))
        self.avPixIntensity_label_12.setText(_translate("mainView", "Intensity:", None))
        self.avPixIntensity_label_13.setText(_translate("mainView", "WCM:", None))
        self.avPixIntensity_label_5.setText(_translate("mainView", "Pixel Avg:", None))
        self.label_15.setText(_translate("mainView", "X:", None))
        self.label_16.setText(_translate("mainView", "Y:", None))
        self.label_17.setText(_translate("mainView", "Sig X:", None))
        self.label_18.setText(_translate("mainView", "Sig Y:", None))
        self.label_19.setText(_translate("mainView", "Cov XY: ", None))
        self.value_header.setText(_translate("mainView", "Value", None))
        self.int_val.setText(_translate("mainView", "-", None))
        self.wcm_val.setText(_translate("mainView", "-", None))
        self.avg_pix_val.setText(_translate("mainView", "-", None))
        self.x_val.setText(_translate("mainView", "-", None))
        self.y_val.setText(_translate("mainView", "-", None))
        self.sx_val.setText(_translate("mainView", "-", None))
        self.sy_val.setText(_translate("mainView", "-", None))
        self.cov_val.setText(_translate("mainView", "-", None))
        self.mean_header.setText(_translate("mainView", "Mean", None))
        self.int_mean.setText(_translate("mainView", "-", None))
        self.wcm_mean.setText(_translate("mainView", "-", None))
        self.avg_pix_mean.setText(_translate("mainView", "-", None))
        self.x_mean.setText(_translate("mainView", "-", None))
        self.y_mean.setText(_translate("mainView", "-", None))
        self.sx_mean.setText(_translate("mainView", "-", None))
        self.sy_mean.setText(_translate("mainView", "-", None))
        self.cov_mean.setText(_translate("mainView", "-", None))
        self.sigma_header.setText(_translate("mainView", "sigma", None))
        self.int_sd.setText(_translate("mainView", "-", None))
        self.wcm_sd.setText(_translate("mainView", "-", None))
        self.avg_pix_sd.setText(_translate("mainView", "-", None))
        self.x_sd.setText(_translate("mainView", "-", None))
        self.y_sd.setText(_translate("mainView", "-", None))
        self.sx_sd.setText(_translate("mainView", "-", None))
        self.sy_sd.setText(_translate("mainView", "-", None))
        self.cov_sd.setText(_translate("mainView", "-", None))
        self.resetMeanSD_pushButton.setText(_translate("mainView", "Reset Means and SD", None))
        self.opencloseShut1_pushButton.setText(_translate("mainView", "Open / Close Shutter", None))
        self.opencloseShut2_pushButton.setText(_translate("mainView", "PushButton", None))
        self.pix_gridlines_checkBox_2.setText(_translate("mainView", "Pixel Grid-Lines", None))
        self.mm_gridlines_checkBox_2.setText(_translate("mainView", "mm Grid-Lines", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainView", "Main", None))
        self.analyse_pushButton.setText(_translate("mainView", "Analyse", None))
        self.resetBackground_pushButton.setText(_translate("mainView", "Reset Background Image", None))
        self.useBackground_pushButton.setText(_translate("mainView", "Use Background", None))
        self.useNPoint_pushButton.setText(_translate("mainView", "Use N-Point Scaling", None))
        self.setStepSize_pushButton.setText(_translate("mainView", "Set StepSize", None))
        self.step_size_read.setText(_translate("mainView", "x Read", None))
        self.label.setText(_translate("mainView", "MASK", None))
        self.label_6.setText(_translate("mainView", "Center X :", None))
        self.mask_x_read.setText(_translate("mainView", "x Read", None))
        self.label_7.setText(_translate("mainView", "Center Y :", None))
        self.mask_y_read.setText(_translate("mainView", "y Read", None))
        self.label_8.setText(_translate("mainView", "X Radius:", None))
        self.mask_x_rad_read.setText(_translate("mainView", "x Rad", None))
        self.label_9.setText(_translate("mainView", "Y Radius :", None))
        self.mask_y_rad_read.setText(_translate("mainView", "y Rad", None))
        self.center_mask_pushButton.setText(_translate("mainView", "Center Mask", None))
        self.feed_back_check.setText(_translate("mainView", "Feedback", None))
        self.setMask_pushButton.setText(_translate("mainView", "Set Mask", None))
        self.label_3.setText(_translate("mainView", "Lo Level", None))
        self.label_4.setText(_translate("mainView", "Hi Level", None))
        self.minPixValue.setText(_translate("mainView", "lo", None))
        self.maxPixValue.setText(_translate("mainView", "hi", None))
        self.autoLevel_pushButton.setText(_translate("mainView", "Auto Level", None))
        self.pix_gridlines_checkBox.setText(_translate("mainView", "Pixel Grid-Lines", None))
        self.mm_gridlines_checkBox.setText(_translate("mainView", "mm Grid-Lines", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainView", "Analysis Settings", None))

from pyqtgraph import ImageView
