# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conditioning_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1030, 632)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.outputWidget_15 = QtGui.QLabel(self.centralwidget)
        self.outputWidget_15.setGeometry(QtCore.QRect(1209, 420, 97, 47))
        self.outputWidget_15.setFrameShape(QtGui.QFrame.Box)
        self.outputWidget_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.outputWidget_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.outputWidget_15.setObjectName(_fromUtf8("outputWidget_15"))
        self.outputWidget_16 = QtGui.QLabel(self.centralwidget)
        self.outputWidget_16.setGeometry(QtCore.QRect(1209, 473, 97, 48))
        self.outputWidget_16.setFrameShape(QtGui.QFrame.Box)
        self.outputWidget_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.outputWidget_16.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.outputWidget_16.setObjectName(_fromUtf8("outputWidget_16"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(51, 21, 891, 511))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.traces_plotwidget = PlotWidget(self.layoutWidget)
        self.traces_plotwidget.setObjectName(_fromUtf8("traces_plotwidget"))
        self.verticalLayout_2.addWidget(self.traces_plotwidget)
        self.power_vs_pulses_plotwidget = PlotWidget(self.layoutWidget)
        self.power_vs_pulses_plotwidget.setObjectName(_fromUtf8("power_vs_pulses_plotwidget"))
        self.verticalLayout_2.addWidget(self.power_vs_pulses_plotwidget)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 0, 3, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.start_button = QtGui.QPushButton(self.layoutWidget)
        self.start_button.setObjectName(_fromUtf8("start_button"))
        self.verticalLayout.addWidget(self.start_button)
        self.pause_ramp_button = QtGui.QPushButton(self.layoutWidget)
        self.pause_ramp_button.setObjectName(_fromUtf8("pause_ramp_button"))
        self.verticalLayout.addWidget(self.pause_ramp_button)
        self.shutdown_rf_button = QtGui.QPushButton(self.layoutWidget)
        self.shutdown_rf_button.setCheckable(True)
        self.shutdown_rf_button.setObjectName(_fromUtf8("shutdown_rf_button"))
        self.verticalLayout.addWidget(self.shutdown_rf_button)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.power_aim_label = QtGui.QLabel(self.layoutWidget)
        self.power_aim_label.setFrameShape(QtGui.QFrame.Box)
        self.power_aim_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.power_aim_label.setObjectName(_fromUtf8("power_aim_label"))
        self.gridLayout.addWidget(self.power_aim_label, 0, 0, 1, 1)
        self.power_aim_input = QtGui.QSpinBox(self.layoutWidget)
        self.power_aim_input.setObjectName(_fromUtf8("power_aim_input"))
        self.gridLayout.addWidget(self.power_aim_input, 0, 1, 1, 1)
        self.pulse_length_aim_label = QtGui.QLabel(self.layoutWidget)
        self.pulse_length_aim_label.setFrameShape(QtGui.QFrame.Box)
        self.pulse_length_aim_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.pulse_length_aim_label.setObjectName(_fromUtf8("pulse_length_aim_label"))
        self.gridLayout.addWidget(self.pulse_length_aim_label, 1, 0, 1, 1)
        self.pulse_length_aim_input = QtGui.QSpinBox(self.layoutWidget)
        self.pulse_length_aim_input.setObjectName(_fromUtf8("pulse_length_aim_input"))
        self.gridLayout.addWidget(self.pulse_length_aim_input, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 1, 1, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.vac_spike_label = QtGui.QLabel(self.layoutWidget)
        self.vac_spike_label.setFrameShape(QtGui.QFrame.Box)
        self.vac_spike_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_spike_label.setScaledContents(False)
        self.vac_spike_label.setObjectName(_fromUtf8("vac_spike_label"))
        self.gridLayout_3.addWidget(self.vac_spike_label, 2, 0, 1, 1)
        self.rev_power_spike_label = QtGui.QLabel(self.layoutWidget)
        self.rev_power_spike_label.setFrameShape(QtGui.QFrame.Box)
        self.rev_power_spike_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.rev_power_spike_label.setScaledContents(False)
        self.rev_power_spike_label.setObjectName(_fromUtf8("rev_power_spike_label"))
        self.gridLayout_3.addWidget(self.rev_power_spike_label, 0, 0, 1, 1)
        self.vac_spike_status_outputwidget = QtGui.QLabel(self.layoutWidget)
        self.vac_spike_status_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.vac_spike_status_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_spike_status_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.vac_spike_status_outputwidget.setObjectName(_fromUtf8("vac_spike_status_outputwidget"))
        self.gridLayout_3.addWidget(self.vac_spike_status_outputwidget, 2, 1, 1, 2)
        self.DC_spike_label = QtGui.QLabel(self.layoutWidget)
        self.DC_spike_label.setFrameShape(QtGui.QFrame.Box)
        self.DC_spike_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.DC_spike_label.setScaledContents(False)
        self.DC_spike_label.setObjectName(_fromUtf8("DC_spike_label"))
        self.gridLayout_3.addWidget(self.DC_spike_label, 1, 0, 1, 1)
        self.RF_lost_label = QtGui.QLabel(self.layoutWidget)
        self.RF_lost_label.setFrameShape(QtGui.QFrame.Box)
        self.RF_lost_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.RF_lost_label.setScaledContents(False)
        self.RF_lost_label.setObjectName(_fromUtf8("RF_lost_label"))
        self.gridLayout_3.addWidget(self.RF_lost_label, 3, 0, 1, 1)
        self.DC_spike_status_outputwidget = QtGui.QLabel(self.layoutWidget)
        self.DC_spike_status_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.DC_spike_status_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.DC_spike_status_outputwidget.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.DC_spike_status_outputwidget.setObjectName(_fromUtf8("DC_spike_status_outputwidget"))
        self.gridLayout_3.addWidget(self.DC_spike_status_outputwidget, 1, 1, 1, 2)
        self.rev_power_spike_status_outputwidget = QtGui.QLabel(self.layoutWidget)
        self.rev_power_spike_status_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.rev_power_spike_status_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.rev_power_spike_status_outputwidget.setScaledContents(False)
        self.rev_power_spike_status_outputwidget.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.rev_power_spike_status_outputwidget.setIndent(-1)
        self.rev_power_spike_status_outputwidget.setObjectName(_fromUtf8("rev_power_spike_status_outputwidget"))
        self.gridLayout_3.addWidget(self.rev_power_spike_status_outputwidget, 0, 1, 1, 2)
        self.RF_lost_status_outputwidget = QtGui.QLabel(self.layoutWidget)
        self.RF_lost_status_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.RF_lost_status_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.RF_lost_status_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.RF_lost_status_outputwidget.setObjectName(_fromUtf8("RF_lost_status_outputwidget"))
        self.gridLayout_3.addWidget(self.RF_lost_status_outputwidget, 3, 1, 1, 2)
        self.gridLayout_6.addLayout(self.gridLayout_3, 2, 1, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.water_temp_label = QtGui.QLabel(self.layoutWidget)
        self.water_temp_label.setFrameShape(QtGui.QFrame.Box)
        self.water_temp_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.water_temp_label.setScaledContents(False)
        self.water_temp_label.setObjectName(_fromUtf8("water_temp_label"))
        self.gridLayout_2.addWidget(self.water_temp_label, 8, 0, 1, 1)
        self.cav_temp_label = QtGui.QLabel(self.layoutWidget)
        self.cav_temp_label.setFrameShape(QtGui.QFrame.Box)
        self.cav_temp_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.cav_temp_label.setScaledContents(False)
        self.cav_temp_label.setObjectName(_fromUtf8("cav_temp_label"))
        self.gridLayout_2.addWidget(self.cav_temp_label, 9, 0, 1, 1)
        self.cav_temp_outputwidget = QtGui.QLabel(self.layoutWidget)
        self.cav_temp_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.cav_temp_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.cav_temp_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.cav_temp_outputwidget.setObjectName(_fromUtf8("cav_temp_outputwidget"))
        self.gridLayout_2.addWidget(self.cav_temp_outputwidget, 9, 1, 1, 1)
        self.water_temp_outputwidget = QtGui.QLabel(self.layoutWidget)
        self.water_temp_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.water_temp_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.water_temp_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.water_temp_outputwidget.setObjectName(_fromUtf8("water_temp_outputwidget"))
        self.gridLayout_2.addWidget(self.water_temp_outputwidget, 8, 1, 1, 1)
        self.pulse_length_outputwidget = QtGui.QLabel(self.layoutWidget)
        self.pulse_length_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.pulse_length_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.pulse_length_outputwidget.setScaledContents(False)
        self.pulse_length_outputwidget.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.pulse_length_outputwidget.setIndent(-1)
        self.pulse_length_outputwidget.setObjectName(_fromUtf8("pulse_length_outputwidget"))
        self.gridLayout_2.addWidget(self.pulse_length_outputwidget, 0, 1, 1, 1)
        self.fwd_kly_power_label = QtGui.QLabel(self.layoutWidget)
        self.fwd_kly_power_label.setFrameShape(QtGui.QFrame.Box)
        self.fwd_kly_power_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.fwd_kly_power_label.setScaledContents(False)
        self.fwd_kly_power_label.setObjectName(_fromUtf8("fwd_kly_power_label"))
        self.gridLayout_2.addWidget(self.fwd_kly_power_label, 1, 0, 1, 1)
        self.rev_kly_power_label = QtGui.QLabel(self.layoutWidget)
        self.rev_kly_power_label.setFrameShape(QtGui.QFrame.Box)
        self.rev_kly_power_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.rev_kly_power_label.setScaledContents(False)
        self.rev_kly_power_label.setObjectName(_fromUtf8("rev_kly_power_label"))
        self.gridLayout_2.addWidget(self.rev_kly_power_label, 2, 0, 1, 1)
        self.fwd_cav_power_outputwidget = QtGui.QLabel(self.layoutWidget)
        self.fwd_cav_power_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.fwd_cav_power_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.fwd_cav_power_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.fwd_cav_power_outputwidget.setObjectName(_fromUtf8("fwd_cav_power_outputwidget"))
        self.gridLayout_2.addWidget(self.fwd_cav_power_outputwidget, 3, 1, 1, 1)
        self.pulse_length_label = QtGui.QLabel(self.layoutWidget)
        self.pulse_length_label.setFrameShape(QtGui.QFrame.Box)
        self.pulse_length_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.pulse_length_label.setScaledContents(False)
        self.pulse_length_label.setObjectName(_fromUtf8("pulse_length_label"))
        self.gridLayout_2.addWidget(self.pulse_length_label, 0, 0, 1, 1)
        self.fwd_kly_power_outputwidget = QtGui.QLabel(self.layoutWidget)
        self.fwd_kly_power_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.fwd_kly_power_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.fwd_kly_power_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.fwd_kly_power_outputwidget.setObjectName(_fromUtf8("fwd_kly_power_outputwidget"))
        self.gridLayout_2.addWidget(self.fwd_kly_power_outputwidget, 1, 1, 1, 1)
        self.fwd_cav_power_label = QtGui.QLabel(self.layoutWidget)
        self.fwd_cav_power_label.setFrameShape(QtGui.QFrame.Box)
        self.fwd_cav_power_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.fwd_cav_power_label.setScaledContents(False)
        self.fwd_cav_power_label.setObjectName(_fromUtf8("fwd_cav_power_label"))
        self.gridLayout_2.addWidget(self.fwd_cav_power_label, 3, 0, 1, 1)
        self.rev_cav_power_label = QtGui.QLabel(self.layoutWidget)
        self.rev_cav_power_label.setFrameShape(QtGui.QFrame.Box)
        self.rev_cav_power_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.rev_cav_power_label.setScaledContents(False)
        self.rev_cav_power_label.setObjectName(_fromUtf8("rev_cav_power_label"))
        self.gridLayout_2.addWidget(self.rev_cav_power_label, 4, 0, 1, 1)
        self.rev_kly_power_outputwidget = QtGui.QLabel(self.layoutWidget)
        self.rev_kly_power_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.rev_kly_power_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.rev_kly_power_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.rev_kly_power_outputwidget.setObjectName(_fromUtf8("rev_kly_power_outputwidget"))
        self.gridLayout_2.addWidget(self.rev_kly_power_outputwidget, 2, 1, 1, 1)
        self.rev_cav_power_outputwidget = QtGui.QLabel(self.layoutWidget)
        self.rev_cav_power_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.rev_cav_power_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.rev_cav_power_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.rev_cav_power_outputwidget.setObjectName(_fromUtf8("rev_cav_power_outputwidget"))
        self.gridLayout_2.addWidget(self.rev_cav_power_outputwidget, 4, 1, 1, 1)
        self.probe_power_label = QtGui.QLabel(self.layoutWidget)
        self.probe_power_label.setFrameShape(QtGui.QFrame.Box)
        self.probe_power_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.probe_power_label.setScaledContents(False)
        self.probe_power_label.setObjectName(_fromUtf8("probe_power_label"))
        self.gridLayout_2.addWidget(self.probe_power_label, 5, 0, 1, 1)
        self.probe_power_outputwidget = QtGui.QLabel(self.layoutWidget)
        self.probe_power_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.probe_power_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.probe_power_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.probe_power_outputwidget.setObjectName(_fromUtf8("probe_power_outputwidget"))
        self.gridLayout_2.addWidget(self.probe_power_outputwidget, 5, 1, 1, 1)
        self.vac_level_label = QtGui.QLabel(self.layoutWidget)
        self.vac_level_label.setFrameShape(QtGui.QFrame.Box)
        self.vac_level_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_level_label.setScaledContents(False)
        self.vac_level_label.setObjectName(_fromUtf8("vac_level_label"))
        self.gridLayout_2.addWidget(self.vac_level_label, 6, 0, 1, 1)
        self.vac_level_outputwidget = QtGui.QLabel(self.layoutWidget)
        self.vac_level_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.vac_level_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_level_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.vac_level_outputwidget.setObjectName(_fromUtf8("vac_level_outputwidget"))
        self.gridLayout_2.addWidget(self.vac_level_outputwidget, 6, 1, 1, 1)
        self.vac_valve_status_label = QtGui.QLabel(self.layoutWidget)
        self.vac_valve_status_label.setFrameShape(QtGui.QFrame.Box)
        self.vac_valve_status_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_valve_status_label.setScaledContents(False)
        self.vac_valve_status_label.setObjectName(_fromUtf8("vac_valve_status_label"))
        self.gridLayout_2.addWidget(self.vac_valve_status_label, 7, 0, 1, 1)
        self.vac_valve_status_outputwidget = QtGui.QLabel(self.layoutWidget)
        self.vac_valve_status_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.vac_valve_status_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.vac_valve_status_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.vac_valve_status_outputwidget.setObjectName(_fromUtf8("vac_valve_status_outputwidget"))
        self.gridLayout_2.addWidget(self.vac_valve_status_outputwidget, 7, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 2, 2, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.breakdown_rate_limit_label = QtGui.QLabel(self.layoutWidget)
        self.breakdown_rate_limit_label.setFrameShape(QtGui.QFrame.Box)
        self.breakdown_rate_limit_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.breakdown_rate_limit_label.setScaledContents(False)
        self.breakdown_rate_limit_label.setObjectName(_fromUtf8("breakdown_rate_limit_label"))
        self.gridLayout_4.addWidget(self.breakdown_rate_limit_label, 0, 0, 1, 1)
        self.measured_breakdown_rate_label = QtGui.QLabel(self.layoutWidget)
        self.measured_breakdown_rate_label.setFrameShape(QtGui.QFrame.Box)
        self.measured_breakdown_rate_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.measured_breakdown_rate_label.setScaledContents(False)
        self.measured_breakdown_rate_label.setObjectName(_fromUtf8("measured_breakdown_rate_label"))
        self.gridLayout_4.addWidget(self.measured_breakdown_rate_label, 1, 0, 1, 1)
        self.breakdown_rate_statistics_label = QtGui.QLabel(self.layoutWidget)
        self.breakdown_rate_statistics_label.setFrameShape(QtGui.QFrame.Box)
        self.breakdown_rate_statistics_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.breakdown_rate_statistics_label.setScaledContents(False)
        self.breakdown_rate_statistics_label.setObjectName(_fromUtf8("breakdown_rate_statistics_label"))
        self.gridLayout_4.addWidget(self.breakdown_rate_statistics_label, 2, 0, 1, 1)
        self.breakdown_rate_limit_outputwidget = QtGui.QLabel(self.layoutWidget)
        self.breakdown_rate_limit_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.breakdown_rate_limit_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.breakdown_rate_limit_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.breakdown_rate_limit_outputwidget.setObjectName(_fromUtf8("breakdown_rate_limit_outputwidget"))
        self.gridLayout_4.addWidget(self.breakdown_rate_limit_outputwidget, 0, 1, 1, 1)
        self.measured_breakdown_rate_outputwidget = QtGui.QLabel(self.layoutWidget)
        self.measured_breakdown_rate_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.measured_breakdown_rate_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.measured_breakdown_rate_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.measured_breakdown_rate_outputwidget.setObjectName(_fromUtf8("measured_breakdown_rate_outputwidget"))
        self.gridLayout_4.addWidget(self.measured_breakdown_rate_outputwidget, 1, 1, 1, 1)
        self.breakdown_rate_statistics_outputwidget = QtGui.QLabel(self.layoutWidget)
        self.breakdown_rate_statistics_outputwidget.setFrameShape(QtGui.QFrame.Box)
        self.breakdown_rate_statistics_outputwidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.breakdown_rate_statistics_outputwidget.setAlignment(QtCore.Qt.AlignAbsolute|QtCore.Qt.AlignBottom|QtCore.Qt.AlignCenter|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignHorizontal_Mask|QtCore.Qt.AlignJustify|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignVertical_Mask)
        self.breakdown_rate_statistics_outputwidget.setObjectName(_fromUtf8("breakdown_rate_statistics_outputwidget"))
        self.gridLayout_4.addWidget(self.breakdown_rate_statistics_outputwidget, 2, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 2, 1, 1)
        self.copy_to_clipboard_button = QtGui.QPushButton(self.layoutWidget)
        self.copy_to_clipboard_button.setCheckable(True)
        self.copy_to_clipboard_button.setObjectName(_fromUtf8("copy_to_clipboard_button"))
        self.gridLayout_6.addWidget(self.copy_to_clipboard_button, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(55, 540, 881, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1030, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.outputWidget_15.setText(_translate("MainWindow", "0", None))
        self.outputWidget_16.setText(_translate("MainWindow", "0", None))
        self.start_button.setText(_translate("MainWindow", "Start ", None))
        self.pause_ramp_button.setText(_translate("MainWindow", "Pause ramp", None))
        self.shutdown_rf_button.setText(_translate("MainWindow", "Shut down RF", None))
        self.power_aim_label.setText(_translate("MainWindow", "Klystron power aim (MW)", None))
        self.pulse_length_aim_label.setText(_translate("MainWindow", "Pulse length aim (us)", None))
        self.vac_spike_label.setText(_translate("MainWindow", "Vacuum spike", None))
        self.rev_power_spike_label.setText(_translate("MainWindow", "Reverse power spike", None))
        self.vac_spike_status_outputwidget.setText(_translate("MainWindow", "RF paused", None))
        self.DC_spike_label.setText(_translate("MainWindow", "Dark current spike", None))
        self.RF_lost_label.setText(_translate("MainWindow", "RF lost", None))
        self.DC_spike_status_outputwidget.setText(_translate("MainWindow", "Nope", None))
        self.rev_power_spike_status_outputwidget.setText(_translate("MainWindow", "Nope", None))
        self.RF_lost_status_outputwidget.setText(_translate("MainWindow", "Reset RF!", None))
        self.water_temp_label.setText(_translate("MainWindow", "Water temperature", None))
        self.cav_temp_label.setText(_translate("MainWindow", "Cavity temperature", None))
        self.cav_temp_outputwidget.setText(_translate("MainWindow", "0", None))
        self.water_temp_outputwidget.setText(_translate("MainWindow", "0", None))
        self.pulse_length_outputwidget.setText(_translate("MainWindow", "0", None))
        self.fwd_kly_power_label.setText(_translate("MainWindow", "Forward power at klystron", None))
        self.rev_kly_power_label.setText(_translate("MainWindow", "Reverse power at klystron", None))
        self.fwd_cav_power_outputwidget.setText(_translate("MainWindow", "No", None))
        self.pulse_length_label.setText(_translate("MainWindow", "Pulse length", None))
        self.fwd_kly_power_outputwidget.setText(_translate("MainWindow", "0", None))
        self.fwd_cav_power_label.setText(_translate("MainWindow", "Forward power at cavity", None))
        self.rev_cav_power_label.setText(_translate("MainWindow", "Reverse power at cavity", None))
        self.rev_kly_power_outputwidget.setText(_translate("MainWindow", "0", None))
        self.rev_cav_power_outputwidget.setText(_translate("MainWindow", "0", None))
        self.probe_power_label.setText(_translate("MainWindow", "Probe power", None))
        self.probe_power_outputwidget.setText(_translate("MainWindow", "0", None))
        self.vac_level_label.setText(_translate("MainWindow", "Vacuum level on IMG", None))
        self.vac_level_outputwidget.setText(_translate("MainWindow", "0", None))
        self.vac_valve_status_label.setText(_translate("MainWindow", "Vacuum valve status", None))
        self.vac_valve_status_outputwidget.setText(_translate("MainWindow", "Open", None))
        self.breakdown_rate_limit_label.setText(_translate("MainWindow", "Breakdown rate limit", None))
        self.measured_breakdown_rate_label.setText(_translate("MainWindow", "Measured breakdown rate", None))
        self.breakdown_rate_statistics_label.setText(_translate("MainWindow", "Breakdown rate statistics", None))
        self.breakdown_rate_limit_outputwidget.setText(_translate("MainWindow", "0", None))
        self.measured_breakdown_rate_outputwidget.setText(_translate("MainWindow", "0", None))
        self.breakdown_rate_statistics_outputwidget.setText(_translate("MainWindow", "Terrible", None))
        self.copy_to_clipboard_button.setToolTip(_translate("MainWindow", "For the log!", None))
        self.copy_to_clipboard_button.setText(_translate("MainWindow", "Copy status to clipboard", None))
        self.label.setText(_translate("MainWindow", "Everything is fine :)", None))

from pyqtgraph import PlotWidget
