from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class scopeWriterUi(object):
    def setupUi(self, mainWindow):
        mainWindow.resize(1010, 510)
        #self.scopeCont = scopeCont
        mainWindow.setObjectName(_fromUtf8("Scope writer"))
        self.mainWidget = QtGui.QWidget(mainWindow)
        self.mainWidget.resize(1000,500)
        self.mainWidget.setObjectName(_fromUtf8("mainWidget"))
        self.mainBox = QtGui.QHBoxLayout(self.mainWidget)
        self.channelsVBox = QtGui.QVBoxLayout()
        #self.addChannel( self.TabWidget, self.channelsVBox, self.scopeCont )
        self.logVBox = QtGui.QVBoxLayout()
        self.labelBox = QtGui.QVBoxLayout()
        self.addToListButton = QtGui.QPushButton()
        self.addToListButton.setObjectName(_fromUtf8("addToListButton"))
        self.addToListButton.setMinimumSize(QtCore.QSize(100,100))
        self.addToListButton.setMaximumSize(QtCore.QSize(100,100))
        self.startButton = QtGui.QPushButton()
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.startButton.setMaximumSize(QtCore.QSize(100,100))
        self.startButton.setMinimumSize(QtCore.QSize(100,100))
        self.stopButton = QtGui.QPushButton()
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.stopButton.setMinimumSize(QtCore.QSize(100,100))
        self.stopButton.setMaximumSize(QtCore.QSize(100,100))
        self.clearLayoutButton = QtGui.QPushButton()
        self.clearLayoutButton.setObjectName(_fromUtf8("clearLayoutButton"))
        self.clearLayoutButton.setMinimumSize(QtCore.QSize(100, 100))
        self.clearLayoutButton.setMaximumSize(QtCore.QSize(100, 100))
        self.tableRows = 1
        self.tableColumns = 2
        self.logTable = QtGui.QTableWidget( self.tableRows, self.tableColumns )
        self.logTable.setObjectName(_fromUtf8("logTable"))
        self.logTable.setItem(0, 0, QtGui.QTableWidgetItem("Timestamp"))
        self.logTable.setItem(0, 1, QtGui.QTableWidgetItem("Q"))
        self.logTable.setMinimumSize(QtCore.QSize(300,100))
        self.logVBox.addWidget( self.addToListButton )
        #self.logVBox.addWidget( self.logTable )
        self.logVBox.addWidget( self.startButton )
        self.logVBox.addWidget( self.stopButton )
        # self.logVBox.addWidget( self.clearLayoutButton )
        self.titleLabel = QtGui.QLabel()
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.titleLabel.setMaximumSize(QtCore.QSize(300,200))
        self.infoLabel = QtGui.QLabel()
        self.infoLabel.setObjectName(_fromUtf8("infoLabel"))
        self.infoLabel.setMaximumSize(QtCore.QSize(300,200))
        # self.loadButton = QtGui.QPushButton()
        # self.loadButton.setObjectName(_fromUtf8("loadButton"))
        # self.loadButton.setMinimumSize(QtCore.QSize(100,100))
        # self.loadButton.setMaximumSize(QtCore.QSize(100,100))
        self.setTimebaseButton = QtGui.QPushButton()
        self.setTimebaseButton.setObjectName(_fromUtf8("setTimebaseButton"))
        self.setTimebaseButton.setMinimumSize(QtCore.QSize(100,30))
        self.setTimebaseButton.setMaximumSize(QtCore.QSize(100,30))
        self.setTimebaseTextEdit = QtGui.QPlainTextEdit()
        self.setTimebaseTextEdit.setObjectName(_fromUtf8("setTimebaseTextEdit"))
        self.setTimebaseTextEdit.setPlainText(_translate("mainWindow", "", None))
        self.setTimebaseTextEdit.setMinimumSize(QtCore.QSize(60, 30))
        self.setTimebaseTextEdit.setMaximumSize(QtCore.QSize(60, 30))
        self.traceLabel = QtGui.QLabel()
        self.traceLabel.setObjectName(_fromUtf8("traceLabel"))
        self.traceLabel.setMaximumSize(QtCore.QSize(50, 30))
        self.traceSizeLabel = QtGui.QLabel()
        self.traceSizeLabel.setObjectName(_fromUtf8("traceSizeLabel"))
        self.traceSizeLabel.setMaximumSize(QtCore.QSize(50, 30))
        self.traceWarningLabel = QtGui.QLabel()
        self.traceWarningLabel.setObjectName(_fromUtf8("traceWarningLabel"))
        self.traceWarningLabel.setMaximumSize(QtCore.QSize(100, 150))
        self.setTimeBaseHBox = QtGui.QHBoxLayout()
        self.setTimeBaseHBox.addWidget(self.setTimebaseButton)
        self.setTimeBaseHBox.addWidget(self.setTimebaseTextEdit)
        self.traceLabelHBox = QtGui.QHBoxLayout()
        self.traceLabelHBox.addWidget(self.traceLabel)
        self.traceLabelHBox.addWidget(self.traceSizeLabel)
        self.traceLabelHBox.addWidget(self.traceWarningLabel)
        self.setTimebaseVBox = QtGui.QVBoxLayout()
        self.setTimebaseVBox.addLayout(self.setTimeBaseHBox)
        self.setTimebaseVBox.addLayout(self.traceLabelHBox)
        # self.ui_lay = QtGui.QHBoxLayout()
        # self.ui_line = QtGui.QLineEdit()
        # self.ui_lay.addWidget(self.ui_line)
        # self.ui_btn = QtGui.QPushButton('...')
        # self.ui_line.setMinimumSize(QtCore.QSize(250,20))
        # self.ui_line.setMaximumSize(QtCore.QSize(250,20))
        # self.ui_btn.setMinimumSize(QtCore.QSize(20,20))
        # self.ui_btn.setMaximumSize(QtCore.QSize(20,20))
        # self.ui_lay.addWidget(self.ui_btn)
        self.labelBox.addWidget(self.titleLabel)
        self.labelBox.addWidget(self.infoLabel)
        # self.labelBox.addLayout(self.ui_lay)
        self.labelBox.addLayout(self.setTimebaseVBox)
        self.mainBox.addLayout(self.labelBox)
        self.mainBox.addLayout(self.logVBox)
        self.mainBox.addLayout(self.channelsVBox)
        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "Scope charge writer", None))
        self.addToListButton.setText(_translate("mainWindow", "Add channel\n to list", None))
        self.startButton.setText(_translate("mainWindow", "Start logging\n to EPICS", None))
        self.stopButton.setText(_translate("mainWindow", "Stop logging", None))
        self.clearLayoutButton.setText(_translate("mainWindow", "Remove channel", None))
        # self.loadButton.setText(_translate("mainWindow", "Load setup", None))
        self.setTimebaseButton.setText(_translate("mainWindow", "Set timebase", None))
        self.newFont = QtGui.QFont("Comic Sans", 20, QtGui.QFont.Bold)
        self.titleLabel.setFont(self.newFont)
        self.titleLabel.setText(_translate("mainWindow", "CLARA \nScope Logger", None))
        self.infoText = "Choose the scope channel to read from EPICS,\n the PV to write the measurement to, the type\n of measurement "
        self.infoText1 = self.infoText+"required, and \nthe regions of interest.\n"
        self.infoText2 = self.infoText1+"CHECK THAT THE CORRECT TRACES\n ARE BEING RECORDED ON THE SCOPE!!!!"
        self.infoLabel.setText(_translate("mainWindow", self.infoText2, None))
        self.traceLabel.setText(_translate("mainWindow", "Trace size", None))


    def addChannel(self, Layout, scopeCont):
        self.channelsLayout = Layout
        self.scopeCont = scopeCont
        self.hBox = QtGui.QHBoxLayout()
        self.chanVBox = QtGui.QVBoxLayout()
        self.channelNameLabel = QtGui.QLabel()
        self.channelNameLabel.setObjectName(_fromUtf8("channelNameLabel"))
        self.channelNameLabel.setText(_translate("mainWindow", "Scope channel", None))
        self.channels = ["Z1", "Z2", "Z3", "Z4"]
        self.chanComboBox = QtGui.QComboBox()
        self.chanComboBox.setObjectName(_fromUtf8("chanComboBox"))
        for i in self.channels:
            self.chanComboBox.addItem( i )
        self.chanVBox.addWidget( self.channelNameLabel )
        self.chanVBox.addWidget( self.chanComboBox )
        self.chanVBox.addStretch()
        self.epicsVBox = QtGui.QVBoxLayout()
        self.epicsNameLabel = QtGui.QLabel()
        self.epicsNameLabel.setObjectName(_fromUtf8("epicsNameLabel"))
        self.epicsNameLabel.setText(_translate("mainWindow", "EPICS PV Name", None))
        self.epicsPVs = ["P1", "P2", "P3", "P4"]
        self.epicsComboBox = QtGui.QComboBox()
        self.epicsComboBox.setObjectName(_fromUtf8("epicsComboBox"))
        self.epicsComboBox.setMinimumSize(QtCore.QSize(130,20))
        self.scopeName = self.scopeCont.getScopeNames()[0]
        self.traceDataStruct = self.scopeCont.getScopeTraceDataStruct( self.scopeName )
        for i in self.epicsPVs:
            self.epicsPVName = self.traceDataStruct.pvRoot+":"+str(i)
            self.epicsComboBox.addItem( self.epicsPVName )
        self.epicsVBox.addWidget(self.epicsNameLabel)
        self.epicsVBox.addWidget(self.epicsComboBox)
        self.epicsVBox.addStretch()
        self.measurementVBox = QtGui.QVBoxLayout()
        self.measurementNameLabel = QtGui.QLabel()
        self.measurementNameLabel.setObjectName(_fromUtf8("measurementNameLabel"))
        self.measurementNameLabel.setText(_translate("mainWindow", "Measurement Type?", None))
        self.types = ["Area", "Max", "Min", "Peak-to-Peak"]
        self.measurementComboBox = QtGui.QComboBox()
        self.measurementComboBox.setObjectName(_fromUtf8("measurementComboBox"))
        for i in self.types:
            self.measurementComboBox.addItem( i )
        self.measurementVBox.addWidget( self.measurementNameLabel )
        self.measurementVBox.addWidget( self.measurementComboBox )
        self.measurementVBox.addStretch()
        self.filterVBox = QtGui.QVBoxLayout()
        self.filterNameLabel = QtGui.QLabel()
        self.filterNameLabel.setObjectName(_fromUtf8("filterNameLabel"))
        self.filterNameLabel.setText(_translate("mainWindow", "Filter Type?", None))
        self.filterTypes = ["None", "Moving Average", "Gaussian filter", "FFT", "Baseline Subtraction"]
        self.filterComboBox = QtGui.QComboBox()
        self.filterComboBox.setObjectName(_fromUtf8("filterComboBox"))
        for i in self.filterTypes:
            self.filterComboBox.addItem( i )
        self.filterVBox.addWidget( self.filterNameLabel )
        self.filterVBox.addWidget( self.filterComboBox )
        self.filterVBox.addStretch()
        self.filterIntervalVBox = QtGui.QVBoxLayout()
        self.filterIntervalNameLabel = QtGui.QLabel()
        self.filterIntervalNameLabel.setObjectName(_fromUtf8("filterIntervalNameLabel"))
        self.filterIntervalNameLabel.setText(_translate("mainWindow", "Filtering interval", None))
        self.filterInterval = QtGui.QPlainTextEdit()
        self.filterInterval.setObjectName(_fromUtf8("filterInterval"))
        self.filterInterval.setPlainText(_translate("mainWindow", "5", None))
        self.filterInterval.setMaximumSize(QtCore.QSize(100,30))
        self.filterIntervalVBox.addWidget( self.filterIntervalNameLabel )
        self.filterIntervalVBox.addWidget( self.filterInterval )
        self.filterIntervalVBox.addStretch()
        self.toLabel = QtGui.QLabel()
        self.toLabel.setObjectName(_fromUtf8("toLabel"))
        self.toLabel.setText(_translate("mainWindow", " to ", None))
        self.signalVBox = QtGui.QVBoxLayout()
        self.signalHBox = QtGui.QHBoxLayout()
        self.signalNameLabel = QtGui.QLabel()
        self.signalNameLabel.setObjectName(_fromUtf8("signalNameLabel"))
        self.signalNameLabel.setText(_translate("mainWindow", "Signal region", None))
        self.lowerSignalBound = QtGui.QPlainTextEdit()
        self.lowerSignalBound.setObjectName(_fromUtf8("lowerSignalBound"))
        self.lowerSignalBound.setPlainText(_translate("mainWindow", "600", None))
        self.upperSignalBound = QtGui.QPlainTextEdit()
        self.upperSignalBound.setObjectName(_fromUtf8("upperSignalBound"))
        self.upperSignalBound.setPlainText(_translate("mainWindow", "1000", None))
        self.lowerSignalBound.setMaximumSize(QtCore.QSize(100,30))
        self.upperSignalBound.setMaximumSize(QtCore.QSize(100,30))
        self.signalHBox.addWidget( self.lowerSignalBound )
        self.signalHBox.addWidget( self.toLabel )
        self.signalHBox.addWidget( self.upperSignalBound )
        self.signalVBox.addWidget( self.signalNameLabel )
        self.signalVBox.addLayout( self.signalHBox )
        self.signalVBox.addStretch()
        self.hBox.addLayout( self.chanVBox )
        self.hBox.addLayout( self.epicsVBox )
        self.hBox.addLayout( self.measurementVBox )
        self.hBox.addLayout( self.filterVBox )
        self.hBox.addLayout( self.filterIntervalVBox )
        self.hBox.addLayout( self.signalVBox )
        self.channelsLayout.addLayout( self.hBox )
