# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(307, 444)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.numImages_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.numImages_spinBox.setMinimum(1)
        self.numImages_spinBox.setObjectName(_fromUtf8("numImages_spinBox"))
        self.gridLayout.addWidget(self.numImages_spinBox, 8, 1, 1, 1)
        self.cameraName_comboBox = QtGui.QComboBox(self.centralwidget)
        self.cameraName_comboBox.setObjectName(_fromUtf8("cameraName_comboBox"))
        self.gridLayout.addWidget(self.cameraName_comboBox, 1, 0, 1, 2)
        self.acquire_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.acquire_pushButton.sizePolicy().hasHeightForWidth())
        self.acquire_pushButton.setSizePolicy(sizePolicy)
        self.acquire_pushButton.setMaximumSize(QtCore.QSize(16777215, 100))
        self.acquire_pushButton.setObjectName(_fromUtf8("acquire_pushButton"))
        self.gridLayout.addWidget(self.acquire_pushButton, 7, 0, 1, 2)
        self.save_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.save_pushButton.sizePolicy().hasHeightForWidth())
        self.save_pushButton.setSizePolicy(sizePolicy)
        self.save_pushButton.setMaximumSize(QtCore.QSize(16777215, 100))
        self.save_pushButton.setObjectName(_fromUtf8("save_pushButton"))
        self.gridLayout.addWidget(self.save_pushButton, 9, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 8, 0, 1, 1)
        self.liveStream_pushButton = QtGui.QPushButton(self.centralwidget)
        self.liveStream_pushButton.setObjectName(_fromUtf8("liveStream_pushButton"))
        self.gridLayout.addWidget(self.liveStream_pushButton, 2, 0, 1, 2)
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.getImages_pushButton = QtGui.QPushButton(self.centralwidget)
        self.getImages_pushButton.setObjectName(_fromUtf8("getImages_pushButton"))
        self.gridLayout.addWidget(self.getImages_pushButton, 10, 0, 1, 2)
        self.spinBox_minLevel = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_minLevel.setMaximum(65536)
        self.spinBox_minLevel.setObjectName(_fromUtf8("spinBox_minLevel"))
        self.gridLayout.addWidget(self.spinBox_minLevel, 5, 0, 1, 1)
        self.spinBox_maxLevel = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_maxLevel.setMaximum(65536)
        self.spinBox_maxLevel.setProperty("value", 65536)
        self.spinBox_maxLevel.setObjectName(_fromUtf8("spinBox_maxLevel"))
        self.gridLayout.addWidget(self.spinBox_maxLevel, 5, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 307, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Collector", None))
        self.label_3.setText(_translate("MainWindow", "Min. Level:", None))
        self.acquire_pushButton.setText(_translate("MainWindow", "Acquire", None))
        self.save_pushButton.setText(_translate("MainWindow", "Collect and Save", None))
        self.label_2.setText(_translate("MainWindow", "Number of Images:", None))
        self.liveStream_pushButton.setText(_translate("MainWindow", "Live Steam", None))
        self.label.setText(_translate("MainWindow", "Selected Camera:", None))
        self.getImages_pushButton.setText(_translate("MainWindow", "Open Image Directory", None))
        self.label_4.setText(_translate("MainWindow", "Max. Level:", None))

