# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(483, 589)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 80, 221, 161))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 270, 61, 31))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(160, 270, 61, 31))
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 250, 46, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 250, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.plainTextEdit_4 = QtGui.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(20, 340, 61, 31))
        self.plainTextEdit_4.setObjectName(_fromUtf8("plainTextEdit_4"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 10, 91, 41))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(8, 20, 231, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.plainTextEdit_5 = QtGui.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(160, 340, 61, 31))
        self.plainTextEdit_5.setObjectName(_fromUtf8("plainTextEdit_5"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 320, 46, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 320, 46, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.plainTextEdit1 = QtGui.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit1.setGeometry(QtCore.QRect(260, 80, 211, 311))
        self.plainTextEdit1.setObjectName(_fromUtf8("plainTextEdit1"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(260, 60, 111, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 420, 91, 41))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.plainTextEdit_3 = QtGui.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(10, 420, 221, 41))
        self.plainTextEdit_3.setObjectName(_fromUtf8("plainTextEdit_3"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(360, 400, 120, 80))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radioButton = QtGui.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 50, 82, 17))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 490, 91, 41))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 483, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton.setText(_translate("MainWindow", "Set random values", None))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "1", None))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "10", None))
        self.label.setText(_translate("MainWindow", "Lower", None))
        self.label_2.setText(_translate("MainWindow", "Upper", None))
        self.plainTextEdit_4.setPlainText(_translate("MainWindow", "-1", None))
        self.pushButton_2.setText(_translate("MainWindow", "Append to List", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "VM-EBT-INJ-SCOPE-01:P1", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "VM-EBT-INJ-SCOPE-01:P2", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "VM-EBT-INJ-SCOPE-01:P3", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "VM-EBT-INJ-SCOPE-01:P4", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "VM-EBT-INJ-DIA-BPMC-02:Y", None))
        self.comboBox.setItemText(5, _translate("MainWindow", "VM-EBT-INJ-DIA-BPMC-04:X", None))
        self.comboBox.setItemText(6, _translate("MainWindow", "VM-EBT-INJ-DIA-BPMC-06:X", None))
        self.comboBox.setItemText(7, _translate("MainWindow", "VM-EBT-INJ-DIA-BPMC-10:X", None))
        self.comboBox.setItemText(8, _translate("MainWindow", "VM-EBT-INJ-DIA-BPMC-12:X", None))
        self.comboBox.setItemText(9, _translate("MainWindow", "VM-EBT-INJ-DIA-BPMC-02:Y", None))
        self.comboBox.setItemText(10, _translate("MainWindow", "VM-EBT-INJ-DIA-BPMC-04:Y", None))
        self.comboBox.setItemText(11, _translate("MainWindow", "VM-EBT-INJ-DIA-BPMC-06:Y", None))
        self.comboBox.setItemText(12, _translate("MainWindow", "VM-EBT-INJ-DIA-BPMC-10:Y", None))
        self.comboBox.setItemText(13, _translate("MainWindow", "VM-EBT-INJ-DIA-BPMC-12:Y", None))
        self.comboBox.setItemText(14, _translate("MainWindow", "VM-EBT-INJ-DIA-BPMC-02:DATA:B2V.VALA", None))
        self.comboBox.setItemText(15, _translate("MainWindow", "VM-EBT-INJ-DIA-BPMC-04:DATA:B2V.VALA", None))
        self.comboBox.setItemText(16, _translate("MainWindow", "VM-EBT-INJ-DIA-BPMC-06:DATA:B2V.VALA", None))
        self.comboBox.setItemText(17, _translate("MainWindow", "VM-EBT-INJ-DIA-BPMC-10:DATA:B2V.VALA", None))
        self.comboBox.setItemText(18, _translate("MainWindow", "VM-EBT-INJ-DIA-BPMC-12:DATA:B2V.VALA", None))
        self.comboBox.setItemText(19, _translate("MainWindow", "VM-EBT-INJ-DIA-BPMC-14:DATA:B2V.VALA", None))
        self.plainTextEdit_5.setPlainText(_translate("MainWindow", "10", None))
        self.label_3.setText(_translate("MainWindow", "# Shots", None))
        self.label_4.setText(_translate("MainWindow", "Rep rate", None))
        self.label_5.setText(_translate("MainWindow", "PV List", None))
        self.pushButton_3.setText(_translate("MainWindow", "Add new PV", None))
        self.groupBox.setTitle(_translate("MainWindow", "PV Type", None))
        self.radioButton.setText(_translate("MainWindow", "Number", None))
        self.radioButton_2.setText(_translate("MainWindow", "Array", None))
        self.pushButton_4.setText(_translate("MainWindow", "Stop", None))
