# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(456, 825)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.spinBox_maxLevel = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_maxLevel.setMaximum(65536)
        self.spinBox_maxLevel.setProperty("value", 65536)
        self.spinBox_maxLevel.setObjectName(_fromUtf8("spinBox_maxLevel"))
        self.gridLayout.addWidget(self.spinBox_maxLevel, 5, 1, 1, 1)
        self.spinBox_minLevel = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_minLevel.setMaximum(65536)
        self.spinBox_minLevel.setObjectName(_fromUtf8("spinBox_minLevel"))
        self.gridLayout.addWidget(self.spinBox_minLevel, 5, 0, 1, 1)
        self.stepSize_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.stepSize_spinBox.setMaximum(10)
        self.stepSize_spinBox.setSingleStep(1)
        self.stepSize_spinBox.setProperty("value", 1)
        self.stepSize_spinBox.setObjectName(_fromUtf8("stepSize_spinBox"))
        self.gridLayout.addWidget(self.stepSize_spinBox, 17, 1, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 7, 0, 1, 2)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 12, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 2)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 17, 0, 1, 1)
        self.analyse_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.analyse_pushButton.sizePolicy().hasHeightForWidth())
        self.analyse_pushButton.setSizePolicy(sizePolicy)
        self.analyse_pushButton.setMaximumSize(QtCore.QSize(16777215, 100))
        self.analyse_pushButton.setObjectName(_fromUtf8("analyse_pushButton"))
        self.gridLayout.addWidget(self.analyse_pushButton, 13, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.numImages_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.numImages_spinBox.setMinimum(1)
        self.numImages_spinBox.setObjectName(_fromUtf8("numImages_spinBox"))
        self.gridLayout.addWidget(self.numImages_spinBox, 9, 1, 1, 1)
        self.cameraName_comboBox = QtGui.QComboBox(self.centralwidget)
        self.cameraName_comboBox.setObjectName(_fromUtf8("cameraName_comboBox"))
        self.gridLayout.addWidget(self.cameraName_comboBox, 1, 0, 1, 2)
        self.acquire_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.acquire_pushButton.sizePolicy().hasHeightForWidth())
        self.acquire_pushButton.setSizePolicy(sizePolicy)
        self.acquire_pushButton.setMaximumSize(QtCore.QSize(16777215, 100))
        self.acquire_pushButton.setObjectName(_fromUtf8("acquire_pushButton"))
        self.gridLayout.addWidget(self.acquire_pushButton, 8, 0, 1, 2)
        self.save_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.save_pushButton.sizePolicy().hasHeightForWidth())
        self.save_pushButton.setSizePolicy(sizePolicy)
        self.save_pushButton.setMaximumSize(QtCore.QSize(16777215, 100))
        self.save_pushButton.setObjectName(_fromUtf8("save_pushButton"))
        self.gridLayout.addWidget(self.save_pushButton, 10, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 9, 0, 1, 1)
        self.liveStream_pushButton = QtGui.QPushButton(self.centralwidget)
        self.liveStream_pushButton.setObjectName(_fromUtf8("liveStream_pushButton"))
        self.gridLayout.addWidget(self.liveStream_pushButton, 2, 0, 1, 2)
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.getImages_pushButton = QtGui.QPushButton(self.centralwidget)
        self.getImages_pushButton.setObjectName(_fromUtf8("getImages_pushButton"))
        self.gridLayout.addWidget(self.getImages_pushButton, 11, 0, 1, 2)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.resetBackground_pushButton = QtGui.QPushButton(self.centralwidget)
        self.resetBackground_pushButton.setObjectName(_fromUtf8("resetBackground_pushButton"))
        self.gridLayout.addWidget(self.resetBackground_pushButton, 14, 0, 1, 1)
        self.useBackground_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.useBackground_checkBox.setObjectName(_fromUtf8("useBackground_checkBox"))
        self.gridLayout.addWidget(self.useBackground_checkBox, 14, 1, 1, 1)
        self.maskX_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.maskX_spinBox.setMaximum(9999)
        self.maskX_spinBox.setObjectName(_fromUtf8("maskX_spinBox"))
        self.gridLayout.addWidget(self.maskX_spinBox, 18, 1, 1, 1)
        self.maskY_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.maskY_spinBox.setMaximum(9999)
        self.maskY_spinBox.setObjectName(_fromUtf8("maskY_spinBox"))
        self.gridLayout.addWidget(self.maskY_spinBox, 19, 1, 1, 1)
        self.maskXRadius_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.maskXRadius_spinBox.setMaximum(9999)
        self.maskXRadius_spinBox.setObjectName(_fromUtf8("maskXRadius_spinBox"))
        self.gridLayout.addWidget(self.maskXRadius_spinBox, 20, 1, 1, 1)
        self.maskYRadius_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.maskYRadius_spinBox.setMaximum(9999)
        self.maskYRadius_spinBox.setObjectName(_fromUtf8("maskYRadius_spinBox"))
        self.gridLayout.addWidget(self.maskYRadius_spinBox, 21, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 18, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 19, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 20, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 21, 0, 1, 1)
        self.setMask_pushButton = QtGui.QPushButton(self.centralwidget)
        self.setMask_pushButton.setObjectName(_fromUtf8("setMask_pushButton"))
        self.gridLayout.addWidget(self.setMask_pushButton, 22, 0, 1, 2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout.addLayout(self.gridLayout_2, 0, 2, 24, 1)
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 16, 1, 1, 1)
        self.useNPoint_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.useNPoint_checkBox.setObjectName(_fromUtf8("useNPoint_checkBox"))
        self.gridLayout.addWidget(self.useNPoint_checkBox, 16, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 456, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Collector", None))
        self.label_5.setText(_translate("MainWindow", "Step Size:", None))
        self.analyse_pushButton.setText(_translate("MainWindow", "Analyse", None))
        self.label_3.setText(_translate("MainWindow", "Min. Level:", None))
        self.acquire_pushButton.setText(_translate("MainWindow", "Acquire", None))
        self.save_pushButton.setText(_translate("MainWindow", "Collect and Save", None))
        self.label_2.setText(_translate("MainWindow", "Number of Images:", None))
        self.liveStream_pushButton.setText(_translate("MainWindow", "Live Steam", None))
        self.label.setText(_translate("MainWindow", "Selected Camera:", None))
        self.getImages_pushButton.setText(_translate("MainWindow", "Open Image Directory", None))
        self.label_4.setText(_translate("MainWindow", "Max. Level:", None))
        self.resetBackground_pushButton.setText(_translate("MainWindow", "Reset Background Image", None))
        self.useBackground_checkBox.setText(_translate("MainWindow", "Use Background", None))
        self.label_6.setText(_translate("MainWindow", "Mask Center X Pixel:", None))
        self.label_7.setText(_translate("MainWindow", "Mask Center Y Pixel:", None))
        self.label_8.setText(_translate("MainWindow", "Mask X Radius Pixel:", None))
        self.label_9.setText(_translate("MainWindow", "Mask Y Radius Pixel:", None))
        self.setMask_pushButton.setText(_translate("MainWindow", "Set Mask", None))
        self.checkBox.setText(_translate("MainWindow", "Feedback", None))
        self.useNPoint_checkBox.setText(_translate("MainWindow", "Use N-Point Scaling", None))

