# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!
import sys,os
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

def resource_path(relative_path):
	if hasattr(sys, '_MEIPASS'):
		return os.path.join(sys._MEIPASS, relative_path)
	return os.path.join(os.path.abspath("."), relative_path)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(1141, 878)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(resource_path("Solenoids.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.groupBox_X = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_X.setMinimumSize(QtCore.QSize(400, 0))
        self.groupBox_X.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_X.setObjectName(_fromUtf8("groupBox_X"))
        self.gridLayout_sky = QtGui.QGridLayout(self.groupBox_X)
        self.gridLayout_sky.setObjectName(_fromUtf8("gridLayout_sky"))
        self.gridLayout_6.addWidget(self.groupBox_X, 0, 0, 2, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1141, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)
        self.dockWidget_5 = QtGui.QDockWidget(mainWindow)
        self.dockWidget_5.setWindowIcon(icon)
        self.dockWidget_5.setWindowTitle(_fromUtf8(""))
        self.dockWidget_5.setObjectName(_fromUtf8("dockWidget_5"))
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName(_fromUtf8("dockWidgetContents_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.dockWidgetContents_6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.groupBox_4 = QtGui.QGroupBox(self.dockWidgetContents_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_93 = QtGui.QLabel(self.groupBox_4)
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.gridLayout_5.addWidget(self.label_93, 6, 1, 1, 1)
        self.doubleSpinBox_c2v_hcor01 = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_c2v_hcor01.setDecimals(4)
        self.doubleSpinBox_c2v_hcor01.setSingleStep(0.0001)
        self.doubleSpinBox_c2v_hcor01.setObjectName(_fromUtf8("doubleSpinBox_c2v_hcor01"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_c2v_hcor01, 1, 2, 1, 1)
        self.label_80 = QtGui.QLabel(self.groupBox_4)
        self.label_80.setMaximumSize(QtCore.QSize(20, 20))
        self.label_80.setText(_fromUtf8(""))
        self.label_80.setPixmap(QtGui.QPixmap(resource_path("Dipoles.png")))
        self.label_80.setScaledContents(True)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.gridLayout_5.addWidget(self.label_80, 0, 0, 1, 1)
        self.doubleSpinBox_c2v_d2 = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_c2v_d2.setDecimals(3)
        self.doubleSpinBox_c2v_d2.setMinimum(-999.999)
        self.doubleSpinBox_c2v_d2.setMaximum(999.999)
        self.doubleSpinBox_c2v_d2.setSingleStep(0.001)
        self.doubleSpinBox_c2v_d2.setObjectName(_fromUtf8("doubleSpinBox_c2v_d2"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_c2v_d2, 6, 2, 1, 1)
        self.doubleSpinBox_c2v_q3 = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_c2v_q3.setDecimals(3)
        self.doubleSpinBox_c2v_q3.setMinimum(-999.999)
        self.doubleSpinBox_c2v_q3.setMaximum(999.999)
        self.doubleSpinBox_c2v_q3.setSingleStep(0.001)
        self.doubleSpinBox_c2v_q3.setObjectName(_fromUtf8("doubleSpinBox_c2v_q3"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_c2v_q3, 5, 2, 1, 1)
        self.doubleSpinBox_c2v_q2 = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_c2v_q2.setDecimals(3)
        self.doubleSpinBox_c2v_q2.setMinimum(-999.999)
        self.doubleSpinBox_c2v_q2.setMaximum(999.999)
        self.doubleSpinBox_c2v_q2.setSingleStep(0.001)
        self.doubleSpinBox_c2v_q2.setObjectName(_fromUtf8("doubleSpinBox_c2v_q2"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_c2v_q2, 4, 2, 1, 1)
        self.label_92 = QtGui.QLabel(self.groupBox_4)
        self.label_92.setMaximumSize(QtCore.QSize(20, 20))
        self.label_92.setText(_fromUtf8(""))
        self.label_92.setPixmap(QtGui.QPixmap(resource_path("Dipoles.png")))
        self.label_92.setScaledContents(True)
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.gridLayout_5.addWidget(self.label_92, 6, 0, 1, 1)
        self.label_91 = QtGui.QLabel(self.groupBox_4)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.gridLayout_5.addWidget(self.label_91, 5, 1, 1, 1)
        self.label_90 = QtGui.QLabel(self.groupBox_4)
        self.label_90.setMaximumSize(QtCore.QSize(20, 20))
        self.label_90.setText(_fromUtf8(""))
        self.label_90.setPixmap(QtGui.QPixmap(resource_path("Quadrupoles.png")))
        self.label_90.setScaledContents(True)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.gridLayout_5.addWidget(self.label_90, 5, 0, 1, 1)
        self.label_89 = QtGui.QLabel(self.groupBox_4)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.gridLayout_5.addWidget(self.label_89, 4, 1, 1, 1)
        self.label_88 = QtGui.QLabel(self.groupBox_4)
        self.label_88.setMaximumSize(QtCore.QSize(20, 20))
        self.label_88.setText(_fromUtf8(""))
        self.label_88.setPixmap(QtGui.QPixmap(resource_path("Quadrupoles.png")))
        self.label_88.setScaledContents(True)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.gridLayout_5.addWidget(self.label_88, 4, 0, 1, 1)
        self.doubleSpinBox_c2v_q1 = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_c2v_q1.setDecimals(3)
        self.doubleSpinBox_c2v_q1.setMinimum(-999.999)
        self.doubleSpinBox_c2v_q1.setMaximum(999.999)
        self.doubleSpinBox_c2v_q1.setSingleStep(0.001)
        self.doubleSpinBox_c2v_q1.setObjectName(_fromUtf8("doubleSpinBox_c2v_q1"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_c2v_q1, 3, 2, 1, 1)
        self.doubleSpinBox_c2v_vcor01 = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_c2v_vcor01.setDecimals(4)
        self.doubleSpinBox_c2v_vcor01.setSingleStep(0.0001)
        self.doubleSpinBox_c2v_vcor01.setObjectName(_fromUtf8("doubleSpinBox_c2v_vcor01"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_c2v_vcor01, 2, 2, 1, 1)
        self.label_87 = QtGui.QLabel(self.groupBox_4)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.gridLayout_5.addWidget(self.label_87, 3, 1, 1, 1)
        self.label_86 = QtGui.QLabel(self.groupBox_4)
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.gridLayout_5.addWidget(self.label_86, 2, 1, 1, 1)
        self.label_85 = QtGui.QLabel(self.groupBox_4)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.gridLayout_5.addWidget(self.label_85, 1, 1, 1, 1)
        self.label_84 = QtGui.QLabel(self.groupBox_4)
        self.label_84.setMaximumSize(QtCore.QSize(20, 20))
        self.label_84.setText(_fromUtf8(""))
        self.label_84.setPixmap(QtGui.QPixmap(resource_path("Quadrupoles.png")))
        self.label_84.setScaledContents(True)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.gridLayout_5.addWidget(self.label_84, 3, 0, 1, 1)
        self.label_83 = QtGui.QLabel(self.groupBox_4)
        self.label_83.setMaximumSize(QtCore.QSize(20, 20))
        self.label_83.setText(_fromUtf8(""))
        self.label_83.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_83.setScaledContents(True)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.gridLayout_5.addWidget(self.label_83, 2, 0, 1, 1)
        self.label_82 = QtGui.QLabel(self.groupBox_4)
        self.label_82.setMaximumSize(QtCore.QSize(20, 20))
        self.label_82.setText(_fromUtf8(""))
        self.label_82.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_82.setScaledContents(True)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.gridLayout_5.addWidget(self.label_82, 1, 0, 1, 1)
        self.label_81 = QtGui.QLabel(self.groupBox_4)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.gridLayout_5.addWidget(self.label_81, 0, 1, 1, 1)
        self.doubleSpinBox_c2v_d1 = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_c2v_d1.setDecimals(3)
        self.doubleSpinBox_c2v_d1.setMinimum(-999.999)
        self.doubleSpinBox_c2v_d1.setMaximum(999.999)
        self.doubleSpinBox_c2v_d1.setSingleStep(0.001)
        self.doubleSpinBox_c2v_d1.setObjectName(_fromUtf8("doubleSpinBox_c2v_d1"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_c2v_d1, 0, 2, 1, 1)
        self.doubleSpinBox_c2v_d1.raise_()
        self.label_80.raise_()
        self.label_81.raise_()
        self.label_82.raise_()
        self.label_83.raise_()
        self.label_84.raise_()
        self.label_85.raise_()
        self.label_86.raise_()
        self.label_87.raise_()
        self.doubleSpinBox_c2v_hcor01.raise_()
        self.doubleSpinBox_c2v_vcor01.raise_()
        self.doubleSpinBox_c2v_q1.raise_()
        self.label_88.raise_()
        self.label_89.raise_()
        self.label_90.raise_()
        self.label_91.raise_()
        self.label_92.raise_()
        self.label_93.raise_()
        self.doubleSpinBox_c2v_q2.raise_()
        self.doubleSpinBox_c2v_q3.raise_()
        self.doubleSpinBox_c2v_d2.raise_()
        self.gridLayout_7.addWidget(self.groupBox_4, 0, 3, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.dockWidgetContents_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 160))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_40 = QtGui.QLabel(self.groupBox_5)
        self.label_40.setMaximumSize(QtCore.QSize(20, 20))
        self.label_40.setText(_fromUtf8(""))
        self.label_40.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_40.setScaledContents(True)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_4.addWidget(self.label_40, 1, 0, 1, 1)
        self.doubleSpinBox_sp_q5 = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.doubleSpinBox_sp_q5.setDecimals(3)
        self.doubleSpinBox_sp_q5.setMinimum(-999.999)
        self.doubleSpinBox_sp_q5.setMaximum(999.999)
        self.doubleSpinBox_sp_q5.setSingleStep(0.001)
        self.doubleSpinBox_sp_q5.setObjectName(_fromUtf8("doubleSpinBox_sp_q5"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_sp_q5, 2, 2, 1, 1)
        self.doubleSpinBox_sp_vcor05 = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.doubleSpinBox_sp_vcor05.setDecimals(4)
        self.doubleSpinBox_sp_vcor05.setMinimum(-0.9999)
        self.doubleSpinBox_sp_vcor05.setMaximum(0.9999)
        self.doubleSpinBox_sp_vcor05.setSingleStep(0.0001)
        self.doubleSpinBox_sp_vcor05.setObjectName(_fromUtf8("doubleSpinBox_sp_vcor05"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_sp_vcor05, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 3, 1, 1, 1)
        self.label_41 = QtGui.QLabel(self.groupBox_5)
        self.label_41.setMaximumSize(QtCore.QSize(20, 20))
        self.label_41.setText(_fromUtf8(""))
        self.label_41.setPixmap(QtGui.QPixmap(resource_path("Quadrupoles.png")))
        self.label_41.setScaledContents(True)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_4.addWidget(self.label_41, 2, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_5)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_4.addWidget(self.label_24, 1, 1, 1, 1)
        self.label_42 = QtGui.QLabel(self.groupBox_5)
        self.label_42.setMaximumSize(QtCore.QSize(20, 20))
        self.label_42.setText(_fromUtf8(""))
        self.label_42.setPixmap(QtGui.QPixmap(resource_path("Quadrupoles.png")))
        self.label_42.setScaledContents(True)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_4.addWidget(self.label_42, 3, 0, 1, 1)
        self.doubleSpinBox_sp_hcor05 = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.doubleSpinBox_sp_hcor05.setDecimals(4)
        self.doubleSpinBox_sp_hcor05.setMinimum(-0.9999)
        self.doubleSpinBox_sp_hcor05.setMaximum(0.9999)
        self.doubleSpinBox_sp_hcor05.setSingleStep(0.0001)
        self.doubleSpinBox_sp_hcor05.setProperty("value", 0.0)
        self.doubleSpinBox_sp_hcor05.setObjectName(_fromUtf8("doubleSpinBox_sp_hcor05"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_sp_hcor05, 0, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_5)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_4.addWidget(self.label_23, 0, 1, 1, 1)
        self.doubleSpinBox_sp_q6 = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.doubleSpinBox_sp_q6.setDecimals(3)
        self.doubleSpinBox_sp_q6.setMinimum(-999.999)
        self.doubleSpinBox_sp_q6.setSingleStep(0.001)
        self.doubleSpinBox_sp_q6.setProperty("value", 0.0)
        self.doubleSpinBox_sp_q6.setObjectName(_fromUtf8("doubleSpinBox_sp_q6"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_sp_q6, 3, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 2, 1, 1, 1)
        self.label_39 = QtGui.QLabel(self.groupBox_5)
        self.label_39.setMaximumSize(QtCore.QSize(20, 20))
        self.label_39.setText(_fromUtf8(""))
        self.label_39.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_39.setScaledContents(True)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_4.addWidget(self.label_39, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_5, 1, 3, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.dockWidgetContents_6)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(224, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 2, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 2, 2, 1, 1)
        self.doubleSpinBox_x_off = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_x_off.setMinimum(-99.99)
        self.doubleSpinBox_x_off.setSingleStep(0.01)
        self.doubleSpinBox_x_off.setObjectName(_fromUtf8("doubleSpinBox_x_off"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_x_off, 3, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 2, 1, 1)
        self.lineEdit_stop = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_stop.setObjectName(_fromUtf8("lineEdit_stop"))
        self.gridLayout_2.addWidget(self.lineEdit_stop, 1, 2, 1, 1)
        self.lineEdit_start = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_start.setObjectName(_fromUtf8("lineEdit_start"))
        self.gridLayout_2.addWidget(self.lineEdit_start, 1, 1, 1, 1)
        self.doubleSpinBox_y_off = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_y_off.setMinimum(-99.99)
        self.doubleSpinBox_y_off.setSingleStep(0.01)
        self.doubleSpinBox_y_off.setObjectName(_fromUtf8("doubleSpinBox_y_off"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_y_off, 3, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 33, 1, 1, 2)
        self.pushButton = QtGui.QPushButton(self.groupBox_2)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_2.addWidget(self.pushButton, 32, 1, 1, 2)
        self.label_95 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_95.setFont(font)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.gridLayout_2.addWidget(self.label_95, 33, 1, 1, 2)
        self.gridLayout_7.addWidget(self.groupBox_2, 2, 3, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents_6)
        self.groupBox.setMaximumSize(QtCore.QSize(224, 16777215))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 0, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox)
        self.label_29.setMaximumSize(QtCore.QSize(20, 20))
        self.label_29.setText(_fromUtf8(""))
        self.label_29.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_3.addWidget(self.label_29, 7, 0, 1, 1)
        self.doubleSpinBox_V_hcor02 = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_V_hcor02.setDecimals(4)
        self.doubleSpinBox_V_hcor02.setMinimum(-0.9999)
        self.doubleSpinBox_V_hcor02.setMaximum(0.9999)
        self.doubleSpinBox_V_hcor02.setSingleStep(0.0001)
        self.doubleSpinBox_V_hcor02.setObjectName(_fromUtf8("doubleSpinBox_V_hcor02"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_V_hcor02, 6, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 6, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox)
        self.label_28.setMaximumSize(QtCore.QSize(20, 20))
        self.label_28.setText(_fromUtf8(""))
        self.label_28.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_3.addWidget(self.label_28, 6, 0, 1, 1)
        self.doubleSpinBox_V_vcor01 = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_V_vcor01.setDecimals(4)
        self.doubleSpinBox_V_vcor01.setMinimum(-0.9999)
        self.doubleSpinBox_V_vcor01.setMaximum(0.9999)
        self.doubleSpinBox_V_vcor01.setSingleStep(0.0001)
        self.doubleSpinBox_V_vcor01.setObjectName(_fromUtf8("doubleSpinBox_V_vcor01"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_V_vcor01, 5, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 5, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox)
        self.label_27.setMaximumSize(QtCore.QSize(20, 20))
        self.label_27.setText(_fromUtf8(""))
        self.label_27.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_3.addWidget(self.label_27, 5, 0, 1, 1)
        self.doubleSpinBox_V_hcor01 = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_V_hcor01.setDecimals(4)
        self.doubleSpinBox_V_hcor01.setMinimum(-0.9999)
        self.doubleSpinBox_V_hcor01.setMaximum(0.9999)
        self.doubleSpinBox_V_hcor01.setSingleStep(0.0001)
        self.doubleSpinBox_V_hcor01.setObjectName(_fromUtf8("doubleSpinBox_V_hcor01"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_V_hcor01, 4, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 4, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox)
        self.label_26.setMaximumSize(QtCore.QSize(20, 20))
        self.label_26.setText(_fromUtf8(""))
        self.label_26.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_3.addWidget(self.label_26, 4, 0, 1, 1)
        self.doubleSpinBox_V_sol = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_V_sol.setDecimals(3)
        self.doubleSpinBox_V_sol.setMinimum(-999.999)
        self.doubleSpinBox_V_sol.setMaximum(999.999)
        self.doubleSpinBox_V_sol.setObjectName(_fromUtf8("doubleSpinBox_V_sol"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_V_sol, 3, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 3, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox)
        self.label_25.setMaximumSize(QtCore.QSize(20, 20))
        self.label_25.setText(_fromUtf8(""))
        self.label_25.setPixmap(QtGui.QPixmap(resource_path("Solenoids.png")))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_3.addWidget(self.label_25, 3, 0, 1, 1)
        self.doubleSpinBox_VGUN_phi = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_VGUN_phi.setDecimals(3)
        self.doubleSpinBox_VGUN_phi.setMinimum(-360.0)
        self.doubleSpinBox_VGUN_phi.setMaximum(360.0)
        self.doubleSpinBox_VGUN_phi.setSingleStep(0.1)
        self.doubleSpinBox_VGUN_phi.setObjectName(_fromUtf8("doubleSpinBox_VGUN_phi"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_VGUN_phi, 1, 2, 1, 1)
        self.doubleSpinBox_VGUN_grad = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_VGUN_grad.setDecimals(3)
        self.doubleSpinBox_VGUN_grad.setMinimum(-999.999)
        self.doubleSpinBox_VGUN_grad.setMaximum(999.999)
        self.doubleSpinBox_VGUN_grad.setSingleStep(0.001)
        self.doubleSpinBox_VGUN_grad.setObjectName(_fromUtf8("doubleSpinBox_VGUN_grad"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_VGUN_grad, 1, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 9, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.groupBox)
        self.label_35.setMaximumSize(QtCore.QSize(20, 20))
        self.label_35.setText(_fromUtf8(""))
        self.label_35.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_35.setScaledContents(True)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_3.addWidget(self.label_35, 13, 0, 1, 1)
        self.doubleSpinBox_V_q2 = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_V_q2.setDecimals(3)
        self.doubleSpinBox_V_q2.setMinimum(-999.999)
        self.doubleSpinBox_V_q2.setMaximum(999.999)
        self.doubleSpinBox_V_q2.setSingleStep(0.001)
        self.doubleSpinBox_V_q2.setObjectName(_fromUtf8("doubleSpinBox_V_q2"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_V_q2, 9, 2, 1, 1)
        self.doubleSpinBox_V_vcor03 = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_V_vcor03.setDecimals(4)
        self.doubleSpinBox_V_vcor03.setMinimum(-0.9999)
        self.doubleSpinBox_V_vcor03.setMaximum(0.9999)
        self.doubleSpinBox_V_vcor03.setSingleStep(0.0001)
        self.doubleSpinBox_V_vcor03.setObjectName(_fromUtf8("doubleSpinBox_V_vcor03"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_V_vcor03, 13, 2, 1, 1)
        self.doubleSpinBox_V_vcor02 = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_V_vcor02.setDecimals(4)
        self.doubleSpinBox_V_vcor02.setMinimum(-0.9999)
        self.doubleSpinBox_V_vcor02.setMaximum(0.9999)
        self.doubleSpinBox_V_vcor02.setSingleStep(0.0001)
        self.doubleSpinBox_V_vcor02.setObjectName(_fromUtf8("doubleSpinBox_V_vcor02"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_V_vcor02, 7, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 8, 1, 1, 1)
        self.doubleSpinBox_V_hcor04 = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_V_hcor04.setDecimals(4)
        self.doubleSpinBox_V_hcor04.setMinimum(-0.9999)
        self.doubleSpinBox_V_hcor04.setMaximum(0.9999)
        self.doubleSpinBox_V_hcor04.setSingleStep(0.0001)
        self.doubleSpinBox_V_hcor04.setObjectName(_fromUtf8("doubleSpinBox_V_hcor04"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_V_hcor04, 14, 2, 1, 1)
        self.doubleSpinBox_V_vcor04 = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_V_vcor04.setDecimals(4)
        self.doubleSpinBox_V_vcor04.setMinimum(-0.9999)
        self.doubleSpinBox_V_vcor04.setMaximum(0.9999)
        self.doubleSpinBox_V_vcor04.setSingleStep(0.0001)
        self.doubleSpinBox_V_vcor04.setObjectName(_fromUtf8("doubleSpinBox_V_vcor04"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_V_vcor04, 15, 2, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox)
        self.label_32.setMaximumSize(QtCore.QSize(20, 20))
        self.label_32.setText(_fromUtf8(""))
        self.label_32.setPixmap(QtGui.QPixmap(resource_path("Quadrupoles.png")))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_3.addWidget(self.label_32, 10, 0, 1, 1)
        self.label_33 = QtGui.QLabel(self.groupBox)
        self.label_33.setMaximumSize(QtCore.QSize(20, 20))
        self.label_33.setText(_fromUtf8(""))
        self.label_33.setPixmap(QtGui.QPixmap(resource_path("Quadrupoles.png")))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_3.addWidget(self.label_33, 11, 0, 1, 1)
        self.doubleSpinBox_V_q1 = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_V_q1.setDecimals(3)
        self.doubleSpinBox_V_q1.setMinimum(-999.999)
        self.doubleSpinBox_V_q1.setMaximum(999.999)
        self.doubleSpinBox_V_q1.setSingleStep(0.001)
        self.doubleSpinBox_V_q1.setObjectName(_fromUtf8("doubleSpinBox_V_q1"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_V_q1, 8, 2, 1, 1)
        self.doubleSpinBox_V_hcor03 = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_V_hcor03.setDecimals(4)
        self.doubleSpinBox_V_hcor03.setMinimum(-0.9999)
        self.doubleSpinBox_V_hcor03.setMaximum(0.9999)
        self.doubleSpinBox_V_hcor03.setSingleStep(0.0001)
        self.doubleSpinBox_V_hcor03.setObjectName(_fromUtf8("doubleSpinBox_V_hcor03"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_V_hcor03, 12, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 7, 1, 1, 1)
        self.doubleSpinBox_V_q4 = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_V_q4.setDecimals(3)
        self.doubleSpinBox_V_q4.setMinimum(-999.999)
        self.doubleSpinBox_V_q4.setMaximum(999.999)
        self.doubleSpinBox_V_q4.setSingleStep(0.001)
        self.doubleSpinBox_V_q4.setObjectName(_fromUtf8("doubleSpinBox_V_q4"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_V_q4, 11, 2, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox)
        self.label_31.setMaximumSize(QtCore.QSize(20, 20))
        self.label_31.setText(_fromUtf8(""))
        self.label_31.setPixmap(QtGui.QPixmap(resource_path("Quadrupoles.png")))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_3.addWidget(self.label_31, 9, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_3.addWidget(self.label_21, 14, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 13, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.groupBox)
        self.label_34.setMaximumSize(QtCore.QSize(20, 20))
        self.label_34.setText(_fromUtf8(""))
        self.label_34.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_3.addWidget(self.label_34, 12, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 12, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox)
        self.label_30.setMaximumSize(QtCore.QSize(20, 20))
        self.label_30.setText(_fromUtf8(""))
        self.label_30.setPixmap(QtGui.QPixmap(resource_path("Quadrupoles.png")))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_3.addWidget(self.label_30, 8, 0, 1, 1)
        self.doubleSpinBox_V_q3 = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_V_q3.setDecimals(3)
        self.doubleSpinBox_V_q3.setMinimum(-999.999)
        self.doubleSpinBox_V_q3.setMaximum(999.999)
        self.doubleSpinBox_V_q3.setSingleStep(0.001)
        self.doubleSpinBox_V_q3.setObjectName(_fromUtf8("doubleSpinBox_V_q3"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_V_q3, 10, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 11, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 10, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 15, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 16, 0, 1, 3)
        self.label_36 = QtGui.QLabel(self.groupBox)
        self.label_36.setMaximumSize(QtCore.QSize(20, 20))
        self.label_36.setText(_fromUtf8(""))
        self.label_36.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_3.addWidget(self.label_36, 14, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.groupBox)
        self.label_37.setMaximumSize(QtCore.QSize(20, 20))
        self.label_37.setText(_fromUtf8(""))
        self.label_37.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_37.setScaledContents(True)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_3.addWidget(self.label_37, 15, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox, 0, 0, 3, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.dockWidgetContents_6)
        self.groupBox_3.setMaximumSize(QtCore.QSize(249, 16777215))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_78 = QtGui.QLabel(self.groupBox_3)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.gridLayout.addWidget(self.label_78, 9, 2, 1, 1)
        self.doubleSpinBox_C_s02_vcor03 = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_C_s02_vcor03.setDecimals(4)
        self.doubleSpinBox_C_s02_vcor03.setMinimum(-0.9999)
        self.doubleSpinBox_C_s02_vcor03.setMaximum(0.9999)
        self.doubleSpinBox_C_s02_vcor03.setSingleStep(0.0001)
        self.doubleSpinBox_C_s02_vcor03.setObjectName(_fromUtf8("doubleSpinBox_C_s02_vcor03"))
        self.gridLayout.addWidget(self.doubleSpinBox_C_s02_vcor03, 18, 3, 1, 1)
        self.label_76 = QtGui.QLabel(self.groupBox_3)
        self.label_76.setMaximumSize(QtCore.QSize(20, 20))
        self.label_76.setText(_fromUtf8(""))
        self.label_76.setPixmap(QtGui.QPixmap(resource_path("Solenoids.png")))
        self.label_76.setScaledContents(True)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.gridLayout.addWidget(self.label_76, 9, 0, 1, 1)
        self.doubleSpinBox_C_s02_q3 = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_C_s02_q3.setDecimals(3)
        self.doubleSpinBox_C_s02_q3.setMinimum(-999.999)
        self.doubleSpinBox_C_s02_q3.setMaximum(999.999)
        self.doubleSpinBox_C_s02_q3.setSingleStep(0.001)
        self.doubleSpinBox_C_s02_q3.setObjectName(_fromUtf8("doubleSpinBox_C_s02_q3"))
        self.gridLayout.addWidget(self.doubleSpinBox_C_s02_q3, 19, 3, 1, 1)
        self.doubleSpinBox_C_s02_vcor02 = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_C_s02_vcor02.setDecimals(4)
        self.doubleSpinBox_C_s02_vcor02.setMinimum(-0.9999)
        self.doubleSpinBox_C_s02_vcor02.setMaximum(0.9999)
        self.doubleSpinBox_C_s02_vcor02.setSingleStep(0.0001)
        self.doubleSpinBox_C_s02_vcor02.setObjectName(_fromUtf8("doubleSpinBox_C_s02_vcor02"))
        self.gridLayout.addWidget(self.doubleSpinBox_C_s02_vcor02, 16, 3, 1, 1)
        self.doubleSpinBox_C_s02_q4 = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_C_s02_q4.setDecimals(3)
        self.doubleSpinBox_C_s02_q4.setMinimum(-999.999)
        self.doubleSpinBox_C_s02_q4.setMaximum(999.999)
        self.doubleSpinBox_C_s02_q4.setSingleStep(0.001)
        self.doubleSpinBox_C_s02_q4.setObjectName(_fromUtf8("doubleSpinBox_C_s02_q4"))
        self.gridLayout.addWidget(self.doubleSpinBox_C_s02_q4, 20, 3, 1, 1)
        self.doubleSpinBox_C_s02_hcor03 = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_C_s02_hcor03.setDecimals(4)
        self.doubleSpinBox_C_s02_hcor03.setMinimum(-0.9999)
        self.doubleSpinBox_C_s02_hcor03.setMaximum(0.9999)
        self.doubleSpinBox_C_s02_hcor03.setSingleStep(0.0001)
        self.doubleSpinBox_C_s02_hcor03.setObjectName(_fromUtf8("doubleSpinBox_C_s02_hcor03"))
        self.gridLayout.addWidget(self.doubleSpinBox_C_s02_hcor03, 17, 3, 1, 1)
        self.label_79 = QtGui.QLabel(self.groupBox_3)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.gridLayout.addWidget(self.label_79, 10, 2, 1, 1)
        self.label_45 = QtGui.QLabel(self.groupBox_3)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout.addWidget(self.label_45, 3, 2, 1, 1)
        self.label_71 = QtGui.QLabel(self.groupBox_3)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.gridLayout.addWidget(self.label_71, 16, 2, 1, 1)
        self.label_66 = QtGui.QLabel(self.groupBox_3)
        self.label_66.setMaximumSize(QtCore.QSize(20, 20))
        self.label_66.setText(_fromUtf8(""))
        self.label_66.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_66.setScaledContents(True)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout.addWidget(self.label_66, 17, 0, 1, 1)
        self.doubleSpinBox_C_s02_q2 = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_C_s02_q2.setDecimals(3)
        self.doubleSpinBox_C_s02_q2.setMinimum(-999.999)
        self.doubleSpinBox_C_s02_q2.setMaximum(999.999)
        self.doubleSpinBox_C_s02_q2.setSingleStep(0.001)
        self.doubleSpinBox_C_s02_q2.setObjectName(_fromUtf8("doubleSpinBox_C_s02_q2"))
        self.gridLayout.addWidget(self.doubleSpinBox_C_s02_q2, 14, 3, 1, 1)
        self.label_60 = QtGui.QLabel(self.groupBox_3)
        self.label_60.setMaximumSize(QtCore.QSize(20, 20))
        self.label_60.setText(_fromUtf8(""))
        self.label_60.setPixmap(QtGui.QPixmap(resource_path("Quadrupoles.png")))
        self.label_60.setScaledContents(True)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout.addWidget(self.label_60, 13, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 22, 2, 1, 2)
        self.label_61 = QtGui.QLabel(self.groupBox_3)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout.addWidget(self.label_61, 13, 2, 1, 1)
        self.label_75 = QtGui.QLabel(self.groupBox_3)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.gridLayout.addWidget(self.label_75, 20, 2, 1, 1)
        self.label_64 = QtGui.QLabel(self.groupBox_3)
        self.label_64.setMaximumSize(QtCore.QSize(20, 20))
        self.label_64.setText(_fromUtf8(""))
        self.label_64.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_64.setScaledContents(True)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout.addWidget(self.label_64, 15, 0, 1, 1)
        self.label_55 = QtGui.QLabel(self.groupBox_3)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout.addWidget(self.label_55, 11, 2, 1, 1)
        self.doubleSpinBox_C_s01_hcor01 = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_C_s01_hcor01.setDecimals(4)
        self.doubleSpinBox_C_s01_hcor01.setMinimum(-0.9999)
        self.doubleSpinBox_C_s01_hcor01.setMaximum(0.9999)
        self.doubleSpinBox_C_s01_hcor01.setSingleStep(0.0001)
        self.doubleSpinBox_C_s01_hcor01.setObjectName(_fromUtf8("doubleSpinBox_C_s01_hcor01"))
        self.gridLayout.addWidget(self.doubleSpinBox_C_s01_hcor01, 3, 3, 1, 1)
        self.label_46 = QtGui.QLabel(self.groupBox_3)
        self.label_46.setMaximumSize(QtCore.QSize(20, 20))
        self.label_46.setText(_fromUtf8(""))
        self.label_46.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_46.setScaledContents(True)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout.addWidget(self.label_46, 3, 0, 1, 1)
        self.label_72 = QtGui.QLabel(self.groupBox_3)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout.addWidget(self.label_72, 17, 2, 1, 1)
        self.doubleSpinBox_LINAC01_phi = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_LINAC01_phi.setObjectName(_fromUtf8("doubleSpinBox_LINAC01_phi"))
        self.gridLayout.addWidget(self.doubleSpinBox_LINAC01_phi, 8, 3, 1, 1)
        self.doubleSpinBox_LINAC01_grad = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_LINAC01_grad.setObjectName(_fromUtf8("doubleSpinBox_LINAC01_grad"))
        self.gridLayout.addWidget(self.doubleSpinBox_LINAC01_grad, 8, 2, 1, 1)
        self.label_62 = QtGui.QLabel(self.groupBox_3)
        self.label_62.setMaximumSize(QtCore.QSize(20, 20))
        self.label_62.setText(_fromUtf8(""))
        self.label_62.setPixmap(QtGui.QPixmap(resource_path("Quadrupoles.png")))
        self.label_62.setScaledContents(True)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout.addWidget(self.label_62, 14, 0, 1, 1)
        self.doubleSpinBox_C_s02_hcor02 = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_C_s02_hcor02.setDecimals(4)
        self.doubleSpinBox_C_s02_hcor02.setMinimum(-0.9999)
        self.doubleSpinBox_C_s02_hcor02.setMaximum(0.9999)
        self.doubleSpinBox_C_s02_hcor02.setSingleStep(0.0001)
        self.doubleSpinBox_C_s02_hcor02.setObjectName(_fromUtf8("doubleSpinBox_C_s02_hcor02"))
        self.gridLayout.addWidget(self.doubleSpinBox_C_s02_hcor02, 15, 3, 1, 1)
        self.label_54 = QtGui.QLabel(self.groupBox_3)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout.addWidget(self.label_54, 7, 3, 1, 1)
        self.label_53 = QtGui.QLabel(self.groupBox_3)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout.addWidget(self.label_53, 7, 2, 1, 1)
        self.doubleSpinBox_C_s01_vcor02 = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_C_s01_vcor02.setDecimals(4)
        self.doubleSpinBox_C_s01_vcor02.setMinimum(-0.9999)
        self.doubleSpinBox_C_s01_vcor02.setMaximum(0.9999)
        self.doubleSpinBox_C_s01_vcor02.setSingleStep(0.0001)
        self.doubleSpinBox_C_s01_vcor02.setObjectName(_fromUtf8("doubleSpinBox_C_s01_vcor02"))
        self.gridLayout.addWidget(self.doubleSpinBox_C_s01_vcor02, 6, 3, 1, 1)
        self.doubleSpinBox_C_s01_hcor02 = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_C_s01_hcor02.setDecimals(4)
        self.doubleSpinBox_C_s01_hcor02.setMinimum(-0.9999)
        self.doubleSpinBox_C_s01_hcor02.setMaximum(0.9999)
        self.doubleSpinBox_C_s01_hcor02.setSingleStep(0.0001)
        self.doubleSpinBox_C_s01_hcor02.setObjectName(_fromUtf8("doubleSpinBox_C_s01_hcor02"))
        self.gridLayout.addWidget(self.doubleSpinBox_C_s01_hcor02, 5, 3, 1, 1)
        self.doubleSpinBox_C_s01_vcor01 = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_C_s01_vcor01.setDecimals(4)
        self.doubleSpinBox_C_s01_vcor01.setMinimum(-0.9999)
        self.doubleSpinBox_C_s01_vcor01.setMaximum(0.9999)
        self.doubleSpinBox_C_s01_vcor01.setSingleStep(0.0001)
        self.doubleSpinBox_C_s01_vcor01.setObjectName(_fromUtf8("doubleSpinBox_C_s01_vcor01"))
        self.gridLayout.addWidget(self.doubleSpinBox_C_s01_vcor01, 4, 3, 1, 1)
        self.label_52 = QtGui.QLabel(self.groupBox_3)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout.addWidget(self.label_52, 6, 2, 1, 1)
        self.doubleSpinBox_C_s02_q1 = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_C_s02_q1.setDecimals(3)
        self.doubleSpinBox_C_s02_q1.setMinimum(-999.999)
        self.doubleSpinBox_C_s02_q1.setMaximum(999.999)
        self.doubleSpinBox_C_s02_q1.setSingleStep(0.001)
        self.doubleSpinBox_C_s02_q1.setObjectName(_fromUtf8("doubleSpinBox_C_s02_q1"))
        self.gridLayout.addWidget(self.doubleSpinBox_C_s02_q1, 13, 3, 1, 1)
        self.label_51 = QtGui.QLabel(self.groupBox_3)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout.addWidget(self.label_51, 5, 2, 1, 1)
        self.label_50 = QtGui.QLabel(self.groupBox_3)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout.addWidget(self.label_50, 4, 2, 1, 1)
        self.label_48 = QtGui.QLabel(self.groupBox_3)
        self.label_48.setMaximumSize(QtCore.QSize(20, 20))
        self.label_48.setText(_fromUtf8(""))
        self.label_48.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_48.setScaledContents(True)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout.addWidget(self.label_48, 5, 0, 1, 1)
        self.label_47 = QtGui.QLabel(self.groupBox_3)
        self.label_47.setMaximumSize(QtCore.QSize(20, 20))
        self.label_47.setText(_fromUtf8(""))
        self.label_47.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_47.setScaledContents(True)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout.addWidget(self.label_47, 4, 0, 1, 1)
        self.label_49 = QtGui.QLabel(self.groupBox_3)
        self.label_49.setMaximumSize(QtCore.QSize(20, 20))
        self.label_49.setText(_fromUtf8(""))
        self.label_49.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_49.setScaledContents(True)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout.addWidget(self.label_49, 6, 0, 1, 1)
        self.label_63 = QtGui.QLabel(self.groupBox_3)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout.addWidget(self.label_63, 14, 2, 1, 1)
        self.label_67 = QtGui.QLabel(self.groupBox_3)
        self.label_67.setMaximumSize(QtCore.QSize(20, 20))
        self.label_67.setText(_fromUtf8(""))
        self.label_67.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_67.setScaledContents(True)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout.addWidget(self.label_67, 18, 0, 1, 1)
        self.label_73 = QtGui.QLabel(self.groupBox_3)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.gridLayout.addWidget(self.label_73, 18, 2, 1, 1)
        self.label_59 = QtGui.QLabel(self.groupBox_3)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout.addWidget(self.label_59, 7, 0, 1, 1)
        self.label_58 = QtGui.QLabel(self.groupBox_3)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout.addWidget(self.label_58, 12, 2, 1, 1)
        self.label_57 = QtGui.QLabel(self.groupBox_3)
        self.label_57.setMaximumSize(QtCore.QSize(20, 20))
        self.label_57.setText(_fromUtf8(""))
        self.label_57.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_57.setScaledContents(True)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout.addWidget(self.label_57, 12, 0, 1, 1)
        self.doubleSpinBox_C_s02_hcor01 = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_C_s02_hcor01.setDecimals(4)
        self.doubleSpinBox_C_s02_hcor01.setMinimum(-0.9999)
        self.doubleSpinBox_C_s02_hcor01.setMaximum(0.9999)
        self.doubleSpinBox_C_s02_hcor01.setSingleStep(0.0001)
        self.doubleSpinBox_C_s02_hcor01.setObjectName(_fromUtf8("doubleSpinBox_C_s02_hcor01"))
        self.gridLayout.addWidget(self.doubleSpinBox_C_s02_hcor01, 11, 3, 1, 1)
        self.label_56 = QtGui.QLabel(self.groupBox_3)
        self.label_56.setMaximumSize(QtCore.QSize(20, 20))
        self.label_56.setText(_fromUtf8(""))
        self.label_56.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_56.setScaledContents(True)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout.addWidget(self.label_56, 11, 0, 1, 1)
        self.label_70 = QtGui.QLabel(self.groupBox_3)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout.addWidget(self.label_70, 15, 2, 1, 1)
        self.label_74 = QtGui.QLabel(self.groupBox_3)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.gridLayout.addWidget(self.label_74, 19, 2, 1, 1)
        self.label_68 = QtGui.QLabel(self.groupBox_3)
        self.label_68.setMaximumSize(QtCore.QSize(20, 20))
        self.label_68.setText(_fromUtf8(""))
        self.label_68.setPixmap(QtGui.QPixmap(resource_path("Quadrupoles.png")))
        self.label_68.setScaledContents(True)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout.addWidget(self.label_68, 19, 0, 1, 1)
        self.label_69 = QtGui.QLabel(self.groupBox_3)
        self.label_69.setMaximumSize(QtCore.QSize(20, 20))
        self.label_69.setText(_fromUtf8(""))
        self.label_69.setPixmap(QtGui.QPixmap(resource_path("Quadrupoles.png")))
        self.label_69.setScaledContents(True)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout.addWidget(self.label_69, 20, 0, 1, 1)
        self.label_65 = QtGui.QLabel(self.groupBox_3)
        self.label_65.setMaximumSize(QtCore.QSize(20, 20))
        self.label_65.setText(_fromUtf8(""))
        self.label_65.setPixmap(QtGui.QPixmap(resource_path("Correctors.png")))
        self.label_65.setScaledContents(True)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout.addWidget(self.label_65, 16, 0, 1, 1)
        self.doubleSpinBox_CGUN_grad = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_CGUN_grad.setDecimals(3)
        self.doubleSpinBox_CGUN_grad.setMinimum(-999.999)
        self.doubleSpinBox_CGUN_grad.setMaximum(999.999)
        self.doubleSpinBox_CGUN_grad.setSingleStep(0.001)
        self.doubleSpinBox_CGUN_grad.setObjectName(_fromUtf8("doubleSpinBox_CGUN_grad"))
        self.gridLayout.addWidget(self.doubleSpinBox_CGUN_grad, 1, 2, 1, 1)
        self.label_44 = QtGui.QLabel(self.groupBox_3)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout.addWidget(self.label_44, 0, 2, 1, 1)
        self.doubleSpinBox_CGUN_phi = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_CGUN_phi.setDecimals(3)
        self.doubleSpinBox_CGUN_phi.setMinimum(-360.0)
        self.doubleSpinBox_CGUN_phi.setMaximum(360.0)
        self.doubleSpinBox_CGUN_phi.setSingleStep(0.1)
        self.doubleSpinBox_CGUN_phi.setObjectName(_fromUtf8("doubleSpinBox_CGUN_phi"))
        self.gridLayout.addWidget(self.doubleSpinBox_CGUN_phi, 1, 3, 1, 1)
        self.label_43 = QtGui.QLabel(self.groupBox_3)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout.addWidget(self.label_43, 0, 3, 1, 1)
        self.doubleSpinBox_LINAC01_sol01 = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_LINAC01_sol01.setDecimals(3)
        self.doubleSpinBox_LINAC01_sol01.setMinimum(-999.999)
        self.doubleSpinBox_LINAC01_sol01.setMaximum(999.999)
        self.doubleSpinBox_LINAC01_sol01.setSingleStep(0.001)
        self.doubleSpinBox_LINAC01_sol01.setObjectName(_fromUtf8("doubleSpinBox_LINAC01_sol01"))
        self.gridLayout.addWidget(self.doubleSpinBox_LINAC01_sol01, 9, 3, 1, 1)
        self.doubleSpinBox_LINAC01_sol02 = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_LINAC01_sol02.setDecimals(3)
        self.doubleSpinBox_LINAC01_sol02.setMinimum(-999.999)
        self.doubleSpinBox_LINAC01_sol02.setMaximum(999.999)
        self.doubleSpinBox_LINAC01_sol02.setSingleStep(0.001)
        self.doubleSpinBox_LINAC01_sol02.setObjectName(_fromUtf8("doubleSpinBox_LINAC01_sol02"))
        self.gridLayout.addWidget(self.doubleSpinBox_LINAC01_sol02, 10, 3, 1, 1)
        self.label_77 = QtGui.QLabel(self.groupBox_3)
        self.label_77.setMaximumSize(QtCore.QSize(20, 20))
        self.label_77.setText(_fromUtf8(""))
        self.label_77.setPixmap(QtGui.QPixmap(resource_path("Solenoids.png")))
        self.label_77.setScaledContents(True)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.gridLayout.addWidget(self.label_77, 10, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setMaximumSize(QtCore.QSize(20, 20))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setPixmap(QtGui.QPixmap(resource_path("Solenoids.png")))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_38 = QtGui.QLabel(self.groupBox_3)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout.addWidget(self.label_38, 2, 2, 1, 1)
        self.doubleSpinBox_C_sol = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_C_sol.setDecimals(3)
        self.doubleSpinBox_C_sol.setMinimum(-999.999)
        self.doubleSpinBox_C_sol.setMaximum(999.99)
        self.doubleSpinBox_C_sol.setSingleStep(0.001)
        self.doubleSpinBox_C_sol.setObjectName(_fromUtf8("doubleSpinBox_C_sol"))
        self.gridLayout.addWidget(self.doubleSpinBox_C_sol, 2, 3, 1, 1)
        self.doubleSpinBox_C_s02_vcor01 = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_C_s02_vcor01.setDecimals(4)
        self.doubleSpinBox_C_s02_vcor01.setMinimum(-0.9999)
        self.doubleSpinBox_C_s02_vcor01.setMaximum(0.9999)
        self.doubleSpinBox_C_s02_vcor01.setSingleStep(0.0001)
        self.doubleSpinBox_C_s02_vcor01.setObjectName(_fromUtf8("doubleSpinBox_C_s02_vcor01"))
        self.gridLayout.addWidget(self.doubleSpinBox_C_s02_vcor01, 12, 3, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 0, 2, 3, 1)
        self.label_94 = QtGui.QLabel(self.dockWidgetContents_6)
        self.label_94.setMinimumSize(QtCore.QSize(0, 0))
        self.label_94.setMaximumSize(QtCore.QSize(699, 215))
        self.label_94.setText(_fromUtf8(""))
        self.label_94.setPixmap(QtGui.QPixmap(resource_path("schem.png")))
        self.label_94.setScaledContents(True)
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.gridLayout_7.addWidget(self.label_94, 3, 0, 1, 4)
        self.dockWidget_5.setWidget(self.dockWidgetContents_6)
        mainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_5)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.lineEdit_start, self.lineEdit_stop)
        mainWindow.setTabOrder(self.lineEdit_stop, self.doubleSpinBox_x_off)
        mainWindow.setTabOrder(self.doubleSpinBox_x_off, self.doubleSpinBox_y_off)
        mainWindow.setTabOrder(self.doubleSpinBox_y_off, self.pushButton)
        mainWindow.setTabOrder(self.pushButton, self.doubleSpinBox_VGUN_grad)
        mainWindow.setTabOrder(self.doubleSpinBox_VGUN_grad, self.doubleSpinBox_VGUN_phi)
        mainWindow.setTabOrder(self.doubleSpinBox_VGUN_phi, self.doubleSpinBox_V_sol)
        mainWindow.setTabOrder(self.doubleSpinBox_V_sol, self.doubleSpinBox_V_hcor01)
        mainWindow.setTabOrder(self.doubleSpinBox_V_hcor01, self.doubleSpinBox_V_vcor01)
        mainWindow.setTabOrder(self.doubleSpinBox_V_vcor01, self.doubleSpinBox_V_hcor02)
        mainWindow.setTabOrder(self.doubleSpinBox_V_hcor02, self.doubleSpinBox_V_vcor02)
        mainWindow.setTabOrder(self.doubleSpinBox_V_vcor02, self.doubleSpinBox_V_q1)
        mainWindow.setTabOrder(self.doubleSpinBox_V_q1, self.doubleSpinBox_V_q2)
        mainWindow.setTabOrder(self.doubleSpinBox_V_q2, self.doubleSpinBox_V_q3)
        mainWindow.setTabOrder(self.doubleSpinBox_V_q3, self.doubleSpinBox_V_q4)
        mainWindow.setTabOrder(self.doubleSpinBox_V_q4, self.doubleSpinBox_V_hcor03)
        mainWindow.setTabOrder(self.doubleSpinBox_V_hcor03, self.doubleSpinBox_V_vcor03)
        mainWindow.setTabOrder(self.doubleSpinBox_V_vcor03, self.doubleSpinBox_V_hcor04)
        mainWindow.setTabOrder(self.doubleSpinBox_V_hcor04, self.doubleSpinBox_V_vcor04)
        mainWindow.setTabOrder(self.doubleSpinBox_V_vcor04, self.doubleSpinBox_CGUN_grad)
        mainWindow.setTabOrder(self.doubleSpinBox_CGUN_grad, self.doubleSpinBox_CGUN_phi)
        mainWindow.setTabOrder(self.doubleSpinBox_CGUN_phi, self.doubleSpinBox_C_s01_hcor01)
        mainWindow.setTabOrder(self.doubleSpinBox_C_s01_hcor01, self.doubleSpinBox_C_s01_vcor01)
        mainWindow.setTabOrder(self.doubleSpinBox_C_s01_vcor01, self.doubleSpinBox_C_s01_hcor02)
        mainWindow.setTabOrder(self.doubleSpinBox_C_s01_hcor02, self.doubleSpinBox_C_s01_vcor02)
        mainWindow.setTabOrder(self.doubleSpinBox_C_s01_vcor02, self.doubleSpinBox_LINAC01_grad)
        mainWindow.setTabOrder(self.doubleSpinBox_LINAC01_grad, self.doubleSpinBox_LINAC01_phi)
        mainWindow.setTabOrder(self.doubleSpinBox_LINAC01_phi, self.doubleSpinBox_LINAC01_sol01)
        mainWindow.setTabOrder(self.doubleSpinBox_LINAC01_sol01, self.doubleSpinBox_LINAC01_sol02)
        mainWindow.setTabOrder(self.doubleSpinBox_LINAC01_sol02, self.doubleSpinBox_C_s02_hcor01)
        mainWindow.setTabOrder(self.doubleSpinBox_C_s02_hcor01, self.doubleSpinBox_C_s02_vcor01)
        mainWindow.setTabOrder(self.doubleSpinBox_C_s02_vcor01, self.doubleSpinBox_C_s02_q1)
        mainWindow.setTabOrder(self.doubleSpinBox_C_s02_q1, self.doubleSpinBox_C_s02_q2)
        mainWindow.setTabOrder(self.doubleSpinBox_C_s02_q2, self.doubleSpinBox_C_s02_hcor02)
        mainWindow.setTabOrder(self.doubleSpinBox_C_s02_hcor02, self.doubleSpinBox_C_s02_vcor02)
        mainWindow.setTabOrder(self.doubleSpinBox_C_s02_vcor02, self.doubleSpinBox_C_s02_hcor03)
        mainWindow.setTabOrder(self.doubleSpinBox_C_s02_hcor03, self.doubleSpinBox_C_s02_vcor03)
        mainWindow.setTabOrder(self.doubleSpinBox_C_s02_vcor03, self.doubleSpinBox_C_s02_q3)
        mainWindow.setTabOrder(self.doubleSpinBox_C_s02_q3, self.doubleSpinBox_C_s02_q4)
        mainWindow.setTabOrder(self.doubleSpinBox_C_s02_q4, self.doubleSpinBox_c2v_d1)
        mainWindow.setTabOrder(self.doubleSpinBox_c2v_d1, self.doubleSpinBox_c2v_hcor01)
        mainWindow.setTabOrder(self.doubleSpinBox_c2v_hcor01, self.doubleSpinBox_c2v_vcor01)
        mainWindow.setTabOrder(self.doubleSpinBox_c2v_vcor01, self.doubleSpinBox_c2v_q1)
        mainWindow.setTabOrder(self.doubleSpinBox_c2v_q1, self.doubleSpinBox_c2v_q2)
        mainWindow.setTabOrder(self.doubleSpinBox_c2v_q2, self.doubleSpinBox_c2v_q3)
        mainWindow.setTabOrder(self.doubleSpinBox_c2v_q3, self.doubleSpinBox_c2v_d2)
        mainWindow.setTabOrder(self.doubleSpinBox_c2v_d2, self.doubleSpinBox_sp_hcor05)
        mainWindow.setTabOrder(self.doubleSpinBox_sp_hcor05, self.doubleSpinBox_sp_vcor05)
        mainWindow.setTabOrder(self.doubleSpinBox_sp_vcor05, self.doubleSpinBox_sp_q5)
        mainWindow.setTabOrder(self.doubleSpinBox_sp_q5, self.doubleSpinBox_sp_q6)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "Online Model", None))
        self.groupBox_X.setTitle(_translate("mainWindow", " Sky Lines", None))
        self.groupBox_4.setTitle(_translate("mainWindow", "C2V Lline", None))
        self.label_93.setText(_translate("mainWindow", "DIP 02", None))
        self.label_91.setText(_translate("mainWindow", "QUAD 03", None))
        self.label_89.setText(_translate("mainWindow", "QUAD 02", None))
        self.label_87.setText(_translate("mainWindow", "QUAD 01", None))
        self.label_86.setText(_translate("mainWindow", "VCOR 01", None))
        self.label_85.setText(_translate("mainWindow", "HCOR 01", None))
        self.label_81.setText(_translate("mainWindow", "DIP 01", None))
        self.groupBox_5.setTitle(_translate("mainWindow", "Spectrometer Line", None))
        self.label_7.setText(_translate("mainWindow", "QUAD 06", None))
        self.label_24.setText(_translate("mainWindow", "VCOR 05", None))
        self.label_23.setText(_translate("mainWindow", "HCOR 05", None))
        self.label_6.setText(_translate("mainWindow", "QUAD 05", None))
        self.groupBox_2.setTitle(_translate("mainWindow", "Simulation Settings", None))
        self.label.setText(_translate("mainWindow", "X Offset (mm)", None))
        self.label_10.setText(_translate("mainWindow", "Y Offset (mm)", None))
        self.label_9.setText(_translate("mainWindow", "Start Element:", None))
        self.label_11.setText(_translate("mainWindow", "End Element:", None))
        self.pushButton.setText(_translate("mainWindow", "Run", None))
        self.groupBox.setTitle(_translate("mainWindow", "VELA Line", None))
        self.label_12.setText(_translate("mainWindow", "Gun Gradient (MV/m):", None))
        self.label_17.setText(_translate("mainWindow", "HCOR 02", None))
        self.label_16.setText(_translate("mainWindow", "VCOR 01", None))
        self.label_15.setText(_translate("mainWindow", "HCOR 01", None))
        self.label_14.setText(_translate("mainWindow", "SOL", None))
        self.label_13.setText(_translate("mainWindow", "Phi (degrees):", None))
        self.label_3.setText(_translate("mainWindow", "QUAD 02", None))
        self.label_2.setText(_translate("mainWindow", "QUAD 01", None))
        self.label_18.setText(_translate("mainWindow", "VCOR 02", None))
        self.label_21.setText(_translate("mainWindow", "HCOR 04", None))
        self.label_20.setText(_translate("mainWindow", "VCOR 03", None))
        self.label_19.setText(_translate("mainWindow", "HCOR 03", None))
        self.label_5.setText(_translate("mainWindow", "QUAD 04", None))
        self.label_4.setText(_translate("mainWindow", "QUAD 03", None))
        self.label_22.setText(_translate("mainWindow", "VCOR 04", None))
        self.groupBox_3.setTitle(_translate("mainWindow", "CLARA Line", None))
        self.label_78.setText(_translate("mainWindow", "LIN01 SOL 01", None))
        self.label_79.setText(_translate("mainWindow", "LIN01 SOL 02", None))
        self.label_45.setText(_translate("mainWindow", "S01 HCOR 01", None))
        self.label_71.setText(_translate("mainWindow", "S02 VCOR 02", None))
        self.label_61.setText(_translate("mainWindow", "S02 QUAD 01", None))
        self.label_75.setText(_translate("mainWindow", "S02 QUAD 04", None))
        self.label_55.setText(_translate("mainWindow", "S02 HCOR 01", None))
        self.label_72.setText(_translate("mainWindow", "S02 HCOR 03", None))
        self.label_54.setText(_translate("mainWindow", "Phi (degrees):", None))
        self.label_53.setText(_translate("mainWindow", "Gradient (MV/m)", None))
        self.label_52.setText(_translate("mainWindow", "S01 VCOR 02", None))
        self.label_51.setText(_translate("mainWindow", "S01 HCOR 02", None))
        self.label_50.setText(_translate("mainWindow", "S01 VCOR 01", None))
        self.label_63.setText(_translate("mainWindow", "S02 QUAD 02", None))
        self.label_73.setText(_translate("mainWindow", "S02 VCOR 03", None))
        self.label_59.setText(_translate("mainWindow", "LINAC 01", None))
        self.label_58.setText(_translate("mainWindow", "S02 VCOR 01", None))
        self.label_70.setText(_translate("mainWindow", "S02 HCOR 02", None))
        self.label_74.setText(_translate("mainWindow", "S02 QUAD 03", None))
        self.label_44.setText(_translate("mainWindow", "Gun Gradient (MV/m):", None))
        self.label_43.setText(_translate("mainWindow", "Phi (degrees):", None))
        self.label_38.setText(_translate("mainWindow", "INJ SOL", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    mainWindow = QtGui.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

