# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_mainView.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainView(object):
    def setupUi(self, mainView):
        mainView.setObjectName(_fromUtf8("mainView"))
        mainView.resize(1038, 871)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainView.sizePolicy().hasHeightForWidth())
        mainView.setSizePolicy(sizePolicy)
        mainView.setMinimumSize(QtCore.QSize(1038, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainView.setWindowIcon(icon)
        mainView.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(mainView)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 182, 522))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.collectAndSave_pushButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collectAndSave_pushButton.sizePolicy().hasHeightForWidth())
        self.collectAndSave_pushButton.setSizePolicy(sizePolicy)
        self.collectAndSave_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.collectAndSave_pushButton.setObjectName(_fromUtf8("collectAndSave_pushButton"))
        self.verticalLayout_2.addWidget(self.collectAndSave_pushButton)
        self.last_filename = QtGui.QLineEdit(self.tab)
        self.last_filename.setReadOnly(True)
        self.last_filename.setObjectName(_fromUtf8("last_filename"))
        self.verticalLayout_2.addWidget(self.last_filename)
        self.liveStream_pushButton = QtGui.QPushButton(self.tab)
        self.liveStream_pushButton.setObjectName(_fromUtf8("liveStream_pushButton"))
        self.verticalLayout_2.addWidget(self.liveStream_pushButton)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_3 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 1)
        self.spinBox_maxLevel = QtGui.QSpinBox(self.tab)
        self.spinBox_maxLevel.setMaximum(65536)
        self.spinBox_maxLevel.setSingleStep(100)
        self.spinBox_maxLevel.setProperty("value", 65536)
        self.spinBox_maxLevel.setObjectName(_fromUtf8("spinBox_maxLevel"))
        self.gridLayout_5.addWidget(self.spinBox_maxLevel, 1, 1, 1, 1)
        self.spinBox_minLevel = QtGui.QSpinBox(self.tab)
        self.spinBox_minLevel.setMaximum(65536)
        self.spinBox_minLevel.setSingleStep(100)
        self.spinBox_minLevel.setObjectName(_fromUtf8("spinBox_minLevel"))
        self.gridLayout_5.addWidget(self.spinBox_minLevel, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.avPixIntensity_label_8 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.avPixIntensity_label_8.setFont(font)
        self.avPixIntensity_label_8.setObjectName(_fromUtf8("avPixIntensity_label_8"))
        self.gridLayout_7.addWidget(self.avPixIntensity_label_8, 0, 0, 1, 1)
        self.avPixIntensity_label_15 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.avPixIntensity_label_15.setFont(font)
        self.avPixIntensity_label_15.setObjectName(_fromUtf8("avPixIntensity_label_15"))
        self.gridLayout_7.addWidget(self.avPixIntensity_label_15, 0, 1, 1, 1)
        self.maskX_spinBox_5 = QtGui.QSpinBox(self.tab)
        self.maskX_spinBox_5.setMaximum(9999)
        self.maskX_spinBox_5.setObjectName(_fromUtf8("maskX_spinBox_5"))
        self.gridLayout_7.addWidget(self.maskX_spinBox_5, 0, 2, 1, 1)
        self.avPixIntensity_label_7 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.avPixIntensity_label_7.setFont(font)
        self.avPixIntensity_label_7.setObjectName(_fromUtf8("avPixIntensity_label_7"))
        self.gridLayout_7.addWidget(self.avPixIntensity_label_7, 1, 0, 1, 1)
        self.y_read_2 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.y_read_2.setFont(font)
        self.y_read_2.setObjectName(_fromUtf8("y_read_2"))
        self.gridLayout_7.addWidget(self.y_read_2, 1, 1, 1, 1)
        self.maskX_spinBox_4 = QtGui.QSpinBox(self.tab)
        self.maskX_spinBox_4.setMaximum(9999)
        self.maskX_spinBox_4.setObjectName(_fromUtf8("maskX_spinBox_4"))
        self.gridLayout_7.addWidget(self.maskX_spinBox_4, 1, 2, 1, 1)
        self.avPixIntensity_label_6 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.avPixIntensity_label_6.setFont(font)
        self.avPixIntensity_label_6.setObjectName(_fromUtf8("avPixIntensity_label_6"))
        self.gridLayout_7.addWidget(self.avPixIntensity_label_6, 2, 0, 1, 1)
        self.int_read_2 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.int_read_2.setFont(font)
        self.int_read_2.setObjectName(_fromUtf8("int_read_2"))
        self.gridLayout_7.addWidget(self.int_read_2, 2, 1, 1, 1)
        self.int_spinBox_2 = QtGui.QSpinBox(self.tab)
        self.int_spinBox_2.setMaximum(9999)
        self.int_spinBox_2.setObjectName(_fromUtf8("int_spinBox_2"))
        self.gridLayout_7.addWidget(self.int_spinBox_2, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_7)
        self.setPosition_pushButton = QtGui.QPushButton(self.tab)
        self.setPosition_pushButton.setObjectName(_fromUtf8("setPosition_pushButton"))
        self.verticalLayout_2.addWidget(self.setPosition_pushButton)
        self.setInt_pushButton = QtGui.QPushButton(self.tab)
        self.setInt_pushButton.setObjectName(_fromUtf8("setInt_pushButton"))
        self.verticalLayout_2.addWidget(self.setInt_pushButton)
        self.setMask_pushButton_2 = QtGui.QPushButton(self.tab)
        self.setMask_pushButton_2.setObjectName(_fromUtf8("setMask_pushButton_2"))
        self.verticalLayout_2.addWidget(self.setMask_pushButton_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.load_pushButton = QtGui.QPushButton(self.tab)
        self.load_pushButton.setObjectName(_fromUtf8("load_pushButton"))
        self.horizontalLayout_6.addWidget(self.load_pushButton)
        self.save_pushButton_2 = QtGui.QPushButton(self.tab)
        self.save_pushButton_2.setObjectName(_fromUtf8("save_pushButton_2"))
        self.horizontalLayout_6.addWidget(self.save_pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.avPixIntensity_label_5 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.avPixIntensity_label_5.setFont(font)
        self.avPixIntensity_label_5.setObjectName(_fromUtf8("avPixIntensity_label_5"))
        self.verticalLayout_7.addWidget(self.avPixIntensity_label_5)
        self.label_15 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_7.addWidget(self.label_15)
        self.label_16 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_7.addWidget(self.label_16)
        self.label_17 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_7.addWidget(self.label_17)
        self.label_18 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_7.addWidget(self.label_18)
        self.label_19 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_7.addWidget(self.label_19)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.sum_val = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.sum_val.setFont(font)
        self.sum_val.setObjectName(_fromUtf8("sum_val"))
        self.gridLayout.addWidget(self.sum_val, 0, 0, 1, 1)
        self.sum_mean = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.sum_mean.setFont(font)
        self.sum_mean.setObjectName(_fromUtf8("sum_mean"))
        self.gridLayout.addWidget(self.sum_mean, 0, 1, 1, 1)
        self.sum_sd = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.sum_sd.setFont(font)
        self.sum_sd.setObjectName(_fromUtf8("sum_sd"))
        self.gridLayout.addWidget(self.sum_sd, 0, 2, 1, 1)
        self.x_val = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.x_val.setFont(font)
        self.x_val.setObjectName(_fromUtf8("x_val"))
        self.gridLayout.addWidget(self.x_val, 1, 0, 1, 1)
        self.x_mean = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.x_mean.setFont(font)
        self.x_mean.setObjectName(_fromUtf8("x_mean"))
        self.gridLayout.addWidget(self.x_mean, 1, 1, 1, 1)
        self.x_sd = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.x_sd.setFont(font)
        self.x_sd.setObjectName(_fromUtf8("x_sd"))
        self.gridLayout.addWidget(self.x_sd, 1, 2, 1, 1)
        self.y_val = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.y_val.setFont(font)
        self.y_val.setObjectName(_fromUtf8("y_val"))
        self.gridLayout.addWidget(self.y_val, 2, 0, 1, 1)
        self.y_mean = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.y_mean.setFont(font)
        self.y_mean.setObjectName(_fromUtf8("y_mean"))
        self.gridLayout.addWidget(self.y_mean, 2, 1, 1, 1)
        self.y_sd = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.y_sd.setFont(font)
        self.y_sd.setObjectName(_fromUtf8("y_sd"))
        self.gridLayout.addWidget(self.y_sd, 2, 2, 1, 1)
        self.sx_val = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.sx_val.setFont(font)
        self.sx_val.setObjectName(_fromUtf8("sx_val"))
        self.gridLayout.addWidget(self.sx_val, 3, 0, 1, 1)
        self.sx_mean = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.sx_mean.setFont(font)
        self.sx_mean.setObjectName(_fromUtf8("sx_mean"))
        self.gridLayout.addWidget(self.sx_mean, 3, 1, 1, 1)
        self.sx_sd = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.sx_sd.setFont(font)
        self.sx_sd.setObjectName(_fromUtf8("sx_sd"))
        self.gridLayout.addWidget(self.sx_sd, 3, 2, 1, 1)
        self.sy_val = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.sy_val.setFont(font)
        self.sy_val.setObjectName(_fromUtf8("sy_val"))
        self.gridLayout.addWidget(self.sy_val, 4, 0, 1, 1)
        self.sy_mean = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.sy_mean.setFont(font)
        self.sy_mean.setObjectName(_fromUtf8("sy_mean"))
        self.gridLayout.addWidget(self.sy_mean, 4, 1, 1, 1)
        self.sy_sd = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.sy_sd.setFont(font)
        self.sy_sd.setObjectName(_fromUtf8("sy_sd"))
        self.gridLayout.addWidget(self.sy_sd, 4, 2, 1, 1)
        self.cov_val = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.cov_val.setFont(font)
        self.cov_val.setObjectName(_fromUtf8("cov_val"))
        self.gridLayout.addWidget(self.cov_val, 5, 0, 1, 1)
        self.cov_mean = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.cov_mean.setFont(font)
        self.cov_mean.setObjectName(_fromUtf8("cov_mean"))
        self.gridLayout.addWidget(self.cov_mean, 5, 1, 1, 1)
        self.cov_sd = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.cov_sd.setFont(font)
        self.cov_sd.setObjectName(_fromUtf8("cov_sd"))
        self.gridLayout.addWidget(self.cov_sd, 5, 2, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.resetMeanSD_pushButton = QtGui.QPushButton(self.tab)
        self.resetMeanSD_pushButton.setObjectName(_fromUtf8("resetMeanSD_pushButton"))
        self.verticalLayout_2.addWidget(self.resetMeanSD_pushButton)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.analyse_pushButton = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyse_pushButton.sizePolicy().hasHeightForWidth())
        self.analyse_pushButton.setSizePolicy(sizePolicy)
        self.analyse_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.analyse_pushButton.setObjectName(_fromUtf8("analyse_pushButton"))
        self.verticalLayout.addWidget(self.analyse_pushButton)
        self.resetBackground_pushButton = QtGui.QPushButton(self.tab_2)
        self.resetBackground_pushButton.setObjectName(_fromUtf8("resetBackground_pushButton"))
        self.verticalLayout.addWidget(self.resetBackground_pushButton)
        self.useBackground_checkBox = QtGui.QCheckBox(self.tab_2)
        self.useBackground_checkBox.setObjectName(_fromUtf8("useBackground_checkBox"))
        self.verticalLayout.addWidget(self.useBackground_checkBox)
        self.useNPoint_checkBox = QtGui.QCheckBox(self.tab_2)
        self.useNPoint_checkBox.setObjectName(_fromUtf8("useNPoint_checkBox"))
        self.verticalLayout.addWidget(self.useNPoint_checkBox)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.stepSize_spinBox = QtGui.QSpinBox(self.tab_2)
        self.stepSize_spinBox.setMinimum(1)
        self.stepSize_spinBox.setMaximum(10)
        self.stepSize_spinBox.setSingleStep(1)
        self.stepSize_spinBox.setProperty("value", 1)
        self.stepSize_spinBox.setObjectName(_fromUtf8("stepSize_spinBox"))
        self.horizontalLayout_5.addWidget(self.stepSize_spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.mask_x_read = QtGui.QLabel(self.tab_2)
        self.mask_x_read.setObjectName(_fromUtf8("mask_x_read"))
        self.gridLayout_6.addWidget(self.mask_x_read, 0, 1, 1, 1)
        self.maskX_spinBox = QtGui.QSpinBox(self.tab_2)
        self.maskX_spinBox.setMaximum(9999)
        self.maskX_spinBox.setObjectName(_fromUtf8("maskX_spinBox"))
        self.gridLayout_6.addWidget(self.maskX_spinBox, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 1, 0, 1, 1)
        self.mask_y_read = QtGui.QLabel(self.tab_2)
        self.mask_y_read.setObjectName(_fromUtf8("mask_y_read"))
        self.gridLayout_6.addWidget(self.mask_y_read, 1, 1, 1, 1)
        self.maskY_spinBox = QtGui.QSpinBox(self.tab_2)
        self.maskY_spinBox.setMaximum(9999)
        self.maskY_spinBox.setObjectName(_fromUtf8("maskY_spinBox"))
        self.gridLayout_6.addWidget(self.maskY_spinBox, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 2, 0, 1, 1)
        self.mas_y_rad = QtGui.QLabel(self.tab_2)
        self.mas_y_rad.setObjectName(_fromUtf8("mas_y_rad"))
        self.gridLayout_6.addWidget(self.mas_y_rad, 2, 1, 1, 1)
        self.maskXRadius_spinBox = QtGui.QSpinBox(self.tab_2)
        self.maskXRadius_spinBox.setMaximum(9999)
        self.maskXRadius_spinBox.setObjectName(_fromUtf8("maskXRadius_spinBox"))
        self.gridLayout_6.addWidget(self.maskXRadius_spinBox, 2, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 3, 0, 1, 1)
        self.mask_y_rad = QtGui.QLabel(self.tab_2)
        self.mask_y_rad.setObjectName(_fromUtf8("mask_y_rad"))
        self.gridLayout_6.addWidget(self.mask_y_rad, 3, 1, 1, 1)
        self.maskYRadius_spinBox = QtGui.QSpinBox(self.tab_2)
        self.maskYRadius_spinBox.setMaximum(9999)
        self.maskYRadius_spinBox.setObjectName(_fromUtf8("maskYRadius_spinBox"))
        self.gridLayout_6.addWidget(self.maskYRadius_spinBox, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.feed_back_check = QtGui.QCheckBox(self.tab_2)
        self.feed_back_check.setObjectName(_fromUtf8("feed_back_check"))
        self.horizontalLayout.addWidget(self.feed_back_check)
        self.setMask_pushButton = QtGui.QPushButton(self.tab_2)
        self.setMask_pushButton.setObjectName(_fromUtf8("setMask_pushButton"))
        self.horizontalLayout.addWidget(self.setMask_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.acquire_pushButton = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acquire_pushButton.sizePolicy().hasHeightForWidth())
        self.acquire_pushButton.setSizePolicy(sizePolicy)
        self.acquire_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.acquire_pushButton.setObjectName(_fromUtf8("acquire_pushButton"))
        self.verticalLayout.addWidget(self.acquire_pushButton)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.numImages_spinBox = QtGui.QSpinBox(self.tab_2)
        self.numImages_spinBox.setMinimum(1)
        self.numImages_spinBox.setObjectName(_fromUtf8("numImages_spinBox"))
        self.horizontalLayout_2.addWidget(self.numImages_spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.save_pushButton = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_pushButton.sizePolicy().hasHeightForWidth())
        self.save_pushButton.setSizePolicy(sizePolicy)
        self.save_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.save_pushButton.setObjectName(_fromUtf8("save_pushButton"))
        self.verticalLayout.addWidget(self.save_pushButton)
        self.getImages_pushButton = QtGui.QPushButton(self.tab_2)
        self.getImages_pushButton.setObjectName(_fromUtf8("getImages_pushButton"))
        self.verticalLayout.addWidget(self.getImages_pushButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 540, 991, 271))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.graphLayout = QtGui.QGridLayout(self.layoutWidget)
        self.graphLayout.setObjectName(_fromUtf8("graphLayout"))
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(190, 10, 811, 521))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.imageLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.imageLayout.setObjectName(_fromUtf8("imageLayout"))
        mainView.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1038, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        mainView.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainView)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainView.setStatusBar(self.statusbar)

        self.retranslateUi(mainView)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainView)
        mainView.setTabOrder(self.liveStream_pushButton, self.spinBox_minLevel)
        mainView.setTabOrder(self.spinBox_minLevel, self.spinBox_maxLevel)
        mainView.setTabOrder(self.spinBox_maxLevel, self.analyse_pushButton)
        mainView.setTabOrder(self.analyse_pushButton, self.resetBackground_pushButton)
        mainView.setTabOrder(self.resetBackground_pushButton, self.useBackground_checkBox)
        mainView.setTabOrder(self.useBackground_checkBox, self.useNPoint_checkBox)
        mainView.setTabOrder(self.useNPoint_checkBox, self.stepSize_spinBox)
        mainView.setTabOrder(self.stepSize_spinBox, self.maskX_spinBox)
        mainView.setTabOrder(self.maskX_spinBox, self.maskY_spinBox)
        mainView.setTabOrder(self.maskY_spinBox, self.maskXRadius_spinBox)
        mainView.setTabOrder(self.maskXRadius_spinBox, self.maskYRadius_spinBox)

    def retranslateUi(self, mainView):
        mainView.setWindowTitle(_translate("mainView", "Image Collector", None))
        self.collectAndSave_pushButton.setText(_translate("mainView", "Collect and Save Image", None))
        self.liveStream_pushButton.setText(_translate("mainView", "Live Stream", None))
        self.label_3.setText(_translate("mainView", "Min. Level:", None))
        self.label_4.setText(_translate("mainView", "Max. Level:", None))
        self.avPixIntensity_label_8.setText(_translate("mainView", "Set X", None))
        self.avPixIntensity_label_15.setText(_translate("mainView", "Read X", None))
        self.avPixIntensity_label_7.setText(_translate("mainView", "Set Y", None))
        self.y_read_2.setText(_translate("mainView", "Read Y", None))
        self.avPixIntensity_label_6.setText(_translate("mainView", "Set Int", None))
        self.int_read_2.setText(_translate("mainView", "Read Int", None))
        self.setPosition_pushButton.setText(_translate("mainView", "Set Position", None))
        self.setInt_pushButton.setText(_translate("mainView", "Set Intensity", None))
        self.setMask_pushButton_2.setText(_translate("mainView", "Set Mask", None))
        self.load_pushButton.setText(_translate("mainView", "Load", None))
        self.save_pushButton_2.setText(_translate("mainView", "Save", None))
        self.avPixIntensity_label_5.setText(_translate("mainView", "Sum :", None))
        self.label_15.setText(_translate("mainView", "X:", None))
        self.label_16.setText(_translate("mainView", "Y:", None))
        self.label_17.setText(_translate("mainView", "Sig X:", None))
        self.label_18.setText(_translate("mainView", "Sig Y:", None))
        self.label_19.setText(_translate("mainView", "Cov XY  : ", None))
        self.sum_val.setText(_translate("mainView", "-", None))
        self.sum_mean.setText(_translate("mainView", "-", None))
        self.sum_sd.setText(_translate("mainView", "-", None))
        self.x_val.setText(_translate("mainView", "-", None))
        self.x_mean.setText(_translate("mainView", "-", None))
        self.x_sd.setText(_translate("mainView", "-", None))
        self.y_val.setText(_translate("mainView", "-", None))
        self.y_mean.setText(_translate("mainView", "-", None))
        self.y_sd.setText(_translate("mainView", "-", None))
        self.sx_val.setText(_translate("mainView", "-", None))
        self.sx_mean.setText(_translate("mainView", "-", None))
        self.sx_sd.setText(_translate("mainView", "-", None))
        self.sy_val.setText(_translate("mainView", "-", None))
        self.sy_mean.setText(_translate("mainView", "-", None))
        self.sy_sd.setText(_translate("mainView", "-", None))
        self.cov_val.setText(_translate("mainView", "-", None))
        self.cov_mean.setText(_translate("mainView", "-", None))
        self.cov_sd.setText(_translate("mainView", "-", None))
        self.resetMeanSD_pushButton.setText(_translate("mainView", "Reset Means and SD", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainView", "Tab 1", None))
        self.analyse_pushButton.setText(_translate("mainView", "Analyse", None))
        self.resetBackground_pushButton.setText(_translate("mainView", "Reset Background Image", None))
        self.useBackground_checkBox.setText(_translate("mainView", "Use Background", None))
        self.useNPoint_checkBox.setText(_translate("mainView", "Use N-Point Scaling", None))
        self.label_5.setText(_translate("mainView", "Step Size:", None))
        self.label.setText(_translate("mainView", "MASK", None))
        self.label_6.setText(_translate("mainView", "Center X :", None))
        self.mask_x_read.setText(_translate("mainView", "x Read", None))
        self.label_7.setText(_translate("mainView", "Center Y :", None))
        self.mask_y_read.setText(_translate("mainView", "y Read", None))
        self.label_8.setText(_translate("mainView", "X Radius:", None))
        self.mas_y_rad.setText(_translate("mainView", "x Rad", None))
        self.label_9.setText(_translate("mainView", "Y Radius :", None))
        self.mask_y_rad.setText(_translate("mainView", "y Rad", None))
        self.feed_back_check.setText(_translate("mainView", "Feedback", None))
        self.setMask_pushButton.setText(_translate("mainView", "Set Mask", None))
        self.acquire_pushButton.setText(_translate("mainView", "Acquire", None))
        self.label_2.setText(_translate("mainView", "Number of Images:", None))
        self.save_pushButton.setText(_translate("mainView", "Collect and Save", None))
        self.getImages_pushButton.setText(_translate("mainView", "Open Image Directory", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainView", "Tab 2", None))

