# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_windows_source.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(867, 360)
        mainWindow.setMaximumSize(QtCore.QSize(16777215, 500))
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(3, 11, 851, 341))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.clear_for_beam_button = QtGui.QPushButton(self.widget)
        self.clear_for_beam_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.clear_for_beam_button.setFont(font)
        self.clear_for_beam_button.setObjectName(_fromUtf8("clear_for_beam_button"))
        self.verticalLayout.addWidget(self.clear_for_beam_button)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 8, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 6, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 7, 1, 1)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 5, 1, 1)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 9, 1, 1)
        self.device_stage_3 = QtGui.QComboBox(self.widget)
        self.device_stage_3.setMinimumSize(QtCore.QSize(60, 0))
        self.device_stage_3.setObjectName(_fromUtf8("device_stage_3"))
        self.gridLayout.addWidget(self.device_stage_3, 3, 3, 1, 1)
        self.read_dev_stage_2 = QtGui.QLabel(self.widget)
        self.read_dev_stage_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.read_dev_stage_2.setObjectName(_fromUtf8("read_dev_stage_2"))
        self.gridLayout.addWidget(self.read_dev_stage_2, 2, 2, 1, 1)
        self.set_pos_stage_1 = QtGui.QDoubleSpinBox(self.widget)
        self.set_pos_stage_1.setMinimumSize(QtCore.QSize(60, 0))
        self.set_pos_stage_1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.set_pos_stage_1.setAlignment(QtCore.Qt.AlignCenter)
        self.set_pos_stage_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.set_pos_stage_1.setDecimals(3)
        self.set_pos_stage_1.setMinimum(-250.0)
        self.set_pos_stage_1.setMaximum(250.0)
        self.set_pos_stage_1.setObjectName(_fromUtf8("set_pos_stage_1"))
        self.gridLayout.addWidget(self.set_pos_stage_1, 1, 7, 1, 1)
        self.move2dev_stage_1 = QtGui.QPushButton(self.widget)
        self.move2dev_stage_1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.move2dev_stage_1.setObjectName(_fromUtf8("move2dev_stage_1"))
        self.gridLayout.addWidget(self.move2dev_stage_1, 1, 4, 1, 1)
        self.move2dev_stage_2 = QtGui.QPushButton(self.widget)
        self.move2dev_stage_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.move2dev_stage_2.setObjectName(_fromUtf8("move2dev_stage_2"))
        self.gridLayout.addWidget(self.move2dev_stage_2, 2, 4, 1, 1)
        self.name_stage_3 = QtGui.QLabel(self.widget)
        self.name_stage_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.name_stage_3.setObjectName(_fromUtf8("name_stage_3"))
        self.gridLayout.addWidget(self.name_stage_3, 3, 1, 1, 1)
        self.label_stage_2 = QtGui.QLabel(self.widget)
        self.label_stage_2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_stage_2.setObjectName(_fromUtf8("label_stage_2"))
        self.gridLayout.addWidget(self.label_stage_2, 2, 0, 1, 1)
        self.read_dev_stage_3 = QtGui.QLabel(self.widget)
        self.read_dev_stage_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.read_dev_stage_3.setObjectName(_fromUtf8("read_dev_stage_3"))
        self.gridLayout.addWidget(self.read_dev_stage_3, 3, 2, 1, 1)
        self.device_stage_1 = QtGui.QComboBox(self.widget)
        self.device_stage_1.setMinimumSize(QtCore.QSize(60, 0))
        self.device_stage_1.setMaximumSize(QtCore.QSize(120, 16777215))
        self.device_stage_1.setObjectName(_fromUtf8("device_stage_1"))
        self.gridLayout.addWidget(self.device_stage_1, 1, 3, 1, 1)
        self.move2dev_stage_3 = QtGui.QPushButton(self.widget)
        self.move2dev_stage_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.move2dev_stage_3.setObjectName(_fromUtf8("move2dev_stage_3"))
        self.gridLayout.addWidget(self.move2dev_stage_3, 3, 4, 1, 1)
        self.read_dev_stage_1 = QtGui.QLabel(self.widget)
        self.read_dev_stage_1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.read_dev_stage_1.setObjectName(_fromUtf8("read_dev_stage_1"))
        self.gridLayout.addWidget(self.read_dev_stage_1, 1, 2, 1, 1)
        self.set_pos_stage_3 = QtGui.QDoubleSpinBox(self.widget)
        self.set_pos_stage_3.setMinimumSize(QtCore.QSize(60, 0))
        self.set_pos_stage_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.set_pos_stage_3.setAlignment(QtCore.Qt.AlignCenter)
        self.set_pos_stage_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.set_pos_stage_3.setDecimals(3)
        self.set_pos_stage_3.setMinimum(-250.0)
        self.set_pos_stage_3.setMaximum(250.0)
        self.set_pos_stage_3.setObjectName(_fromUtf8("set_pos_stage_3"))
        self.gridLayout.addWidget(self.set_pos_stage_3, 3, 7, 1, 1)
        self.set_pos_stage_2 = QtGui.QDoubleSpinBox(self.widget)
        self.set_pos_stage_2.setMinimumSize(QtCore.QSize(60, 0))
        self.set_pos_stage_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.set_pos_stage_2.setAlignment(QtCore.Qt.AlignCenter)
        self.set_pos_stage_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.set_pos_stage_2.setDecimals(3)
        self.set_pos_stage_2.setMinimum(-250.0)
        self.set_pos_stage_2.setMaximum(250.0)
        self.set_pos_stage_2.setObjectName(_fromUtf8("set_pos_stage_2"))
        self.gridLayout.addWidget(self.set_pos_stage_2, 2, 7, 1, 1)
        self.label_stage_3 = QtGui.QLabel(self.widget)
        self.label_stage_3.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_stage_3.setObjectName(_fromUtf8("label_stage_3"))
        self.gridLayout.addWidget(self.label_stage_3, 3, 0, 1, 1)
        self.name_stage_1 = QtGui.QLabel(self.widget)
        self.name_stage_1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.name_stage_1.setObjectName(_fromUtf8("name_stage_1"))
        self.gridLayout.addWidget(self.name_stage_1, 1, 1, 1, 1)
        self.label_stage_1 = QtGui.QLabel(self.widget)
        self.label_stage_1.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_stage_1.setObjectName(_fromUtf8("label_stage_1"))
        self.gridLayout.addWidget(self.label_stage_1, 1, 0, 1, 1)
        self.name_stage_2 = QtGui.QLabel(self.widget)
        self.name_stage_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.name_stage_2.setObjectName(_fromUtf8("name_stage_2"))
        self.gridLayout.addWidget(self.name_stage_2, 2, 1, 1, 1)
        self.device_stage_2 = QtGui.QComboBox(self.widget)
        self.device_stage_2.setMinimumSize(QtCore.QSize(60, 0))
        self.device_stage_2.setObjectName(_fromUtf8("device_stage_2"))
        self.gridLayout.addWidget(self.device_stage_2, 2, 3, 1, 1)
        self.set_pos_stage_5 = QtGui.QDoubleSpinBox(self.widget)
        self.set_pos_stage_5.setMinimumSize(QtCore.QSize(60, 0))
        self.set_pos_stage_5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.set_pos_stage_5.setAlignment(QtCore.Qt.AlignCenter)
        self.set_pos_stage_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.set_pos_stage_5.setDecimals(3)
        self.set_pos_stage_5.setMinimum(-250.0)
        self.set_pos_stage_5.setMaximum(250.0)
        self.set_pos_stage_5.setObjectName(_fromUtf8("set_pos_stage_5"))
        self.gridLayout.addWidget(self.set_pos_stage_5, 5, 7, 1, 1)
        self.label_stage_5 = QtGui.QLabel(self.widget)
        self.label_stage_5.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_stage_5.setObjectName(_fromUtf8("label_stage_5"))
        self.gridLayout.addWidget(self.label_stage_5, 5, 0, 1, 1)
        self.device_stage_6 = QtGui.QComboBox(self.widget)
        self.device_stage_6.setMinimumSize(QtCore.QSize(60, 0))
        self.device_stage_6.setObjectName(_fromUtf8("device_stage_6"))
        self.gridLayout.addWidget(self.device_stage_6, 6, 3, 1, 1)
        self.move2dev_stage_6 = QtGui.QPushButton(self.widget)
        self.move2dev_stage_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.move2dev_stage_6.setObjectName(_fromUtf8("move2dev_stage_6"))
        self.gridLayout.addWidget(self.move2dev_stage_6, 6, 4, 1, 1)
        self.move2dev_stage_4 = QtGui.QPushButton(self.widget)
        self.move2dev_stage_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.move2dev_stage_4.setObjectName(_fromUtf8("move2dev_stage_4"))
        self.gridLayout.addWidget(self.move2dev_stage_4, 4, 4, 1, 1)
        self.set_pos_stage_4 = QtGui.QDoubleSpinBox(self.widget)
        self.set_pos_stage_4.setMinimumSize(QtCore.QSize(60, 0))
        self.set_pos_stage_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.set_pos_stage_4.setAlignment(QtCore.Qt.AlignCenter)
        self.set_pos_stage_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.set_pos_stage_4.setDecimals(3)
        self.set_pos_stage_4.setMinimum(-250.0)
        self.set_pos_stage_4.setMaximum(250.0)
        self.set_pos_stage_4.setObjectName(_fromUtf8("set_pos_stage_4"))
        self.gridLayout.addWidget(self.set_pos_stage_4, 4, 7, 1, 1)
        self.device_stage_5 = QtGui.QComboBox(self.widget)
        self.device_stage_5.setMinimumSize(QtCore.QSize(60, 0))
        self.device_stage_5.setObjectName(_fromUtf8("device_stage_5"))
        self.gridLayout.addWidget(self.device_stage_5, 5, 3, 1, 1)
        self.name_stage_6 = QtGui.QLabel(self.widget)
        self.name_stage_6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.name_stage_6.setObjectName(_fromUtf8("name_stage_6"))
        self.gridLayout.addWidget(self.name_stage_6, 6, 1, 1, 1)
        self.name_stage_4 = QtGui.QLabel(self.widget)
        self.name_stage_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.name_stage_4.setObjectName(_fromUtf8("name_stage_4"))
        self.gridLayout.addWidget(self.name_stage_4, 4, 1, 1, 1)
        self.label_stage_4 = QtGui.QLabel(self.widget)
        self.label_stage_4.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_stage_4.setObjectName(_fromUtf8("label_stage_4"))
        self.gridLayout.addWidget(self.label_stage_4, 4, 0, 1, 1)
        self.read_dev_stage_5 = QtGui.QLabel(self.widget)
        self.read_dev_stage_5.setMaximumSize(QtCore.QSize(60, 16777215))
        self.read_dev_stage_5.setObjectName(_fromUtf8("read_dev_stage_5"))
        self.gridLayout.addWidget(self.read_dev_stage_5, 5, 2, 1, 1)
        self.read_dev_stage_4 = QtGui.QLabel(self.widget)
        self.read_dev_stage_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.read_dev_stage_4.setObjectName(_fromUtf8("read_dev_stage_4"))
        self.gridLayout.addWidget(self.read_dev_stage_4, 4, 2, 1, 1)
        self.device_stage_4 = QtGui.QComboBox(self.widget)
        self.device_stage_4.setMinimumSize(QtCore.QSize(60, 0))
        self.device_stage_4.setObjectName(_fromUtf8("device_stage_4"))
        self.gridLayout.addWidget(self.device_stage_4, 4, 3, 1, 1)
        self.read_dev_stage_6 = QtGui.QLabel(self.widget)
        self.read_dev_stage_6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.read_dev_stage_6.setObjectName(_fromUtf8("read_dev_stage_6"))
        self.gridLayout.addWidget(self.read_dev_stage_6, 6, 2, 1, 1)
        self.label_stage_6 = QtGui.QLabel(self.widget)
        self.label_stage_6.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_stage_6.setObjectName(_fromUtf8("label_stage_6"))
        self.gridLayout.addWidget(self.label_stage_6, 6, 0, 1, 1)
        self.name_stage_5 = QtGui.QLabel(self.widget)
        self.name_stage_5.setMaximumSize(QtCore.QSize(60, 16777215))
        self.name_stage_5.setObjectName(_fromUtf8("name_stage_5"))
        self.gridLayout.addWidget(self.name_stage_5, 5, 1, 1, 1)
        self.move2dev_stage_5 = QtGui.QPushButton(self.widget)
        self.move2dev_stage_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.move2dev_stage_5.setObjectName(_fromUtf8("move2dev_stage_5"))
        self.gridLayout.addWidget(self.move2dev_stage_5, 5, 4, 1, 1)
        self.read_dev_stage_7 = QtGui.QLabel(self.widget)
        self.read_dev_stage_7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.read_dev_stage_7.setObjectName(_fromUtf8("read_dev_stage_7"))
        self.gridLayout.addWidget(self.read_dev_stage_7, 7, 2, 1, 1)
        self.set_pos_stage_6 = QtGui.QDoubleSpinBox(self.widget)
        self.set_pos_stage_6.setMinimumSize(QtCore.QSize(60, 0))
        self.set_pos_stage_6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.set_pos_stage_6.setAlignment(QtCore.Qt.AlignCenter)
        self.set_pos_stage_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.set_pos_stage_6.setDecimals(3)
        self.set_pos_stage_6.setMinimum(-250.0)
        self.set_pos_stage_6.setMaximum(250.0)
        self.set_pos_stage_6.setObjectName(_fromUtf8("set_pos_stage_6"))
        self.gridLayout.addWidget(self.set_pos_stage_6, 6, 7, 1, 1)
        self.label_stage_7 = QtGui.QLabel(self.widget)
        self.label_stage_7.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_stage_7.setObjectName(_fromUtf8("label_stage_7"))
        self.gridLayout.addWidget(self.label_stage_7, 7, 0, 1, 1)
        self.name_stage_7 = QtGui.QLabel(self.widget)
        self.name_stage_7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.name_stage_7.setObjectName(_fromUtf8("name_stage_7"))
        self.gridLayout.addWidget(self.name_stage_7, 7, 1, 1, 1)
        self.device_stage_8 = QtGui.QComboBox(self.widget)
        self.device_stage_8.setMinimumSize(QtCore.QSize(60, 0))
        self.device_stage_8.setObjectName(_fromUtf8("device_stage_8"))
        self.gridLayout.addWidget(self.device_stage_8, 8, 3, 1, 1)
        self.move2dev_stage_7 = QtGui.QPushButton(self.widget)
        self.move2dev_stage_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.move2dev_stage_7.setObjectName(_fromUtf8("move2dev_stage_7"))
        self.gridLayout.addWidget(self.move2dev_stage_7, 7, 4, 1, 1)
        self.label_stage_9 = QtGui.QLabel(self.widget)
        self.label_stage_9.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_stage_9.setObjectName(_fromUtf8("label_stage_9"))
        self.gridLayout.addWidget(self.label_stage_9, 9, 0, 1, 1)
        self.read_dev_stage_9 = QtGui.QLabel(self.widget)
        self.read_dev_stage_9.setMaximumSize(QtCore.QSize(60, 16777215))
        self.read_dev_stage_9.setObjectName(_fromUtf8("read_dev_stage_9"))
        self.gridLayout.addWidget(self.read_dev_stage_9, 9, 2, 1, 1)
        self.device_stage_9 = QtGui.QComboBox(self.widget)
        self.device_stage_9.setMinimumSize(QtCore.QSize(60, 0))
        self.device_stage_9.setObjectName(_fromUtf8("device_stage_9"))
        self.gridLayout.addWidget(self.device_stage_9, 9, 3, 1, 1)
        self.set_pos_stage_7 = QtGui.QDoubleSpinBox(self.widget)
        self.set_pos_stage_7.setMinimumSize(QtCore.QSize(60, 0))
        self.set_pos_stage_7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.set_pos_stage_7.setAlignment(QtCore.Qt.AlignCenter)
        self.set_pos_stage_7.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.set_pos_stage_7.setDecimals(3)
        self.set_pos_stage_7.setMinimum(-250.0)
        self.set_pos_stage_7.setMaximum(250.0)
        self.set_pos_stage_7.setObjectName(_fromUtf8("set_pos_stage_7"))
        self.gridLayout.addWidget(self.set_pos_stage_7, 7, 7, 1, 1)
        self.name_stage_9 = QtGui.QLabel(self.widget)
        self.name_stage_9.setMaximumSize(QtCore.QSize(60, 16777215))
        self.name_stage_9.setObjectName(_fromUtf8("name_stage_9"))
        self.gridLayout.addWidget(self.name_stage_9, 9, 1, 1, 1)
        self.label_stage_8 = QtGui.QLabel(self.widget)
        self.label_stage_8.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_stage_8.setObjectName(_fromUtf8("label_stage_8"))
        self.gridLayout.addWidget(self.label_stage_8, 8, 0, 1, 1)
        self.read_dev_stage_8 = QtGui.QLabel(self.widget)
        self.read_dev_stage_8.setMaximumSize(QtCore.QSize(60, 16777215))
        self.read_dev_stage_8.setObjectName(_fromUtf8("read_dev_stage_8"))
        self.gridLayout.addWidget(self.read_dev_stage_8, 8, 2, 1, 1)
        self.move2dev_stage_8 = QtGui.QPushButton(self.widget)
        self.move2dev_stage_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.move2dev_stage_8.setObjectName(_fromUtf8("move2dev_stage_8"))
        self.gridLayout.addWidget(self.move2dev_stage_8, 8, 4, 1, 1)
        self.set_pos_stage_8 = QtGui.QDoubleSpinBox(self.widget)
        self.set_pos_stage_8.setMinimumSize(QtCore.QSize(60, 0))
        self.set_pos_stage_8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.set_pos_stage_8.setAlignment(QtCore.Qt.AlignCenter)
        self.set_pos_stage_8.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.set_pos_stage_8.setDecimals(3)
        self.set_pos_stage_8.setMinimum(-250.0)
        self.set_pos_stage_8.setMaximum(250.0)
        self.set_pos_stage_8.setObjectName(_fromUtf8("set_pos_stage_8"))
        self.gridLayout.addWidget(self.set_pos_stage_8, 8, 7, 1, 1)
        self.device_stage_7 = QtGui.QComboBox(self.widget)
        self.device_stage_7.setMinimumSize(QtCore.QSize(60, 0))
        self.device_stage_7.setObjectName(_fromUtf8("device_stage_7"))
        self.gridLayout.addWidget(self.device_stage_7, 7, 3, 1, 1)
        self.name_stage_8 = QtGui.QLabel(self.widget)
        self.name_stage_8.setMaximumSize(QtCore.QSize(60, 16777215))
        self.name_stage_8.setObjectName(_fromUtf8("name_stage_8"))
        self.gridLayout.addWidget(self.name_stage_8, 8, 1, 1, 1)
        self.move2dev_stage_9 = QtGui.QPushButton(self.widget)
        self.move2dev_stage_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.move2dev_stage_9.setObjectName(_fromUtf8("move2dev_stage_9"))
        self.gridLayout.addWidget(self.move2dev_stage_9, 9, 4, 1, 1)
        self.set_pos_stage_9 = QtGui.QDoubleSpinBox(self.widget)
        self.set_pos_stage_9.setMinimumSize(QtCore.QSize(60, 0))
        self.set_pos_stage_9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.set_pos_stage_9.setAlignment(QtCore.Qt.AlignCenter)
        self.set_pos_stage_9.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.set_pos_stage_9.setDecimals(3)
        self.set_pos_stage_9.setMinimum(-250.0)
        self.set_pos_stage_9.setMaximum(250.0)
        self.set_pos_stage_9.setObjectName(_fromUtf8("set_pos_stage_9"))
        self.gridLayout.addWidget(self.set_pos_stage_9, 9, 7, 1, 1)
        self.read_pos_stage_1 = QtGui.QDoubleSpinBox(self.widget)
        self.read_pos_stage_1.setMinimumSize(QtCore.QSize(60, 0))
        self.read_pos_stage_1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.read_pos_stage_1.setAlignment(QtCore.Qt.AlignCenter)
        self.read_pos_stage_1.setReadOnly(True)
        self.read_pos_stage_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.read_pos_stage_1.setDecimals(3)
        self.read_pos_stage_1.setMinimum(-250.0)
        self.read_pos_stage_1.setMaximum(250.0)
        self.read_pos_stage_1.setObjectName(_fromUtf8("read_pos_stage_1"))
        self.gridLayout.addWidget(self.read_pos_stage_1, 1, 5, 1, 1)
        self.read_set_pos_stage_1 = QtGui.QDoubleSpinBox(self.widget)
        self.read_set_pos_stage_1.setMinimumSize(QtCore.QSize(60, 0))
        self.read_set_pos_stage_1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.read_set_pos_stage_1.setAlignment(QtCore.Qt.AlignCenter)
        self.read_set_pos_stage_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.read_set_pos_stage_1.setDecimals(3)
        self.read_set_pos_stage_1.setMinimum(-250.0)
        self.read_set_pos_stage_1.setMaximum(250.0)
        self.read_set_pos_stage_1.setObjectName(_fromUtf8("read_set_pos_stage_1"))
        self.gridLayout.addWidget(self.read_set_pos_stage_1, 1, 6, 1, 1)
        self.min_pos_stage_1 = QtGui.QDoubleSpinBox(self.widget)
        self.min_pos_stage_1.setMinimumSize(QtCore.QSize(60, 0))
        self.min_pos_stage_1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.min_pos_stage_1.setAlignment(QtCore.Qt.AlignCenter)
        self.min_pos_stage_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.min_pos_stage_1.setDecimals(3)
        self.min_pos_stage_1.setMinimum(-250.0)
        self.min_pos_stage_1.setMaximum(250.0)
        self.min_pos_stage_1.setObjectName(_fromUtf8("min_pos_stage_1"))
        self.gridLayout.addWidget(self.min_pos_stage_1, 1, 8, 1, 1)
        self.max_pos_stage_1 = QtGui.QDoubleSpinBox(self.widget)
        self.max_pos_stage_1.setMinimumSize(QtCore.QSize(60, 0))
        self.max_pos_stage_1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.max_pos_stage_1.setAlignment(QtCore.Qt.AlignCenter)
        self.max_pos_stage_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.max_pos_stage_1.setDecimals(3)
        self.max_pos_stage_1.setMinimum(-250.0)
        self.max_pos_stage_1.setMaximum(250.0)
        self.max_pos_stage_1.setObjectName(_fromUtf8("max_pos_stage_1"))
        self.gridLayout.addWidget(self.max_pos_stage_1, 1, 9, 1, 1)
        self.read_pos_stage_2 = QtGui.QDoubleSpinBox(self.widget)
        self.read_pos_stage_2.setMinimumSize(QtCore.QSize(60, 0))
        self.read_pos_stage_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.read_pos_stage_2.setAlignment(QtCore.Qt.AlignCenter)
        self.read_pos_stage_2.setReadOnly(True)
        self.read_pos_stage_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.read_pos_stage_2.setDecimals(3)
        self.read_pos_stage_2.setMinimum(-250.0)
        self.read_pos_stage_2.setMaximum(250.0)
        self.read_pos_stage_2.setObjectName(_fromUtf8("read_pos_stage_2"))
        self.gridLayout.addWidget(self.read_pos_stage_2, 2, 5, 1, 1)
        self.read_pos_stage_3 = QtGui.QDoubleSpinBox(self.widget)
        self.read_pos_stage_3.setMinimumSize(QtCore.QSize(60, 0))
        self.read_pos_stage_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.read_pos_stage_3.setAlignment(QtCore.Qt.AlignCenter)
        self.read_pos_stage_3.setReadOnly(True)
        self.read_pos_stage_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.read_pos_stage_3.setDecimals(3)
        self.read_pos_stage_3.setMinimum(-250.0)
        self.read_pos_stage_3.setMaximum(250.0)
        self.read_pos_stage_3.setObjectName(_fromUtf8("read_pos_stage_3"))
        self.gridLayout.addWidget(self.read_pos_stage_3, 3, 5, 1, 1)
        self.read_pos_stage_4 = QtGui.QDoubleSpinBox(self.widget)
        self.read_pos_stage_4.setMinimumSize(QtCore.QSize(60, 0))
        self.read_pos_stage_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.read_pos_stage_4.setAlignment(QtCore.Qt.AlignCenter)
        self.read_pos_stage_4.setReadOnly(True)
        self.read_pos_stage_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.read_pos_stage_4.setDecimals(3)
        self.read_pos_stage_4.setMinimum(-250.0)
        self.read_pos_stage_4.setMaximum(250.0)
        self.read_pos_stage_4.setObjectName(_fromUtf8("read_pos_stage_4"))
        self.gridLayout.addWidget(self.read_pos_stage_4, 4, 5, 1, 1)
        self.read_pos_stage_5 = QtGui.QDoubleSpinBox(self.widget)
        self.read_pos_stage_5.setMinimumSize(QtCore.QSize(60, 0))
        self.read_pos_stage_5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.read_pos_stage_5.setAlignment(QtCore.Qt.AlignCenter)
        self.read_pos_stage_5.setReadOnly(True)
        self.read_pos_stage_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.read_pos_stage_5.setDecimals(3)
        self.read_pos_stage_5.setMinimum(-250.0)
        self.read_pos_stage_5.setMaximum(250.0)
        self.read_pos_stage_5.setObjectName(_fromUtf8("read_pos_stage_5"))
        self.gridLayout.addWidget(self.read_pos_stage_5, 5, 5, 1, 1)
        self.read_pos_stage_6 = QtGui.QDoubleSpinBox(self.widget)
        self.read_pos_stage_6.setMinimumSize(QtCore.QSize(60, 0))
        self.read_pos_stage_6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.read_pos_stage_6.setAlignment(QtCore.Qt.AlignCenter)
        self.read_pos_stage_6.setReadOnly(True)
        self.read_pos_stage_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.read_pos_stage_6.setDecimals(3)
        self.read_pos_stage_6.setMinimum(-250.0)
        self.read_pos_stage_6.setMaximum(250.0)
        self.read_pos_stage_6.setObjectName(_fromUtf8("read_pos_stage_6"))
        self.gridLayout.addWidget(self.read_pos_stage_6, 6, 5, 1, 1)
        self.read_pos_stage_7 = QtGui.QDoubleSpinBox(self.widget)
        self.read_pos_stage_7.setMinimumSize(QtCore.QSize(60, 0))
        self.read_pos_stage_7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.read_pos_stage_7.setAlignment(QtCore.Qt.AlignCenter)
        self.read_pos_stage_7.setReadOnly(True)
        self.read_pos_stage_7.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.read_pos_stage_7.setDecimals(3)
        self.read_pos_stage_7.setMinimum(-250.0)
        self.read_pos_stage_7.setMaximum(250.0)
        self.read_pos_stage_7.setObjectName(_fromUtf8("read_pos_stage_7"))
        self.gridLayout.addWidget(self.read_pos_stage_7, 7, 5, 1, 1)
        self.read_pos_stage_8 = QtGui.QDoubleSpinBox(self.widget)
        self.read_pos_stage_8.setMinimumSize(QtCore.QSize(60, 0))
        self.read_pos_stage_8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.read_pos_stage_8.setAlignment(QtCore.Qt.AlignCenter)
        self.read_pos_stage_8.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.read_pos_stage_8.setDecimals(3)
        self.read_pos_stage_8.setMinimum(-250.0)
        self.read_pos_stage_8.setMaximum(250.0)
        self.read_pos_stage_8.setObjectName(_fromUtf8("read_pos_stage_8"))
        self.gridLayout.addWidget(self.read_pos_stage_8, 8, 5, 1, 1)
        self.read_pos_stage_9 = QtGui.QDoubleSpinBox(self.widget)
        self.read_pos_stage_9.setMinimumSize(QtCore.QSize(60, 0))
        self.read_pos_stage_9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.read_pos_stage_9.setAlignment(QtCore.Qt.AlignCenter)
        self.read_pos_stage_9.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.read_pos_stage_9.setDecimals(3)
        self.read_pos_stage_9.setMinimum(-250.0)
        self.read_pos_stage_9.setMaximum(250.0)
        self.read_pos_stage_9.setObjectName(_fromUtf8("read_pos_stage_9"))
        self.gridLayout.addWidget(self.read_pos_stage_9, 9, 5, 1, 1)
        self.read_set_pos_stage_2 = QtGui.QDoubleSpinBox(self.widget)
        self.read_set_pos_stage_2.setMinimumSize(QtCore.QSize(60, 0))
        self.read_set_pos_stage_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.read_set_pos_stage_2.setAlignment(QtCore.Qt.AlignCenter)
        self.read_set_pos_stage_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.read_set_pos_stage_2.setDecimals(3)
        self.read_set_pos_stage_2.setMinimum(-250.0)
        self.read_set_pos_stage_2.setMaximum(250.0)
        self.read_set_pos_stage_2.setObjectName(_fromUtf8("read_set_pos_stage_2"))
        self.gridLayout.addWidget(self.read_set_pos_stage_2, 2, 6, 1, 1)
        self.read_set_pos_stage_3 = QtGui.QDoubleSpinBox(self.widget)
        self.read_set_pos_stage_3.setMinimumSize(QtCore.QSize(60, 0))
        self.read_set_pos_stage_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.read_set_pos_stage_3.setAlignment(QtCore.Qt.AlignCenter)
        self.read_set_pos_stage_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.read_set_pos_stage_3.setDecimals(3)
        self.read_set_pos_stage_3.setMinimum(-250.0)
        self.read_set_pos_stage_3.setMaximum(250.0)
        self.read_set_pos_stage_3.setObjectName(_fromUtf8("read_set_pos_stage_3"))
        self.gridLayout.addWidget(self.read_set_pos_stage_3, 3, 6, 1, 1)
        self.read_set_pos_stage_4 = QtGui.QDoubleSpinBox(self.widget)
        self.read_set_pos_stage_4.setMinimumSize(QtCore.QSize(60, 0))
        self.read_set_pos_stage_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.read_set_pos_stage_4.setAlignment(QtCore.Qt.AlignCenter)
        self.read_set_pos_stage_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.read_set_pos_stage_4.setDecimals(3)
        self.read_set_pos_stage_4.setMinimum(-250.0)
        self.read_set_pos_stage_4.setMaximum(250.0)
        self.read_set_pos_stage_4.setObjectName(_fromUtf8("read_set_pos_stage_4"))
        self.gridLayout.addWidget(self.read_set_pos_stage_4, 4, 6, 1, 1)
        self.read_set_pos_stage_5 = QtGui.QDoubleSpinBox(self.widget)
        self.read_set_pos_stage_5.setMinimumSize(QtCore.QSize(60, 0))
        self.read_set_pos_stage_5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.read_set_pos_stage_5.setAlignment(QtCore.Qt.AlignCenter)
        self.read_set_pos_stage_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.read_set_pos_stage_5.setDecimals(3)
        self.read_set_pos_stage_5.setMinimum(-250.0)
        self.read_set_pos_stage_5.setMaximum(250.0)
        self.read_set_pos_stage_5.setObjectName(_fromUtf8("read_set_pos_stage_5"))
        self.gridLayout.addWidget(self.read_set_pos_stage_5, 5, 6, 1, 1)
        self.read_set_pos_stage_6 = QtGui.QDoubleSpinBox(self.widget)
        self.read_set_pos_stage_6.setMinimumSize(QtCore.QSize(60, 0))
        self.read_set_pos_stage_6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.read_set_pos_stage_6.setAlignment(QtCore.Qt.AlignCenter)
        self.read_set_pos_stage_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.read_set_pos_stage_6.setDecimals(3)
        self.read_set_pos_stage_6.setMinimum(-250.0)
        self.read_set_pos_stage_6.setMaximum(250.0)
        self.read_set_pos_stage_6.setObjectName(_fromUtf8("read_set_pos_stage_6"))
        self.gridLayout.addWidget(self.read_set_pos_stage_6, 6, 6, 1, 1)
        self.read_set_pos_stage_7 = QtGui.QDoubleSpinBox(self.widget)
        self.read_set_pos_stage_7.setMinimumSize(QtCore.QSize(60, 0))
        self.read_set_pos_stage_7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.read_set_pos_stage_7.setAlignment(QtCore.Qt.AlignCenter)
        self.read_set_pos_stage_7.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.read_set_pos_stage_7.setDecimals(3)
        self.read_set_pos_stage_7.setMinimum(-250.0)
        self.read_set_pos_stage_7.setMaximum(250.0)
        self.read_set_pos_stage_7.setObjectName(_fromUtf8("read_set_pos_stage_7"))
        self.gridLayout.addWidget(self.read_set_pos_stage_7, 7, 6, 1, 1)
        self.read_set_pos_stage_8 = QtGui.QDoubleSpinBox(self.widget)
        self.read_set_pos_stage_8.setMinimumSize(QtCore.QSize(60, 0))
        self.read_set_pos_stage_8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.read_set_pos_stage_8.setAlignment(QtCore.Qt.AlignCenter)
        self.read_set_pos_stage_8.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.read_set_pos_stage_8.setDecimals(3)
        self.read_set_pos_stage_8.setMinimum(-250.0)
        self.read_set_pos_stage_8.setMaximum(250.0)
        self.read_set_pos_stage_8.setObjectName(_fromUtf8("read_set_pos_stage_8"))
        self.gridLayout.addWidget(self.read_set_pos_stage_8, 8, 6, 1, 1)
        self.read_set_pos_stage_9 = QtGui.QDoubleSpinBox(self.widget)
        self.read_set_pos_stage_9.setMinimumSize(QtCore.QSize(60, 0))
        self.read_set_pos_stage_9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.read_set_pos_stage_9.setAlignment(QtCore.Qt.AlignCenter)
        self.read_set_pos_stage_9.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.read_set_pos_stage_9.setDecimals(3)
        self.read_set_pos_stage_9.setMinimum(-250.0)
        self.read_set_pos_stage_9.setMaximum(250.0)
        self.read_set_pos_stage_9.setObjectName(_fromUtf8("read_set_pos_stage_9"))
        self.gridLayout.addWidget(self.read_set_pos_stage_9, 9, 6, 1, 1)
        self.min_pos_stage_2 = QtGui.QDoubleSpinBox(self.widget)
        self.min_pos_stage_2.setMinimumSize(QtCore.QSize(60, 0))
        self.min_pos_stage_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.min_pos_stage_2.setAlignment(QtCore.Qt.AlignCenter)
        self.min_pos_stage_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.min_pos_stage_2.setDecimals(3)
        self.min_pos_stage_2.setMinimum(-250.0)
        self.min_pos_stage_2.setMaximum(250.0)
        self.min_pos_stage_2.setObjectName(_fromUtf8("min_pos_stage_2"))
        self.gridLayout.addWidget(self.min_pos_stage_2, 2, 8, 1, 1)
        self.min_pos_stage_3 = QtGui.QDoubleSpinBox(self.widget)
        self.min_pos_stage_3.setMinimumSize(QtCore.QSize(60, 0))
        self.min_pos_stage_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.min_pos_stage_3.setAlignment(QtCore.Qt.AlignCenter)
        self.min_pos_stage_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.min_pos_stage_3.setDecimals(3)
        self.min_pos_stage_3.setMinimum(-250.0)
        self.min_pos_stage_3.setMaximum(250.0)
        self.min_pos_stage_3.setObjectName(_fromUtf8("min_pos_stage_3"))
        self.gridLayout.addWidget(self.min_pos_stage_3, 3, 8, 1, 1)
        self.min_pos_stage_4 = QtGui.QDoubleSpinBox(self.widget)
        self.min_pos_stage_4.setMinimumSize(QtCore.QSize(60, 0))
        self.min_pos_stage_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.min_pos_stage_4.setAlignment(QtCore.Qt.AlignCenter)
        self.min_pos_stage_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.min_pos_stage_4.setDecimals(3)
        self.min_pos_stage_4.setMinimum(-250.0)
        self.min_pos_stage_4.setMaximum(250.0)
        self.min_pos_stage_4.setObjectName(_fromUtf8("min_pos_stage_4"))
        self.gridLayout.addWidget(self.min_pos_stage_4, 4, 8, 1, 1)
        self.min_pos_stage_5 = QtGui.QDoubleSpinBox(self.widget)
        self.min_pos_stage_5.setMinimumSize(QtCore.QSize(60, 0))
        self.min_pos_stage_5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.min_pos_stage_5.setAlignment(QtCore.Qt.AlignCenter)
        self.min_pos_stage_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.min_pos_stage_5.setDecimals(3)
        self.min_pos_stage_5.setMinimum(-250.0)
        self.min_pos_stage_5.setMaximum(250.0)
        self.min_pos_stage_5.setObjectName(_fromUtf8("min_pos_stage_5"))
        self.gridLayout.addWidget(self.min_pos_stage_5, 5, 8, 1, 1)
        self.min_pos_stage_6 = QtGui.QDoubleSpinBox(self.widget)
        self.min_pos_stage_6.setMinimumSize(QtCore.QSize(60, 0))
        self.min_pos_stage_6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.min_pos_stage_6.setAlignment(QtCore.Qt.AlignCenter)
        self.min_pos_stage_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.min_pos_stage_6.setDecimals(3)
        self.min_pos_stage_6.setMinimum(-250.0)
        self.min_pos_stage_6.setMaximum(250.0)
        self.min_pos_stage_6.setObjectName(_fromUtf8("min_pos_stage_6"))
        self.gridLayout.addWidget(self.min_pos_stage_6, 6, 8, 1, 1)
        self.min_pos_stage_7 = QtGui.QDoubleSpinBox(self.widget)
        self.min_pos_stage_7.setMinimumSize(QtCore.QSize(60, 0))
        self.min_pos_stage_7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.min_pos_stage_7.setAlignment(QtCore.Qt.AlignCenter)
        self.min_pos_stage_7.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.min_pos_stage_7.setDecimals(3)
        self.min_pos_stage_7.setMinimum(-250.0)
        self.min_pos_stage_7.setMaximum(250.0)
        self.min_pos_stage_7.setObjectName(_fromUtf8("min_pos_stage_7"))
        self.gridLayout.addWidget(self.min_pos_stage_7, 7, 8, 1, 1)
        self.min_pos_stage_8 = QtGui.QDoubleSpinBox(self.widget)
        self.min_pos_stage_8.setMinimumSize(QtCore.QSize(60, 0))
        self.min_pos_stage_8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.min_pos_stage_8.setAlignment(QtCore.Qt.AlignCenter)
        self.min_pos_stage_8.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.min_pos_stage_8.setDecimals(3)
        self.min_pos_stage_8.setMinimum(-250.0)
        self.min_pos_stage_8.setMaximum(250.0)
        self.min_pos_stage_8.setObjectName(_fromUtf8("min_pos_stage_8"))
        self.gridLayout.addWidget(self.min_pos_stage_8, 8, 8, 1, 1)
        self.min_pos_stage_9 = QtGui.QDoubleSpinBox(self.widget)
        self.min_pos_stage_9.setMinimumSize(QtCore.QSize(60, 0))
        self.min_pos_stage_9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.min_pos_stage_9.setAlignment(QtCore.Qt.AlignCenter)
        self.min_pos_stage_9.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.min_pos_stage_9.setDecimals(3)
        self.min_pos_stage_9.setMinimum(-250.0)
        self.min_pos_stage_9.setMaximum(250.0)
        self.min_pos_stage_9.setObjectName(_fromUtf8("min_pos_stage_9"))
        self.gridLayout.addWidget(self.min_pos_stage_9, 9, 8, 1, 1)
        self.max_pos_stage_2 = QtGui.QDoubleSpinBox(self.widget)
        self.max_pos_stage_2.setMinimumSize(QtCore.QSize(60, 0))
        self.max_pos_stage_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.max_pos_stage_2.setAlignment(QtCore.Qt.AlignCenter)
        self.max_pos_stage_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.max_pos_stage_2.setDecimals(3)
        self.max_pos_stage_2.setMinimum(-250.0)
        self.max_pos_stage_2.setMaximum(250.0)
        self.max_pos_stage_2.setObjectName(_fromUtf8("max_pos_stage_2"))
        self.gridLayout.addWidget(self.max_pos_stage_2, 2, 9, 1, 1)
        self.max_pos_stage_3 = QtGui.QDoubleSpinBox(self.widget)
        self.max_pos_stage_3.setMinimumSize(QtCore.QSize(60, 0))
        self.max_pos_stage_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.max_pos_stage_3.setAlignment(QtCore.Qt.AlignCenter)
        self.max_pos_stage_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.max_pos_stage_3.setDecimals(3)
        self.max_pos_stage_3.setMinimum(-250.0)
        self.max_pos_stage_3.setMaximum(250.0)
        self.max_pos_stage_3.setObjectName(_fromUtf8("max_pos_stage_3"))
        self.gridLayout.addWidget(self.max_pos_stage_3, 3, 9, 1, 1)
        self.max_pos_stage_4 = QtGui.QDoubleSpinBox(self.widget)
        self.max_pos_stage_4.setMinimumSize(QtCore.QSize(60, 0))
        self.max_pos_stage_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.max_pos_stage_4.setAlignment(QtCore.Qt.AlignCenter)
        self.max_pos_stage_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.max_pos_stage_4.setDecimals(3)
        self.max_pos_stage_4.setMinimum(-250.0)
        self.max_pos_stage_4.setMaximum(250.0)
        self.max_pos_stage_4.setObjectName(_fromUtf8("max_pos_stage_4"))
        self.gridLayout.addWidget(self.max_pos_stage_4, 4, 9, 1, 1)
        self.max_pos_stage_5 = QtGui.QDoubleSpinBox(self.widget)
        self.max_pos_stage_5.setMinimumSize(QtCore.QSize(60, 0))
        self.max_pos_stage_5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.max_pos_stage_5.setAlignment(QtCore.Qt.AlignCenter)
        self.max_pos_stage_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.max_pos_stage_5.setDecimals(3)
        self.max_pos_stage_5.setMinimum(-250.0)
        self.max_pos_stage_5.setMaximum(250.0)
        self.max_pos_stage_5.setObjectName(_fromUtf8("max_pos_stage_5"))
        self.gridLayout.addWidget(self.max_pos_stage_5, 5, 9, 1, 1)
        self.max_pos_stage_6 = QtGui.QDoubleSpinBox(self.widget)
        self.max_pos_stage_6.setMinimumSize(QtCore.QSize(60, 0))
        self.max_pos_stage_6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.max_pos_stage_6.setAlignment(QtCore.Qt.AlignCenter)
        self.max_pos_stage_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.max_pos_stage_6.setDecimals(3)
        self.max_pos_stage_6.setMinimum(-250.0)
        self.max_pos_stage_6.setMaximum(250.0)
        self.max_pos_stage_6.setObjectName(_fromUtf8("max_pos_stage_6"))
        self.gridLayout.addWidget(self.max_pos_stage_6, 6, 9, 1, 1)
        self.max_pos_stage_7 = QtGui.QDoubleSpinBox(self.widget)
        self.max_pos_stage_7.setMinimumSize(QtCore.QSize(60, 0))
        self.max_pos_stage_7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.max_pos_stage_7.setAlignment(QtCore.Qt.AlignCenter)
        self.max_pos_stage_7.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.max_pos_stage_7.setDecimals(3)
        self.max_pos_stage_7.setMinimum(-250.0)
        self.max_pos_stage_7.setMaximum(250.0)
        self.max_pos_stage_7.setObjectName(_fromUtf8("max_pos_stage_7"))
        self.gridLayout.addWidget(self.max_pos_stage_7, 7, 9, 1, 1)
        self.max_pos_stage_8 = QtGui.QDoubleSpinBox(self.widget)
        self.max_pos_stage_8.setMinimumSize(QtCore.QSize(60, 0))
        self.max_pos_stage_8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.max_pos_stage_8.setAlignment(QtCore.Qt.AlignCenter)
        self.max_pos_stage_8.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.max_pos_stage_8.setDecimals(3)
        self.max_pos_stage_8.setMinimum(-250.0)
        self.max_pos_stage_8.setMaximum(250.0)
        self.max_pos_stage_8.setObjectName(_fromUtf8("max_pos_stage_8"))
        self.gridLayout.addWidget(self.max_pos_stage_8, 8, 9, 1, 1)
        self.max_pos_stage_9 = QtGui.QDoubleSpinBox(self.widget)
        self.max_pos_stage_9.setMinimumSize(QtCore.QSize(60, 0))
        self.max_pos_stage_9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.max_pos_stage_9.setAlignment(QtCore.Qt.AlignCenter)
        self.max_pos_stage_9.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.max_pos_stage_9.setDecimals(3)
        self.max_pos_stage_9.setMinimum(-250.0)
        self.max_pos_stage_9.setMaximum(250.0)
        self.max_pos_stage_9.setObjectName(_fromUtf8("max_pos_stage_9"))
        self.gridLayout.addWidget(self.max_pos_stage_9, 9, 9, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow", None))
        self.clear_for_beam_button.setText(_translate("mainWindow", "PRESS TO MOVE ALL TO CLEAR FOR BEAM", None))
        self.label_2.setText(_translate("mainWindow", "Set Device", None))
        self.label_7.setText(_translate("mainWindow", "MIN POS", None))
        self.label_10.setText(_translate("mainWindow", "Set (mm)", None))
        self.label_4.setText(_translate("mainWindow", "NEW Set (mm)", None))
        self.label.setText(_translate("mainWindow", "Stage NAME", None))
        self.label_9.setText(_translate("mainWindow", "Read Device", None))
        self.label_5.setText(_translate("mainWindow", "MOVE To DEVICE", None))
        self.label_3.setText(_translate("mainWindow", "Read (mm)", None))
        self.label_8.setText(_translate("mainWindow", "MAX POS", None))
        self.read_dev_stage_2.setText(_translate("mainWindow", "UNKNOWN", None))
        self.move2dev_stage_1.setText(_translate("mainWindow", "Move To Device", None))
        self.move2dev_stage_2.setText(_translate("mainWindow", "Move To Device", None))
        self.name_stage_3.setText(_translate("mainWindow", "UNKNOWN", None))
        self.label_stage_2.setText(_translate("mainWindow", "2", None))
        self.read_dev_stage_3.setText(_translate("mainWindow", "UNKNOWN", None))
        self.move2dev_stage_3.setText(_translate("mainWindow", "Move To Device", None))
        self.read_dev_stage_1.setText(_translate("mainWindow", "UNKNOWN", None))
        self.label_stage_3.setText(_translate("mainWindow", "3", None))
        self.name_stage_1.setText(_translate("mainWindow", "UNKNOWN", None))
        self.label_stage_1.setText(_translate("mainWindow", "1", None))
        self.name_stage_2.setText(_translate("mainWindow", "UNKNOWN", None))
        self.label_stage_5.setText(_translate("mainWindow", "5", None))
        self.move2dev_stage_6.setText(_translate("mainWindow", "Move To Device", None))
        self.move2dev_stage_4.setText(_translate("mainWindow", "Move To Device", None))
        self.name_stage_6.setText(_translate("mainWindow", "UNKNOWN", None))
        self.name_stage_4.setText(_translate("mainWindow", "UNKNOWN", None))
        self.label_stage_4.setText(_translate("mainWindow", "4", None))
        self.read_dev_stage_5.setText(_translate("mainWindow", "UNKNOWN", None))
        self.read_dev_stage_4.setText(_translate("mainWindow", "UNKNOWN", None))
        self.read_dev_stage_6.setText(_translate("mainWindow", "UNKNOWN", None))
        self.label_stage_6.setText(_translate("mainWindow", "6", None))
        self.name_stage_5.setText(_translate("mainWindow", "UNKNOWN", None))
        self.move2dev_stage_5.setText(_translate("mainWindow", "Move To Device", None))
        self.read_dev_stage_7.setText(_translate("mainWindow", "UNKNOWN", None))
        self.label_stage_7.setText(_translate("mainWindow", "7", None))
        self.name_stage_7.setText(_translate("mainWindow", "UNKNOWN", None))
        self.move2dev_stage_7.setText(_translate("mainWindow", "Move To Device", None))
        self.label_stage_9.setText(_translate("mainWindow", "9", None))
        self.read_dev_stage_9.setText(_translate("mainWindow", "UNKNOWN", None))
        self.name_stage_9.setText(_translate("mainWindow", "UNKNOWN", None))
        self.label_stage_8.setText(_translate("mainWindow", "8", None))
        self.read_dev_stage_8.setText(_translate("mainWindow", "UNKNOWN", None))
        self.move2dev_stage_8.setText(_translate("mainWindow", "Move To Device", None))
        self.name_stage_8.setText(_translate("mainWindow", "UNKNOWN", None))
        self.move2dev_stage_9.setText(_translate("mainWindow", "Move To Device", None))

