# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_windows_source.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(641, 245)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 5, 1, 1)
        self.s1_name = QtGui.QLabel(self.centralwidget)
        self.s1_name.setMaximumSize(QtCore.QSize(100, 16777215))
        self.s1_name.setObjectName(_fromUtf8("s1_name"))
        self.gridLayout.addWidget(self.s1_name, 1, 0, 1, 1)
        self.s1_dev = QtGui.QComboBox(self.centralwidget)
        self.s1_dev.setMinimumSize(QtCore.QSize(100, 0))
        self.s1_dev.setObjectName(_fromUtf8("s1_dev"))
        self.gridLayout.addWidget(self.s1_dev, 1, 1, 1, 1)
        self.s1_move2dev = QtGui.QPushButton(self.centralwidget)
        self.s1_move2dev.setMaximumSize(QtCore.QSize(100, 16777215))
        self.s1_move2dev.setObjectName(_fromUtf8("s1_move2dev"))
        self.gridLayout.addWidget(self.s1_move2dev, 1, 2, 1, 1)
        self.s1_read = QtGui.QLabel(self.centralwidget)
        self.s1_read.setMaximumSize(QtCore.QSize(100, 16777215))
        self.s1_read.setObjectName(_fromUtf8("s1_read"))
        self.gridLayout.addWidget(self.s1_read, 1, 3, 1, 1)
        self.s1_set = QtGui.QDoubleSpinBox(self.centralwidget)
        self.s1_set.setMinimumSize(QtCore.QSize(100, 0))
        self.s1_set.setMaximumSize(QtCore.QSize(100, 16777215))
        self.s1_set.setDecimals(3)
        self.s1_set.setMinimum(-250.0)
        self.s1_set.setMaximum(250.0)
        self.s1_set.setObjectName(_fromUtf8("s1_set"))
        self.gridLayout.addWidget(self.s1_set, 1, 4, 1, 1)
        self.s1_move2set = QtGui.QPushButton(self.centralwidget)
        self.s1_move2set.setMaximumSize(QtCore.QSize(100, 16777215))
        self.s1_move2set.setObjectName(_fromUtf8("s1_move2set"))
        self.gridLayout.addWidget(self.s1_move2set, 1, 5, 1, 1)
        self.s2_name = QtGui.QLabel(self.centralwidget)
        self.s2_name.setObjectName(_fromUtf8("s2_name"))
        self.gridLayout.addWidget(self.s2_name, 2, 0, 1, 1)
        self.s2_dev = QtGui.QComboBox(self.centralwidget)
        self.s2_dev.setMinimumSize(QtCore.QSize(100, 0))
        self.s2_dev.setObjectName(_fromUtf8("s2_dev"))
        self.gridLayout.addWidget(self.s2_dev, 2, 1, 1, 1)
        self.s2_move2dev = QtGui.QPushButton(self.centralwidget)
        self.s2_move2dev.setObjectName(_fromUtf8("s2_move2dev"))
        self.gridLayout.addWidget(self.s2_move2dev, 2, 2, 1, 1)
        self.s2_read = QtGui.QLabel(self.centralwidget)
        self.s2_read.setObjectName(_fromUtf8("s2_read"))
        self.gridLayout.addWidget(self.s2_read, 2, 3, 1, 1)
        self.s2_set = QtGui.QDoubleSpinBox(self.centralwidget)
        self.s2_set.setMinimumSize(QtCore.QSize(100, 0))
        self.s2_set.setMinimum(-250.0)
        self.s2_set.setMaximum(250.0)
        self.s2_set.setObjectName(_fromUtf8("s2_set"))
        self.gridLayout.addWidget(self.s2_set, 2, 4, 1, 1)
        self.s2_move2set = QtGui.QPushButton(self.centralwidget)
        self.s2_move2set.setObjectName(_fromUtf8("s2_move2set"))
        self.gridLayout.addWidget(self.s2_move2set, 2, 5, 1, 1)
        self.s3_name = QtGui.QLabel(self.centralwidget)
        self.s3_name.setObjectName(_fromUtf8("s3_name"))
        self.gridLayout.addWidget(self.s3_name, 3, 0, 1, 1)
        self.s3_dev = QtGui.QComboBox(self.centralwidget)
        self.s3_dev.setMinimumSize(QtCore.QSize(100, 0))
        self.s3_dev.setObjectName(_fromUtf8("s3_dev"))
        self.gridLayout.addWidget(self.s3_dev, 3, 1, 1, 1)
        self.s3_move2dev = QtGui.QPushButton(self.centralwidget)
        self.s3_move2dev.setObjectName(_fromUtf8("s3_move2dev"))
        self.gridLayout.addWidget(self.s3_move2dev, 3, 2, 1, 1)
        self.s3_read = QtGui.QLabel(self.centralwidget)
        self.s3_read.setObjectName(_fromUtf8("s3_read"))
        self.gridLayout.addWidget(self.s3_read, 3, 3, 1, 1)
        self.s3_set = QtGui.QDoubleSpinBox(self.centralwidget)
        self.s3_set.setMinimumSize(QtCore.QSize(100, 0))
        self.s3_set.setMinimum(-250.0)
        self.s3_set.setMaximum(250.0)
        self.s3_set.setObjectName(_fromUtf8("s3_set"))
        self.gridLayout.addWidget(self.s3_set, 3, 4, 1, 1)
        self.s3_move2set = QtGui.QPushButton(self.centralwidget)
        self.s3_move2set.setObjectName(_fromUtf8("s3_move2set"))
        self.gridLayout.addWidget(self.s3_move2set, 3, 5, 1, 1)
        self.s4_name = QtGui.QLabel(self.centralwidget)
        self.s4_name.setObjectName(_fromUtf8("s4_name"))
        self.gridLayout.addWidget(self.s4_name, 4, 0, 1, 1)
        self.s4_dev = QtGui.QComboBox(self.centralwidget)
        self.s4_dev.setMinimumSize(QtCore.QSize(100, 0))
        self.s4_dev.setObjectName(_fromUtf8("s4_dev"))
        self.gridLayout.addWidget(self.s4_dev, 4, 1, 1, 1)
        self.s4_move2dev = QtGui.QPushButton(self.centralwidget)
        self.s4_move2dev.setObjectName(_fromUtf8("s4_move2dev"))
        self.gridLayout.addWidget(self.s4_move2dev, 4, 2, 1, 1)
        self.s4_read = QtGui.QLabel(self.centralwidget)
        self.s4_read.setObjectName(_fromUtf8("s4_read"))
        self.gridLayout.addWidget(self.s4_read, 4, 3, 1, 1)
        self.s4_set = QtGui.QDoubleSpinBox(self.centralwidget)
        self.s4_set.setMinimumSize(QtCore.QSize(100, 0))
        self.s4_set.setMinimum(-250.0)
        self.s4_set.setMaximum(250.0)
        self.s4_set.setObjectName(_fromUtf8("s4_set"))
        self.gridLayout.addWidget(self.s4_set, 4, 4, 1, 1)
        self.s4_move2set = QtGui.QPushButton(self.centralwidget)
        self.s4_move2set.setObjectName(_fromUtf8("s4_move2set"))
        self.gridLayout.addWidget(self.s4_move2set, 4, 5, 1, 1)
        self.s5_name = QtGui.QLabel(self.centralwidget)
        self.s5_name.setObjectName(_fromUtf8("s5_name"))
        self.gridLayout.addWidget(self.s5_name, 5, 0, 1, 1)
        self.s5_dev = QtGui.QComboBox(self.centralwidget)
        self.s5_dev.setMinimumSize(QtCore.QSize(100, 0))
        self.s5_dev.setObjectName(_fromUtf8("s5_dev"))
        self.gridLayout.addWidget(self.s5_dev, 5, 1, 1, 1)
        self.s5_move2dev = QtGui.QPushButton(self.centralwidget)
        self.s5_move2dev.setObjectName(_fromUtf8("s5_move2dev"))
        self.gridLayout.addWidget(self.s5_move2dev, 5, 2, 1, 1)
        self.s5_read = QtGui.QLabel(self.centralwidget)
        self.s5_read.setObjectName(_fromUtf8("s5_read"))
        self.gridLayout.addWidget(self.s5_read, 5, 3, 1, 1)
        self.s5_set = QtGui.QDoubleSpinBox(self.centralwidget)
        self.s5_set.setMinimumSize(QtCore.QSize(100, 0))
        self.s5_set.setMinimum(-250.0)
        self.s5_set.setMaximum(250.0)
        self.s5_set.setObjectName(_fromUtf8("s5_set"))
        self.gridLayout.addWidget(self.s5_set, 5, 4, 1, 1)
        self.s5_move2set = QtGui.QPushButton(self.centralwidget)
        self.s5_move2set.setObjectName(_fromUtf8("s5_move2set"))
        self.gridLayout.addWidget(self.s5_move2set, 5, 5, 1, 1)
        self.s6_name = QtGui.QLabel(self.centralwidget)
        self.s6_name.setObjectName(_fromUtf8("s6_name"))
        self.gridLayout.addWidget(self.s6_name, 6, 0, 1, 1)
        self.s6_dev = QtGui.QComboBox(self.centralwidget)
        self.s6_dev.setMinimumSize(QtCore.QSize(100, 0))
        self.s6_dev.setObjectName(_fromUtf8("s6_dev"))
        self.gridLayout.addWidget(self.s6_dev, 6, 1, 1, 1)
        self.s6_move2dev = QtGui.QPushButton(self.centralwidget)
        self.s6_move2dev.setObjectName(_fromUtf8("s6_move2dev"))
        self.gridLayout.addWidget(self.s6_move2dev, 6, 2, 1, 1)
        self.s6_read = QtGui.QLabel(self.centralwidget)
        self.s6_read.setObjectName(_fromUtf8("s6_read"))
        self.gridLayout.addWidget(self.s6_read, 6, 3, 1, 1)
        self.s6_set = QtGui.QDoubleSpinBox(self.centralwidget)
        self.s6_set.setMinimumSize(QtCore.QSize(100, 0))
        self.s6_set.setMinimum(-250.0)
        self.s6_set.setMaximum(250.0)
        self.s6_set.setObjectName(_fromUtf8("s6_set"))
        self.gridLayout.addWidget(self.s6_set, 6, 4, 1, 1)
        self.s6_move2set = QtGui.QPushButton(self.centralwidget)
        self.s6_move2set.setObjectName(_fromUtf8("s6_move2set"))
        self.gridLayout.addWidget(self.s6_move2set, 6, 5, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Stage NAME", None))
        self.label_2.setText(_translate("MainWindow", "Device Name", None))
        self.label_5.setText(_translate("MainWindow", "TextLabel", None))
        self.label_3.setText(_translate("MainWindow", "Read Position (mm)", None))
        self.label_4.setText(_translate("MainWindow", "Set Position (mm)", None))
        self.label_6.setText(_translate("MainWindow", "TextLabel", None))
        self.s1_name.setText(_translate("MainWindow", "TextLabel", None))
        self.s1_move2dev.setText(_translate("MainWindow", "Move To Device", None))
        self.s1_read.setText(_translate("MainWindow", "TextLabel", None))
        self.s1_move2set.setText(_translate("MainWindow", "Move To Set", None))
        self.s2_name.setText(_translate("MainWindow", "TextLabel", None))
        self.s2_move2dev.setText(_translate("MainWindow", "Move To Device", None))
        self.s2_read.setText(_translate("MainWindow", "TextLabel", None))
        self.s2_move2set.setText(_translate("MainWindow", "Move To Set", None))
        self.s3_name.setText(_translate("MainWindow", "TextLabel", None))
        self.s3_move2dev.setText(_translate("MainWindow", "Move To Device", None))
        self.s3_read.setText(_translate("MainWindow", "TextLabel", None))
        self.s3_move2set.setText(_translate("MainWindow", "Move To Set", None))
        self.s4_name.setText(_translate("MainWindow", "TextLabel", None))
        self.s4_move2dev.setText(_translate("MainWindow", "Move To Device", None))
        self.s4_read.setText(_translate("MainWindow", "TextLabel", None))
        self.s4_move2set.setText(_translate("MainWindow", "Move To Set", None))
        self.s5_name.setText(_translate("MainWindow", "TextLabel", None))
        self.s5_move2dev.setText(_translate("MainWindow", "Move To Device", None))
        self.s5_read.setText(_translate("MainWindow", "TextLabel", None))
        self.s5_move2set.setText(_translate("MainWindow", "Move To Set", None))
        self.s6_name.setText(_translate("MainWindow", "TextLabel", None))
        self.s6_move2dev.setText(_translate("MainWindow", "Move To Device", None))
        self.s6_read.setText(_translate("MainWindow", "TextLabel", None))
        self.s6_move2set.setText(_translate("MainWindow", "Move To Set", None))

